# -*- coding: utf-8 -*-
"""Gen chapters 4-7 for Quyen IV -- tieng Viet co dau day du"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-4/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 4: BẠN BÈ TRI KỶ
# ================================================================
ch4 = chapter(
    "Bạn Bè Tri Kỷ --- Người Hiểu Ta Là Vô Giá", "True Friends --- Those Who Truly Know You",
    "Bạn bè tri kỷ là của cải quý nhất một người có thể sở hữu.",
    "A true friend is the greatest treasure a person can possess.",
    [
    story("Bá Nha Và Tử Kỳ --- Đôi Bạn Tri Âm Muôn Đời", "Truyện Cổ Trung Hoa --- thế kỷ 5 TCN",
          "Bá",
          [("Bá Nha là nhạc sĩ tài hoa bậc nhất nước Sở thời Xuân Thu; ông chơi đàn cầm như tiếng trời.",
            "Bo Ya was the most gifted musician of the state of Chu during the Spring and Autumn period; his zither playing sounded like heaven."),
           ("Nhưng không ai thật sự hiểu tiếng đàn của ông --- cho đến khi ông gặp Tử Kỳ, một người tiều phu bình dị.",
            "But no one truly understood his music --- until he met Ziqi, a simple woodcutter."),
           ("Bá Nha gảy khúc miêu tả núi cao; Tử Kỳ nói: ``Tiếng đàn hùng tráng như núi Thái Sơn vươn lên!''",
            "Bo Ya played a melody depicting high mountains; Ziqi said: `Your music is as majestic as Mount Tai reaching upward!'"),
           ("Bá Nha gảy nhạc tả dòng sông; Tử Kỳ nói: ``Tiếng đàn cuồn cuộn như sông Hoàng Hà chảy xiết!''",
            "Bo Ya played music of flowing rivers; Ziqi said: `Your zither roars like the Yellow River rushing in full current!'"),
           ("Khi Tử Kỳ qua đời, Bá Nha đập vỡ cây đàn và không bao giờ đàn lại --- vì người duy nhất hiểu ông đã không còn nữa.",
            "When Ziqi died, Bo Ya shattered his zither and never played again --- for the one person who truly understood him was gone.")],
          "Người tri âm hiểu bạn không phải qua lời giải thích mà qua tâm hồn --- và khi người đó mất đi, một phần của bạn cũng ra đi.",
          "A true friend understands you not through explanations but through the soul --- and when they are gone, a part of you goes too."),

    story("Anh Em Nhà Wright --- Cùng Bay Lên Trời", "Orville và Wilbur Wright --- Hoa Kỳ, 1903",
          "Orville",
          [("Orville và Wilbur Wright không chỉ là anh em ruột --- họ là đôi bạn tri kỷ kiêm cộng sự hoàn hảo.",
            "Orville and Wilbur Wright were not just brothers --- they were the perfect pair of true friends and collaborators."),
           ("Khi thế giới cười nhạo ước mơ chế tạo máy bay, anh em họ nâng đỡ nhau trong từng thất bại.",
            "When the world laughed at their dream of building a flying machine, they lifted each other through every failure."),
           ("Orville kể lại rằng mỗi khi anh tuyệt vọng, Wilbur tìm đến ngồi bên cạnh --- không nói gì, chỉ ở đó.",
            "Orville recalled that whenever he despaired, Wilbur would come and sit beside him --- saying nothing, just being there."),
           ("Chuyến bay lịch sử ngày 17 tháng 12 năm 1903 tại Kitty Hawk kéo dài 12 giây --- nhưng đó là thành quả của cả một tình bạn.",
            "The historic flight on December 17, 1903 at Kitty Hawk lasted 12 seconds --- but it was the fruit of an entire friendship."),
           ("Orville viết: ``Không có Wilbur, tôi không thể bay được; không có nhau, chúng tôi không là gì.''",
            "Orville wrote: `Without Wilbur, I could not have flown; without each other, we were nothing.'")],
          "Người bạn thật sự không chỉ ăn mừng chiến thắng cùng bạn --- họ ngồi yên bên cạnh bạn trong những lúc tối tăm nhất.",
          "A true friend doesn't just celebrate your victories --- they sit quietly beside you in your darkest moments."),

    story("Marie Curie Và Tình Bạn Khoa Học Với Chồng", "Marie và Pierre Curie --- Pháp, 1898",
          "Marie",
          [("Marie Curie và chồng Pierre không chỉ là vợ chồng --- họ là đôi bạn khoa học tri kỷ.",
            "Marie Curie and her husband Pierre were not just husband and wife --- they were true scientific friends."),
           ("Pierre từng được đề nghị một vị trí danh giá ở Đại học Geneva --- nhưng từ chối vì Marie không được mời cùng.",
            "Pierre was once offered a prestigious position at the University of Geneva --- but refused because Marie was not invited too."),
           ("Ông giải thích ngắn gọn: ``Nghiên cứu của chúng tôi là của chung; tôi không thể tách rời khỏi công việc đó.''",
            "He explained briefly: `Our research belongs to both of us; I cannot separate myself from that work.'"),
           ("Cùng nhau họ khám phá polonium và radium; cùng nhau họ xây dựng nền tảng của hoá phóng xạ học hiện đại.",
            "Together they discovered polonium and radium; together they built the foundations of modern radiochemistry."),
           ("Sau khi Pierre mất, Marie tiếp tục một mình --- mang trong lòng cả tình bạn lẫn sứ mệnh khoa học của hai người.",
            "After Pierre died, Marie continued alone --- carrying within her both their friendship and their shared scientific mission.")],
          "Tình bạn tri kỷ thật sự vượt qua ranh giới của vai trò và mối quan hệ --- nó là sự đồng hành trên cùng một hành trình ý nghĩa.",
          "True friendship transcends the boundaries of roles and relationships --- it is companionship on the same meaningful journey."),

    story("Lưu Bình Và Dương Lễ --- Tình Bạn Thử Lửa", "Truyện Dân Gian Việt Nam",
          "Lưu",
          [("Lưu Bình và Dương Lễ là hai người bạn thân từ thuở còn hàn vi học hành cùng nhau.",
            "Luu Binh and Duong Le were close friends from their poor student days, studying together."),
           ("Khi Dương Lễ đỗ đạt làm quan, Lưu Bình thất thế đến nhà bạn nhờ vả nhưng bị đối xử lạnh nhạt.",
            "When Duong Le passed the exams and became an official, Luu Binh in hardship went to his friend for help but was treated coldly."),
           ("Lưu Bình tủi hổ, quyết chí ôn thi; nhiều năm sau ông đỗ cao và trở lại để hỏi tội người bạn cũ.",
            "Luu Binh, shamed and determined, redoubled his studies; years later he passed with honours and returned to confront his old friend."),
           ("Dương Lễ cười và tiết lộ sự thật: chính ông đã bí mật chu cấp tiền cho Lưu Bình học trong suốt những năm đó.",
            "Duong Le smiled and revealed the truth: he had secretly been funding Luu Binh's studies all those years."),
           ("Sự lạnh nhạt khi xưa là cố tình --- để hun đúc ý chí bạn thay vì làm bạn ỷ lại vào mình.",
            "The coldness back then was deliberate --- to forge his friend's resolve rather than foster dependence.")],
          "Bạn bè tri kỷ đôi khi thể hiện tình bạn theo những cách bạn không nhận ra được --- cho đến khi đã muộn.",
          "True friends sometimes show their friendship in ways you cannot recognise --- until much later."),

    story("Alexander Đại Đế Và Hephaestion --- Tình Huynh Đệ Chiến Trận", "Alexander Đại Đế --- Hy Lạp, thế kỷ 4 TCN",
          "Alexander",
          [("Alexander Đại Đế và Hephaestion là đôi bạn từ thuở nhỏ --- cùng học dưới trướng Aristotle.",
            "Alexander the Great and Hephaestion were childhood friends --- both students under Aristotle."),
           ("Trong suốt các cuộc chinh phạt vĩ đại, Hephaestion luôn ở bên cạnh Alexander như cái bóng.",
            "Throughout the great conquests, Hephaestion was always at Alexander's side like a shadow."),
           ("Một lần sứ giả Ba Tư nhầm lẫn cúi chào Hephaestion thay vì Alexander; Alexander nói: ``Không sao --- ông ấy cũng là Alexander.''",
            "Once a Persian envoy mistakenly bowed to Hephaestion instead of Alexander; Alexander said: `No matter --- he is also Alexander.'"),
           ("Khi Hephaestion đột ngột qua đời vì bệnh, Alexander đau khổ đến nỗi từ chối ăn uống nhiều ngày.",
            "When Hephaestion suddenly died of illness, Alexander grieved so deeply he refused to eat for days."),
           ("Ông ra lệnh để tang hoàng gia trong toàn đế quốc --- vì ông đã mất không chỉ người bạn mà còn một phần bản thân.",
            "He ordered imperial mourning throughout his entire empire --- for he had lost not just a friend but a part of himself.")],
          "Người bạn tri kỷ thật sự là người bạn không thể hình dung cuộc đời của mình nếu không có họ.",
          "A true friend is someone you cannot imagine your own life without."),

    story("Lincoln Và Joshua Speed --- Bạn Thân Giữa Khủng Hoảng", "Abraham Lincoln --- Hoa Kỳ, 1841",
          "Năm",
          [("Năm 1841, Abraham Lincoln rơi vào cuộc khủng hoảng tâm lý nghiêm trọng nhất cuộc đời ông.",
            "In 1841, Abraham Lincoln fell into the most serious psychological crisis of his life."),
           ("Ông huỷ hôn với Mary Todd, mất phương hướng, sút cân nghiêm trọng và sưng tấy tinh thần.",
            "He broke his engagement with Mary Todd, lost direction, lost serious weight, and suffered deeply in spirit."),
           ("Người bạn thân Joshua Speed đã kéo ông đến ở tại trang trại gia đình ở Kentucky --- không giảng giải, chỉ đồng hành.",
            "His close friend Joshua Speed brought him to stay at the family farm in Kentucky --- not lecturing, just accompanying."),
           ("Speed kể lại: ``Tôi không biết nói gì với Lincoln; tôi chỉ biết rằng tôi không thể để anh ấy một mình.''",
            "Speed recalled: `I didn't know what to say to Lincoln; I only knew I could not leave him alone.'"),
           ("Chính tình bạn im lặng và trung thành đó đã giúp Lincoln vượt qua để trở thành Tổng Thống vĩ đại nhất nước Mỹ.",
            "It was that silent, loyal friendship that helped Lincoln pull through to become America's greatest President.")],
          "Đôi khi người bạn tốt nhất không phải là người biết nói điều gì --- mà là người không bỏ đi khi bạn không thể nói.",
          "Sometimes the best friend is not one who knows what to say --- but one who doesn't leave when you can say nothing."),

    story("Nguyễn Du Và Nhà Thơ Nguyễn Hành --- Tri Kỷ Trong Văn Chương", "Nguyễn Du --- Việt Nam, thế kỷ 18-19",
          "Nguyễn",
          [("Nguyễn Du, đại thi hào của Việt Nam, suốt cuộc đời cảm thấy cô đơn dù tiếng tăm lừng lẫy.",
            "Nguyen Du, Vietnam's great poet, felt lonely throughout his life despite his towering fame."),
           ("Nhưng trong đời ông có một người bạn thơ tri kỷ --- người anh họ Nguyễn Hành, cũng là một nhà thơ tài hoa.",
            "But he had one true poetic friend --- his cousin Nguyen Hanh, himself a gifted poet."),
           ("Hai người thường gặp nhau để đọc thơ cho nhau nghe và cùng ngồi im lặng nhìn cảnh vật.",
            "The two often met to read poems to each other and sit together in silence looking at the scenery."),
           ("Nguyễn Du viết trong thư gửi bạn: ``Người hay thơ đang thiếu --- thiếu kẻ hiểu ta trong từng câu chữ.''",
            "Nguyen Du wrote in a letter to his friend: `Poets are lacking --- lacking someone who understands me in every word.'"),
           ("Tình bạn văn chương đó là nền tảng tinh thần giúp ông viết nên Truyện Kiều --- kiệt tác bất hủ của văn học Việt Nam.",
            "That literary friendship was the spiritual foundation that helped him write the Tale of Kieu --- Vietnam's immortal masterpiece.")],
          "Một người bạn hiểu tâm hồn bạn có thể giải phóng những điều tốt đẹp nhất trong bạn mà tự mình bạn không thể làm được.",
          "A friend who understands your soul can unlock the best in you that you could never unlock alone."),

    story("David Và Jonathan --- Tình Bạn Vượt Qua Lòng Ghen Ghét", "Kinh Thánh --- Do Thái, khoảng 1000 TCN",
          "David",
          [("David là chàng trai trẻ đã giết gã khổng lồ Goliath và được cả dân tộc Do Thái tôn sùng.",
            "David was the young man who slew the giant Goliath and was adored by all of Israel."),
           ("Jonathan, con trai vua Saul, lẽ ra là người phải ghen ghét David --- vì David đe doạ ngôi vị kế thừa của ông.",
            "Jonathan, King Saul's son, had every reason to resent David --- for David threatened his rightful inheritance of the throne."),
           ("Nhưng Jonathan chọn tình bạn thay vì địa vị; ông cất giấu David khi vua cha ra lệnh giết.",
            "But Jonathan chose friendship over position; he hid David when his father ordered David killed."),
           ("Ông nói với David: ``Dù có chuyện gì xảy ra, bạn là người tôi chọn để bên cạnh.''",
            "He told David: `Whatever happens, you are the person I choose to stand beside.'"),
           ("Tình bạn này vượt qua quyền lực, chính trị và cả ý chí của người cha --- vì lòng trung thành là thứ không thể ra lệnh.",
            "Their friendship transcended power, politics, and even a father's command --- for loyalty cannot be commanded.")],
          "Tình bạn chân thật là khi bạn chọn người bạn mình dù điều đó đi ngược lại lợi ích cá nhân của chính bạn.",
          "True friendship is when you choose your friend even when it goes against your own personal interest."),

    story("Goethe Và Schiller --- Tình Bạn Văn Học Vĩ Đại", "Goethe và Schiller --- Đức, 1794",
          "Johann",
          [("Johann Wolfgang von Goethe và Friedrich Schiller gặp nhau lần đầu năm 1794 --- hai nhà thơ đã nổi tiếng và đầy cá tính.",
            "Johann Wolfgang von Goethe and Friedrich Schiller met for the first time in 1794 --- two poets already famous and fiercely individual."),
           ("Goethe ban đầu coi Schiller là đối thủ cạnh tranh; Schiller viết thư thẳng thắn chia sẻ quan điểm khác biệt.",
            "Goethe initially saw Schiller as a rival; Schiller wrote directly, candidly sharing his differing views."),
           ("Từ đó bắt đầu một trong những tình bạn trí thức vĩ đại nhất lịch sử văn học phương Tây.",
            "From that grew one of the greatest intellectual friendships in the history of Western literature."),
           ("Họ viết thư cho nhau hằng ngày, thách thức nhau, khích lệ nhau --- và cùng nhau tạo ra những tác phẩm bất hủ.",
            "They wrote to each other daily, challenged each other, encouraged each other --- and together created immortal works."),
           ("Goethe nói sau khi Schiller mất: ``Tôi nghĩ mình đã mất một nửa cuộc đời.''",
            "Goethe said after Schiller's death: `I thought I had lost half of my own existence.'")],
          "Bạn bè tri kỷ không làm cho bạn thoải mái --- họ khiến bạn trở nên tốt hơn bằng cách thách thức bạn mỗi ngày.",
          "True friends do not make you comfortable --- they make you better by challenging you every single day."),

    story("Roosevelt Và Louis Howe --- Người Bạn Nói Thật", "Franklin D. Roosevelt --- Hoa Kỳ, 1921",
          "Năm",
          [("Năm 1921, Franklin D. Roosevelt bị bại liệt do bệnh bại liệt và nhiều người nghĩ sự nghiệp chính trị của ông đã kết thúc.",
            "In 1921, Franklin D. Roosevelt was paralysed by polio and many believed his political career was finished."),
           ("Người bạn Louis Howe không nghĩ như vậy; ông từ chối để FDR từ bỏ và không ngừng lên kế hoạch cho tương lai.",
            "His friend Louis Howe did not think so; he refused to let FDR give up and never stopped planning for the future."),
           ("Khi FDR nản lòng và nói: ``Tôi không thể làm chính trị với đôi chân không đứng được.'' Howe đáp:",
            "When FDR despaired and said: `I cannot do politics with legs that cannot stand.' Howe replied:"),
           ("``Anh ngồi trên chiếc ghế đó mà vẫn có thể trở thành Tổng Thống --- và ta sẽ giúp anh làm điều đó.''",
            "`You can still become President from that chair --- and I will help you do it.'"),
           ("FDR trở thành Tổng Thống bốn nhiệm kỳ và lãnh đạo nước Mỹ qua Đại Khủng Hoảng và Thế chiến II --- nhờ niềm tin của một người bạn.",
            "FDR became a four-term President and led America through the Great Depression and World War II --- thanks to the faith of one friend.")],
          "Người bạn tốt nhất là người nhìn thấy điều bạn có thể trở thành --- ngay cả khi bạn không còn nhìn thấy điều đó nữa.",
          "The best friend is one who sees what you can become --- even when you can no longer see it yourself."),
    ])

with open(os.path.join(BASE, "ch04-ban-be-tri-ky.tex"), "w", encoding="utf-8") as f:
    f.write(ch4)
print("ch04 done")

# ================================================================
# CHƯƠNG 5: NHÂN QUẢ
# ================================================================
ch5 = chapter(
    "Nhân Quả --- Những Gì Bạn Gieo, Bạn Sẽ Gặt", "Cause and Effect --- You Reap What You Sow",
    "Mỗi hạt giống thiện lành được gieo hôm nay là một đoá hoa sẽ nở mai sau.",
    "Every seed of goodness sown today is a flower that will bloom tomorrow.",
    [
    story("Fleming Và Churchill --- Nhân Quả Xuyên Thế Hệ", "Alexander Fleming và Winston Churchill --- Anh, 1908",
          "Một",
          [("Một ngày mưa năm 1908, một nông dân nghèo tên Alec Fleming nghe thấy tiếng kêu cứu từ vũng lầy.",
            "On a rainy day in 1908, a poor farmer named Alec Fleming heard cries for help from a muddy bog."),
           ("Ông lao xuống cứu một cậu bé đang sắp chết đuối --- không hỏi tên, không mong trả ơn.",
            "He plunged in to save a young boy who was nearly drowning --- asking no name, expecting no reward."),
           ("Hôm sau, một quý tộc giàu có đến cảm ơn và hỏi: ``Tôi có thể giúp gì cho ông không?'' --- đó là cha của cậu bé.",
            "The next day, a wealthy lord came to thank him and asked: `Can I do anything for you?' --- he was the boy's father."),
           ("Fleming từ chối nhận tiền nhưng nhận học bổng cho con trai ông --- người con đó trở thành Alexander Fleming, người phát minh ra penicillin.",
            "Fleming refused money but accepted a scholarship for his son --- that son became Alexander Fleming, who discovered penicillin."),
           ("Cậu bé được cứu năm xưa, lớn lên từ học bổng cũng được tặng, là Winston Churchill --- chính penicillin đã cứu mạng ông sau này.",
            "The boy saved that day, later also given a scholarship by that lord, was Winston Churchill --- penicillin itself would later save his life.")],
          "Một hành động tốt gieo ra thường trở về nhiều hơn bạn có thể hình dung --- và thường là khi bạn quên nó từ lâu rồi.",
          "A good deed sown often returns far more than you can imagine --- and usually long after you have forgotten it."),

    story("Cụ Già Và Cây Hồ Đào --- Trồng Cây Cho Đời Sau", "Truyện Cổ La Mã --- Cicero kể lại",
          "Một",
          [("Một lữ khách đi ngang qua thấy một cụ già đang cần mẫn trồng cây hồ đào bên vườn.",
            "A traveller passing by saw an old man diligently planting walnut trees by his garden."),
           ("Lữ khách dừng lại hỏi: ``Cụ ơi, cây này hai mươi năm nữa mới có quả; cụ còn sống đến lúc đó không?''",
            "The traveller stopped and asked: `Old man, this tree won't bear fruit for twenty years; will you live to see it?'"),
           ("Cụ già mỉm cười đáp: ``Tôi ăn quả hồ đào cả đời mà quả đó do ai đó trước tôi trồng.''",
            "The old man smiled and replied: `I have eaten walnuts all my life, and those trees were planted by someone before me.'"),
           ("``Đến lượt tôi, tôi trồng cho người đến sau tôi --- đó là cách thế giới này tiếp tục.''",
            "`Now it is my turn to plant for those who come after me --- that is how this world continues.'"),
           ("Cicero kể lại câu chuyện này và nói: ``Những ai trồng cây mà họ không được hái quả là những người thật sự đang phục vụ tương lai.''",
            "Cicero retold this story and said: `Those who plant trees under whose shade they shall never sit are truly serving the future.'")],
          "Một xã hội phát triển là xã hội mà các ông già trồng cây biết họ sẽ không ngồi dưới bóng mát của nó.",
          "A society grows great when old men plant trees whose shade they know they shall never sit in."),

    story("Andrew Carnegie Và Thư Viện Miễn Phí", "Andrew Carnegie --- Hoa Kỳ, 1881",
          "Andrew",
          [("Andrew Carnegie lớn lên trong nghèo khó; trái tim ông thay đổi khi một người hàng xóm giàu có cho ông mượn sách.",
            "Andrew Carnegie grew up in poverty; his heart changed when a wealthy neighbour allowed him to borrow books freely."),
           ("``Kẻ cho tôi đọc sách đó không biết rằng ông ta đang thay đổi cả cuộc đời tôi,'' ông kể lại.",
            "`The man who gave me access to those books did not know he was changing my entire life,' he recalled."),
           ("Khi trở thành tỷ phú, Carnegie nhớ lại ơn đó và dùng phần lớn tài sản xây 2.509 thư viện miễn phí trên khắp thế giới.",
            "When he became a billionaire, Carnegie remembered that kindness and used most of his wealth to build 2,509 free libraries worldwide."),
           ("Ông viết: ``Người giàu mà chết giàu là chết nhục --- vì họ có cơ hội làm thế giới tốt hơn mà đã không làm.''",
            "He wrote: `The man who dies rich dies disgraced --- for he had the chance to make the world better and chose not to.'"),
           ("Hàng triệu người đọc sách trong thư viện Carnegie đã thay đổi cuộc đời --- đó là hạt giống nhân quả từ một người hàng xóm tốt bụng.",
            "Millions who read in Carnegie's libraries changed their lives --- all seeded by one kind neighbour's generosity.")],
          "Một hành động tốt đến đúng lúc có thể nhân lên thành hàng triệu kết quả mà bạn không bao giờ nhìn thấy được.",
          "One timely good deed can multiply into millions of outcomes you will never be able to see."),

    story("Khổng Tử Và Học Trò Nghèo Nàn Nhất", "Khổng Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Trong",
          [("Trong số các học trò của Khổng Tử, Nhan Hồi là người nghèo nhất --- ông ở trong một căn nhà nhỏ và ăn cơm đạm bạc mỗi ngày.",
            "Among Confucius's students, Yan Hui was the poorest --- he lived in a small hut and ate simple rice daily."),
           ("Nhưng mỗi khi học, Nhan Hồi luôn là người hiểu sâu nhất và thực hành nghiêm chỉnh nhất.",
            "Yet whenever they studied, Yan Hui always understood most deeply and practised most diligently."),
           ("Khổng Tử hỏi ông tại sao sống khổ cực vậy mà lúc nào cũng vui; Nhan Hồi đáp:",
            "Confucius asked why, living so humbly, he was always joyful; Yan Hui replied:"),
           ("``Thầy dạy con rằng người quân tử tìm niềm vui trong việc làm điều phải --- con đang làm điều phải mỗi ngày.''",
            "`Master taught me that a noble person finds joy in doing what is right --- I am doing what is right every day.'"),
           ("Khổng Tử sau đó nói với các học trò: ``Nhan Hồi là người học của ta --- và ta học được nhiều điều từ ông ấy.''",
            "Confucius afterward told his students: `Yan Hui is my student --- and I have learned much from him.'")],
          "Người gieo hạt thiện lành mỗi ngày trong im lặng --- họ là người đang sống trong nhân quả quý nhất của cuộc đời.",
          "Those who sow seeds of goodness daily in silence --- they are living in the most precious cause and effect of life."),

    story("Matsutaro Shoriki Và Báo Yomiuri", "Matsutaro Shoriki --- Nhật Bản, 1924",
          "Matsutaro",
          [("Matsutaro Shoriki mua lại tờ báo Yomiuri Shimbun năm 1924 khi nó gần như phá sản hoàn toàn.",
            "Matsutaro Shoriki acquired the Yomiuri Shimbun newspaper in 1924 when it was nearly bankrupt."),
           ("Ông đầu tư vào phóng viên giỏi, đầu tư vào chất lượng tin tức thay vì chạy theo lợi nhuận ngắn hạn.",
            "He invested in skilled reporters and news quality instead of chasing short-term profit."),
           ("Những năm đầu lỗ nặng; nhiều người khuyên ông bán đi --- ông từ chối và tiếp tục gieo hạt chất lượng.",
            "The early years were heavy losses; many advised him to sell --- he refused and kept sowing seeds of quality."),
           ("Hai mươi năm sau, Yomiuri trở thành tờ báo có số người đọc lớn nhất toàn cầu --- công của những hạt giống tốt.",
            "Twenty years later, Yomiuri became the highest-circulation newspaper in the world --- the fruit of those good seeds."),
           ("Shoriki nói: ``Người gieo hạt chất lượng luôn gặt được chất lượng lại --- nhưng họ phải kiên nhẫn với mùa gặt.''",
            "Shoriki said: `Those who sow quality always reap quality in return --- but they must be patient with the harvest.'")],
          "Gieo hạt chất lượng là hành động can đảm nhất trong nền kinh tế ngắn hạn --- vì nó đòi hỏi tin tưởng vào tương lai.",
          "Sowing quality is the most courageous act in a short-term economy --- for it requires faith in the future."),

    story("Người Thợ Rèn La Mã Và Lưỡi Kiếm", "Truyện Cổ La Mã --- thế kỷ 1 TCN",
          "Trong",
          [("Trong thành Rome thời cộng hoà, có một người thợ rèn nổi tiếng làm kiếm tốt nhất thành phố.",
            "In republican Rome, there was a blacksmith famous for forging the finest swords in the city."),
           ("Học trò hỏi bí quyết; ông chỉ vào bể nước lạnh và nói: ``Đây là người thầy thật sự của ta.''",
            "His apprentice asked his secret; he pointed to the cold water basin and said: `This is my true teacher.'"),
           ("Ông giải thích: ``Sắt nung nóng của ta chỉ trở nên cứng dẻo sau khi chịu đựng được nước lạnh.''",
            "He explained: `My heated iron only becomes strong and flexible after enduring the cold water.'"),
           ("``Cuộc đời cũng vậy --- những thử thách và khó khăn không phá hủy bạn; chúng hun đúc bạn thành con người tốt hơn.''",
            "`Life is the same --- trials and hardships do not destroy you; they forge you into a better person.'"),
           ("Mỗi lưỡi kiếm ông rèn ra mang trong mình cả triết học này --- và chúng không bao giờ gãy trong trận chiến.",
            "Every sword he forged carried this philosophy within it --- and they never broke in battle.")],
          "Những thử thách bạn trải qua không phải hình phạt --- chúng là quá trình rèn luyện để bạn trở nên bền vững hơn.",
          "The trials you go through are not punishments --- they are the forging process that makes you more resilient."),

    story("Martin Luther King Jr. Và Hạt Giống Bình Đẳng", "Martin Luther King Jr. --- Hoa Kỳ, 1955",
          "Martin",
          [("Martin Luther King Jr. biết rằng cuộc đấu tranh dân quyền sẽ không xong trong đời ông.",
            "Martin Luther King Jr. knew the civil rights struggle would not be completed in his lifetime."),
           ("Nhưng ông tiếp tục gieo hạt --- mỗi bài phát biểu, mỗi cuộc tuần hành, mỗi hành động bất tuân thủ ôn hoà.",
            "But he kept sowing seeds --- every speech, every march, every act of peaceful non-compliance."),
           ("Ông nói với những người ủng hộ đang nản lòng: ``Chúng ta có thể không nhìn thấy hết Đất Hứa, nhưng chúng ta sẽ đến được.''",
            "He told discouraged supporters: `We may not all see the Promised Land, but we, as a people, will get there.'"),
           ("Năm 1968, ông bị ám sát trước khi thấy nhiều thành quả --- nhưng hạt giống ông gieo không bao giờ dừng lớn.",
            "In 1968 he was assassinated before seeing many fruits --- but the seeds he sowed never stopped growing."),
           ("Barack Obama, Tổng Thống da đen đầu tiên của Hoa Kỳ, nói trong diễn văn nhậu chức: ``Chúng ta đã đến được He.''",
            "Barack Obama, America's first Black President, said in his inaugural address: `We have arrived.'")],
          "Hạt giống gieo vào một thế hệ thường nở hoa ở thế hệ sau --- đó không phải thất bại mà là kế hoạch của lịch sử.",
          "Seeds sown in one generation often bloom in the next --- that is not failure but the plan of history."),

    story("Người Phụ Nữ Và Bát Cơm Cứu Người", "Truyện Dân Gian Châu Á",
          "Trong",
          [("Trong một làng quê nghèo, có một người phụ nữ goá bụa mỗi ngày để dành một bát cơm ở cổng cho người qua đường đói.",
            "In a poor village, a widowed woman every day left one bowl of rice at her gate for any passing hungry traveller."),
           ("Nhiều năm trôi qua; ai cũng biết về bát cơm đó nhưng không ai biết ai để lại ngoài bà.",
            "Years passed; everyone knew of the bowl but no one knew who left it except for her."),
           ("Một năm mất mùa khủng khiếp ập đến; làng đói kém, bà cũng không còn gì để ăn.",
            "One year a terrible famine struck; the village went hungry, and she herself had nothing left to eat."),
           ("Đúng lúc đó, cả làng kéo đến trước nhà bà --- mỗi người mang một bát thức ăn từ nhà họ để trả ơn.",
            "At that moment, the whole village came to her door --- each person carrying a bowl of food from their own home to repay her."),
           ("Bà hiểu ra rằng bát cơm nhỏ bé nhiều năm của bà đã lặng lẽ gieo một mùa gặt lớn trong lòng người.",
            "She understood that her small daily bowl over many years had quietly sown a great harvest in human hearts.")],
          "Những hành động tốt nhỏ bé lặp đi lặp lại mỗi ngày tích luỹ thành một kho tàng lòng người lớn hơn bạn biết.",
          "Small good deeds repeated daily accumulate into a treasury of human goodwill greater than you know."),

    story("Người Đào Giếng Và Làng Khát Nước", "Truyện Dân Gian Việt Nam",
          "Ngày",
          [("Ngày xưa có một người nông dân tốt bụng thấy cả làng mình đi xa mới có nước uống, ông quyết tâm đào giếng.",
            "Long ago, a kind farmer seeing his whole village must travel far for water, resolved to dig a well."),
           ("Ông đào một mình suốt ba tháng; người trong làng ban đầu cười nhạo vì đất vùng đó rất khô cằn.",
            "He dug alone for three months; villagers at first laughed at him for the land there was notoriously dry."),
           ("Đến tháng thứ tư, nước bắt đầu rỉ ra; đến tháng thứ năm, giếng đầy nước trong mát.",
            "By the fourth month, water began seeping up; by the fifth month, the well was full of cool clear water."),
           ("Cả làng đổ ra uống nước mà không ai hỏi người đào là ai; nhưng người nông dân không cần ai hỏi.",
            "The whole village came to drink and no one asked who had dug it; but the farmer needed no one to ask."),
           ("Ông nói với con cái: ``Giếng nước ngọt ta đào là để tặng làng --- và đó chính là điều ta sẽ không bao giờ thấy mất đi.''",
            "He told his children: `The sweet-water well I dug is a gift to the village --- and that is something I will never see taken away.'")],
          "Hành động tốt không cần người biết tên bạn --- nó tự mang theo sức mạnh của chính mình vào thế giới.",
          "Good deeds do not need anyone to know your name --- they carry their own power into the world."),

    story("Người Đầu Bếp Nhật Và Sự Kiên Định Về Chất Lượng", "Truyện Truyền Thống Nhật Bản",
          "Có",
          [("Có một người đầu bếp sushi ở Tokyo dành 10 năm chỉ học cách nấu nồi cơm --- trước khi được phép đụng vào cá.",
            "A sushi chef in Tokyo spent 10 years learning only to cook rice --- before being permitted to touch the fish."),
           ("Học trò thường nản lòng và hỏi tại sao mất quá nhiều thời gian cho một việc dường như đơn giản.",
            "Apprentices often grew discouraged and asked why so much time was spent on something seemingly simple."),
           ("Người thầy trả lời: ``Cơm là nền tảng; nếu nền tảng không hoàn hảo, mọi thứ trên đó đều lung lay.''",
            "The master replied: `Rice is the foundation; if the foundation is not perfect, everything above it is unstable.'"),
           ("Học trò học cách nấu cơm mười năm rồi sau đó học mọi thứ còn lại trong ba năm --- vì nền tảng vững chắc.",
            "The apprentice spent ten years learning rice then learned everything else in three --- because the foundation was solid."),
           ("Triết học ông dạy là: hãy gieo hạt kỹ năng cơ bản thật sâu trước --- mọi thứ còn lại sẽ theo sau.",
            "The philosophy he taught was: sow the seed of basic skill deeply first --- everything else will follow.")],
          "Gieo hạt kỹ năng nền tảng thật nghiêm túc và thật sâu --- đó là khoản đầu tư sinh lợi lâu dài nhất trong bất kỳ nghề nào.",
          "Sow the seeds of foundational skills seriously and deeply --- that is the longest-lasting investment in any craft."),
    ])

with open(os.path.join(BASE, "ch05-nhan-qua.tex"), "w", encoding="utf-8") as f:
    f.write(ch5)
print("ch05 done")

# ================================================================
# CHƯƠNG 6: VƯỢT QUA NGHỊCH CẢNH
# ================================================================
ch6 = chapter(
    "Vượt Qua Nghịch Cảnh --- Lửa Thử Vàng, Gian Nan Thử Sức", "Overcoming Adversity --- Fire Tests Gold, Hardship Tests Character",
    "Nhân vật được hình thành không phải trong sự thoải mái và tiện nghi mà trong những thử thách và giông tố.",
    "Character is not formed in ease and comfort but in trial and storm.",
    [
    story("Helen Keller --- Ánh Sáng Từ Bóng Tối", "Helen Keller --- Hoa Kỳ, 1887",
          "Helen",
          [("Helen Keller bị mù và điếc từ năm dưới hai tuổi vì một cơn bệnh; thế giới của bà là bóng tối và im lặng tuyệt đối.",
            "Helen Keller became blind and deaf before age two from an illness; her world was total darkness and absolute silence."),
           ("Cha mẹ bà không biết phải làm gì; họ thuê Anne Sullivan --- người thầy sẽ thay đổi tất cả mọi thứ.",
            "Her parents did not know what to do; they hired Anne Sullivan --- the teacher who would change everything."),
           ("Sau nhiều tháng đau khổ và giận dữ, một ngày tại bơm nước, Helen hiểu ra rằng mọi thứ đều có tên gọi.",
            "After months of anguish and fury, one day at the water pump, Helen understood that everything had a name."),
           ("Từ đó bà học đọc, học viết, học nói --- và trở thành nhà văn, diễn giả, nhà hoạt động xã hội nổi tiếng toàn cầu.",
            "From then she learned to read, write, and speak --- becoming a globally renowned writer, lecturer, and social activist."),
           ("Bà nói: ``Mặc dù thế giới đầy khổ đau, nó cũng đầy những con người vượt lên trên khổ đau đó.''",
            "She said: `Although the world is full of suffering, it is also full of the overcoming of it.'")],
          "Nghịch cảnh không định nghĩa bạn là ai; phản ứng của bạn với nghịch cảnh mới là thứ định nghĩa bạn.",
          "Adversity does not define who you are; your response to adversity is what defines you."),

    story("Beethoven --- Bản Nhạc Của Người Điếc", "Ludwig van Beethoven --- Đức, 1818",
          "Ludwig",
          [("Ludwig van Beethoven bắt đầu mất thính giác từ năm 27 tuổi --- nguồn sống và công cụ kiếm sống của ông.",
            "Ludwig van Beethoven began losing his hearing at age 27 --- his life's breath and livelihood."),
           ("Ông viết thư tuyệt vọng nói về việc tự kết liễu cuộc đời mình; nhưng cuối cùng ông chọn âm nhạc.",
            "He wrote desperate letters speaking of ending his own life; but ultimately he chose music."),
           ("``Nhiệm vụ nghệ thuật của tôi vẫn chưa hoàn thành,'' ông viết, ``và tôi không thể rời đi cho đến khi làm xong.''",
            "`My artistic mission is not yet complete,' he wrote, `and I cannot leave until it is done.'"),
           ("Bản Giao Hưởng Số 9 --- kiệt tác lớn nhất của ông --- được viết khi ông hoàn toàn điếc, không nghe được một nốt nhạc.",
            "The Ninth Symphony --- his greatest masterpiece --- was composed when he was completely deaf, unable to hear a single note."),
           ("Khi ông chỉ huy buổi ra mắt và khán phòng đứng dậy vỗ tay, người ta phải quay ông lại để ông biết rằng họ đang hoan nghênh.",
            "When he conducted the premiere and the audience rose in applause, someone had to turn him around so he could know they were cheering.")],
          "Những gì bạn mất trong nghịch cảnh đôi khi là thứ giải phóng bạn tìm ra thứ sâu hơn bên trong bản thân.",
          "What you lose in adversity sometimes is what frees you to find something deeper within yourself."),

    story("J.K. Rowling --- Từ Nghèo Khổ Đến Harry Potter", "J.K. Rowling --- Anh, 1995",
          "Joanne",
          [("Joanne Rowling năm 1995 là người mẹ đơn thân nghèo khổ, đang trầm cảm, đang sống nhờ trợ cấp xã hội.",
            "Joanne Rowling in 1995 was a poor single mother, suffering depression, living on welfare benefits."),
           ("Nhưng bà viết --- mỗi ngày, trong quán cà phê nhỏ ở Edinburgh, khi con gái ngủ trong xe đẩy bên cạnh.",
            "But she wrote --- every day, in a small Edinburgh café, while her baby daughter slept in a pushchair beside her."),
           ("Mười hai nhà xuất bản từ chối Harry Potter; bà tiếp tục gửi và tiếp tục tin tưởng vào câu chuyện của mình.",
            "Twelve publishers rejected Harry Potter; she kept submitting and kept believing in her story."),
           ("Khi nhà xuất bản thứ mười ba nhận, người biên tập khuyên bà đừng hy vọng kiếm tiền từ sách thiếu nhi.",
            "When the thirteenth publisher accepted, the editor advised her not to expect to earn money from children's books."),
           ("Harry Potter trở thành bộ sách thiếu nhi bán chạy nhất mọi thời đại; Rowling từ người sống nhờ trợ cấp thành tỷ phú.",
            "Harry Potter became the best-selling children's series of all time; Rowling went from welfare to billionaire.")],
          "Nghịch cảnh không phải là lý do để dừng lại --- nó là môi trường trong đó những tác phẩm lớn nhất thường được tạo ra.",
          "Adversity is not a reason to stop --- it is the environment in which the greatest works are often created."),

    story("Abraham Lincoln --- Danh Sách Thất Bại Vẫn Đứng Dậy", "Abraham Lincoln --- Hoa Kỳ, 1861",
          "Abraham",
          [("Abraham Lincoln thất bại trong kinh doanh năm 1831, thất bại tranh cử lần đầu năm 1832, người yêu mất năm 1835.",
            "Abraham Lincoln failed in business in 1831, lost his first election in 1832, and lost his sweetheart in 1835."),
           ("Ông suy sụp tinh thần trầm trọng năm 1836, thất bại tranh cử Quốc Hội năm 1843 và 1848.",
            "He suffered serious nervous breakdown in 1836, lost Congressional elections in 1843 and 1848."),
           ("Thất bại tranh cử Thượng Nghị Viện năm 1855 và 1858; thất bại tranh cử Phó Tổng Thống năm 1856.",
            "Lost Senate races in 1855 and 1858; lost the Vice-Presidential nomination in 1856."),
           ("Năm 1860, Abraham Lincoln được bầu làm Tổng Thống thứ 16 của Hoa Kỳ và trở thành một trong những Tổng Thống vĩ đại nhất.",
            "In 1860, Abraham Lincoln was elected the 16th President of the United States and became one of its greatest."),
           ("Ông nói: ``Thành công là đi từ thất bại này sang thất bại khác mà không mất đi sự nhiệt tình.''",
            "He said: `Success is going from failure to failure without loss of enthusiasm.'")],
          "Lịch sử của thành công lớn gần như luôn là lịch sử của những thất bại liên tiếp --- điều khác biệt là không dừng lại.",
          "The history of great success is almost always the history of repeated failures --- the difference is not stopping."),

    story("Nick Vujicic --- Không Tay Không Chân Không Giới Hạn", "Nick Vujicic --- Úc, 1982",
          "Nick",
          [("Nick Vujicic sinh ra không có tay và không có chân --- trong một thế giới được thiết kế cho những người có đủ tứ chi.",
            "Nick Vujicic was born without arms and without legs --- in a world designed for people with all four limbs."),
           ("Thuở nhỏ ông từng cố tự làm hại mình vì không thể chịu đựng được cảm giác khác biệt và cô đơn.",
            "As a child he once tried to harm himself, unable to endure the feeling of being different and alone."),
           ("Nhưng ở tuổi mười chín ông nhận ra rằng ông có thể chọn cách sống của mình --- và ông chọn niềm vui.",
            "But at nineteen he realised he could choose how to live --- and he chose joy."),
           ("Ông học bơi, học lướt sóng, lấy bằng đại học, kết hôn, có bốn con --- và đi diễn thuyết khắp thế giới.",
            "He learned to swim, to surf, earned a university degree, married, had four children --- and speaks all over the world."),
           ("Ông nói: ``Nếu Chúa không cho tôi điều tôi muốn, có lẽ Ngài muốn cho tôi điều tôi cần.''",
            "He says: `If God does not give me what I want, maybe He wants to give me what I need.'")],
          "Không có tình huống nào là hoàn toàn vô vọng; điều duy nhất cần là ý chí muốn tìm thấy ý nghĩa trong hoàn cảnh đó.",
          "No situation is truly hopeless; the only thing needed is the will to find meaning within that circumstance."),

    story("Stephen Hawking --- Trí Tuệ Vẫn Bay Trong Thân Xác Bị Giam Lỏng", "Stephen Hawking --- Anh, 1963",
          "Stephen",
          [("Stephen Hawking được chẩn đoán bệnh ALS năm 21 tuổi, khi các bác sĩ cho ông biết ông chỉ còn vài năm sống.",
            "Stephen Hawking was diagnosed with ALS at 21, when doctors told him he had only a few years to live."),
           ("Ông rơi vào trầm cảm nặng --- cho đến khi ông nhận ra rằng tâm trí ông vẫn hoàn toàn tự do.",
            "He fell into deep depression --- until he realised his mind was still completely free."),
           ("Thay vì đầu tư vào cơ thể đang mục nát, ông đầu tư hoàn toàn vào trí tuệ và vũ trụ học.",
            "Instead of focusing on his deteriorating body, he invested completely in his mind and cosmology."),
           ("Ông sống thêm 55 năm sau chẩn đoán đó và viết ra Lược Sử Thời Gian --- cuốn sách khoa học bán chạy nhất lịch sử.",
            "He lived 55 more years after that diagnosis and wrote A Brief History of Time --- the best-selling science book in history."),
           ("Ông nói: ``Dù cuộc đời có khó khăn đến đâu, bạn vẫn luôn có thể làm điều gì đó và thành công.''",
            "He said: `However difficult life may seem, there is always something you can do and succeed at.'")],
          "Thân xác có thể bị giới hạn nhưng ý chí và tâm trí --- khi được nuôi dưỡng đúng cách --- không bao giờ bị giới hạn.",
          "The body can be limited but the will and mind --- when properly nurtured --- are never bound."),

    story("Malala Yousafzai --- Đứng Dậy Sau Viên Đạn", "Malala Yousafzai --- Pakistan, 2012",
          "Ngày",
          [("Ngày 9 tháng 10 năm 2012, Malala Yousafzai, 15 tuổi, bị Taliban bắn vào đầu vì dám cổ suý quyền học hành cho bé gái.",
            "On October 9, 2012, Malala Yousafzai, aged 15, was shot in the head by the Taliban for advocating girls' education."),
           ("Các bác sĩ không chắc bà có sống sót không; nhưng sau ba tháng chăm sóc y tế chuyên sâu, bà hồi phục.",
            "Doctors were not sure she would survive; but after three months of intensive medical care, she recovered."),
           ("Khi được hỏi bà có sợ không sau vụ ám sát, Malala nói: ``Họ đã câm lặng được tiếng nói của tôi một ngày --- nhưng chỉ một ngày.''",
            "When asked if she was afraid after the assassination attempt, Malala said: `They silenced my voice for one day --- but only one day.'"),
           ("Bà tiếp tục vận động cho giáo dục, diễn thuyết tại Liên Hiệp Quốc khi 16 tuổi, và nhận giải Nobel Hoà Bình khi 17 tuổi.",
            "She continued advocating for education, addressed the UN at 16, and received the Nobel Peace Prize at 17."),
           ("Malala nói: ``Một đứa trẻ, một giáo viên, một cuốn sách và một cái bút có thể thay đổi thế giới.''",
            "Malala said: `One child, one teacher, one book and one pen can change the world.'")],
          "Nghịch cảnh có thể xô ngã bạn nhưng không thể tiêu huỷ ý chí của bạn --- trừ khi bạn tự cho phép nó làm điều đó.",
          "Adversity can knock you down but cannot destroy your will --- unless you allow it to."),

    story("Edison --- Nhà Máy Bị Cháy Không Tắt Được Tinh Thần", "Thomas Edison --- Hoa Kỳ, 1914",
          "Năm",
          [("Năm 1914, nhà máy của Edison bị bốc cháy toàn bộ --- thiệt hại ước tính 23 triệu đô la theo thời giá lúc đó.",
            "In 1914, Edison's factory complex burst into flames --- total damage estimated at 23 million dollars in period values."),
           ("Edison, 67 tuổi, đứng nhìn lửa thiêu rụi công trình của cả đời mình mà không khóc, không sụp đổ.",
            "Edison, aged 67, stood watching the fire consuming his life's work without weeping, without collapsing."),
           ("Ông gọi con trai đến và nói: ``Hãy đi gọi mẹ và bạn bè của con đến --- họ sẽ không bao giờ thấy lại ngọn lửa như thế này.''",
            "He called his son over and said: `Go get your mother and her friends --- they will never see a fire like this again.'"),
           ("Ngày hôm sau, Edison đã bắt đầu kế hoạch xây dựng lại nhà máy.",
            "The very next day, Edison had already begun planning to rebuild the factory."),
           ("Ông nói: ``Thảm hoạ có giá trị vì nó xoá sạch tất cả những sai lầm cũ của mình và cho ta cơ hội bắt đầu lại mới mẻ hơn.''",
            "He said: `Disaster has value because it clears away all my old mistakes and gives me the chance to start fresh.'")],
          "Nghịch cảnh không thể lấy đi từ bạn điều bạn đã học được --- và kiến thức đó chính là nền tảng để bắt đầu lại.",
          "Adversity cannot take from you what you have already learned --- and that knowledge is the foundation for starting again."),

    story("Nguyễn Ngọc Ký --- Viết Bằng Chân, Sống Bằng Ý Chí", "Nguyễn Ngọc Ký --- Việt Nam, 1956",
          "Nguyễn",
          [("Nguyễn Ngọc Ký bị liệt cả hai tay từ khi còn nhỏ bởi một trận bệnh --- trong khi các bạn đồng lứa cầm bút bằng tay.",
            "Nguyen Ngoc Ky was paralysed in both arms from childhood by an illness --- while his peers held pens with their hands."),
           ("Ông quyết tâm đi học và học viết bằng chân --- một quá trình đau đớn và nhọc nhằn kéo dài nhiều năm.",
            "He was determined to study and trained himself to write with his feet --- a painful and laborious process lasting years."),
           ("Thầy hiệu trưởng ban đầu từ chối nhận ông vì nghi ngại về khả năng theo kịp; nhưng ông kiên trì.",
            "The headmaster initially refused to admit him, doubting his ability to keep up; but he persisted."),
           ("Ông đỗ đại học, trở thành giáo viên dạy văn, viết nhiều tác phẩm và nhận danh hiệu Nhà giáo nhân dân.",
            "He passed university entrance exams, became a literature teacher, wrote many works, and received the title of People's Teacher."),
           ("Ông nói: ``Hai bàn tay không làm được nhưng ý chí không bao giờ bị liệt --- và ý chí mới là thứ tôi cần.''",
            "He said: `My two hands could not work, but my will was never paralysed --- and it is will that I have needed.'")],
          "Thứ cơ thể không làm được, ý chí và sự kiên trì có thể tìm cách hoàn thành --- theo cách riêng của chúng.",
          "What the body cannot do, will and persistence can find a way to accomplish --- in their own fashion."),

    story("Florence Nightingale Và Sức Kháng Cự Của Tổ Chức", "Florence Nightingale --- Anh, 1854",
          "Khi",
          [("Khi Florence Nightingale đến Crimea để cứu thương binh, quân đội Anh không chào đón bà --- họ từ chối hợp tác.",
            "When Florence Nightingale arrived in Crimea to nurse the wounded, the British army did not welcome her --- they refused to cooperate."),
           ("Các bác sĩ quân y coi bà là kẻ xâm phạm lãnh thổ của họ; quản lý bệnh xá chặn không cho bà làm gì.",
            "Military surgeons saw her as an intruder in their territory; hospital administrators blocked her at every step."),
           ("Bà không tranh cãi --- bà thu thập số liệu và dùng biểu đồ Coxcomb nổi tiếng để chứng minh binh sĩ đang chết vì điều kiện vệ sinh.",
            "She did not argue --- she collected data and used her famous Coxcomb diagram to prove soldiers were dying from sanitary conditions."),
           ("Bằng chứng không thể phủ nhận; dần dần bà được trao quyền cải thiện các bệnh xá, và tỉ lệ tử vong giảm mạnh.",
            "The evidence was irrefutable; gradually she was given authority to improve the wards, and mortality rates fell sharply."),
           ("Bà chứng minh rằng nghịch cảnh từ thể chế có thể bị vượt qua bằng sự thật được chứng minh bằng dữ liệu.",
            "She proved that institutional adversity can be overcome with truth backed by data.")],
          "Khi đối mặt với tường rào quyền lực, đừng phá tường --- hãy thu thập bằng chứng không thể bị bác bỏ để từ từ mở cửa.",
          "When facing a wall of power, don't try to break it --- gather irrefutable evidence to gradually open its gate."),
    ])

with open(os.path.join(BASE, "ch06-vuot-nghich-canh.tex"), "w", encoding="utf-8") as f:
    f.write(ch6)
print("ch06 done")

# ================================================================
# CHƯƠNG 7: TỰ BIẾT MÌNH
# ================================================================
ch7 = chapter(
    "Tự Biết Mình --- Trí Tuệ Bắt Đầu Từ Sự Khiêm Tốn", "Know Thyself --- Wisdom Begins with Humility",
    "Biết người khác là khôn ngoan; biết chính mình là giác ngộ.",
    "Knowing others is wisdom; knowing yourself is enlightenment.",
    [
    story("Socrates --- Tôi Chỉ Biết Rằng Tôi Không Biết Gì", "Socrates --- Hy Lạp, thế kỷ 5 TCN",
          "Khi",
          [("Khi nhà tiên tri Oracle ở Delphi công bố rằng Socrates là người khôn ngoan nhất Athens, ông không tin và đi kiểm chứng.",
            "When the Oracle at Delphi declared Socrates the wisest man in Athens, he disbelieved it and set out to verify."),
           ("Ông đến gặp những người được xem là khôn ngoan nhất --- chính khách, nhà thơ, các nghệ nhân --- và đặt câu hỏi cho họ.",
            "He visited those considered wisest --- statesmen, poets, craftsmen --- and questioned them all."),
           ("Ông nhận ra rằng tất cả họ đều nghĩ mình biết những điều mà thực ra họ không biết.",
            "He found that every one of them thought they knew things they actually did not know."),
           ("Còn ông --- ông không biết gì, nhưng ít nhất ông biết rằng mình không biết gì.",
            "Whereas he --- he knew nothing, but at least he knew that he knew nothing."),
           ("Ông kết luận: ``Tôi khôn ngoan hơn những người đó một chút thôi: tôi không nghĩ mình biết điều tôi không biết.''",
            "He concluded: `I am only wiser than those people in this one small way: I do not think I know what I do not know.'")],
          "Bước đầu tiên của sự khôn ngoan là nhận ra giới hạn của kiến thức của chính mình --- không phải thể hiện ra kiến thức đó.",
          "The first step of wisdom is recognising the limits of your own knowledge --- not displaying what you know."),

    story("Benjamin Franklin Và Danh Sách Đức Hạnh", "Benjamin Franklin --- Hoa Kỳ, 1726",
          "Năm",
          [("Năm 20 tuổi, Benjamin Franklin lập ra một hệ thống tự hoàn thiện bản thân gồm 13 đức hạnh cần rèn luyện.",
            "At 20, Benjamin Franklin created a self-improvement system of 13 virtues he wished to cultivate."),
           ("Mỗi tuần ông tập trung vào một đức hạnh --- tiết độ, kiên nhẫn, trật tự, khiêm tốn --- và tự chấm điểm hàng ngày.",
            "Each week he focused on one virtue --- temperance, silence, order, humility --- grading himself daily."),
           ("Ông phát hiện ra `khiêm tốn' là đức hạnh khó rèn nhất --- ngay khi ông nghĩ mình đã khiêm tốn, ông biết mình đang kiêu ngạo.",
            "He found `humility' the hardest virtue to cultivate --- the moment he thought he had achieved it, he knew he was proud."),
           ("Franklin viết: ``Tôi không thể tự hào về việc hoàn toàn đạt được sự khiêm tốn; nhưng tôi thành công trong việc không khoe khoang về nó.''",
            "Franklin wrote: `I cannot boast of much success in acquiring humility; but I had the advantage of not boasting about it.'"),
           ("Hệ thống tự hoàn thiện đó ông thực hành suốt đời --- không bao giờ Đánh dấu hoàn thành, luôn tìm chỗ để cải thiện.",
            "He practised that self-improvement system his whole life --- never marking it complete, always finding room to improve.")],
          "Người khôn ngoan không bao giờ ngừng tự đặt câu hỏi về chính mình --- vì sự hoàn thiện bản thân là hành trình, không phải điểm đến.",
          "The wise person never stops questioning themselves --- for self-improvement is a journey, not a destination."),

    story("Marcus Aurelius --- Hoàng Đế Triết Học", "Marcus Aurelius --- Rome, thế kỷ 2",
          "Mỗi",
          [("Mỗi buổi sáng trước khi bắt đầu xử lý công việc triều đình, Marcus Aurelius ngồi viết nhật ký tự kiểm.",
            "Each morning before beginning court business, Marcus Aurelius sat and wrote his self-examination journal."),
           ("Ông viết những điều người có thể lý giải là nhỏ nhặt --- ``Tôi đã xử sự không tốt hôm qua; tôi có thể làm tốt hơn.''",
            "He wrote things some might consider trivial --- `I behaved poorly yesterday; I can do better.'"),
           ("Nhật ký không bao giờ được viết để xuất bản; nó là cuộc trò chuyện trung thực của ông với chính mình.",
            "The journal was never written to be published; it was his honest conversation with himself."),
           ("Ông viết: ``Nhìn vào bên trong. Bên trong là nguồn thiện lành; nếu bạn đào xuống, nó sẽ tuôn chảy mãi mãi.''",
            "He wrote: `Look within. Within is the fountain of good; if you dig there, it will always flow.'"),
           ("Suy Ngẫm --- cuốn nhật ký đó --- trở thành một trong những tác phẩm triết học vĩ đại nhất của mọi thời đại.",
            "Meditations --- that journal --- became one of the greatest philosophical works of all time.")],
          "Nhật ký tự kiểm viết không phải cho ai đọc mà cho chính mình --- là công cụ tự biết mình sâu sắc nhất.",
          "A self-examination journal written for no one else but yourself --- is the deepest tool for self-knowledge."),

    story("Tăng Sâm Và Ba Câu Hỏi Mỗi Ngày", "Khổng Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Tăng",
          [("Tăng Sâm, một môn đồ của Khổng Tử, có thói quen mỗi ngày tự hỏi mình ba câu hỏi trước khi đi ngủ.",
            "Zeng Shen, a disciple of Confucius, had the habit of asking himself three questions every night before sleep."),
           ("Câu hỏi thứ nhất: ``Hôm nay làm việc cho người khác, ta có tận tâm không?''",
            "First question: `In doing things for others today, was I fully faithful?'"),
           ("Câu hỏi thứ hai: ``Hôm nay giao tiếp với bạn bè, ta có thành thật không?''",
            "Second question: `In interacting with friends today, was I genuinely honest?'"),
           ("Câu hỏi thứ ba: ``Những điều thầy dạy, hôm nay ta đã ôn tập và thực hành chưa?''",
            "Third question: `The things my teacher taught, did I review and practise them today?'"),
           ("Ông thực hành nghi thức này suốt cả cuộc đời --- và trở thành một trong những người cao đức nhất trong trường Khổng Tử.",
            "He practised this nightly ritual his entire life --- and became one of the most virtuous within the Confucian school.")],
          "Ba câu hỏi tự kiểm mỗi đêm là phương pháp xây dựng nhân cách đáng tin cậy nhất --- vì chúng không để sai lầm tích luỹ.",
          "Three self-examination questions each night are the most reliable character-building method --- for they prevent mistakes from accumulating."),

    story("Gandhi --- Thí Nghiệm Sự Thật", "Mahatma Gandhi --- Ấn Độ, thế kỷ 20",
          "Trong",
          [("Trong cuốn tự truyện nổi tiếng của mình, Gandhi gọi cuộc đời ông là `Những thí nghiệm với sự thật'.",
            "In his famous autobiography, Gandhi called his life `Experiments with Truth.'"),
           ("Ông không xem bản thân là người hoàn hảo; ông xem bản thân là một nhà khoa học đang thí nghiệm cách sống đạo đức.",
            "He did not see himself as perfect; he saw himself as a scientist experimenting with how to live ethically."),
           ("Mỗi khi ông mắc sai lầm, ông ghi lại và coi đó là dữ liệu --- không phải là bằng chứng của sự thất bại.",
            "Whenever he made a mistake, he recorded it and treated it as data --- not as evidence of failure."),
           ("Ông giữ chay, kiêng khem và tự kiểm nghiệm thường xuyên --- không phải để đạt thánh thiện mà để hiểu bản thân.",
            "He fasted, abstained, and self-examined regularly --- not to achieve sainthood but to understand himself."),
           ("Ông viết: ``Sức mạnh không đến từ năng lực thể chất mà từ ý chí không khuất phục.''",
            "He wrote: `Strength does not come from physical capacity; it comes from an indomitable will.'")],
          "Tự biết mình không phải là một trạng thái tĩnh bạn đạt được --- mà là một quá trình liên tục thử nghiệm, ghi chép và điều chỉnh.",
          "Self-knowledge is not a static state you achieve --- it is a continuous process of experimenting, recording, and adjusting."),

    story("Einstein --- Tưởng Tượng Quan Trọng Hơn Kiến Thức", "Albert Einstein --- Đức, thế kỷ 20",
          "Albert",
          [("Albert Einstein xiêu hứng đứng đầu ở trường tiểu học và cấp hai --- thầy giáo nói với cha mẹ ông rằng ông không có năng lực.",
            "Albert Einstein was not a top student in primary or secondary school --- his teachers told his parents he lacked ability."),
           ("Ông trượt kỳ thi vào trường Bách Khoa Zurich lần đầu; ông mất việc sau khi tốt nghiệp, không ai thuê ông.",
            "He failed his first entrance exam to Zurich Polytechnic; he was unemployed after graduating, with no one willing to hire him."),
           ("Nhưng Einstein biết điều mà người khác không biết về bản thân ông: ông tư duy bằng hình ảnh và trực giác.",
            "But Einstein knew something others did not about himself: he thought in images and intuition."),
           ("Ông sử dụng những `thí nghiệm tư duy' --- tưởng tượng mình đang cưỡi trên một tia sáng --- và từ đó xây dựng lý thuyết tương đối.",
            "He used `thought experiments' --- imagining himself riding a beam of light --- and from that built the theory of relativity."),
           ("Ông luôn nói: ``Tưởng tượng quan trọng hơn kiến thức; vì kiến thức bị giới hạn còn tưởng tượng bao phủ toàn thế giới.''",
            "He always said: `Imagination is more important than knowledge; for knowledge is limited, while imagination encircles the world.'")],
          "Biết cách chính mình suy nghĩ và học hỏi tốt nhất là tri thức quý nhất giúp bạn khai thác mọi tiềm năng bên trong.",
          "Knowing how you yourself think and learn best is the most precious knowledge for unlocking all your inner potential."),

    story("Tolstoy --- Mảnh Gương Tự Phản Chiếu Trong Tác Phẩm", "Leo Tolstoy --- Nga, thế kỷ 19",
          "Leo",
          [("Leo Tolstoy là nhà văn vĩ đại nhất nước Nga; nhưng ít ai biết ông dùng tiểu thuyết như một tấm gương tự soi.",
            "Leo Tolstoy was Russia's greatest novelist; but few knew he used fiction as a mirror to examine himself."),
           ("Nhân vật Levin trong Anna Karenina và Pierre trong Chiến Tranh và Hoà Bình đều là hình ảnh của chính Tolstoy.",
            "The character Levin in Anna Karenina and Pierre in War and Peace were both portraits of Tolstoy himself."),
           ("Ông viết các nhân vật này để hiểu những câu hỏi mà ông không thể trả lời trong cuộc sống thực của mình.",
            "He wrote these characters to understand questions he could not answer in his own real life."),
           ("Tolstoy nhật ký bắt đầu ở tuổi mười tám và kết thúc vào đêm trước khi ông chết --- hơn sáu mươi năm tự kiểm.",
            "Tolstoy's diary began at eighteen and ended the night before he died --- over sixty years of self-examination."),
           ("Ông viết trong nhật ký: ``Điều quan trọng duy nhất trong cuộc đời là sống trung thực với chính mình.''",
            "He wrote in his diary: `The only important thing in life is to live in accordance with the truth of yourself.'")],
          "Sáng tạo và tự hiểu bản thân không phải hai con đường khác nhau --- khi được thực hành sâu, chúng là một.",
          "Creativity and self-understanding are not two separate paths --- when practised deeply, they are one."),

    story("Lê Thánh Tông --- Vua Tự Kiểm Để Trị Nước", "Lê Thánh Tông --- Việt Nam, thế kỷ 15",
          "Vua",
          [("Vua Lê Thánh Tông của Việt Nam nổi tiếng không chỉ vì tài năng quân sự mà còn vì tính tự kiểm bản thân.",
            "King Le Thanh Tong of Vietnam was famous not only for military talent but also for his habit of self-examination."),
           ("Ông lập ra Hội Tao Đàn --- câu lạc bộ thơ văn của vua và các đại thần --- để cùng nhau phê bình lẫn nhau.",
            "He founded the Tao Dan Society --- a poetry club of the king and officials --- to critique one another's work."),
           ("Ông không ngại để các học giả tranh luận với quan điểm của mình ngay trên sân triều.",
            "He was not averse to having scholars argue against his views right in the royal court."),
           ("Ông học tiếng Nôm không chỉ vì yêu văn chương mà vì ông muốn đọc trực tiếp nỗi lòng của người dân.",
            "He learned chu Nom not only for love of literature but because he wanted to read the people's hearts directly."),
           ("Triều đại của ông là đỉnh cao của văn minh Đai Việt --- nhờ một vị vua biết mình và không ngại học hỏi.",
            "His reign was the pinnacle of Dai Viet civilisation --- because of a king who knew himself and was unafraid to keep learning.")],
          "Người lãnh đạo tốt nhất là người không bao giờ ngừng tự hỏi: ``Ta đang lãnh đạo theo đúng giá trị mà ta tin chưa?''",
          "The best leader is one who never stops asking: `Am I leading in accordance with the values I truly believe in?'"),

    story("Diogenes --- Đốt Đuốc Giữa Ban Ngày Tìm Người Thật", "Diogenes --- Hy Lạp, thế kỷ 4 TCN",
          "Diogenes",
          [("Diogenes xứ Sinope một ngày đốt đuốc đi giữa ban ngày ở chợ Athens; người qua đường hỏi ông tìm gì.",
            "Diogenes of Sinope one day carried a lit torch in the marketplace in broad daylight; passersby asked what he sought."),
           ("Ông trả lời: ``Tôi đang tìm một người thật.'' --- ý muốn nói rằng người thật, người trung thực với bản thân, cực kỳ hiếm.",
            "He replied: `I am looking for an honest man.' --- meaning truly authentic, self-knowing people are exceedingly rare."),
           ("Khi Đại Đế Alexander đến thăm và hỏi ông muốn gì, Diogenes nói: ``Xin ông hãy đứng tránh ra khỏi ánh mặt trời của tôi.''",
            "When Alexander the Great visited and asked what he could do for him, Diogenes said: `Please step out of my sunlight.'"),
           ("Alexander, thay vì nổi giận, nói với tùy tùng: ``Nếu ta không phải là Alexander, ta muốn là Diogenes.''",
            "Alexander, instead of growing angry, told his entourage: `If I were not Alexander, I would wish to be Diogenes.'"),
           ("Diogenes sống hoàn toàn theo những gì ông tin --- không sợ hãi, không giả tạo, không thèm thuồng quyền lực.",
            "Diogenes lived completely in accordance with what he believed --- without fear, pretence, or craving for power.")],
          "Tự biết mình thật sự đồng nghĩa với sống thật với chính mình --- ngay cả khi điều đó không được thế giới chấp nhận.",
          "Truly knowing yourself means living authentically as yourself --- even when the world does not approve."),

    story("Khổng Tử Ở Tuổi Bảy Mươi --- Hành Trình Cả Đời Tự Hoàn Thiện", "Khổng Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Khổng",
          [("Khổng Tử tự mô tả hành trình trưởng thành của ông qua từng thập kỷ trong một câu nói nổi tiếng.",
            "Confucius described his own journey of growth decade by decade in one famous passage."),
           ("``Mười lăm tuổi, ta để tâm vào học; ba mươi tuổi, ta đứng vững; bốn mươi tuổi, ta không còn nghi ngờ.''",
            "`At fifteen, I set my heart on learning; at thirty, I stood firm; at forty, I had no more doubts.'"),
           ("``Năm mươi tuổi, ta hiểu mệnh trời; sáu mươi tuổi, tai ta nghe thấu; bảy mươi tuổi, ta theo lòng không trái lẽ.''",
            "`At fifty, I understood heaven's commands; at sixty, my ear understood truth; at seventy, I follow my heart without transgression.'"),
           ("Bảy mươi năm liên tục học hỏi và tự hoàn thiện --- chỉ đến cuối đời mới đạt đến trạng thái tự nhiên và hài hoà.",
            "Seventy years of continuous learning and self-cultivation --- only at life's end did he reach natural harmony."),
           ("Bài học của câu nói đó: tự biết mình không phải điểm kết thúc mà là hành trình trọn đời không bao giờ kết thúc.",
            "The lesson of those words: self-knowledge is not an endpoint but a lifelong journey that is never finished.")],
          "Cuộc đời là hành trình liên tục học cách trở thành người bạn muốn là --- và sự khôn ngoan là biết rằng hành trình đó không bao giờ hoàn tất.",
          "Life is the continuous journey of learning to become who you wish to be --- and wisdom is knowing that journey is never complete."),
    ])

with open(os.path.join(BASE, "ch07-tu-biet-minh.tex"), "w", encoding="utf-8") as f:
    f.write(ch7)
print("ch07 done")

print("\nAll chapters 4-7 generated successfully with correct Vietnamese!")
