# -*- coding: utf-8 -*-
"""Gen chapters 1-3 for Quyen IV -- tieng Viet co dau day du"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-4/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 1: KHOAN DUNG
# ================================================================
ch1 = chapter(
    "Khoan Dung --- Sức Mạnh Của Sự Tha Thứ", "Forgiveness --- The Greatest Power",
    "Tha thứ không phải là yếu đuối; đó là lòng can đảm của người mạnh.",
    "Forgiveness is not weakness; it is the courage of the strong.",
    [
    story("Lincoln Và Kẻ Thù Chính Trị", "Abraham Lincoln --- Hoa Kỳ, 1862",
          "Abraham",
          [("Abraham Lincoln sau khi đắc cử Tổng Thống đã làm điều mà cả nước Mỹ không ai ngờ tới.",
            "After winning the presidency, Abraham Lincoln did what no one in America expected."),
           ("Ông bổ nhiệm Edwin Stanton --- người đã công khai chế giễu ông là ``con khỉ từ Illinois'' --- vào chức Bộ trưởng Chiến tranh.",
            "He appointed Edwin Stanton --- who had publicly mocked him as `the gorilla from Illinois' --- as Secretary of War."),
           ("Các cộng sự kinh ngạc hỏi tại sao; Lincoln trả lời thật giản dị: ``Ông ta là người giỏi nhất cho vị trí này.''",
            "His aides were stunned and asked why; Lincoln replied simply: `He is the best man for the position.'"),
           ("Stanton, được trọng dụng như vậy, trở thành Bộ trưởng tận tụy nhất trong lịch sử nước Mỹ.",
            "Stanton, treated with such respect, became the most dedicated Secretary in American history."),
           ("Khi Lincoln bị ám sát, chính Stanton là người khóc và nói: ``Đây là người vĩ đại nhất tôi từng biết.''",
            "When Lincoln was assassinated, it was Stanton who wept and said: `He is the greatest man I have ever known.'")],
          "Tha thứ kẻ thù và trao họ cơ hội là cách biến kẻ thù thành đồng minh --- và viết nên lịch sử.",
          "Forgiving an enemy and giving them a chance is how we transform foes into allies --- and make history."),

    story("Mandela Ra Tù Không Căm Thù", "Nelson Mandela --- Nam Phi, 1990",
          "Sau",
          [("Sau 27 năm bị giam cầm trong nhà tù Robben Island vì đấu tranh chống phân biệt chủng tộc, Nelson Mandela bước ra tự do.",
            "After 27 years imprisoned on Robben Island for fighting apartheid, Nelson Mandela walked free."),
           ("Phóng viên hỏi ông có căm thù những kẻ đã giam cầm ông suốt gần ba mươi năm không.",
            "A reporter asked whether he hated those who had imprisoned him for nearly thirty years."),
           ("Mandela trả lời: ``Nếu tôi bước ra kia với lòng căm thù, tôi vẫn còn là tù nhân, dù cánh cửa tù đã mở.''",
            "Mandela answered: `If I walked out with hatred in my heart, I would still be a prisoner, even with the door open.'"),
           ("Ông không chỉ tha thứ --- ông mời chính người cảnh sát từng giam giữ ông đến dự lễ nhậu chức tổng thống.",
            "He didn't just forgive --- he invited the very guard who had once held him prisoner to attend his presidential inauguration."),
           ("Nam Phi thoát khỏi vòng xoáy bạo lực nhờ chính sự khoan dung phi thường đó của Mandela.",
            "South Africa escaped a cycle of violence largely because of Mandela's extraordinary forgiveness.")],
          "Lòng căm thù chỉ giam cầm bạn trong lòng mình; sự tha thứ giải phóng chính bạn trước khi giải phóng người khác.",
          "Hatred imprisons you within yourself; forgiveness liberates you before it liberates anyone else."),

    story("Khổng Tử Tha Học Trò Phản Bội", "Khổng Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Một",
          [("Một học trò của Khổng Tử đã công khai lợi dụng lời dạy của thầy để trục lợi cho bản thân trước mặt nhà vua.",
            "One of Confucius's students publicly exploited the master's teachings for personal gain before the king."),
           ("Các môn sinh khác yêu cầu Khổng Tử đuổi học trò này; nhà triết học im lặng và hỏi thăm trước.",
            "Other disciples demanded Confucius expel the student; the philosopher said nothing and asked questions first."),
           ("Nghe xong câu trả lời, Khổng Tử nói: ``Người ấy chưa hiểu đạo; lỗi là của ta chứ không phải lỗi người ấy.''",
            "After hearing the answer, Confucius said: `He does not yet understand the Way; the fault is mine, not his.'"),
           ("Ông tiếp tục dạy học trò đó thêm ba năm cho đến khi người này thật sự hiểu và thay đổi.",
            "He continued teaching that student for three more years until the person truly understood and transformed."),
           ("Học trò này về sau trở thành một trong những quan chức công bằng và thanh liêm nhất của thời đại đó.",
            "That student later became one of the most just and upright officials of that era.")],
          "Người phản bội bạn thường là người mà bạn đã chưa dạy đủ; hãy nhận trách nhiệm trước khi phán xét.",
          "Someone who betrays you is often someone you didn't teach well enough; take responsibility before judging."),

    story("Vua Lý Thái Tổ Ân Xá Kẻ Thù", "Lý Thái Tổ --- Việt Nam, 1010",
          "Khi",
          [("Khi Lý Công Uẩn lên ngôi vua khai sáng triều Lý, nhiều người từng chống đối ông vẫn còn sống.",
            "When Ly Cong Uan ascended the throne and founded the Ly Dynasty, many who had opposed him still lived."),
           ("Các quan đề nghị truy sát để trừ hậu hoạ; nhà vua lặng yên rồi chuyển sang bàn chuyện khác.",
            "Officials proposed hunting them down to prevent future threats; the king fell silent and turned to other matters."),
           ("Cuối năm đó, ông ban chính sách đại xá rộng rãi --- tha bổ tất cả tội phạm chính trị và mời mọi người trở về.",
            "At year's end, he proclaimed a broad amnesty --- pardoning all political offenders and welcoming all to return."),
           ("Một vị quan cũ trở về phục vụ Lý Thái Tổ trung thành đến cuối đời, lập nên nhiều công tích to lớn.",
            "A former official returned and served Ly Thai To faithfully for the rest of his life, achieving many great things."),
           ("Triều đại Lý trở thành một trong những giai đoạn hùng cường và thịnh vượng nhất trong lịch sử Việt Nam.",
            "The Ly Dynasty went on to become one of the most powerful and prosperous eras in Vietnamese history.")],
          "Gieo hạt khoan dung bao giờ cũng xây dựng đất nước bền vững hơn là gieo hạt thù hận và sợ hãi.",
          "Sowing seeds of forgiveness always builds a stronger nation than sowing seeds of resentment and fear."),

    story("Corrie Ten Boom Tha Tên Lính Đức", "Corrie ten Boom --- Đức, 1947",
          "Sau",
          [("Sau Chiến tranh Thế giới II, Corrie ten Boom --- người phụ nữ Hà Lan sống sót sau trại tập trung --- đến Đức giảng về sự tha thứ.",
            "After World War II, Corrie ten Boom, a Dutch survivor of the Nazi camps, came to Germany to preach about forgiveness."),
           ("Sau bài giảng, một người đàn ông tiến lại bắt tay bà; Corrie nhận ra đây chính là tên lính đã hành hạ bà trong trại.",
            "After the lecture, a man approached to shake her hand; Corrie recognised him as the very guard who had brutalised her."),
           ("Tim bà đóng cứng lại, bàn tay bà không muốn đưa ra, nhưng bà vẫn cầu nguyện trong lòng và từ từ giơ tay.",
            "Her heart froze, her hand refused to move, but she prayed silently and slowly extended her hand anyway."),
           ("Ngay khi tay bà chạm vào tay ông, bà cảm nhận sự bình an tuôn chảy qua người như một luồng ấm áp.",
            "The moment her hand touched his, she felt a wave of peace flowing through her like warmth."),
           ("Bà viết lại: ``Tình yêu là thứ mạnh mẽ hơn bất kỳ cảm xúc nào --- và sự tha thứ là một sự lựa chọn.''",
            "She later wrote: `Love is stronger than any feeling --- and forgiveness is a choice that can be made.'")],
          "Sự tha thứ chữa lành tâm hồn người tha thứ trước --- đó là món quà bạn trao cho chính mình.",
          "Forgiveness heals the soul of the forgiver first --- it is a gift you give to yourself."),

    story("Gandhi Và Người Quan Toà Anh Quốc", "Mahatma Gandhi --- Ấn Độ, 1922",
          "Năm",
          [("Năm 1922, Gandhi bị bắt giam và đưa ra toà vì tội xúi giục chống lại chính quyền thực dân Anh.",
            "In 1922, Gandhi was arrested and brought to trial for inciting rebellion against British colonial rule."),
           ("Quan toà --- người Anh tên Broomfield --- nói rằng ông rất khó xử với vụ án đặc biệt này.",
            "The judge, an Englishman named Broomfield, said he found this particular case deeply difficult."),
           ("Broomfield nói thẳng: ``Nếu pháp luật cho phép, tôi đã tha ông; nhưng luật bắt buộc tôi phải kết án.''",
            "Broomfield said plainly: `If the law allowed it, I would release you; but the law requires me to sentence you.'"),
           ("Gandhi mỉm cười đáp: ``Thưa Quý Toà, tôi biết Quý Toà đã làm tất cả những gì trong khả năng của mình.''",
            "Gandhi smiled and replied: `Your Honour, I know you have done everything within your power.'"),
           ("Chính sự khoan dung và tôn trọng lẫn nhau đó đã cảm hoá nhiều người Anh hơn bất kỳ cuộc biểu tình nào.",
            "That mutual grace and respect moved more English hearts than any protest march ever had.")],
          "Khoan dung với người đang bắt mình là hành động mạnh mẽ nhất trước mắt cả thế giới đang dõi theo.",
          "Being gracious to those who oppress you is the most powerful act before a world that is watching."),

    story("Tống Tử Trường Tha Kẻ Vu Cáo", "Truyện Cổ Trung Hoa --- thế kỷ 6 TCN",
          "Tống",
          [("Tống Tử Trường là quan đại phu nước Tề thời Xuân Thu, nổi tiếng về sự khéo léo và tâm đức cao quý.",
            "Song Ziqiang was a senior official of the state of Qi during the Spring and Autumn period, famed for wisdom and virtue."),
           ("Một quan chức cấp dưới đã vu cáo ông trước mặt vua nhằm chiếm đoạt chức vị của ông.",
            "A subordinate official had falsely accused him before the king in order to seize his position."),
           ("Sau khi bằng chứng chứng minh ông vô tội, mọi người chờ đợi xem ông sẽ trả thù kẻ vu cáo ra sao.",
            "Once evidence proved his innocence, everyone waited to see how he would retaliate against his accuser."),
           ("Ông không trả thù; thay vào đó ông chủ động đề nghị nhà vua tha thứ cho kẻ đó, nói rằng: ``Kẻ đó chỉ làm vì quá tham vọng.''",
            "He did not retaliate; instead he proactively asked the king to pardon the man, saying: `He acted only out of excessive ambition.'"),
           ("Người quan chức đó sau này trở thành người ủng hộ nhiệt tình nhất của ông, mang ơn đến suốt cuộc đời.",
            "That official afterward became his most devoted supporter, grateful for the rest of his life.")],
          "Khoan dung thật sự khó hơn trả thù; nhưng phần thưởng của nó --- lòng trung thành --- không tiền nào mua được.",
          "True forgiveness is harder than revenge; but its reward --- loyalty --- cannot be bought at any price."),

    story("Archbishop Tutu Và Uỷ Ban Hoà Giải", "Desmond Tutu --- Nam Phi, 1995",
          "Sau",
          [("Sau khi chế độ phân biệt chủng tộc apartheid sụp đổ, Nam Phi đứng trước lựa chọn: truy tố hay hoà giải.",
            "After apartheid collapsed, South Africa faced a choice: full prosecution or national reconciliation."),
           ("Archbishop Desmond Tutu lãnh đạo Uỷ Ban Sự Thật và Hoà Giải --- một thí nghiệm xã hội chưa từng có trong lịch sử.",
            "Archbishop Desmond Tutu led the Truth and Reconciliation Commission --- an unprecedented social experiment."),
           ("Kẻ gây tội phải ra công khai khai nhận trước mọi người; nạn nhân được quyền nói lên nỗi đau của họ.",
            "Perpetrators had to confess publicly before everyone; victims were given the right to speak of their pain."),
           ("Nhiều nạn nhân --- những người có quyền căm ghét nhất --- đã chủ động chọn sự tha thứ thay vì trả thù.",
            "Many victims --- those with the greatest right to hatred --- actively chose forgiveness over revenge."),
           ("Uỷ ban này giúp Nam Phi tránh được cuộc nội chiến mà phần lớn thế giới cho là không thể tránh khỏi.",
            "The Commission helped South Africa avoid a civil war that most of the world believed was inevitable.")],
          "Sự thật không có tha thứ sinh ra bạo lực; tha thứ không có sự thật là sự lừa dối --- chỉ có cả hai mới chữa lành.",
          "Truth without forgiveness breeds violence; forgiveness without truth is deception --- only both together truly heal."),

    story("Minh Thái Tổ Ân Xá Quân Địch", "Minh Thái Tổ --- Trung Hoa, 1368",
          "Sau",
          [("Sau khi thành lập triều Minh và đánh đuổi quân Mông Cổ, Chu Nguyên Chương đối mặt với áp lực từ quần thần.",
            "After founding the Ming Dynasty and expelling the Mongols, Zhu Yuanzhang faced pressure from his generals."),
           ("Họ thúc ép ông tiêu diệt toàn bộ gia tộc các tướng Mông Cổ để trừ mọi hậu hoạ về sau.",
            "They pressed him to exterminate the entire clans of Mongol commanders to prevent all future threats."),
           ("Hoàng đế hỏi trực tiếp các binh lính Mông Cổ còn lại: ``Các ngươi có trung thành nếu nhận được khoan hồng?''",
            "The emperor asked the remaining Mongol soldiers directly: `Will you be loyal if you receive mercy?'"),
           ("Khi họ do dự, ông ra lệnh cho họ nộp vũ khí và ban cho họ đất để canh tác --- không giết thêm một ai.",
            "When they hesitated, he ordered them to hand over their weapons and gave them farmland --- killing no one more."),
           ("Biên cương phía bắc giữ yên bình trong nhiều thập niên nhờ chính sách khoan hoà bất ngờ đó của ông.",
            "The northern border remained peaceful for decades because of this unexpected policy of mercy.")],
          "Một hành động tha thứ đúng lúc có thể đem lại hoà bình lâu dài hơn một trăm trận chiến thắng quân sự.",
          "One timely act of forgiveness can bring longer peace than a hundred military victories."),

    story("Võ Nguyên Giáp Đối Xử Nhân Đạo Với Tù Binh", "Võ Nguyên Giáp --- Việt Nam, 1954",
          "Sau",
          [("Sau chiến thắng lịch sử Điện Biên Phủ năm 1954, quân đội Việt Nam nắm giữ hàng ngàn tù binh Pháp.",
            "After the historic victory at Dien Bien Phu in 1954, the Vietnamese army held thousands of French prisoners."),
           ("Tướng Võ Nguyên Giáp ra lệnh nghiêm đối xử nhân đạo với tù binh --- chăm sóc người bị thương, cung cấp thực phẩm đầy đủ.",
            "General Vo Nguyen Giap issued strict orders for humane treatment --- caring for the wounded, providing adequate food."),
           ("Nhiều người trông đợi sự trả thù sau nhiều năm chiến tranh tàn khốc; nhưng tướng từ chối mọi đề nghị báo thù.",
            "Many expected retaliation after years of brutal war; but the general refused all proposals for revenge."),
           ("Một số sĩ quan Pháp trở về nước đã viết sách ca ngợi sự đối xử nhân đạo này với lòng kính trọng sâu sắc.",
            "Some French officers returned home and wrote books praising this humane treatment with deep respect."),
           ("Sự khoan hoà đó góp phần xây dựng hình ảnh Việt Nam là cuộc đấu tranh chính nghĩa trước mắt thế giới.",
            "This magnanimity helped build Vietnam's image as a righteous struggle in the eyes of the world.")],
          "Đối xử nhân đạo với kẻ bại trận không chỉ là đạo đức --- đó còn là chiến lược ngoại giao khôn ngoan nhất.",
          "Treating defeated enemies humanely is not only moral --- it is also the wisest diplomatic strategy."),
    ])

with open(os.path.join(BASE, "ch01-khoan-dung.tex"), "w", encoding="utf-8") as f:
    f.write(ch1)
print("ch01 done")

# ================================================================
# CHƯƠNG 2: BIẾT LẮNG NGHE
# ================================================================
ch2 = chapter(
    "Biết Lắng Nghe --- Nghe Để Hiểu, Không Chỉ Nghe Để Trả Lời", "Listening to Understand, Not to Reply",
    "Phần lớn mọi người nghe không phải để hiểu; họ nghe để chuẩn bị trả lời.",
    "Most people do not listen to understand; they listen to prepare their reply.",
    [
    story("Socrates Và Nghệ Thuật Đặt Câu Hỏi", "Socrates --- Hy Lạp, thế kỷ 5 TCN",
          "Socrates",
          [("Socrates nổi tiếng khắp Athens không phải vì ông biết nhiều, mà vì ông biết đặt câu hỏi và lắng nghe.",
            "Socrates was famous throughout Athens not because he knew much, but because he knew how to ask and listen."),
           ("Ông thường ngồi ở góc phố bắt chuyện với người qua đường --- lắng nghe trước, đặt câu hỏi sau, không bao giờ ngắt lời.",
            "He would sit at street corners and talk with passersby --- listening first, asking later, never interrupting."),
           ("Một lần một vị tướng kiêu ngạo đến tranh luận; Socrates chỉ hỏi và không nói gì về bản thân mình.",
            "Once an arrogant general came to debate; Socrates only asked questions and said nothing about himself."),
           ("Sau ba giờ trò chuyện, vị tướng nói: ``Tôi chưa bao giờ suy nghĩ sâu về vấn đề này cho đến hôm nay.''",
            "After three hours of conversation, the general said: `I have never thought so deeply about this until today.'"),
           ("Socrates trả lời: ``Tôi không dạy ông điều gì --- tôi chỉ đặt câu hỏi để ông tự tìm ra sự thật của chính ông.''",
            "Socrates replied: `I taught you nothing --- I only asked questions so you could find your own truth.'")],
          "Sự khôn ngoan thật sự nằm ở việc biết đặt câu hỏi đúng --- người hỏi tốt làm chủ buổi trò chuyện.",
          "True wisdom lies in asking the right questions --- the one who asks well masters the conversation."),

    story("Lincoln Lắng Nghe Dân Trước Khi Quyết Định", "Abraham Lincoln --- Hoa Kỳ, 1862",
          "Mỗi",
          [("Mỗi tuần, Lincoln dành thời gian gặp bất kỳ ai đến Nhà Trắng --- từ binh sĩ, dân oan đến người mẹ có con nhỏ.",
            "Every week, Lincoln kept open hours for anyone who came to the White House --- from soldiers to petitioners to mothers with small children."),
           ("Các cố vấn khuyên ông đừng lãng phí thời gian quý báu; ông trả lời: ``Đây là cách tôi bắt mạch dân tình.''",
            "Advisers urged him not to waste precious time; he replied: `This is how I take the pulse of the people.'"),
           ("Một lần một bà cụ đến xin tha mạng cho con trai sắp bị xử bắn vì tội đào ngũ; Lincoln lắng nghe suốt một tiếng đồng hồ.",
            "Once an old woman came begging clemency for her son about to be shot for desertion; Lincoln listened for a full hour."),
           ("Sau đó ông tự tay viết lệnh ân xá và cho bà cầm theo khi bà ra về.",
            "Afterward he handwrote a clemency order and let her take it with her when she left."),
           ("Ông nói với cố vấn: ``Bất kỳ ai chịu lắng nghe nỗi đau của người khác --- chính họ mới xứng đáng được lắng nghe.''",
            "He told his aide: `Anyone who takes time to hear others' pain --- they are the ones truly worthy of being heard.'")],
          "Lắng nghe người dân không phải lãng phí thời gian mà là đầu tư vào lòng tin --- và lòng tin là nền tảng của lãnh đạo.",
          "Listening to the people is not wasting time but investing in trust --- and trust is the foundation of leadership."),

    story("Khổng Tử Học Bài Từ Một Đứa Trẻ", "Khổng Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Một",
          [("Một hôm đi qua một vùng quê, Khổng Tử nghe một đứa trẻ đang hát bài dân ca về mùa gặt.",
            "One day, travelling through the countryside, Confucius heard a child singing a folk song about the harvest."),
           ("Bài hát có một câu nói về thiên nhiên rất tinh tế mà Khổng Tử chưa từng nghĩ đến.",
            "The song contained a line about nature so subtle that Confucius had never considered it before."),
           ("Ông dừng lại, hỏi tên đứa trẻ, bảo nó hát lại một lần nữa, rồi cẩn thận ghi vào sổ tay của mình.",
            "He stopped, asked the child's name, had it sing the song again, then carefully wrote it in his notebook."),
           ("Các môn sinh kinh ngạc: ``Tại sao thầy lại học từ trẻ con?'' Khổng Tử từ tốn trả lời:",
            "His disciples were astonished: `Why does the master learn from a child?' Confucius replied calmly:"),
           ("``Lắng nghe dù chỉ một lần là học; tưởng mình đã biết hết mà không lắng nghe nữa là tụt hậu.''",
            "`To listen even once is to learn; to think you know all and stop listening is to fall behind.'")],
          "Kiến thức đến với những người còn chịu lắng nghe --- dù nguồn gốc đó là một đứa trẻ hay một người bình dị.",
          "Knowledge comes to those who still choose to listen --- even if the source is a child or someone seemingly lesser."),

    story("Theodore Roosevelt Nhớ Tên Mọi Người", "Theodore Roosevelt --- Hoa Kỳ, 1901",
          "Khi",
          [("Khi Theodore Roosevelt trở thành Tổng Thống Hoa Kỳ, ông có một thói quen đặc biệt: ông nhớ tên tất cả nhân viên.",
            "When Theodore Roosevelt became President, he had an unusual habit: he remembered the name of every employee."),
           ("Từ người đầu bếp, người giữ cửa đến người lau sàn --- ông đều chào bằng tên khi gặp nhau.",
            "From the cook to the doorkeeper to the floor-sweeper --- he greeted each one by name when passing."),
           ("Ông giải thích: ``Nhớ tên ai là nói với họ rằng họ quan trọng với tôi --- và họ thật sự quan trọng.''",
            "He explained: `Remembering a name tells that person they matter to me --- and they genuinely do matter.'"),
           ("Một nhân viên lau sàn kể lại: khi Tổng Thống chào ông bằng tên, ông cảm thấy mình là một phần của lịch sử.",
            "A floor-sweeper recalled: when the President greeted him by name, he felt himself to be part of history."),
           ("Roosevelt nói: ``Là lãnh đạo, công việc của tôi là lắng nghe không chỉ lời nói mà cả con người sau lời nói đó.''",
            "Roosevelt said: `As a leader, my job is to listen not just to words but to the person behind those words.'")],
          "Nhớ tên và lắng nghe người khác là hành động rẻ nhất bạn có thể làm --- nhưng tác động của nó lớn hơn bất kỳ khoản thưởng nào.",
          "Remembering names and listening is the cheapest thing you can do --- but its impact surpasses any bonus."),

    story("Bác Hồ Lắng Nghe Nỗi Oan Của Người Dân", "Hồ Chí Minh --- Việt Nam, 1945",
          "Hồi",
          [("Hồi đầu năm 1945, một bà cụ nông dân đi bộ mấy chục cây số lên Hà Nội để gặp Chủ tịch Hồ Chí Minh.",
            "In early 1945, an elderly peasant woman walked dozens of kilometres to Hanoi to meet Chairman Ho Chi Minh."),
           ("Người bảo vệ ngăn không cho bà vào vì không có lịch hẹn; bà ngồi chờ bên ngoài cả buổi sáng.",
            "Guards would not let her in without an appointment; she sat waiting outside the whole morning."),
           ("Bác Hồ đi ngang qua thấy bà cụ, dừng lại hỏi thăm, rồi tự mình dẫn bà vào văn phòng và ngồi nghe.",
            "Uncle Ho, walking by, noticed the old woman, stopped to ask, and personally led her into his office to listen."),
           ("Bà kêu oan đất đai bị cường hào chiếm đoạt; Bác ghi lại ngay và chỉ thị cấp dưới giải quyết dứt điểm.",
            "She complained of land seized by local tyrants; Uncle Ho wrote it down immediately and ordered subordinates to resolve it completely."),
           ("Ông nói với cán bộ: ``Mỗi người dân tìm đến lãnh đạo là mang theo một viên gạch của cách mạng đến cho ta.''",
            "He told his staff: `Every citizen who comes to their leader brings a brick of the revolution to our hands.'")],
          "Lắng nghe người dân không phải dấu hiệu của sự yếu đuối --- đó là bằng chứng của người lãnh đạo biết sức mạnh đến từ đâu.",
          "Listening to the people is not a sign of weakness --- it is proof that a leader knows where their strength comes from."),

    story("Kofi Annan Và Nghệ Thuật Hoà Giải Quốc Tế", "Kofi Annan --- Liên Hiệp Quốc, 1997",
          "Kofi",
          [("Kofi Annan, Tổng Thư Ký Liên Hiệp Quốc, nổi tiếng với khả năng hoà giải những bên đang xung đột gay gắt nhất.",
            "Kofi Annan, UN Secretary-General, was renowned for his ability to reconcile even the most fiercely opposing sides."),
           ("Bí mật của ông rất đơn giản: ông ngồi lắng nghe từng bên nói đến cùng --- không ngắt lời, không chuẩn bị phản bác.",
            "His secret was simple: he sat and listened to each side speak fully --- not interrupting, not preparing a rebuttal."),
           ("Sau khi cả hai bên nói xong, ông chỉ tóm tắt lại những điều mỗi bên đã nói --- để họ nghe chính mình qua lời kể lại.",
            "After both sides finished, he simply summarised what each had said --- letting them hear themselves through his retelling."),
           ("Nhiều cuộc xung đột hạ nhiệt ngay sau bước này --- vì phần lớn mâu thuẫn bắt nguồn từ chưa bao giờ thật sự được nghe.",
            "Many conflicts cooled after just this step --- because most disputes originate from never having been truly heard."),
           ("Annan nói: ``Chưa cuộc đàm phán nào thất bại vì nghe quá nhiều; chúng chỉ thất bại vì nói quá nhiều.''",
            "Annan said: `No negotiation has ever failed from listening too much; they only fail from talking too much.'")],
          "Trong bất kỳ cuộc đàm phán nào, bên nào lắng nghe nhiều hơn sẽ có lợi thế --- vì họ hiểu rõ hơn đối phương.",
          "In any negotiation, the side that listens more gains the advantage --- because they understand the other side better."),

    story("Bác Sĩ Osler Và Bệnh Nhân Không Bị Ngắt Lời", "William Osler --- Canada, 1890",
          "Bác",
          [("Bác sĩ William Osler, được gọi là `cha đẻ của y học hiện đại', có một nguyên tắc bất biến suốt sự nghiệp.",
            "Dr William Osler, called `the father of modern medicine', had one unwavering principle throughout his career."),
           ("Mỗi khi gặp bệnh nhân, ông tự hỏi bản thân: ``Bệnh nhân này có điều gì muốn nói mà họ chưa dám nói?''",
            "Whenever he met a patient, he asked himself: `What does this patient want to say that they haven't dared say yet?'"),
           ("Ông ngồi xuống ngang tầm mắt với người bệnh, không nhìn đồng hồ, và hỏi nhẹ nhàng: ``Bạn có thể kể cho tôi nghe không?''",
            "He sat down to the patient's eye level, didn't glance at his watch, and asked gently: `Can you tell me about it?'"),
           ("Một nghiên cứu sau này cho thấy: nếu bác sĩ không ngắt lời, bệnh nhân chỉ mất trung bình 92 giây để mô tả hết triệu chứng.",
            "A later study showed: if a doctor doesn't interrupt, patients take an average of only 92 seconds to describe all their symptoms."),
           ("Thế nhưng 80 phần trăm bác sĩ ngắt lời bệnh nhân trước 23 giây --- và 40 phần trăm bỏ lỡ chẩn đoán đúng vì thế.",
            "Yet 80 percent of doctors interrupt before 23 seconds --- and 40 percent miss the correct diagnosis as a result.")],
          "Lắng nghe là kỹ năng y khoa quan trọng nhất mà các trường y dạy ít nhất --- và cũng là liệu pháp chữa lành hiệu quả nhất.",
          "Listening is the most important clinical skill that medical schools teach the least --- and the most effective healing therapy."),

    story("Diogenes Và Bài Học Im Lặng Trước Khi Hiểu", "Diogenes --- Hy Lạp, thế kỷ 4 TCN",
          "Diogenes",
          [("Diogenes xứ Sinope, nhà triết học nổi tiếng với lối sống giản dị khắc khổ, có một cách dạy học độc đáo.",
            "Diogenes of Sinope, the philosopher famous for his radically simple lifestyle, had a unique teaching method."),
           ("Khi một học trò chuộng lời hoa hoè đến hỏi, Diogenes nhắm mắt lại ngồi yên không nói một lời.",
            "When a long-winded student came to ask a question, Diogenes closed his eyes and sat in complete silence."),
           ("Học trò hỏi mãi, cuối cùng bực bội đứng lên định về; Diogenes mở mắt gọi lại: ``Bây giờ ta sẽ trả lời.''",
            "The student kept asking, finally stood up in frustration to leave; Diogenes opened his eyes and called: `Now I will answer.'"),
           ("Học trò hỏi: ``Sao lúc nãy thầy không trả lời?'' Diogenes nói: ``Vì lúc nãy ta chưa hiểu hết điều ngươi thật sự muốn hỏi.''",
            "The student asked: `Why didn't you answer before?' Diogenes said: `Because I hadn't yet understood what you truly wanted to ask.'"),
           ("Bài học: Kẻ ngu nói trước khi hiểu; người khôn lắng nghe cho đến khi thật sự hiểu rõ.",
            "The lesson: fools speak before understanding; the wise listen until they truly understand.")],
          "Hai tai, một miệng --- tỷ lệ này không phải ngẫu nhiên; hãy lắng nghe gấp đôi so với khi nói.",
          "Two ears, one mouth --- this ratio is not accidental; listen twice as much as you speak."),

    story("Florence Nightingale Và Sức Mạnh Của Sự Hỏi Thăm", "Florence Nightingale --- Anh, 1854",
          "Trong",
          [("Trong cuộc chiến tranh Crimea, Florence Nightingale đến chăm sóc thương binh trong những bệnh xá tàn tệ.",
            "During the Crimean War, Florence Nightingale arrived to care for wounded soldiers in appalling hospital wards."),
           ("Các sĩ quan quân đội chỉ quan tâm đến số liệu thống kê; Nightingale muốn biết tên từng người binh sĩ.",
            "Military officers only cared about statistics; Nightingale wanted to know each soldier's name."),
           ("Mỗi đêm bà đi qua các dãy giường thương binh với ngọn đèn trên tay, ngồi lại bên mỗi người để hỏi thăm.",
            "Each night she walked miles of wards with her lamp, sitting beside each person to ask after them."),
           ("Những người lính viết thư về nhà kể: ``Cô ấy ngồi với tôi lúc nửa đêm và hỏi tôi quê ở đâu.''",
            "The soldiers wrote home saying: `She sat with me at midnight and asked where I was from.'"),
           ("Tỉ lệ tử vong giảm từ 40 phần trăm xuống 2 phần trăm --- không chỉ nhờ thuốc mà nhờ mỗi người biết họ được lắng nghe.",
            "The mortality rate fell from 40 to 2 percent --- not only from medicine but from each person knowing they were heard.")],
          "Đôi khi liệu pháp hiệu quả nhất không phải là thuốc --- mà là sự biết rằng có một người đang thật sự lắng nghe.",
          "Sometimes the most effective therapy is not medicine --- but the knowledge that someone is truly listening."),

    story("Thái Tử Đằng Văn Công Học Cách Lắng Nghe", "Khổng Tử --- Trung Hoa, thế kỷ 5 TCN",
          "Thái",
          [("Thái tử Đằng Văn Công, một vị hoàng tử trẻ, đến gặp Khổng Tử và hỏi: ``Làm người cần học điều gì trước nhất?''",
            "Prince Teng Wengong, a young prince, came to Confucius and asked: `What must a person learn above all else?'"),
           ("Khổng Tử không trả lời ngay; ông ngồi im lặng một hồi lâu và nhìn người hỏi.",
            "Confucius did not answer immediately; he sat in silence for a long while and looked at the questioner."),
           ("Rồi thầy hỏi ngược lại: ``Trước khi ta trả lời, ngươi hãy nói cho ta biết: ngươi nghe điều này để làm gì?''",
            "Then the master asked back: `Before I answer, you tell me: what will you do with whatever I say?'"),
           ("Học trò dừng lại suy nghĩ --- và từ đó bắt đầu lắng nghe với một tinh thần khác hẳn, có mục đích rõ ràng.",
            "The student paused to think --- and from then on began listening in a completely different spirit, with clear purpose."),
           ("Khổng Tử nói: ``Lắng nghe đúng cách còn quan trọng hơn nói hay --- người nghe quyết định giá trị của lời nói.''",
            "Confucius said: `Listening rightly matters more than speaking well --- the listener determines the value of words.'")],
          "Nghe mà không có mục đích chỉ là tiếng ồn; lắng nghe với ý thức rõ ràng mới thực sự là học.",
          "Listening without purpose is just noise; listening with clear awareness is genuine learning."),
    ])

with open(os.path.join(BASE, "ch02-lang-nghe.tex"), "w", encoding="utf-8") as f:
    f.write(ch2)
print("ch02 done")

# ================================================================
# CHƯƠNG 3: LỜI NÓI VÀ HÀNH ĐỘNG
# ================================================================
ch3 = chapter(
    "Lời Nói Và Hành Động --- Hành Động Nói To Hơn Lời Nói", "Actions Speak Louder Than Words",
    "Làm tốt còn hơn là nói hay.",
    "Well done is better than well said.",
    [
    story("Gandhi --- Hãy Là Sự Thay Đổi Bạn Muốn Thấy", "Mahatma Gandhi --- Ấn Độ, thế kỷ 20",
          "Một",
          [("Một bà mẹ dẫn con trai đến gặp Gandhi và van xin: ``Thưa Ngài, xin Ngài nói với con tôi đừng ăn quá nhiều đường.''",
            "A mother brought her son to Gandhi and pleaded: `Sir, please tell my son not to eat too much sugar.'"),
           ("Gandhi im lặng rồi nói: ``Một tuần sau hãy cho cậu bé đến gặp tôi.'' Bà mẹ bối rối nhưng vẫn làm theo.",
            "Gandhi was silent then said: `Bring the boy to me again in one week.' The mother was puzzled but complied."),
           ("Một tuần sau, Gandhi nhìn đứa trẻ và nói nhẹ nhàng: ``Con ơi, đừng ăn quá nhiều đường --- không tốt cho sức khoẻ đâu.''",
            "One week later, Gandhi looked at the boy and said gently: `Son, don't eat too much sugar --- it's not good for your health.'"),
           ("Bà mẹ hỏi: ``Tại sao tuần trước Ngài không nói ngay? Tại sao lại bắt chúng tôi đi rồi lại đến?'' Gandhi đáp:",
            "The mother asked: `Why didn't you say that last week? Why make us come and go?' Gandhi answered:"),
           ("``Tuần trước, chính bản thân tôi cũng còn đang ăn nhiều đường. Tôi cần một tuần để bỏ nó trước khi dạy người khác.''",
            "`Last week I myself was still eating much sugar. I needed a week to stop before teaching others to do so.'")],
          "Chỉ dạy điều mình đang thực hành; không ai có quyền dạy người khác điều mình chưa thật sự sống qua.",
          "Only teach what you practise; no one has the right to teach others what they have not yet truly lived."),

    story("Lincoln Và Những Bức Thư Không Bao Giờ Gửi", "Abraham Lincoln --- Hoa Kỳ, 1864",
          "Khi",
          [("Khi ai đó làm Lincoln tức giận, ông có một thói quen đặc biệt: viết ngay một bức thư giận dữ gửi cho người đó.",
            "Whenever someone angered Lincoln, he had a special habit: immediately writing a furious letter to that person."),
           ("Ông viết thật thành thật, trút hết bức xúc ra giấy, rồi... gấp thư lại cất vào ngăn bàn và không bao giờ gửi.",
            "He wrote with complete honesty, pouring all frustration onto the page, then... folded the letter, put it in his drawer, and never sent it."),
           ("Thư ký hỏi tại sao không gửi, ông giải thích: ``Sau khi viết xong, tôi đã nói được những điều mình cần nói.''",
            "His secretary asked why he never sent them; he explained: `After writing it, I have already said what I needed to say.'"),
           ("``Gửi đi chỉ gây thêm xung đột --- tôi cần giải pháp, không cần thêm một kẻ thù nữa.''",
            "`Sending it would only create more conflict --- I need solutions, not another enemy.'"),
           ("Sau khi ông mất, người ta tìm thấy hàng chục bức thư giận dữ chưa bao giờ được gửi trong ngăn bàn của ông.",
            "After his death, people found dozens of furious, never-sent letters stored in his desk drawers.")],
          "Hành động khôn ngoan nhất đôi khi là không hành động --- hãy viết ra để xả stress nhưng đừng gửi đi khi đang tức.",
          "The wisest action is sometimes inaction --- write it out to release stress, but never send it while angry."),

    story("Socrates Và Ba Cái Rổ Lọc Lời Nói", "Socrates --- Hy Lạp, thế kỷ 5 TCN",
          "Một",
          [("Một người chạy xộc đến gặp Socrates: ``Thầy ơi! Tôi có một chuyện cần kể cho thầy nghe về bạn của thầy!''",
            "A man rushed to Socrates: `Master! I have something I must tell you about your friend!'"),
           ("Socrates giơ tay lên nói: ``Khoan đã --- trước tiên hãy để lời nói của bạn đi qua ba cái rổ.''",
            "Socrates raised his hand and said: `Wait --- first let your words pass through three sieves.'"),
           ("``Rổ thứ nhất: Nó có thật không? Rổ thứ hai: Nó có tốt không? Rổ thứ ba: Nó có cần thiết không?''",
            "`First sieve: Is it true? Second sieve: Is it good? Third sieve: Is it necessary?'"),
           ("Người đàn ông đó lúng túng: ``Điều tôi định kể không chắc là thật, không tốt, và có lẽ cũng chẳng cần thiết lắm.''",
            "The man faltered: `What I was going to say is not certainly true, not good, and probably not very necessary either.'"),
           ("Socrates mỉm cười: ``Nếu lời nói của bạn không vượt qua được ba cái rổ này --- tốt nhất là hãy giữ nó cho mình.''",
            "Socrates smiled: `If your words cannot pass these three sieves --- it is best to keep them to yourself.'")],
          "Trước khi nói, tự hỏi: Có thật? Có tốt? Có cần? Nếu không đáp ứng ít nhất hai tiêu chí, tốt nhất là đừng nói.",
          "Before speaking, ask yourself: Is it true? Is it good? Is it needed? If it fails at least two, it is best left unsaid."),

    story("Thomas Edison --- Thất Bại Chỉ Là Bài Học Chưa Hoàn Chỉnh", "Thomas Edison --- Hoa Kỳ, 1879",
          "Sau",
          [("Sau khi thử nghiệm bóng đèn điện tới gần mười nghìn lần, có người hỏi Edison có cảm thấy mình thất bại không.",
            "After testing the light bulb nearly ten thousand times, someone asked Edison if he felt like a failure."),
           ("Edison bình thản trả lời: ``Tôi không hề thất bại một lần nào --- tôi đã tìm ra mười nghìn cách không hoạt động.''",
            "Edison calmly replied: `I have not failed even once --- I have found ten thousand ways that do not work.'"),
           ("Những điều Edison nói không chỉ là lời hay --- đó chính xác là cách ông sống và làm việc mỗi ngày.",
            "What Edison said was not just a fine phrase --- it was exactly how he lived and worked every single day."),
           ("Ông giữ nhật ký thí nghiệm tỉ mỉ --- ghi lại kết quả từng lần thử một cách cẩn thận và khoa học.",
            "He kept meticulous experiment journals --- recording each trial's results carefully and scientifically."),
           ("Khi bóng đèn cuối cùng sáng lên, nó sáng trên nền tảng vững chắc của chính những lần thất bại đó.",
            "When the light bulb finally lit up, it did so upon the solid foundation of those very failures.")],
          "Bất cứ ai gọi mọi kết quả không mong muốn là `thất bại' thực ra đang từ chối bài học quý giá nhất mà thực nghiệm mang lại.",
          "Anyone who calls every unwanted result a `failure' is refusing the most valuable lesson the experiment offers."),

    story("Nguyễn Trãi --- Nhân Nghĩa Là Nền Tảng Của Sức Mạnh", "Nguyễn Trãi --- Việt Nam, thế kỷ 15",
          "Khi",
          [("Khi Nguyễn Trãi viết Bình Ngô Đại Cáo, ông không chỉ viết một tuyên ngôn chiến thắng --- ông viết để dạy đời sau.",
            "When Nguyen Trai wrote the Great Proclamation of Victory, he was not just writing a victory declaration --- he was teaching future generations."),
           ("Ông viết: ``Việc nhân nghĩa cốt ở yên dân; quân điếu phạt trước lo trừ bạo.''",
            "He wrote: `The purpose of humanity and justice lies in bringing peace to the people; punishment first removes tyranny.'"),
           ("Ông dạy rằng dùng sức mạnh quân sự nhất thiết phải đi kèm với mục đích nhân văn cao cả.",
            "He taught that military force must always be accompanied by a noble humane purpose."),
           ("Sau khi đánh đuổi giặc Minh, ông đề nghị tha bổ tướng giặc bị bắt vì ``làm nhục kẻ bại trận không bao giờ tạo ra hoà bình lâu dài.''",
            "After expelling the Ming invaders, he proposed releasing captured enemy commanders because `humiliating the defeated never creates lasting peace.'"),
           ("Chính sách nhân nghĩa đó giúp Việt Nam duy trì hoà bình bền vững với Trung Hoa trong nhiều thế kỷ tiếp theo.",
            "That humane policy helped Vietnam maintain lasting peace with China for the following centuries.")],
          "Hành động nhân nghĩa sau khi chiến thắng còn khó hơn dũng khí trong lúc chiến tranh --- và cũng quan trọng hơn rất nhiều.",
          "Acting with humanity after victory is harder than courage in war --- and far more important."),

    story("Marcus Aurelius --- Triết Học Gặp Chiến Trường", "Marcus Aurelius --- Rome, thế kỷ 2",
          "Người",
          [("Người ta gọi Marcus Aurelius là Hoàng Đế vĩ đại nhất của đế chế La Mã vì ông vừa là chiến binh vừa là triết gia.",
            "Marcus Aurelius was called Rome's greatest emperor because he was both a warrior and a philosopher."),
           ("Nhưng bí mật thực sự của ông nằm ở trong quyển nhật ký cá nhân --- cuốn Suy Ngẫm --- mà ông không bao giờ có ý định xuất bản.",
            "But his true secret lay in his personal journal --- Meditations --- which he never intended to publish."),
           ("Ông viết cho chính mình: ``Người khác không thuộc quyền kiểm soát của ta khi họ xúc phạm ta; điều thuộc về ta là phản ứng của ta.''",
            "He wrote to himself: `Others are beyond my control when they offend me; what belongs to me is my reaction.'"),
           ("Mỗi buổi sáng ông tự kiểm tra bản thân trước khi ra quyết định --- như một nhà triết học nghiêm ngặt đang chỉ huy những đạo quân khó trị.",
            "Every morning he cross-examined himself before making decisions --- like a rigorous philosopher commanding unruly armies."),
           ("Ông làm đúng những gì ông viết --- và đế chế La Mã tồn tại thêm hai thế kỷ nhờ một phần tinh thần đó.",
            "He did precisely what he wrote --- and the Roman Empire endured two more centuries partly because of that spirit.")],
          "Nhật ký tự kiểm thật ra là sân tập luyện kỷ luật bản thân --- viết ra để tự kiểm nghiệm mình trước, rồi mới hành động.",
          "A self-examination journal is a training ground for self-discipline --- write to test yourself first, then act."),

    story("Churchill --- Lời Nói Cứu Nước Anh", "Winston Churchill --- Anh, 1940",
          "Tháng",
          [("Tháng 5 năm 1940, quân Đức đã chiếm Pháp, đã tràn qua Hà Lan và Bỉ --- nước Anh gần như hoàn toàn đơn độc.",
            "In May 1940, Germany had taken France, overrun Holland and Belgium --- Britain stood nearly completely alone."),
           ("Churchill lên làm Thủ tướng trong hoàn cảnh tuyệt vọng nhất có thể hình dung; ông bước lên bục phát biểu đầu tiên.",
            "Churchill became Prime Minister in the most desperate circumstances imaginable; he stepped up to give his first address."),
           ("Không một lời hứa hẹn chiến thắng dễ dàng; ông nói thẳng: ``Tôi không có gì để trao ngoài máu, mồ hôi và nước mắt.''",
            "Not a single promise of easy victory; he said plainly: `I have nothing to offer but blood, toil, tears and sweat.'"),
           ("Nhưng Quốc Hội và toàn dân nước Anh cảm thấy khác --- họ cảm thấy được nghe nói thật và được lãnh đạo thật sự.",
            "But Parliament and the whole of Britain felt something different --- they felt they were hearing truth and being truly led."),
           ("Lời nói không có sự thật không bao giờ khích lệ được ai; chỉ lời nói sống bằng sự thật mới lay động được lòng người.",
            "Words empty of truth never truly inspire; only words alive with truth can move hearts.")],
          "Hành động trung thực --- kể cả khi sự thật cay đắng --- luôn hiệu quả hơn sự an ủi giả tạo khi bước vào lúc thật sự thử thách.",
          "Honest action --- even when truth is bitter --- always works better than false comfort when the real test comes."),

    story("Mark Twain --- Một Từ Đúng Thay Đổi Cả Câu Chuyện", "Mark Twain --- Hoa Kỳ, 1880",
          "Mark",
          [("Mark Twain là nhà văn Mỹ nổi tiếng mà ít ai biết ông cũng là bậc thầy trong việc biết khi nào nên im lặng.",
            "Mark Twain was a famous American writer, but few knew he was equally a master of knowing when to be silent."),
           ("Một lần ông được mời phát biểu trước đám đông đang phẫn nộ vì chính sách thuế khoá bất công.",
            "Once he was invited to speak before a crowd furious about unjust tax policies."),
           ("Thấy đám đông đã quá nóng, thay vì thêm lửa vào, ông chỉ nói một câu ngắn: ``Những gì cái túi rỗng không nói được thì mặt người nói thay.''",
            "Seeing the crowd already overheated, instead of adding fuel, he said only one short sentence: `What the empty pocket cannot say, the face says for it.'"),
           ("Đó là bài phát biểu ngắn nhất trong sự nghiệp ông --- nhưng được nhớ lâu nhất bởi những người chứng kiến.",
            "It was the shortest speech of his career --- but remembered longest by those who witnessed it."),
           ("Twain viết: ``Sự khác biệt giữa từ đúng và từ gần đúng cũng lớn như sự khác biệt giữa tia sét và con đom đóm.''",
            "Twain wrote: `The difference between the right word and the almost right word is the difference between lightning and a lightning bug.'")],
          "Một từ đúng có thể thay đổi cả cuộc trò chuyện; phần còn lại của ngôn ngữ chỉ là để bảo vệ từ đúng đó.",
          "One right word can change an entire conversation; the rest of language exists only to protect that right word."),

    story("Hồ Xuân Hương --- Thơ Ca Là Vũ Khí Xã Hội", "Hồ Xuân Hương --- Việt Nam, thế kỷ 18",
          "Hồ",
          [("Hồ Xuân Hương sống trong xã hội phong kiến khắt khe ràng buộc phụ nữ --- nhưng bà dùng thơ ca như một thứ vũ khí tinh tế.",
            "Ho Xuan Huong lived in a feudal society that tightly bound women --- but she used poetry as a subtle weapon."),
           ("Bà không cần xin phép hay đợi ân thưởng --- bà nói điều bà cần nói qua những bài thơ đầy tầng ẩn dụ.",
            "She needed no permission or approval --- she said what she needed through poems layered with metaphor."),
           ("Những bài thơ của bà có hai tầng ý nghĩa: tầng ngoài dí dỏm, tầng trong táo bạo và phá cách.",
            "Her poems had two layers: a witty surface layer and a bold, subversive inner layer."),
           ("Người đọc hời hợt chỉ thấy văn chương; người hiểu thì kinh ngạc trước sự can đảm của tư tưởng ẩn chứa bên trong.",
            "Shallow readers only saw literature; those who understood were stunned by the courage of the thought within."),
           ("Ngôn ngữ được dùng khéo léo là vũ khí có thể xuyên thủng mọi rào cản xã hội mà không cần đến bạo lực.",
            "Language used cleverly is a weapon that can pierce any social barrier without needing violence.")],
          "Khi không thể nói thẳng, hãy học cách nói khéo --- đôi khi còn hiệu quả và sắc bén hơn nói thẳng.",
          "When you cannot speak directly, learn to speak cleverly --- sometimes it is even more effective and sharp."),

    story("Bertrand Russell --- Hành Động Theo Lương Tâm Dù Bị Cô Lập", "Bertrand Russell --- Anh, thế kỷ 20",
          "Bertrand",
          [("Bertrand Russell là nhà triết học nổi tiếng người Anh đã dành cả đời suy nghĩ về chiến tranh, hoà bình và lẽ phải.",
            "Bertrand Russell was a famous British philosopher who spent his entire life thinking about war, peace, and what is right."),
           ("Trong Thế chiến I, khi chiến tranh được tôn vinh, ông là một trong số rất ít người công khai phản đối.",
            "During World War I, when war was being glorified, he was one of very few who publicly opposed it."),
           ("Ông mất chức ở đại học, bị bắt giam sáu tháng --- nhưng không bao giờ từ bỏ lập trường của mình.",
            "He lost his university post, was imprisoned for six months --- but never abandoned his position."),
           ("Gần cuối cuộc đời, ở tuổi chín mươi, ông vẫn xuống đường biểu tình phản đối vũ khí hạt nhân giữa Chiến tranh Lạnh.",
            "Near the end of his life at ninety, he still marched in the streets protesting nuclear weapons during the Cold War."),
           ("Ông nói: ``Tội nghiêm trọng nhất về mặt đạo đức là làm điều bạn biết là sai chỉ vì người khác mong bạn làm.''",
            "He said: `The most serious moral crime is doing what you know is wrong simply because others expect you to.'")],
          "Nói điều bạn tin tưởng --- dù thế giới cho bạn là sai --- là hành động trí thức cao nhất mà một con người có thể thực hiện.",
          "Speaking what you believe --- even when the world says you are wrong --- is the highest intellectual act a person can perform."),
    ])

with open(os.path.join(BASE, "ch03-loi-noi-hanh-dong.tex"), "w", encoding="utf-8") as f:
    f.write(ch3)
print("ch03 done")

print("\nAll chapters 1-3 generated successfully with correct Vietnamese!")
