# -*- coding: utf-8 -*-
"""Gen chapters 8-10 for Quyen IV -- tieng Viet co dau day du"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-4/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 8: THIỆN LƯƠNG
# ================================================================
ch8 = chapter(
    "Thiện Lương --- Tâm Lòng Tốt Lành Là Sức Mạnh Thầm Lặng", "Goodness of Heart --- The Silent Power",
    "Ba điều quan trọng nhất trong đời là lòng tốt, lòng tốt và lòng tốt.",
    "The three most important things in life are kindness, kindness and kindness.",
    [
    story("Mẹ Teresa Và Người Hấp Hối Trên Đường Phố", "Mẹ Teresa --- Ấn Độ, 1952",
          "Mẹ",
          [("Mẹ Teresa nhặt người hấp hối bên đường Calcutta --- người bị chuột gặm nhấm và ruồi bu đầy --- đưa vào chăm sóc.",
            "Mother Teresa picked up a dying person from the Calcutta streets --- gnawed by rats and covered in flies --- and brought him to care."),
           ("Nhà bác học và quan chức không muốn chạm vào những người như vậy; Mẹ Teresa chăm sóc họ như người thân trong gia đình.",
            "Scholars and officials would not touch such people; Mother Teresa cared for them as she would family members."),
           ("Có người hỏi bà: ``Sao bà làm điều này khi không được trả công, không được vinh danh và không có hy vọng thành công?''",
            "Someone asked her: `Why do you do this when there is no payment, no recognition, and no hope of success?'"),
           ("Mẹ Teresa trả lời bình thản: ``Tôi không làm điều này để thành công; tôi làm vì mỗi người đó là Chúa trong một y phục khác.''",
            "Mother Teresa replied calmly: `I do not do this to succeed; I do it because each person is God in a different disguise.'"),
           ("Bà đã thành lập hơn 600 cơ sở từ thiện ở 123 quốc gia --- tất cả đều bắt đầu từ một người hấp hối trên vỉa hè.",
            "She founded more than 600 charitable missions in 123 countries --- all beginning with one dying person on a pavement.")],
          "Lòng tốt thật sự không hỏi `Cái gì tôi được từ việc này?' --- nó chỉ nhìn thấy người cần giúp và hành động.",
          "True goodness does not ask `What do I get from this?' --- it only sees someone in need and acts."),

    story("Albert Schweitzer Và Bệnh Viện Trong Rừng Châu Phi", "Albert Schweitzer --- Gabon, 1913",
          "Albert",
          [("Albert Schweitzer là nhà thần học, nhạc sĩ và nhà triết học tài năng --- ông có thể có cuộc đời danh vọng ở châu Âu.",
            "Albert Schweitzer was a gifted theologian, musician, and philosopher --- he could have had a prestigious life in Europe."),
           ("Nhưng ở tuổi 38, ông quyết định học y khoa và đến Gabon, châu Phi, xây dựng bệnh viện giữa rừng già.",
            "But at 38 he decided to study medicine and go to Gabon, Africa, to build a hospital in the deep forest."),
           ("Ông sống và làm việc ở đó 50 năm --- chữa trị cho hàng triệu người không có điều kiện tiếp cận y tế.",
            "He lived and worked there for 50 years --- treating millions of people with no access to healthcare."),
           ("Khi nhận giải Nobel Hoà Bình năm 1952, ông nói: ``Tôi không xứng đáng; những bệnh nhân của tôi mới xứng đáng.''",
            "On receiving the Nobel Peace Prize in 1952, he said: `I do not deserve it; my patients are the ones who deserve it.'"),
           ("Triết học sống của ông: ``Lòng kính trọng sự sống'' --- mọi sinh vật đều xứng đáng được sống và được tôn trọng.",
            "His life philosophy: `Reverence for Life' --- all living things deserve to live and to be treated with respect.")],
          "Lòng tốt lành sâu sắc nhất là hiến dâng không tính toán --- khi không ai bắt buộc và không ai nhìn.",
          "The deepest goodness is giving without calculation --- when no one compels it and no one is watching."),

    story("Bác Sĩ Norman Bethune Và Máu Trong Chiến Tranh", "Norman Bethune --- Trung Quốc, 1938",
          "Norman",
          [("Norman Bethune là bác sĩ người Canada đến Trung Quốc năm 1938 để hỗ trợ quân đội kháng Nhật.",
            "Norman Bethune was a Canadian doctor who went to China in 1938 to support the army fighting Japanese invasion."),
           ("Ông phát minh ra dịch vụ truyền máu lưu động --- đưa máu trực tiếp ra chiến trường để cứu thương binh.",
            "He invented a mobile blood transfusion service --- bringing blood directly to the battlefield to save the wounded."),
           ("Trong một ca phẫu thuật giữa chiến trận, ông bị thương ở tay nhưng vẫn tiếp tục mổ suốt nhiều giờ.",
            "During an operation in the midst of battle, he cut his hand but continued operating for many more hours."),
           ("Nhiễm trùng từ vết thương đó cướp đi mạng sống ông; thư cuối cùng ông viết: ``Tôi hạnh phúc vì được cống hiến.''",
            "The infection from that wound took his life; his final letter read: `I am happy because I have been of service.'"),
           ("Mao Trạch Đông viết bài tưởng niệm Bethune --- nó đã được đọc bởi hàng tỷ người ở Trung Quốc suốt nhiều thế hệ.",
            "Mao Zedong wrote a memorial essay on Bethune --- it has been read by billions in China across generations.")],
          "Lòng tốt lành không sợ chịu thiệt --- người thiện lương thật sự không hỏi cái giá phải trả là bao nhiêu.",
          "True goodness is not afraid of cost --- the truly good-hearted do not ask what the price will be."),

    story("Miep Gies Và Gia Đình Frank", "Miep Gies --- Hà Lan, 1942",
          "Miep",
          [("Miep Gies là thư ký bình thường ở Amsterdam khi Thế chiến II bắt đầu và Đức Quốc Xã chiếm Hà Lan.",
            "Miep Gies was an ordinary secretary in Amsterdam when World War II began and Nazi Germany occupied Holland."),
           ("Trong hai năm, bà bí mật cung cấp thức ăn và nguồn lực cho gia đình Do Thái Frank ẩn náu trong căn gác thượng.",
            "For two years she secretly supplied food and resources to the Jewish Frank family hiding in a secret annex."),
           ("Mỗi ngày bà đối mặt với nguy cơ bị bắt và xử tử nếu bị phát hiện; nhưng bà không bao giờ dừng lại.",
            "Every day she faced the risk of arrest and execution if discovered; but she never stopped."),
           ("Sau khi gia đình Frank bị bắt, bà nhặt nhật ký của Anne Frank và giữ cho đến sau chiến tranh.",
            "After the Frank family was arrested, she picked up Anne Frank's diary and kept it safe until after the war."),
           ("Bà nói: ``Tôi không anh hùng gì; tôi chỉ làm điều bất kỳ người tử tế nào cũng sẽ làm.''",
            "She said: `I was not a hero; I only did what any decent person would have done.'")],
          "Lòng tốt lành thường không tự nhận mình là anh hùng --- nó chỉ thấy điều phải làm và lặng lẽ làm điều đó.",
          "Goodness of heart rarely calls itself heroic --- it simply sees what must be done and quietly does it."),

    story("Nicholas Winton Và Chuyến Tàu Cứu Trẻ Em Do Thái", "Nicholas Winton --- Tiệp Khắc, 1938",
          "Nicholas",
          [("Nicholas Winton, một nhà môi giới chứng khoán người Anh, đến Prague năm 1938 và thấy hàng nghìn trẻ em Do Thái đang nguy hiểm.",
            "Nicholas Winton, a British stockbroker, went to Prague in 1938 and saw thousands of Jewish children in danger."),
           ("Ông huỷ kỳ nghỉ trượt tuyết của mình và bắt đầu tổ chức đưa trẻ em ra khỏi Tiệp Khắc bằng tàu lửa.",
            "He cancelled his skiing holiday and began organizing the evacuation of children from Czechoslovakia by train."),
           ("Trong vòng vài tháng, ông tổ chức 9 chuyến tàu đưa 669 trẻ em sang Anh --- phần lớn cha mẹ chúng đã chết trong Holocaust.",
            "Within months he organised 9 trains carrying 669 children to Britain --- most of whose parents would die in the Holocaust."),
           ("Ông không kể cho ai nghe việc này trong 50 năm; chỉ khi vợ ông tìm thấy giấy tờ cũ, câu chuyện mới được tiết lộ.",
            "He told no one of this for 50 years; only when his wife found old papers was the story revealed."),
           ("Năm 1988, trong một chương trình truyền hình, ông ngồi cạnh những người mà ông đã cứu --- những người giờ đây đã là ông bà.",
            "In 1988, on a television programme, he sat surrounded by the people he had saved --- now grandparents themselves.")],
          "Lòng tốt lành thật sự không cần khán giả --- nó hành động ngay cả khi không ai biết và không ai cảm ơn.",
          "True goodness needs no audience --- it acts even when no one knows and no one says thank you."),

    story("Clara Barton Và Nền Tảng Của Hội Chữ Thập Đỏ Mỹ", "Clara Barton --- Hoa Kỳ, 1861",
          "Clara",
          [("Clara Barton là giáo viên bình thường khi Nội Chiến Mỹ bùng nổ; bà không có kinh nghiệm y tế.",
            "Clara Barton was an ordinary schoolteacher when the American Civil War broke out; she had no medical experience."),
           ("Nhưng khi thấy các thương binh thiếu thuốc và thức ăn, bà tự mình đứng ra quyên góp và phân phát.",
            "But seeing the wounded lacking medicine and food, she personally stepped forward to collect and distribute supplies."),
           ("Bà xin phép đi ra mặt trận để chăm sóc thương binh --- bị từ chối nhiều lần nhưng không bỏ cuộc.",
            "She requested permission to go to the front to nurse the wounded --- refused many times but never giving up."),
           ("Cuối cùng được phép, bà ra chiến trường và tiếp tục làm việc trong điều kiện nguy hiểm nhất.",
            "Finally given permission, she went to the battlefield and worked in the most dangerous conditions."),
           ("Sau chiến tranh, bà thành lập Hội Chữ Thập Đỏ Mỹ --- tổ chức nhân đạo lớn nhất ở Hoa Kỳ cho đến ngày nay.",
            "After the war she founded the American Red Cross --- the largest humanitarian organisation in the US to this day.")],
          "Lòng tốt lành tìm ra cách --- nó không chờ điều kiện hoàn hảo hay sự cho phép hoàn toàn để bắt đầu.",
          "Goodness of heart finds a way --- it does not wait for perfect conditions or complete permission to begin."),

    story("Raoul Wallenberg Và Hộ Chiếu Cứu Mạng", "Raoul Wallenberg --- Hungary, 1944",
          "Raoul",
          [("Raoul Wallenberg, nhà ngoại giao Thuỵ Điển, được gửi đến Budapest năm 1944 khi Đức Quốc Xã đang trục xuất người Do Thái.",
            "Raoul Wallenberg, a Swedish diplomat, was sent to Budapest in 1944 as the Nazis were deporting Jews."),
           ("Ông phát minh ra `hộ chiếu bảo vệ' của Thuỵ Điển --- tài liệu ngoại giao đặc biệt cho phép người mang nó không bị trục xuất.",
            "He invented `Swedish protective passports' --- special diplomatic documents allowing the holder to avoid deportation."),
           ("Ông phát hàng ngàn tấm hộ chiếu đó --- đôi khi chạy theo những đoàn tàu chở người Do Thái để phát hộ chiếu qua cửa sổ.",
            "He issued thousands of these passports --- sometimes running after trains deporting Jews to pass passports through the windows."),
           ("Ông cũng mua và thuê 32 toà nhà, treo cờ Thuỵ Điển, tuyên bố chúng là lãnh thổ ngoại giao không thể bị bắt người.",
            "He also bought and rented 32 buildings, flew Swedish flags, declaring them diplomatic territory where no one could be seized."),
           ("Ông cứu được khoảng 100.000 người Do Thái Hungary --- sau đó bị bắt bởi Liên Xô và mất tích trong ngục tù.",
            "He saved approximately 100,000 Hungarian Jews --- then was arrested by the Soviets and disappeared in their prisons.")],
          "Lòng tốt lành đích thực dám chấp nhận rủi ro vì người khác --- không phải vì không biết nguy hiểm mà vì biết và vẫn chọn.",
          "Genuine goodness dares to take risks for others --- not from not knowing the danger, but from knowing it and choosing anyway."),

    story("Nguyễn Trãi --- Nhân Nghĩa Là Nền Tảng Của Sức Mạnh", "Nguyễn Trãi --- Việt Nam, thế kỷ 15",
          "Nguyễn",
          [("Nguyễn Trãi, đại danh nhân của dân tộc Việt Nam, xuất thân từ gia đình quan lại nhưng chọn sống vì dân.",
            "Nguyen Trai, a great figure of the Vietnamese people, came from a mandarin family but chose to live for the people."),
           ("Khi quân Minh đô hộ và ông nội bị giết, ông không chọn trả thù cá nhân --- ông chọn con đường giải phóng dân tộc.",
            "When the Ming occupied Vietnam and his grandfather was killed, he did not choose personal revenge --- he chose national liberation."),
           ("Trong Bình Ngô Đại Cáo, ông viết: ``Việc nhân nghĩa cốt ở yên dân'' --- lấy lợi ích của người dân làm trung tâm.",
            "In the Proclamation, he wrote: `The purpose of humanity is to bring peace to the people' --- placing the people's welfare at the centre."),
           ("Sau khi đất nước giải phóng, ông về ẩn cư ở Côn Sơn, viết thơ và sống giản dị --- từ chối quyền lực và danh lợi.",
            "After liberation, he retired to Con Son, wrote poetry and lived simply --- refusing power and fame."),
           ("Ông để lại di sản văn hoá và đạo đức cho hàng thế kỷ sau trong nền văn hiến Việt Nam.",
            "He left a cultural and ethical legacy lasting centuries in Vietnamese civilisation.")],
          "Người thiện lương thật sự không giữ lại lòng tốt cho riêng mình --- họ dùng nó để phụng sự người khác và xây dựng tương lai.",
          "The truly good-hearted do not keep goodness for themselves --- they use it to serve others and build the future."),

    story("Eglantyne Jebb Và Tổ Chức Cứu Trợ Trẻ Em", "Eglantyne Jebb --- Anh, 1919",
          "Eglantyne",
          [("Eglantyne Jebb, người phụ nữ Anh, bị bắt năm 1919 vì phát tờ truyền đơn kêu gọi giúp đỡ trẻ em Đức và Áo đang chết đói sau Thế chiến I.",
            "Eglantyne Jebb, an English woman, was arrested in 1919 for distributing leaflets calling for aid to German and Austrian children starving after World War I."),
           ("Bà bị phạt năm bảng; nhưng công tố viên cảm động đến mức trả lại tiền phạt và quyên góp thêm cho quỹ từ thiện của bà.",
            "She was fined five pounds; but the prosecutor was so moved he returned the fine money and donated more to her charity fund."),
           ("Từ vụ bị bắt đó, bà quyết tâm hơn bao giờ hết; bà cùng em gái thành lập tổ chức Cứu Trợ Trẻ Em.",
            "From that arrest she was more determined than ever; she and her sister founded the organisation Save the Children."),
           ("Bà viết Tuyên Ngôn Quyền Trẻ Em --- tài liệu đặt nền tảng cho Công Ước Liên Hiệp Quốc về Quyền Trẻ Em sau này.",
            "She wrote the Declaration of the Rights of the Child --- the document that laid foundations for the later UN Convention on the Rights of the Child."),
           ("Bà nói: ``Mỗi bộ óc con người và mỗi bàn tay con người có thể làm cho thế giới này tốt hơn.''",
            "She said: `Every human brain and every pair of human hands can make this world a better place.'")],
          "Lòng tốt lành không sợ bị hiểu nhầm hay bị phạt --- nó tiếp tục làm điều phải làm dù thế giới có phản ứng ra sao.",
          "Goodness of heart is not afraid of being misunderstood or penalised --- it continues doing what must be done whatever the world's reaction."),

    story("Phan Bội Châu --- Lòng Yêu Nước Là Phẩm Chất Thiện Lương Cao Nhất", "Phan Bội Châu --- Việt Nam, đầu thế kỷ 20",
          "Phan",
          [("Phan Bội Châu dành cả cuộc đời đấu tranh giải phóng Việt Nam khỏi ách thực dân Pháp, chấp nhận lưu vong và tù đày.",
            "Phan Boi Chau devoted his entire life to liberating Vietnam from French colonialism, accepting exile and imprisonment."),
           ("Khi bị bắt và áp giải về Việt Nam năm 1925, người dân đổ ra đường đón ông với lòng kính trọng sâu sắc.",
            "When arrested and escorted back to Vietnam in 1925, people lined the streets to welcome him with profound respect."),
           ("Pháp dự định xử tử ông; nhưng trước áp lực của dân chúng, họ phải giảm án xuống còn quản thúc tại gia suốt đời.",
            "France intended to execute him; but under public pressure, they had to reduce the sentence to lifelong house arrest."),
           ("Những năm bị giam lỏng ở Huế, ông vẫn viết, dạy học, truyền lửa yêu nước cho thế hệ trẻ.",
            "During years of house arrest in Hue, he still wrote, taught, and passed the flame of patriotism to young generations."),
           ("Ông nói: ``Nước mất thì dù sống cũng như đã chết; nước còn thì dù chết cũng như vẫn đang sống.''",
            "He said: `If the country is lost, to live is as if dead; if the country endures, to die is as if still living.'")],
          "Yêu nước không chỉ là cảm xúc --- đó là hành động sẵn sàng hy sinh điều quý nhất của mình vì điều còn quý hơn.",
          "Patriotism is not just an emotion --- it is the action of willingly sacrificing what is precious for something even more precious."),
    ])

with open(os.path.join(BASE, "ch08-thien-luong.tex"), "w", encoding="utf-8") as f:
    f.write(ch8)
print("ch08 done")

# ================================================================
# CHƯƠNG 9: TRÍ TUỆ CỔ NHÂN
# ================================================================
ch9 = chapter(
    "Trí Tuệ Cổ Nhân --- Kho Tàng Muôn Đời", "Ancient Wisdom --- Timeless Treasure",
    "Sông có thể cạn, núi có thể mòn, nhưng trí tuệ của người xưa không bao giờ lỗi thời.",
    "Rivers may dry, mountains may erode, but the wisdom of the ancients never goes out of date.",
    [
    story("Tôn Tử Và Nghệ Thuật Chiến Tranh", "Tôn Tử --- Trung Quốc, thế kỷ 6 TCN",
          "Tôn",
          [("Tôn Tử viết Binh Pháp --- cuốn sách quân sự ngắn nhất và ảnh hưởng nhất trong lịch sử nhân loại.",
            "Sun Tzu wrote The Art of War --- the shortest and most influential military treatise in human history."),
           ("Ông viết: ``Biết người biết ta, trăm trận trăm thắng; biết ta mà không biết người, thắng bại bằng nhau.''",
            "He wrote: `Know the enemy, know yourself, and in a hundred battles you will never be defeated.'"),
           ("Triết học chiến tranh của ông đặt sự tự hiểu và hiểu đối phương lên trên mọi chiến thuật.",
            "His war philosophy placed self-understanding and understanding the opponent above all tactics."),
           ("Cuốn sách này được nghiên cứu bởi Napoleon, Mao Trạch Đông, các CEO hiện đại và các nhà ngoại giao toàn cầu.",
            "This book has been studied by Napoleon, Mao Zedong, modern CEOs, and diplomats worldwide."),
           ("Trí tuệ 2500 năm tuổi này vẫn được dạy ở các trường kinh doanh và quân sự uy tín nhất thế giới.",
            "This 2,500-year-old wisdom is still taught at the world's most prestigious business and military schools.")],
          "Trí tuệ bền vững nhất là trí tuệ dựa trên bản chất của con người --- vì bản chất con người không thay đổi dù thế kỷ trôi qua.",
          "The most enduring wisdom is wisdom based on human nature --- for human nature does not change though centuries pass."),

    story("Lão Tử Và Đạo Đức Kinh", "Lão Tử --- Trung Quốc, thế kỷ 6 TCN",
          "Lão",
          [("Lão Tử, người được gọi là `ông già' vì sinh ra đã có râu, viết Đạo Đức Kinh chỉ có 81 chương ngắn.",
            "Laozi, called `the old master' for being born allegedly already with white hair, wrote the Tao Te Ching in just 81 short chapters."),
           ("Ông viết: ``Tri túc giả phú'' --- người biết đủ thì giàu --- trái ngược hoàn toàn với triết học tích luỹ hiện đại.",
            "He wrote: `Knowing what is enough is wealth' --- completely opposed to modern accumulation philosophy."),
           ("Ông dạy về vô vi --- hành động không ép buộc, để vạn vật tự nhiên vận hành theo đúng bản chất của nó.",
            "He taught wu wei --- effortless action, allowing all things to move naturally according to their own nature."),
           ("``Người thắng người khác là kẻ mạnh; người thắng chính mình mới thật sự hùng mạnh.''",
            "`One who conquers others is strong; one who conquers himself is truly powerful.'"),
           ("Đạo Đức Kinh là cuốn sách được dịch nhiều thứ hai trên thế giới --- chỉ sau Kinh Thánh.",
            "The Tao Te Ching is the second most translated book in the world --- just after the Bible.")],
          "Trí tuệ đích thực thường đơn giản đến mức dễ bị bỏ qua --- nhưng khi thực hành, nó thay đổi mọi thứ.",
          "True wisdom is often so simple it is easily overlooked --- but when practised, it changes everything."),

    story("Khổng Tử Và Năm Đức Hạnh Của Người Quân Tử", "Khổng Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Khổng",
          [("Khổng Tử dạy rằng người quân tử --- người có phẩm chất cao quý --- phải có năm đức hạnh cơ bản.",
            "Confucius taught that the junzi --- the person of noble character --- must possess five fundamental virtues."),
           ("Nhân --- lòng nhân từ và yêu thương người; Nghĩa --- sự công bằng và đúng đắn; Lễ --- sự tôn trọng và lịch thiệp.",
            "Ren --- benevolence and love; Yi --- righteousness and justice; Li --- respect and propriety."),
           ("Trí --- sự khôn ngoan và hiểu biết đúng đắn; Tín --- sự thành thật và đáng tin cậy.",
            "Zhi --- wisdom and right understanding; Xin --- honesty and trustworthiness."),
           ("Ông không dạy những đức hạnh này như quy tắc cứng nhắc mà như phẩm chất cần rèn luyện suốt đời.",
            "He did not teach these virtues as rigid rules but as qualities that must be cultivated throughout life."),
           ("Hai nghìn năm trăm năm sau, những nguyên tắc này vẫn là nền tảng của nhiều xã hội châu Á và cả thế giới.",
            "Two thousand five hundred years later, these principles remain foundational to many Asian societies and the wider world.")],
          "Đức hạnh không phải quy tắc phải tuân theo mà là thói quen cần rèn giũa --- sự khác biệt đó thay đổi tất cả.",
          "Virtue is not a rule to obey but a habit to cultivate --- that difference changes everything."),

    story("Trang Tử Và Bướm Bay Trong Giấc Mơ", "Trang Tử --- Trung Quốc, thế kỷ 4 TCN",
          "Trang",
          [("Trang Tử một đêm mơ thấy mình là con bướm bay nhẹ nhàng; khi tỉnh dậy, ông đặt câu hỏi:",
            "Zhuangzi one night dreamed he was a butterfly floating freely; upon waking, he asked:"),
           ("``Ta là người Trang Chu mơ thấy mình là bướm, hay ta là con bướm đang mơ thấy mình là Trang Chu?''",
            "`Am I Zhuangzi who dreamed of being a butterfly, or am I a butterfly now dreaming of being Zhuangzi?'"),
           ("Triết học đơn giản này chứa đựng thông điệp sâu xa: thực tại không nhất thiết là những gì ta nhìn thấy.",
            "This simple philosophy contains a profound message: reality is not necessarily what we perceive."),
           ("Ông dạy rằng cái chết không đáng sợ vì nó chỉ là sự chuyển hoá --- như nước thành băng rồi thành hơi.",
            "He taught that death is not to be feared because it is only transformation --- like water becoming ice then vapour."),
           ("Khi vợ ông mất, ông ngồi hát --- không phải vì nhẫn tâm mà vì ông tin bà đang trở về nguồn cội vũ trụ.",
            "When his wife died, he sat singing --- not heartlessly but because he believed she was returning to the cosmic source.")],
          "Trí tuệ đôi khi đến từ việc đặt câu hỏi về các giả định chúng ta cho là hiển nhiên --- thực tại thường phức tạp hơn ta tưởng.",
          "Wisdom sometimes comes from questioning what we assume is obvious --- reality is usually more complex than we suppose."),

    story("Mạnh Tử Và Bản Tính Thiện Của Con Người", "Mạnh Tử --- Trung Quốc, thế kỷ 4 TCN",
          "Mạnh",
          [("Mạnh Tử, học trò của Khổng Tử nhiều thế hệ sau, đặt ra câu hỏi nền tảng: bản tính con người thiện hay ác?",
            "Mencius, a student in the Confucian tradition generations later, posed the fundamental question: is human nature good or evil?"),
           ("Ông lý luận rằng bản tính con người vốn thiện --- lấy ví dụ ai thấy đứa trẻ sắp rơi xuống giếng cũng phản xạ cứu.",
            "He argued that human nature is inherently good --- citing that anyone seeing a child about to fall into a well instinctively reaches to save it."),
           ("Ông so sánh việc trau dồi đức hạnh như trồng cây --- cần nước tưới, đất tốt và kiên nhẫn, không thể bỏ bê.",
            "He compared cultivating virtue to growing a tree --- needing water, good soil, and patience, not neglect."),
           ("``Lấy người dạy người là vui hơn'' --- học từ người khác và dạy người khác là con đường hoàn thiện bản thân.",
            "`Learning from others and teaching others is the greater joy' --- mutual learning is the path to self-cultivation."),
           ("Triết học của ông là nền tảng của hệ thống giáo dục và quản trị xã hội ở nhiều quốc gia châu Á hàng nghìn năm.",
            "His philosophy has been the foundation of educational systems and social governance in many Asian nations for millennia.")],
          "Tin vào bản tính tốt đẹp của con người không phải ngây thơ --- đó là xuất phát điểm của mọi hệ thống giáo dục hiệu quả.",
          "Believing in the inherent goodness of human nature is not naivety --- it is the starting point of every effective education system."),

    story("Hàn Phi Tử Và Nghệ Thuật Quản Trị", "Hàn Phi Tử --- Trung Quốc, thế kỷ 3 TCN",
          "Hàn",
          [("Hàn Phi Tử là nhà triết học pháp gia --- người đặt câu hỏi: làm sao trị quốc khi người không thể tin vào thiện tâm?",
            "Han Fei Zi was a Legalist philosopher --- who asked: how do you govern when you cannot rely on people's goodwill?"),
           ("Câu trả lời của ông: xây dựng hệ thống pháp luật rõ ràng, thưởng đúng người xứng, phạt đúng người sai.",
            "His answer: build clear legal systems, reward those who deserve it, punish those who commit wrongs."),
           ("Ông không tin vào đức hạnh như Khổng Tử; ông tin vào cơ chế khuyến khích đúng đắn.",
            "He did not trust virtue as Confucius did; he trusted correct incentive mechanisms."),
           ("``Thánh nhân không trông đợi sự thiện lương của người dân; ông ta dùng những gì khiến người dân không thể làm điều xấu.''",
            "`A sage does not depend on people's goodness; he uses what prevents people from being able to do wrong.'"),
           ("Tư tưởng của Hàn Phi Tử ảnh hưởng đến hệ thống pháp luật và quản trị của nhiều nền văn minh.",
            "Han Fei Zi's thought influenced legal systems and governance of many civilisations.")],
          "Trí tuệ quản trị nằm ở chỗ xây dựng hệ thống khiến người ta làm điều đúng dễ hơn làm điều sai.",
          "Governance wisdom lies in building systems that make doing right easier than doing wrong."),

    story("Aristotle Và Nghệ Thuật Sống Hạnh Phúc", "Aristotle --- Hy Lạp, thế kỷ 4 TCN",
          "Aristotle",
          [("Aristotle dạy rằng mục tiêu của cuộc đời là `eudaimonia' --- thường dịch là hạnh phúc nhưng thực ra có nghĩa là `phát triển thịnh vượng'.",
            "Aristotle taught that the purpose of life is `eudaimonia' --- usually translated as happiness but more precisely meaning `flourishing.'"),
           ("Ông phân biệt hạnh phúc thụ động --- cảm thấy vui vẻ --- với hạnh phúc chủ động --- sống đúng với phẩm chất tốt nhất của mình.",
            "He distinguished passive happiness --- feeling pleased --- from active happiness --- living in accordance with one's best qualities."),
           ("Ông nói: ``Chúng ta là những gì chúng ta liên tục làm; sự xuất sắc, vì vậy, không phải hành động mà là thói quen.''",
            "He said: `We are what we repeatedly do; excellence, therefore, is not an act but a habit.'"),
           ("Ông dạy rằng đức hạnh là `trung đạo' giữa hai thái cực --- dũng cảm nằm giữa hèn nhát và liều lĩnh.",
            "He taught that virtue is the `golden mean' between two extremes --- courage lies between cowardice and recklessness."),
           ("Tư tưởng của Aristotle là nền tảng của triết học phương Tây, khoa học hiện đại và đạo đức học.",
            "Aristotle's thought is the foundation of Western philosophy, modern science, and ethics.")],
          "Hạnh phúc thật sự không phải trạng thái cảm xúc mà là kết quả của việc sống đúng với những phẩm chất tốt nhất của bạn.",
          "True happiness is not an emotional state but the result of living in accordance with your best qualities."),

    story("Ibn Sina Và Bộ Bách Khoa Toàn Thư Y Học", "Ibn Sina --- Ba Tư, thế kỷ 11",
          "Ibn",
          [("Ibn Sina, được phương Tây gọi là Avicenna, là nhà bác học người Ba Tư sống vào thế kỷ 11.",
            "Ibn Sina, known in the West as Avicenna, was a Persian polymath of the 11th century."),
           ("Ông viết hơn 450 công trình về y học, triết học, thiên văn học, âm nhạc và toán học.",
            "He wrote more than 450 works on medicine, philosophy, astronomy, music, and mathematics."),
           ("Bộ Quy Tắc Y Học của ông là giáo trình y khoa tiêu chuẩn ở châu Âu và thế giới Hồi giáo suốt 600 năm.",
            "His Canon of Medicine was the standard medical textbook in Europe and the Islamic world for 600 years."),
           ("Ông lý thuyết hoá về cách lây lan bệnh qua đất và nước --- tiền thân của lý thuyết vi khuẩn học.",
            "He theorised on how disease spreads through soil and water --- a precursor of germ theory."),
           ("Ông học một cách chưa từng thấy: `vào lúc khó khăn nhất, tôi trở lại nhà thờ Hồi giáo và cầu nguyện cho đến khi tìm ra câu trả lời.'",
            "He described his learning: `In the most difficult moments, I returned to the mosque and prayed until the answer came.'")],
          "Trí tuệ không phân biệt nguồn gốc văn hoá hay tôn giáo --- người tìm kiếm nó với lòng thành thật sẽ tìm thấy nó ở bất kỳ đâu.",
          "Wisdom does not distinguish between cultural or religious origins --- those who seek it sincerely will find it anywhere."),

    story("Plato Và Cái Hang Huyền Thoại", "Plato --- Hy Lạp, thế kỷ 4 TCN",
          "Plato",
          [("Plato kể câu chuyện huyền thoại về những người bị xích trong hang tối, chỉ thấy bóng mờ trên tường hang.",
            "Plato told the famous allegorical story of people chained in a dark cave, seeing only shadows on the cave wall."),
           ("Những người đó nhầm bóng mờ là thực tại; khi một người được thả ra và thấy mặt trời, ban đầu anh bị mù loà.",
            "These people mistook shadows for reality; when one is freed and sees the sun, he is initially blinded."),
           ("Khi trở lại hang để kể sự thật cho người khác, họ nghĩ anh điên và không tin.",
            "When he returns to tell the others the truth, they think him mad and do not believe him."),
           ("Câu chuyện này là ẩn dụ cho quá trình giáo dục: mỗi lần học là thêm một bước ra khỏi bóng tối về phía ánh sáng.",
            "This story is a metaphor for education: every time we learn is one more step from darkness toward light."),
           ("Plato dạy rằng nhiệm vụ của triết học là giúp con người nhìn thấy sự thật thay vì chỉ nhìn thấy bóng của sự thật.",
            "Plato taught that the task of philosophy is to help people see truth rather than only the shadows of truth.")],
          "Giáo dục thật sự không phải nhồi thêm thông tin vào đầu --- mà là giúp người học nhìn thấy thực tại rõ ràng hơn.",
          "True education is not cramming more information into the head --- but helping the learner see reality more clearly."),

    story("Nguyễn Bỉnh Khiêm Và Triết Học Nhàn Cư", "Nguyễn Bỉnh Khiêm --- Việt Nam, thế kỷ 16",
          "Nguyễn",
          [("Nguyễn Bỉnh Khiêm, hiệu Trạng Trình, là nhà tiên tri và triết học gia lớn nhất Việt Nam thế kỷ 16.",
            "Nguyen Binh Khiem, known as Trang Trinh, was the greatest prophet and philosopher of 16th-century Vietnam."),
           ("Ông làm quan nhưng sớm cáo quan về quê vì không chịu được sự gian tà trong triều đình.",
            "He served as an official but soon resigned and returned home, unable to bear the treachery of the court."),
           ("Thơ ông dạy triết học nhàn cư --- sống hài hoà với thiên nhiên, không chạy đua với danh lợi phù du.",
            "His poetry taught a philosophy of leisured living --- in harmony with nature, not racing after transient fame and gain."),
           ("``Ta dại, ta tìm nơi vắng vẻ; người khôn, người đến chốn lao xao'' --- ông dạy rằng thật sự khôn ngoan là biết dừng lại.",
            "`I foolish, seek places of quiet; the wise, they go to places of clamour' --- he taught that true wisdom is knowing when to stop."),
           ("Nhiều vua chúa thời đó đến hỏi ông về kế sách --- ông trả lời bằng thơ, không bao giờ bằng lời khuyên trực tiếp.",
            "Many lords of that era came to ask his advice --- he always answered in poetry, never in direct counsel.")],
          "Trí tuệ của người ẩn cư không phải từ bỏ thế giới --- mà là giữ khoảng cách đủ để nhìn thế giới rõ ràng hơn.",
          "The wisdom of the recluse is not abandoning the world --- but keeping enough distance to see the world more clearly."),
    ])

with open(os.path.join(BASE, "ch09-tri-tue-co-nhan.tex"), "w", encoding="utf-8") as f:
    f.write(ch9)
print("ch09 done")

# ================================================================
# CHƯƠNG 10: KIẾN TẠO CUỘC ĐỜI
# ================================================================
ch10 = chapter(
    "Kiến Tạo Cuộc Đời --- Bạn Là Kiến Trúc Sư Của Chính Mình", "Building Your Life --- You Are Your Own Architect",
    "Tương lai thuộc về những ai tin vào vẻ đẹp của ước mơ của họ.",
    "The future belongs to those who believe in the beauty of their dreams.",
    [
    story("Steve Jobs Và Nghệ Thuật Kết Nối Những Dấu Chấm", "Steve Jobs --- Hoa Kỳ, 2005",
          "Steve",
          [("Steve Jobs trong bài phát biểu tốt nghiệp nổi tiếng tại Stanford năm 2005 kể câu chuyện về những dấu chấm.",
            "Steve Jobs in his famous 2005 Stanford commencement address told the story of connecting the dots."),
           ("Sau khi bỏ học đại học, ông vẫn ở lại nghe lén các lớp học --- và học thêm khoá thư pháp vì cảm thấy thú vị.",
            "After dropping out of college, he still stayed and sneaked into classes --- and studied calligraphy because he found it fascinating."),
           ("Mười năm sau, khi thiết kế Mac, ông đưa thư pháp vào máy tính --- tạo ra những font chữ đẹp đầu tiên trong lịch sử.",
            "Ten years later, designing the Mac, he put calligraphy into the computer --- creating the first beautiful typefaces in history."),
           ("Ông nói: ``Bạn không thể kết nối những dấu chấm nhìn về phía trước; bạn chỉ có thể kết nối nhìn ngược lại.''",
            "He said: `You cannot connect the dots looking forward; you can only connect them looking backwards.'"),
           ("``Vì vậy bạn phải tin rằng những dấu chấm sẽ được kết nối theo một cách nào đó trong tương lai.''",
            "`So you must trust that the dots will somehow connect in your future.'")],
          "Mỗi điều bạn học --- dù có vẻ vô dụng tức thì --- đều có thể trở thành viên gạch xây nên kỳ tích của bạn về sau.",
          "Every thing you learn --- however apparently useless immediately --- can become a brick building your future masterpiece."),

    story("Walt Disney --- Bảy Lần Phá Sản, Một Lần Đế Chế", "Walt Disney --- Hoa Kỳ, 1966",
          "Walt",
          [("Walt Disney bị đuổi khỏi tờ báo vì ``thiếu trí tưởng tượng và không có ý tưởng tốt nào.''",
            "Walt Disney was fired from a newspaper for `lacking imagination and having no good ideas.'"),
           ("Ông thành lập công ty hoạt hình đầu tiên và phá sản; thành lập lại và phá sản lần hai.",
            "He founded his first animation company and went bankrupt; founded another and went bankrupt again."),
           ("Mickey Mouse bị 300 nhà đầu tư từ chối trước khi một người chịu nghe --- và khi phim Bạch Tuyết ra mắt, mọi người kinh ngạc.",
            "Mickey Mouse was rejected by 300 investors before one listened --- and when Snow White premiered, audiences were astonished."),
           ("Disney nói: ``Tất cả những ước mơ của chúng ta có thể trở thành sự thật nếu chúng ta có can đảm theo đuổi chúng.''",
            "Disney said: `All our dreams can come true if we have the courage to pursue them.'"),
           ("Đế chế Disney ngày nay là một trong những thương hiệu giá trị nhất thế giới --- sinh ra từ những lần phá sản và những giấc mơ không tắt.",
            "The Disney empire today is one of the world's most valuable brands --- born from bankruptcies and undying dreams.")],
          "Giấc mơ không chết vì thất bại --- nó chỉ chết khi bạn quyết định ngừng theo đuổi nó.",
          "A dream does not die from failure --- it only dies when you decide to stop pursuing it."),

    story("Oprah Winfrey --- Từ Nghèo Khổ Đến Ảnh Hưởng", "Oprah Winfrey --- Hoa Kỳ, 1954",
          "Oprah",
          [("Oprah Winfrey sinh ra trong nghèo khổ ở Mississippi; bị lạm dụng từ nhỏ và mang thai năm 14 tuổi.",
            "Oprah Winfrey was born into poverty in Mississippi; she was abused as a child and became pregnant at 14."),
           ("Bị đuổi khỏi chương trình tin tức vì ``quá cảm xúc''; đã tưởng sự nghiệp truyền hình kết thúc.",
            "She was fired from a news programme for being `too emotional'; her television career seemed finished."),
           ("Nhưng bà tiếp tục --- và show Oprah Winfrey trở thành chương trình talkshow thành công nhất lịch sử truyền hình Mỹ.",
            "But she continued --- and The Oprah Winfrey Show became the most successful talk show in American television history."),
           ("Bà nói: ``Không có người thành công nào mà không từng thất bại nhiều lần; điều khác biệt là họ không đứng yên sau khi ngã.''",
            "She said: `No truly successful person has not failed many times; what is different is they don't stay down after falling.'"),
           ("Bà dùng tầm ảnh hưởng của mình để trao học bổng, thành lập trường học ở Nam Phi và cổ suý đọc sách trên toàn cầu.",
            "She used her influence to fund scholarships, establish a school in South Africa, and champion reading globally.")],
          "Câu chuyện bạn kể về chính mình quyết định tất cả --- ai nói mình không thể thì thường đúng về bản thân họ.",
          "The story you tell about yourself determines everything --- those who say they cannot are usually right about themselves."),

    story("Thomas Edison Và Một Nghìn Bước Tới Thành Công", "Thomas Edison --- Hoa Kỳ, 1879",
          "Thomas",
          [("Thomas Edison thử nghiệm gần một nghìn loại vật liệu trước khi tìm ra sợi than cho bóng đèn điện.",
            "Thomas Edison tested nearly one thousand materials before finding the carbon filament for the electric light bulb."),
           ("Khi phóng viên hỏi cảm giác thất bại cả nghìn lần, ông trả lời: ``Tôi chưa thất bại --- tôi đã học 999 cách không hoạt động.''",
            "When a reporter asked how it felt to fail a thousand times, he replied: `I have not failed --- I have learned 999 ways that do not work.'"),
           ("Edison nói: ``Thiên tài là một phần trăm cảm hứng và chín mươi chín phần trăm mồ hôi và nỗ lực.''",
            "Edison said: `Genius is one percent inspiration and ninety-nine percent perspiration.'"),
           ("Phòng thí nghiệm của ông ở Menlo Park đăng ký hơn một nghìn bằng sáng chế --- trung bình mười bốn ngày một bằng.",
            "His laboratory at Menlo Park registered over one thousand patents --- an average of one every fourteen days."),
           ("Chìa khoá không phải là thiên tài hay may mắn mà là hệ thống làm việc có kỷ luật và không chịu bỏ cuộc.",
            "The key was not genius or luck but a disciplined work system and refusing to give up.")],
          "Thành công không đến một lần --- nó là kết quả tích luỹ của hàng trăm lần thử, học và thử lại.",
          "Success does not come once --- it is the cumulative result of hundreds of attempts, learnings, and attempts again."),

    story("J.K. Rowling --- Hành Trình Từ Vô Danh Đến Huyền Thoại", "J.K. Rowling --- Anh, 1997",
          "Joanne",
          [("Joanne Rowling viết Harry Potter trên những tờ giấy ăn trong quán cà phê ở Edinburgh --- người mẹ đơn thân đang sống nhờ trợ cấp.",
            "Joanne Rowling wrote Harry Potter on napkins in an Edinburgh café --- a single mother living on welfare."),
           ("Mười hai nhà xuất bản từ chối bản thảo; nhà xuất bản thứ mười ba nhận với điều kiện bà không hy vọng kiếm tiền từ sách thiếu nhi.",
            "Twelve publishers rejected the manuscript; the thirteenth accepted on condition she not expect to earn money from children's books."),
           ("Harry Potter và Hòn Đá Phù Thuỷ ra mắt năm 1997 và trở thành cơn sốt toàn cầu.",
            "Harry Potter and the Philosopher's Stone was published in 1997 and became a worldwide phenomenon."),
           ("Rowling nói: ``Bạn không thể nhìn thấy con đường phía trước từ nơi bạn đang đứng; bạn chỉ thấy từng bước tiếp theo.''",
            "Rowling said: `You cannot see the path ahead from where you stand; you can only see the very next step.'"),
           ("Cuộc sống của bà là bằng chứng rằng thất bại không phải điểm cuối --- nó là phần không thể thiếu của hành trình.",
            "Her life is proof that failure is not the end --- it is an essential part of the journey.")],
          "Bước tiếp theo --- không phải cánh chung --- là tất cả những gì bạn cần nhìn thấy để tiếp tục đi.",
          "The very next step --- not the final destination --- is all you need to see in order to keep going."),

    story("Elon Musk Và Những Canh Bạc Không Ai Dám Làm", "Elon Musk --- Hoa Kỳ, 2002",
          "Elon",
          [("Elon Musk sau khi bán PayPal có 180 triệu đô la và đặt câu hỏi: điều gì quan trọng nhất cho tương lai của nhân loại?",
            "Elon Musk after selling PayPal had 180 million dollars and asked: what matters most for humanity's future?"),
           ("Câu trả lời của ông: năng lượng bền vững và thuộc địa hoá đa hành tinh để bảo đảm sự tồn vong của loài người.",
            "His answer: sustainable energy and multi-planet colonisation to ensure humanity's survival."),
           ("Ông đặt cược phần lớn tài sản vào Tesla và SpaceX --- cả hai đều suýt phá sản nhiều lần.",
            "He bet most of his wealth on Tesla and SpaceX --- both came near bankruptcy multiple times."),
           ("Năm 2008, trong cuộc khủng hoảng tài chính, ông hầu như không còn tiền và mượn bạn bè để trả lương nhân viên.",
            "In 2008, during the financial crisis, he was almost out of money and borrowed from friends to pay employees."),
           ("SpaceX trở thành công ty tư nhân đầu tiên đưa tàu vũ trụ lên quỹ đạo; Tesla trở thành hãng xe điện giá trị nhất thế giới.",
            "SpaceX became the first private company to send spacecraft to orbit; Tesla became the world's most valuable electric car company.")],
          "Những ước mơ lớn đòi hỏi những canh bạc lớn --- và chỉ những người dám đặt cược bản thân mới có thể thay đổi thế giới.",
          "Big dreams require big bets --- and only those willing to wager themselves can change the world."),

    story("Warren Buffett Và Triết Học Đầu Tư Dài Hạn", "Warren Buffett --- Hoa Kỳ, 1956",
          "Warren",
          [("Warren Buffett mua cổ phiếu đầu tiên năm 11 tuổi và học bài học đắt giá đầu tiên khi nó giảm giá.",
            "Warren Buffett bought his first stock at age 11 and learned his first costly lesson when it fell in value."),
           ("Ông đọc hơn 500 trang sách và báo cáo kinh doanh mỗi ngày --- hành động này ông duy trì suốt hơn 70 năm đầu tư.",
            "He reads more than 500 pages of books and business reports every day --- a practice he has maintained throughout over 70 years of investing."),
           ("Triết học đầu tư của ông: ``Hãy mua cổ phiếu khi người khác sợ hãi và bán khi người khác tham lam.''",
            "His investment philosophy: `Buy when others are fearful and sell when others are greedy.'"),
           ("Ông nói: ``Ai ngồi mát mà không gieo hạt sẽ không có gì mà gặt khi mùa thu đến.''",
            "He says: `One who sits in shade without planting will have nothing to harvest when autumn comes.'"),
           ("Buffett cam kết tặng 99 phần trăm tài sản của mình cho từ thiện --- đó là triết học sống, không phải chiến lược PR.",
            "Buffett has pledged to give 99 percent of his wealth to charity --- that is a life philosophy, not a PR strategy.")],
          "Kiến tạo cuộc đời là hành động lâu dài --- mỗi ngày gieo một hạt giống nhỏ vào đúng đất là cách thay đổi bền vững nhất.",
          "Building a life is a long-term endeavour --- planting one small seed daily in the right soil is the most sustainable way to transform."),

    story("Hồ Chí Minh Và Ý Chí Kiến Tạo Đất Nước", "Hồ Chí Minh --- Việt Nam, 1945",
          "Năm",
          [("Năm 1945, Hồ Chí Minh đọc Tuyên Ngôn Độc Lập của Việt Nam --- bắt đầu bằng trích dẫn từ Tuyên Ngôn Độc Lập Mỹ.",
            "In 1945, Ho Chi Minh read Vietnam's Declaration of Independence --- beginning with a quote from the American Declaration of Independence."),
           ("Đó là tuyên bố về tầm nhìn: Việt Nam sẽ xây dựng một đất nước bình đẳng và tự do, như những gì nhân loại mơ ước.",
            "It was a vision statement: Vietnam would build a nation of equality and freedom, as all humanity dreams."),
           ("Ông đã dành 30 năm bôn ba khắp thế giới --- Paris, Moscow, Trung Quốc, Thái Lan --- học hỏi và chuẩn bị.",
            "He had spent 30 years travelling the world --- Paris, Moscow, China, Thailand --- learning and preparing."),
           ("Khi về nước lãnh đạo, ông không chỉ là nhà cách mạng mà là người thầy --- dạy dân đọc, dạy dân vệ sinh, dạy đạo đức.",
            "When he returned to lead the country, he was not just a revolutionary but a teacher --- teaching literacy, hygiene, and ethics."),
           ("Di sản của ông là một nước Việt Nam có độc lập --- và hành trình xây dựng đó vẫn tiếp tục sau ông.",
            "His legacy is an independent Vietnam --- and the building journey he began continues after him.")],
          "Kiến tạo đất nước cũng như kiến tạo cuộc đời --- cần tầm nhìn rõ ràng, sự chuẩn bị kỹ lưỡng và ý chí không khuất phục.",
          "Building a nation is like building a life --- it needs clear vision, thorough preparation, and an indomitable will."),

    story("Marie Curie Và Sự Kiên Trì Trong Khoa Học", "Marie Curie --- Pháp, 1898",
          "Marie",
          [("Marie Curie là người phụ nữ đầu tiên nhận giải Nobel và người đầu tiên trong lịch sử nhận giải Nobel hai lần ở hai lĩnh vực khác nhau.",
            "Marie Curie was the first woman to receive a Nobel Prize and the first person ever to receive two Nobels in two different fields."),
           ("Sinh ra ở Ba Lan khi phụ nữ không được vào đại học, bà đến Paris học lậu và sau đó học chính thức.",
            "Born in Poland where women could not attend university, she went to Paris to study and eventually gained formal admission."),
           ("Bà và Pierre làm việc trong điều kiện cực kỳ thiếu thốn --- phòng thí nghiệm bị dột, mùa đông lạnh giá không có sưởi.",
            "She and Pierre worked in extremely poor conditions --- a leaking laboratory, freezing winters without heat."),
           ("Bà xử lý hàng tấn quặng uranium bằng tay --- không biết rằng phóng xạ đang từ từ giết chết bà.",
            "She processed tons of uranium ore by hand --- not knowing that radiation was slowly killing her."),
           ("Bà nói: ``Trong cuộc sống không có gì đáng sợ, chỉ có những điều cần được hiểu. Giờ là lúc hiểu thêm để sợ ít hơn.''",
            "She said: `Nothing in life is to be feared, only to be understood. Now is the time to understand more, so that we may fear less.'")],
          "Hành trình khoa học và hành trình sống giống nhau: bạn không thấy hết trước hành trình; nhưng mỗi bước sáng tỏ thêm một chút.",
          "The scientific journey and life journey are alike: you cannot see the whole path ahead; but each step illuminates a little more."),

    story("Nguyễn Trường Tộ Và Giấc Mơ Canh Tân Dang Dở", "Nguyễn Trường Tộ --- Việt Nam, thế kỷ 19",
          "Nguyễn",
          [("Nguyễn Trường Tộ là nhà trí thức Công giáo người Việt sống cuối thế kỷ 19, đi châu Âu và thấy sự tiến bộ của phương Tây.",
            "Nguyen Truong To was a Vietnamese Catholic intellectual of the late 19th century who went to Europe and saw Western progress."),
           ("Ông viết hàng chục bản điều trần gửi vua Tự Đức và triều đình, đề nghị canh tân đất nước toàn diện.",
            "He wrote dozens of policy memoranda to Emperor Tu Duc and the court, proposing comprehensive modernisation of the country."),
           ("Ông đề xuất cải cách giáo dục, học khoa học kỹ thuật phương Tây, mở cửa thương mại --- trước Nhật Bản cải cách Minh Trị.",
            "He proposed education reform, learning Western science and technology, opening trade --- before Japan's Meiji reforms."),
           ("Triều đình không nghe; Pháp xâm lược và chiếm Việt Nam --- sau đó người ta mới tiếc những điều ông đã cảnh báo.",
            "The court did not listen; France invaded and occupied Vietnam --- only then did people regret what he had warned."),
           ("Giấc mơ của ông dang dở --- nhưng tầm nhìn của ông vẫn là tấm gương cho những ai muốn kiến tạo tương lai của dân tộc.",
            "His dream remained unfulfilled --- but his vision remains a mirror for all who wish to build their nation's future.")],
          "Kiến tạo tương lai đòi hỏi can đảm nói sự thật cho người không muốn nghe --- dù kết quả không được thấy trong đời mình.",
          "Building the future requires the courage to tell truth to those who do not wish to hear --- even if you never see the result in your lifetime."),
    ])

with open(os.path.join(BASE, "ch10-kien-tao-cuoc-doi.tex"), "w", encoding="utf-8") as f:
    f.write(ch10)
print("ch10 done")

print("\nAll chapters 8-10 generated successfully with correct Vietnamese!")
