#!/usr/bin/env python3
from gen_q9_a import make_chapter, ch01, ch02, ch03, ch04
from gen_q9_b import ch05, ch06, ch07, ch08
from gen_q9_c import ch09, ch10, ch11, ch12

TITLE_FIXES = {
    'Khong Ai Nhac Em Hoc Nua': 'Không Ai Nhắc Em Học Nữa',
    'Thu Hai Dau Tien Khong Co Lop': 'Thứ Hai Đầu Tiên Không Có Lớp',
    'Qua Nhieu Nga Re': 'Quá Nhiều Ngã Rẽ',
    'Danh Hieu Cu Khong Theo Em Mai': 'Danh Hiệu Cũ Không Theo Em Mãi',
    'Khong Ai Cham No Luc Cong Khai': 'Không Ai Chấm Nỗ Lực Công Khai',
    'Phong Van Phong Cung Co Chinh Tri': 'Văn Phòng Cũng Có Chính Trị',
    'Hoi Khong Phai La Kem': 'Hỏi Không Phải Là Kém',
    'Di Tre Mot Lan Cung Day Rat Nhieu': 'Đi Trễ Một Lần Cũng Dạy Rất Nhiều',
    'Ngay Binh Thuong Moi Xay Uy Tin': 'Ngày Bình Thường Mới Xây Uy Tín',
    'Nghi Viec Hay O Lai': 'Nghỉ Việc Hay Ở Lại',
    'Quy Luong Dau Cho Nha': 'Quỹ Lương Đầu Cho Nhà',
    'Quy Du Phong Dau Tien': 'Quỹ Dự Phòng Đầu Tiên',
    'Mua De Bang Ban Bang Be': 'Mua Để Bằng Bạn Bằng Bè',
    'Gia Cua Song Rieng': 'Giá Của Sống Riêng',
    'Gui Tien Ve Nha': 'Gửi Tiền Về Nhà',
    'Khong Ai Co Nghia Vu Hieu Em Ngay': 'Không Ai Có Nghĩa Vụ Hiểu Em Ngay',
    'Khong Co Thu Tu Phan Hoi Em': 'Không Có Thư Phản Hồi Em',
    'Phong Trong Khong San Cho Em': 'Phòng Trống Không Sẵn Cho Em',
    'Dung Luc Cung La Mot Phan Nang Luc': 'Đúng Lúc Cũng Là Một Phần Năng Lực',
    'Dung Luc Xay Minh Hon La Xin Cho': 'Đúng Lúc Xây Mình Hơn Là Xin Chỗ',
    'Nhin Nguoi Khac Duoc Chon': 'Nhìn Người Khác Được Chọn',
    'Bi Gop Y Truoc Mat Nguoi Khac': 'Bị Góp Ý Trước Mặt Người Khác',
    'Thu Tu Choi Dau Tien': 'Thư Từ Chối Đầu Tiên',
    'Duong Di Thu Hai': 'Đường Đi Thứ Hai',
    'Dung Day Sau Khi Bi Thay': 'Đứng Dậy Sau Khi Bị Thay',
    'Tet Dau Tien Xa Nha': 'Tết Đầu Tiên Xa Nhà',
    'Tu Nau Cho Minh': 'Tự Nấu Cho Mình',
    'Can Phong Va Su Co Don': 'Căn Phòng Và Sự Cô Đơn',
    'Nho Duong Hoi Giup': 'Nhớ Đường Hỏi Giúp',
    'Biet On Cha Me Hon': 'Biết Ơn Cha Mẹ Hơn',
    'Ban Chi Tim Den Khi Can': 'Bạn Chỉ Tìm Đến Khi Cần',
    'Tinh Ban Lon Len Cung Can Cong Cham': 'Tình Bạn Lớn Lên Cũng Cần Công Chăm',
    'Thu Nhap Khac, Vong Tron Khac': 'Thu Nhập Khác, Vòng Tròn Khác',
    'Loi Hua Cu Phai Song Trong Hien Tai': 'Lời Hứa Cũ Phải Sống Trong Hiện Tại',
    'Giua Lai Su Ton Trong Sau Khi Tan Ra': 'Giữ Lại Sự Tôn Trọng Sau Khi Tan Ra',
    'Dung Bien Nguoi Ay Thanh Ca The Gioi': 'Đừng Biến Người Ấy Thành Cả Thế Giới',
    'Yeu Sau Mot Lan That Bong': 'Yêu Sau Một Lần Thất Vọng',
    'Cam Xuc Manh Khong Bang Nhan Cach Tot': 'Cảm Xúc Mạnh Không Bằng Nhân Cách Tốt',
    'Chia Tay Cho Dang Hoang': 'Chia Tay Cho Đàng Hoàng',
    'Chua Lanh Truoc Khi Bat Dau Moi': 'Chữa Lành Trước Khi Bắt Đầu Mới',
    'Tu Choi Lich Su': 'Từ Chối Lịch Sự',
    'Dung Giai Thich Qua Nhieu': 'Đừng Giải Thích Quá Nhiều',
    'Giup Gia Dinh Co Gioi Han': 'Giúp Gia Đình Có Giới Hạn',
    'Tu Te Noi Lam Viec Khong Phai Ngo Nghech': 'Tử Tế Nơi Làm Việc Không Phải Ngô Nghêch',
    'Nghi Ngoi Ma Khong Co Loi': 'Nghỉ Ngơi Mà Không Có Lỗi',
    'Ho So Co Dau Vet': 'Hồ Sơ Có Dấu Vết',
    'Bay Thuc Tap Khong Loi Ra': 'Bẫy Thực Tập Không Lối Ra',
    'Ket Noi Khong Phai Xin Xo': 'Kết Nối Không Phải Xin Xỏ',
    'Truot Phong Van Dau': 'Trượt Phỏng Vấn Đầu',
    'Hoc Cong Cu, Khong Chi Hoc Ly Thuyet': 'Học Công Cụ, Không Chỉ Học Lý Thuyết',
    'Nang Nep Hon Cam Hung': 'Nề Nếp Hơn Cảm Hứng',
    'Ngu Dung Gio Cuu Rat Nhieu Thu': 'Ngủ Đúng Giờ Cứu Rất Nhiều Thứ',
    'Muc Tieu Nho Moi Ngay': 'Mục Tiêu Nhỏ Mỗi Ngày',
    'Su Deu Dan Chong Buon Chan': 'Sự Đều Đặn Chống Buồn Chán',
    'Bat Dau Lai Sau Mot Tuan Te': 'Bắt Đầu Lại Sau Một Tuần Tệ',
    'Tra Lai Dieu Minh Da Muon': 'Trả Lại Điều Mình Đã Mượn',
    'Giu Loi Voi Viec Nho': 'Giữ Lời Với Việc Nhỏ',
    'Nhan Ra Gioi Han Cua Minh': 'Nhận Ra Giới Hạn Của Mình',
    'Dung Cho Nguoi Lon Den Cuu Mai': 'Đừng Chờ Người Lớn Đến Cứu Mãi',
    'Song De Mai Sau Nhin Lai Khong Xau Ho': 'Sống Để Mai Sau Nhìn Lại Không Xấu Hổ',
}


def story(title_vn, title_en, setup_vn, setup_en, illusion_vn, illusion_en, reality_vn, reality_en, shift_vn, shift_en, lesson_vn, lesson_en):
    return {
        'title_vn': TITLE_FIXES.get(title_vn, title_vn),
        'title_en': title_en,
        'pairs': [
            (setup_vn, setup_en),
            (illusion_vn, illusion_en),
            (reality_vn, reality_en),
            (shift_vn, shift_en),
        ],
        'lesson_vn': lesson_vn,
        'lesson_en': lesson_en,
    }


extra_ch01 = [
    story('Khong Ai Nhac Em Hoc Nua', 'No One Reminds You to Learn Anymore', 'Ra truong roi, khong con ai giao bai tap hay nhac em phai boi them ky nang.', 'After graduation, no one gives homework or reminds you to build new skills.', 'Nhiều người tưởng việc học sẽ tự dừng khi thời khóa biểu dừng lại.', 'Many people think learning ends when the timetable ends.', 'Nhưng người lớn đi nhanh thường là người tự học khi không ai ép.', 'But adults who move well are usually the ones who keep learning without pressure.', 'Ai chờ người khác nhắc mới học sẽ chậm rất lâu sau khi ra trường.', 'Those who wait for reminders will stay slow for a long time.', 'Ra đời là lúc việc học chuyển từ nghĩa vụ sang trách nhiệm tự thân.', 'Adult life turns learning from obligation into personal responsibility.'),
    story('Thu Hai Dau Tien Khong Co Lop', 'The First Monday with No Class', 'Buổi sáng đầu tuần đầu tiên sau khi rời trường làm nhiều người thấy hụt hẫng rất lạ.', 'The first Monday morning after leaving school feels strangely empty for many people.', 'Họ tưởng không có lịch học sẽ là nhẹ tênh và thoải mái.', 'They think having no class schedule will feel light and free.', 'Nhưng khoảng trống không có cấu trúc rất dễ biến thành loay hoay và trì hoãn.', 'But empty time without structure easily becomes confusion and delay.', 'Từ đó người trẻ mới hiểu tự lập bắt đầu từ việc tự chia ngày cho mình.', 'Then young people understand that independence begins by shaping their own day.', 'Sự trống không không tự sinh ra tự do. Nó đòi em biết tổ chức mình.', 'Emptiness does not automatically create freedom. It demands self-organization.'),
    story('Qua Nhieu Nga Re', 'Too Many Crossroads', 'Rời trường xong, có người đứng trước quá nhiều lựa chọn nên không biết bước theo hướng nào.', 'After school, some people face too many options and do not know which way to take.', 'Họ tưởng nhiều lựa chọn đồng nghĩa nhiều thuận lợi.', 'They think more choices always mean more advantage.', 'Nhưng nếu không hiểu mình, nhiều ngã rẽ chỉ làm đầu óc ồn hơn.', 'But without self-understanding, many options only make the mind louder.', 'Người trưởng thành không chỉ chọn nhiều. Họ học cách bỏ bớt để đi chắc hơn.', 'Mature people do not only choose more. They learn to cut options and walk more steadily.', 'Không có đề cương sẵn nghĩa là em phải tự chọn câu hỏi quan trọng cho đời mình.', 'No fixed outline means you must choose the important questions for your own life.'),
    story('Danh Hieu Cu Khong Theo Em Mai', 'Old Titles Do Not Follow You Forever', 'Có người từng sống rất lâu trong lời khen học sinh giỏi nên ra đời mới thấy hụt khi không ai còn gọi mình như vậy.', 'Some lived a long time inside praise as a top student, then felt empty when no one used that title anymore.', 'Họ tưởng tên gọi cũ sẽ tiếp tục bảo vệ giá trị hiện tại.', 'They think old labels will keep protecting present value.', 'Ngoài đời, hôm nay em làm được gì quan trọng hơn em từng được gọi là gì.', 'In real life, what you can do today matters more than what you were once called.', 'Rời danh hiệu cũ đau nhưng nó giúp em bước vào giá trị thật hơn.', 'Leaving old titles hurts, but it leads into a more real value.', 'Muốn lớn tiếp, người trẻ phải đủ can đảm sống mà không dựa mãi vào hào quang cũ.', 'To keep growing, young people need the courage to stop leaning on old glory.'),
    story('Khong Ai Cham No Luc Cong Khai', 'No One Publicly Grades Your Effort', 'Đi học, cố gắng thường được điểm số phản ánh phần nào.', 'In school, effort is often reflected in grades at least partly.', 'Nhiều người tưởng ra đời rồi cố là sẽ có ai đó công nhận rõ ràng như thế.', 'Many people think adult life will recognize effort just as clearly.', 'Nhưng đời ít chấm công khai. Có khi em cố rất lâu mà không nghe một lời khen nào.', 'But life rarely grades openly. Sometimes you work hard for a long time without hearing praise.', 'Lúc đó điều giữ em đi tiếp không còn là điểm, mà là nhận thức mình đang xây gì.', 'At that point, what keeps you moving is no longer a grade, but knowing what you are building.', 'Trưởng thành là làm nhiều việc đúng mà không cần bảng điểm xác nhận mỗi lần.', 'Maturity means doing many right things without needing a score each time.'),
]

extra_ch02 = [
    story('Phong Van Phong Cung Co Chinh Tri', 'Even Offices Have Politics', 'Đi làm một thời gian, người trẻ mới thấy năng lực không phải thứ duy nhất vận hành nơi làm việc.', 'After some time at work, young people see that skill is not the only force in a workplace.', 'Họ tưởng cứ làm tốt là đủ để mọi việc chạy thẳng và sạch.', 'They think doing good work is enough for everything to stay straight and fair.', 'Nhưng còn có quan hệ, cách nói, thời điểm, và cách người ta nhìn nhau.', 'But there are also relationships, timing, communication, and perception.', 'Hiểu điều đó không phải để gian hơn, mà để bớt ngây thơ hơn.', 'Understanding that is not for becoming cynical, but for becoming less naive.', 'Đi làm không chỉ học việc. Nó còn là học cách nhìn một hệ thống thật.', 'Working life teaches not only tasks, but also how a real system behaves.'),
    story('Hoi Khong Phai La Kem', 'Asking Questions Is Not Weakness', 'Nhiều nhân viên mới sợ hỏi vì ngại bị nghĩ là chậm hay dốt.', 'Many new workers fear asking questions because they do not want to look slow or foolish.', 'Họ tưởng im lặng sẽ giúp mình giữ hình ảnh thông minh.', 'They think silence protects an image of intelligence.', 'Nhưng im lặng sai chỗ thường làm lỗi lớn hơn và mất thời gian hơn.', 'But silence in the wrong place usually creates larger mistakes and wastes more time.', 'Người học nhanh không phải người giấu việc không hiểu. Họ là người hỏi đúng lúc rồi sửa nhanh.', 'Fast learners are not those who hide confusion. They ask at the right time and correct quickly.', 'Hỏi sớm thường cứu được cả việc lẫn lòng tự trọng về sau.', 'Asking early often saves both the work and your dignity later.'),
    story('Di Tre Mot Lan Cung Day Rat Nhieu', 'One Late Arrival Can Teach a Lot', 'Có người chỉ đến trễ một lần trong buổi họp đầu nhưng nhớ mãi cảm giác ánh mắt mọi người nhìn mình.', 'Someone arrives late once to an early meeting and never forgets the room looking at them.', 'Họ từng tưởng trễ vài phút chỉ là chuyện nhỏ.', 'They once thought a few late minutes were a small issue.', 'Ngoài đời, đúng giờ là tín hiệu của sự tôn trọng trước khi ai đó kịp thấy năng lực của em.', 'In adult life, punctuality signals respect before anyone can judge your ability.', 'Một lỗi nhỏ về giờ giấc đôi khi làm người khác đọc ra cả một thái độ.', 'A small time error can make others read a larger attitude.', 'Đi làm dạy rằng nhiều điều bé lại mang ý nghĩa lớn hơn ta tưởng.', 'Work teaches that small things often carry larger meaning than we expect.'),
    story('Ngay Binh Thuong Moi Xay Uy Tin', 'Ordinary Days Build Trust', 'Không phải ngày bùng nổ nào cũng quyết định chỗ đứng của em trong công việc đầu tiên.', 'Not every dramatic day decides your place in a first job.', 'Nhiều người trẻ tưởng phải làm một việc thật lớn mới được tin.', 'Many young people think they must do something huge to earn trust.', 'Nhưng niềm tin thường được ghép từ những ngày rất bình thường em vẫn làm việc gọn, đúng, và đều.', 'But trust is usually built from ordinary days when you work neatly, correctly, and steadily.', 'Người đi được lâu là người giữ chất lượng cả khi chẳng ai chú ý.', 'Those who last are those who keep quality even when nobody is watching.', 'Việc đầu tiên không chỉ kiểm tra tài. Nó kiểm tra độ đều của em.', 'The first job does not only test talent. It tests consistency.'),
    story('Nghi Viec Hay O Lai', 'Should You Quit or Stay?', 'Có người đi làm vài tháng đã thấy nản và nghĩ đến chuyện bỏ ngay.', 'Some people feel discouraged after a few months of work and immediately think about quitting.', 'Họ tưởng cứ mệt là chắc chắn mình chọn sai.', 'They think feeling tired automatically means the choice was wrong.', 'Nhưng có lúc mệt vì đang lớn, có lúc mệt vì môi trường thực sự không đáng ở.', 'But sometimes you are tired because you are growing, and sometimes because the environment is truly unhealthy.', 'Khó nhất là học cách phân biệt hai kiểu mệt đó.', 'The hardest part is learning to tell those two kinds of tiredness apart.', 'Người trưởng thành không ở lì cũng không bỏ chạy quá sớm. Họ nhìn cho rõ rồi mới quyết.', 'Mature people neither stay blindly nor run too early. They look carefully before deciding.'),
]

extra_ch03 = [
    story('Quy Luong Dau Cho Nha', 'Giving Part of the First Salary to Home', 'Có người cầm lương đầu rồi nghĩ ngay đến việc phụ bố mẹ một khoản nhỏ.', 'Some people receive their first salary and immediately think about helping their parents with a small part.', 'Trước đó họ tưởng tiền đầu chỉ là phần thưởng cho riêng mình.', 'Before that, they thought the first salary was only a reward for themselves.', 'Nhưng khi bắt đầu nghĩ đến gia đình, họ cảm thấy một tầng trưởng thành khác mở ra.', 'But when they begin to think about family, another layer of maturity opens.', 'Đồng tiền đầu tiên không chỉ thay đổi ví tiền. Nó đổi cách mình nhìn vai trò của mình trong nhà.', 'First money changes not only the wallet. It changes how you see your role at home.', 'Lúc nghĩ đến việc đỡ người khác bằng đồng tiền mình làm ra, em bắt đầu lớn thật hơn.', 'When your earned money starts serving others too, you grow more truly.'),
    story('Quy Du Phong Dau Tien', 'The First Emergency Fund', 'Sau vài cú hụt tiền, có người bắt đầu để riêng một khoản rất nhỏ và gọi đó là quỹ dự phòng.', 'After a few money shortages, someone starts keeping a small amount aside as an emergency fund.', 'Họ từng tưởng tiết kiệm là chuyện của người lớn tuổi hoặc người nhiều tiền.', 'They once thought saving was for older people or for those with more money.', 'Nhưng chính người chưa có nhiều lại càng cần một khoảng đệm nhỏ để bớt hoảng khi có việc.', 'But those with less often need a small buffer even more to avoid panic when problems come.', 'Một khoản nhỏ để yên có thể cứu em khỏi rất nhiều quyết định vội vàng.', 'A small amount left untouched can save you from many rushed decisions.', 'Tiền dự phòng không làm em già đi. Nó làm em bớt ngây thơ.', 'An emergency fund does not make you old. It makes you less naive.'),
    story('Mua De Bang Ban Bang Be', 'Buying Things to Keep Up with Friends', 'Thấy bạn bè có đồ mới, có quán mới, có cuộc vui mới, nhiều người trẻ rất khó đứng yên.', 'Seeing friends with new things, new places, and new outings makes many young people restless.', 'Họ tưởng theo kịp hình ảnh của nhóm là một phần của tự do tài chính.', 'They think keeping up with the group image is part of financial freedom.', 'Nhưng tiêu để bằng người khác thường chỉ mua được vài giờ dễ chịu rồi đổi lấy nhiều ngày áp lực.', 'But spending to match others often buys a few easy hours and many stressed days later.', 'Người biết giữ tiền thường chịu được cảm giác không bằng ai đó trong một lúc.', 'Those who keep money well can tolerate not matching someone else for a while.', 'Trưởng thành tài chính bắt đầu từ lúc em ngừng tiêu để chứng minh mình không thua.', 'Financial maturity begins when you stop spending to prove you are not behind.'),
    story('Gia Cua Song Rieng', 'The Price of Living Independently', 'Có người chỉ khi tự trả tiền nhà, tiền ăn, và tiền hỏng vặt mới hiểu vì sao người lớn luôn cân đo.', 'Only when paying rent, food, and small repair costs do some people understand why adults always calculate.', 'Trước đó họ tưởng sống riêng chủ yếu là cảm giác thoải mái và ít bị quản.', 'Before that, they thought living independently was mostly comfort and less control.', 'Nhưng mỗi sự tiện nghi đều có giá thật, và giá đó lặp lại từng tháng.', 'But every convenience has a real cost, and that cost returns each month.', 'Tự do nhìn rất đẹp cho đến khi em phải tự trả toàn bộ hóa đơn của nó.', 'Freedom looks beautiful until you pay its full bill yourself.', 'Biết giá của cuộc sống là bước đầu để biết quý đồng tiền mình làm ra.', 'Knowing the cost of life is the first step to valuing your earned money.'),
    story('Gui Tien Ve Nha', 'Sending Money Home', 'Một số người trẻ chỉ gửi về một khoản rất nhỏ, nhưng cảm giác bên trong lại lớn hơn nhiều.', 'Some young people send home only a small amount, yet the feeling inside is much larger.', 'Họ từng tưởng trưởng thành là cầm tiền cho mình và mua điều mình thích.', 'They once thought adulthood meant holding money for themselves and buying what they wanted.', 'Đến lúc chủ động san sẻ, họ mới thấy đồng tiền còn mang cả ý nghĩa biết ơn.', 'When they start sharing, they see that money also carries gratitude.', 'Sự trưởng thành đẹp không chỉ nằm ở kiếm được bao nhiêu, mà còn ở mình nhớ đến ai khi kiếm được.', 'Beautiful maturity is not only about how much you earn, but whom you remember when you earn.', 'Kiếm tiền cho mình là bước đầu. Biết chia đồng tiền đó đúng chỗ là bước sâu hơn.', 'Earning for yourself is the first step. Knowing how to share it wisely is a deeper one.'),
]

extra_ch04 = [
    story('Khong Ai Co Nghia Vu Hieu Em Ngay', 'No One Is Obliged to Understand You Immediately', 'Nhiều người trẻ thất vọng vì nghĩ mình đã cố nhưng chẳng ai hiểu cho hoàn cảnh của mình.', 'Many young people feel hurt because they think they tried hard, yet nobody understood their situation.', 'Họ tưởng đời sẽ tự động xét đến câu chuyện phía sau nỗ lực của họ.', 'They think life will automatically consider the story behind their effort.', 'Nhưng phần lớn nơi làm việc và cơ hội chỉ nhìn thấy điều em thể hiện ra được.', 'But most workplaces and opportunities only see what you can actually show.', 'Điều đó lạnh, nhưng biết sớm sẽ giúp em bớt chờ cảm thông và học cách trình bày rõ hơn.', 'It feels cold, but knowing it early helps you stop waiting for sympathy and start communicating better.', 'Đời không luôn hỏi tại sao em khó. Nó thường chỉ hỏi em làm được gì trong cái khó đó.', 'Life does not always ask why you struggled. It often asks what you can do inside that struggle.'),
    story('Khong Co Thu Tu Phan Hoi Em', 'No One Owes You a Detailed Reply', 'Có những hồ sơ em gửi đi và mãi mãi chỉ nhận về sự im lặng.', 'Some applications are sent out and answered only with silence forever.', 'Nhiều người tưởng nếu mình chưa được chọn thì ít nhất người ta phải giải thích cặn kẽ.', 'Many think that if they are not chosen, someone at least owes them a full explanation.', 'Nhưng ngoài đời, rất nhiều cánh cửa chỉ đóng lại mà không để lại lời nhắn tử tế nào.', 'But in real life, many doors simply close without leaving a kind message.', 'Chấp nhận sự thô của đời không phải để cay đắng, mà để bớt lãng phí thời gian vào điều không đổi được.', 'Accepting life’s roughness is not for bitterness, but to stop wasting time on what will not change.', 'Không được phản hồi là khó chịu. Nhưng ở lì trong bực đó còn làm em chậm hơn.', 'No reply is unpleasant. Staying trapped in that anger slows you even more.'),
    story('Phong Trong Khong San Cho Em', 'No Room Is Prepared in Advance for You', 'Có người bước vào đời với hy vọng ngoài kia đã có sẵn một chỗ hợp với mình, chỉ chờ mình tới.', 'Some enter adult life hoping that somewhere there is already a perfect place waiting for them.', 'Họ tưởng chỉ cần mình đủ giỏi là cái chỗ đó sẽ lộ ra rất nhanh.', 'They think ability alone will quickly reveal that place.', 'Nhưng phần lớn chỗ đứng phải được dựng dần từ việc làm nhỏ, quan hệ nhỏ, và độ tin cậy nhỏ.', 'But most positions are built slowly through small tasks, small relationships, and small trust.', 'Chỗ đứng hiếm khi được trao trọn. Nó thường được ráp lên từng phần.', 'A place is rarely handed over whole. It is usually assembled piece by piece.', 'Đừng chỉ đi tìm chỗ đứng hợp sẵn. Hãy học cách tự dựng nó.', 'Do not only search for a ready-made place. Learn how to build one.'),
    story('Dung Luc Cung La Mot Phan Nang Luc', 'Timing Is Also Part of Ability', 'Có người đủ giỏi nhưng bước vào sai thời điểm nên vẫn bị lỡ nhiều cơ hội.', 'Some people are good enough but arrive at the wrong time and still miss many chances.', 'Họ tưởng chỉ cần xứng đáng là mọi thứ phải diễn ra ngay.', 'They think deserving something means it should happen now.', 'Nhưng đời không chỉ chạy bằng năng lực. Nó còn chạy bằng thời điểm và độ chín.', 'But life does not run on skill alone. It also runs on timing and readiness.', 'Hiểu điều này giúp em bớt cay khi chậm hơn một chút.', 'Understanding this helps you feel less bitter when you are delayed.', 'Chậm hơn đôi khi không phải thua. Nó chỉ là chưa đúng lúc.', 'Being later is not always losing. Sometimes it is simply not the right time yet.'),
    story('Dung Luc Xay Minh Hon La Xin Cho', 'Build Yourself Before Asking for the Seat', 'Có người quá mải nhìn chiếc ghế mình muốn nên quên nhìn phần bản thân còn thiếu.', 'Some people stare so hard at the seat they want that they forget to examine what they still lack.', 'Họ tưởng có một chỗ đẹp rồi thì mình sẽ tự trưởng thành theo chỗ đó.', 'They think receiving a good seat will automatically make them grow into it.', 'Nhiều khi phải lớn lên trước một đoạn thì chỗ đứng mới không đè ngược lại em.', 'Often you need to grow first so the role does not crush you later.', 'Xây mình âm thầm có thể chậm, nhưng nó làm cái ghế sau này vừa hơn với vai mình.', 'Building yourself quietly may be slow, but it makes the later seat fit your shoulders better.', 'Đời bền với người biết lớn vào phần còn thiếu trước khi đòi phần quá cao.', 'Life is kinder to those who grow into their gaps before demanding too much height.'),
]

extra_ch05 = [
    story('Nhin Nguoi Khac Duoc Chon', 'Watching Others Get Chosen', 'Có người liên tục nhìn bạn bè hoặc đồng nghiệp được chọn còn mình thì bị bỏ qua.', 'Some people keep watching friends or coworkers get chosen while they are left behind.', 'Họ tưởng bị bỏ lại nhiều lần nghĩa là mình kém hẳn.', 'They think repeated exclusion means they are truly inferior.', 'Nhưng có khi đó chỉ là giai đoạn người khác đang hợp hơn với một loại cơ hội nhất định.', 'But sometimes it only means others fit a certain opportunity better for now.', 'Nếu không biến nó thành danh tính, em vẫn còn rất nhiều đường để đi tiếp.', 'If you do not turn it into identity, many roads still remain open.', 'Bị chọn muộn không có nghĩa là không có lượt. Miễn là em vẫn giữ mình sắc.', 'Being chosen later does not mean you have no turn. Keep yourself sharp.'),
    story('Bi Gop Y Truoc Mat Nguoi Khac', 'Being Corrected in Front of Others', 'Có lần em bị chê ngay trong phòng họp và cảm thấy mặt mình nóng ran.', 'Once you are criticized in a meeting and feel your face burning.', 'Nhiều người tưởng khoảnh khắc đó đủ để làm mình mất giá luôn.', 'Many think that moment permanently reduces their value.', 'Thực ra điều người ta nhớ lâu hơn thường là cách em đón nhận và sửa sau đó.', 'In reality, what people often remember longer is how you receive and fix it afterward.', 'Một phản ứng bình tĩnh đôi khi cứu em nhiều hơn cả một phần giải thích dài.', 'A calm response sometimes saves you more than a long explanation.', 'Bị chê trước mặt người khác đau, nhưng cách em đứng lại sau đó mới nói rõ em là ai.', 'Public criticism hurts, but how you stand afterward says more about you.'),
    story('Thu Tu Choi Dau Tien', 'The First Rejection Letter', 'Một email từ chối đầu tiên có thể làm người trẻ ngồi lặng rất lâu.', 'The first rejection email can leave a young person silent for a long time.', 'Họ tưởng một câu không đủ nói rằng con đường đó không dành cho mình.', 'They think one no is enough to prove the road is not theirs.', 'Nhưng rất nhiều cánh cửa chỉ đang nói rằng em chưa đúng lúc, chưa đúng cách, hoặc chưa đúng chỗ.', 'But many doors are only saying you are not right yet, not right there, or not right now.', 'Bài học nằm ở việc đọc cú từ chối như dữ liệu chứ không như phán quyết toàn đời.', 'The lesson is to read rejection as data, not as a lifelong verdict.', 'Một lá thư từ chối không viết xong giá trị của em. Nó chỉ đóng một cánh cửa hôm đó.', 'One rejection letter does not write your full worth. It closes only one door that day.'),
    story('Duong Di Thu Hai', 'The Second Choice Can Still Be a Road', 'Có người không vào được nơi mình mơ nên miễn cưỡng bước vào một lựa chọn thứ hai.', 'Some people fail to enter their dream place and reluctantly step into a second choice.', 'Họ tưởng đường tốt nhất đã mất thì phần còn lại chỉ là chấp nhận thua.', 'They think losing the best road means accepting defeat.', 'Nhưng nhiều đời người đi rất xa từ con đường không phải lựa chọn đầu tiên.', 'But many lives travel far on roads that were not the first choice.', 'Quan trọng không chỉ là cửa em vào đầu tiên, mà là em đi tiếp trong cửa đó thế nào.', 'What matters is not only the first door you enter, but how you walk inside it.', 'Lựa chọn thứ hai không tự động là đời hạng hai. Nó còn tùy em làm gì với nó.', 'A second choice is not automatically a second-rate life. It depends on what you build there.'),
    story('Dung Day Sau Khi Bi Thay', 'Standing Up After Being Replaced', 'Bị thay ở một vị trí làm nhiều người trẻ thấy như mình bị phủ nhận hoàn toàn.', 'Being replaced in a role makes many young people feel totally rejected.', 'Họ tưởng mất chỗ đó đồng nghĩa mình không còn giá trị.', 'They think losing that place means they no longer matter.', 'Nhưng có lúc bị thay chỉ là lời nhắc rằng năng lực cần được mài lại, hoặc môi trường đó đã không còn hợp.', 'Sometimes replacement only reminds you to sharpen your ability again, or it shows the place no longer fits.', 'Đứng dậy sau cú đó thường cho em một kiểu bản lĩnh sâu hơn cả lúc được giữ lại.', 'Standing up after that blow often gives you a deeper strength than being kept would have.', 'Bị thay đau thật. Nhưng nếu học được, em sẽ không bị cũ đi cùng cú đau đó.', 'Being replaced truly hurts. But if you learn from it, you will not grow old inside that pain.'),
]

extra_ch06 = [
    story('Tet Dau Tien Xa Nha', 'The First New Year Away from Home', 'Có những ngày lễ đầu tiên xa nhà khiến căn phòng trọ bỗng rộng và lạnh hơn hẳn.', 'The first holiday away from home can make a rented room suddenly feel wider and colder.', 'Nhiều người trẻ tưởng mình mạnh cho đến khi những ngày sum vầy đến mà mình không có mặt.', 'Many think they are strong until reunion days come and they are not there.', 'Khi đó nhớ nhà không còn là câu nói mơ hồ. Nó là cảm giác rất rõ trong ngực.', 'Then homesickness is no longer a vague phrase. It becomes a clear feeling in the chest.', 'Những ngày như vậy dạy em biết quý mái nhà cũ theo cách trưởng thành hơn.', 'Days like that teach you to value home in a more adult way.', 'Xa nhà không chỉ dạy tự lập. Nó còn dạy biết ơn.', 'Living away teaches not only independence, but also gratitude.'),
    story('Tu Nau Cho Minh', 'Cooking for Yourself', 'Lần đầu tự nấu một bữa tử tế cho mình, nhiều người mới hiểu sự chăm sóc không tự từ trên trời rơi xuống.', 'The first time someone cooks a proper meal for themselves, they understand care does not fall from the sky.', 'Trước đó họ tưởng bữa cơm ở nhà là điều tự nhiên sẵn có.', 'Before that, they thought family meals were simply there by nature.', 'Đến khi chính tay lo từng món nhỏ, họ mới thấy đằng sau sự bình thường là rất nhiều công sức.', 'When they must handle each small step, they see how much labor sits behind normal comfort.', 'Một căn bếp nhỏ đôi khi dạy em về tình thương mạnh hơn nhiều bài giảng.', 'A small kitchen can teach you about love more deeply than many lectures.', 'Tự lo bữa ăn làm người trẻ hiểu chăm sóc là hành động cụ thể.', 'Preparing your own meal teaches that care is a concrete action.'),
    story('Can Phong Va Su Co Don', 'A Room and Its Loneliness', 'Có những đêm phòng trọ rất yên nhưng lòng người lại rất ồn.', 'Some nights the rented room is very quiet while the mind is very loud.', 'Nhiều người tưởng sống riêng chỉ cần lo vật chất là đủ.', 'Many think living alone is only about handling material needs.', 'Nhưng cô đơn cũng là một hóa đơn tinh thần mà người sống xa nhà phải học cách trả.', 'But loneliness is also a mental bill that people away from home must learn to pay.', 'Biết tự làm đầy đời mình bằng nề nếp tốt và kết nối lành mạnh là một phần của trưởng thành.', 'Knowing how to fill your life with healthy routines and healthy connections is part of maturity.', 'Sống xa nhà không chỉ thử ví tiền. Nó thử cả nội lực bên trong.', 'Living away tests not only your wallet, but also your inner strength.'),
    story('Nho Duong Hoi Giup', 'Knowing How to Ask for Help', 'Có người lên thành phố mang theo sĩ diện nên có khó cũng không dám hỏi ai.', 'Some move to the city carrying so much pride that they do not ask for help even in real difficulty.', 'Họ tưởng tự lập nghĩa là phải tự làm hết mọi thứ một mình.', 'They think independence means doing everything alone.', 'Nhưng người trưởng thành khỏe mạnh biết lúc nào cần tự lo và lúc nào cần mở lời đúng người.', 'But healthy adults know when to handle things alone and when to ask the right person for help.', 'Xin giúp đỡ không làm em nhỏ đi. Nó chỉ giúp em bớt ngu ngơ trước giới hạn của mình.', 'Asking for help does not make you smaller. It makes you less foolish about your limits.', 'Tự lập không phải cô lập. Đó là biết dựa đúng chỗ đúng lúc.', 'Self-reliance is not isolation. It is knowing where to lean at the right moment.'),
    story('Biet On Cha Me Hon', 'Understanding Parents More Deeply', 'Sau vài năm sống xa, có người bất chợt thấy mình dịu hơn khi nghĩ về bố mẹ.', 'After some years away, some people suddenly feel softer when thinking about their parents.', 'Trước đó họ tưởng nhiều điều cha mẹ làm chỉ là nghiêm và khó tính.', 'Before that, they thought many parental choices were only strict or difficult.', 'Nhưng khi tự gánh đời sống, họ mới hiểu nhiều nỗi lo của người lớn không dễ gọi tên.', 'But once they carry life themselves, they understand that many adult worries are hard to describe.', 'Khoảng cách đôi khi làm tình thân rõ hơn chứ không hề mờ đi.', 'Distance sometimes clarifies family love instead of fading it.', 'Lớn lên đẹp là lúc em bớt trách quá khứ và hiểu hơn phần mệt của cha mẹ.', 'A beautiful kind of growing up is blaming the past less and understanding your parents more.'),
]

extra_ch07 = [
    story('Ban Chi Tim Den Khi Can', 'A Friend Who Appears Only When Needing Something', 'Có những tình bạn tưởng thân cho đến khi em nhận ra người kia chỉ tìm tới mỗi lúc cần nhờ vả.', 'Some friendships feel close until you realize the other person appears only when they need something.', 'Em từng tưởng cứ quen lâu là tình nghĩa tự sâu.', 'You once thought time alone automatically deepened the bond.', 'Nhưng thời gian không tự làm nên sự tử tế. Nó chỉ làm rõ người ta thật sự coi em là gì.', 'But time does not automatically create goodness. It only reveals what you truly mean to someone.', 'Nhìn ra điều đó buồn, nhưng nó giúp em bớt đặt lòng tốt sai chỗ.', 'Seeing that is sad, but it helps you place your kindness better.', 'Không phải ai biết số em cũng là bạn của em.', 'Not everyone who has your number is your friend.'),
    story('Tinh Ban Lon Len Cung Can Cong Cham', 'Adult Friendship Also Needs Care', 'Nhiều người buồn vì nghĩ bạn cũ không chủ động nghĩa là tình cảm đã hết.', 'Many feel hurt and think that old friends have stopped caring because they no longer initiate contact.', 'Họ tưởng tình bạn thật sẽ tự sống mãi không cần vun.', 'They think true friendship should survive forever without effort.', 'Nhưng bạn bè trưởng thành cũng cần sự chủ động, lời hỏi han, và vài lần đi về phía nhau.', 'But adult friendship also needs initiative, small check-ins, and both people walking toward each other sometimes.', 'Giữ một tình bạn tốt đôi khi cần cố ý, không chỉ dựa vào thói quen cũ.', 'Keeping a good friendship sometimes requires intention, not only old habit.', 'Tình bạn bền không chỉ ở ký ức đẹp. Nó ở sự chăm lại khi đời đã bận.', 'Stable friendship lives not only in memory, but in renewed care after life becomes busy.'),
    story('Thu Nhap Khac, Vong Tron Khac', 'Different Incomes Create Different Circles', 'Khi thu nhập mỗi người khác nhau rõ hơn, nhiều buổi hẹn bắt đầu trở nên khó xử.', 'When incomes become more different, many meetups begin to feel awkward.', 'Nhiều người tưởng nếu thân thật thì tiền bạc sẽ không bao giờ chen vào.', 'Many think real friendship should never be touched by money differences.', 'Nhưng điều kiện sống ảnh hưởng đến nơi người ta đi, cách người ta tiêu, và cả cảm giác thoải mái khi gặp nhau.', 'But living conditions affect where people go, how they spend, and even how relaxed they feel together.', 'Hiểu điều đó giúp em bớt tự ái và bớt ép người khác phải giữ nhịp như cũ.', 'Understanding that helps you feel less offended and stop forcing old rhythms.', 'Bạn bè lớn lên sẽ có lúc đi qua những khoảng chênh rất thật.', 'Friends growing older must sometimes cross very real gaps.'),
    story('Loi Hua Cu Phai Song Trong Hien Tai', 'Old Promises Must Still Survive the Present', 'Ngày trước ai cũng từng hứa sẽ không bỏ nhau, nhưng rồi cuộc sống kéo từng người vào một hướng khác.', 'In the past everyone promised never to leave, but life later pulled each person in a different direction.', 'Em tưởng lời hứa cũ đủ mạnh để giữ mọi thứ nguyên như trước.', 'You think old promises are strong enough to keep things unchanged.', 'Nhưng lời hứa chỉ sống được khi hiện tại còn có hành động nuôi nó.', 'But a promise lives only when present actions still feed it.', 'Không phải lời hứa nào cũng bị phản bội. Có khi chỉ là nó không đủ sức đi qua một đời sống quá khác.', 'Not every promise is betrayed. Sometimes it simply cannot survive a very different life.', 'Người trưởng thành biết trân trọng lời hứa đẹp mà vẫn nhìn thẳng vào thực tại.', 'A mature person respects beautiful promises while still facing reality.'),
    story('Giua Lai Su Ton Trong Sau Khi Tan Ra', 'Keeping Respect After Drifting Apart', 'Có những tình bạn không còn gần nữa nhưng vẫn không cần biến thành cay cú hay mỉa mai.', 'Some friendships are no longer close, yet they do not need to turn bitter or mocking.', 'Nhiều người tưởng đã không đi cùng được thì phải kết thúc bằng tổn thương.', 'Many people think that if a friendship cannot continue closely, it must end in hurt.', 'Thật ra có những mối quan hệ đẹp nhất ở chỗ nó biết rời xa một cách tử tế.', 'In truth, some relationships are most beautiful in the way they know how to part with decency.', 'Giữ sự tôn trọng sau khi không còn thân là một dấu hiệu rất trưởng thành.', 'Keeping respect after distance is a very mature sign.', 'Không phải tình bạn nào cũng cần ở lại. Nhưng tình người thì vẫn có thể được giữ lại.', 'Not every friendship must remain close. Human respect can still remain.'),
]

extra_ch08 = [
    story('Dung Bien Nguoi Ay Thanh Ca The Gioi', 'Do Not Turn One Person into Your Whole World', 'Có người yêu xong thì cắt dần bạn bè, sở thích, và cả mục tiêu riêng của mình.', 'Some people fall in love and slowly cut off friends, hobbies, and personal goals.', 'Họ tưởng tập trung hết vào một người là dấu hiệu yêu sâu.', 'They think centering everything on one person proves deep love.', 'Nhưng khi một mối quan hệ gánh cả vai trò của thế giới, nó trở nên quá nặng cho cả hai.', 'But when one relationship carries the role of an entire world, it becomes too heavy for both people.', 'Yêu đúng không xóa các phần khác của đời em. Nó chỉ đứng cạnh chúng.', 'Loving well does not erase the other parts of your life. It stands beside them.', 'Một tình yêu khỏe không bắt em thu nhỏ đời mình lại.', 'Healthy love does not require shrinking your whole life.'),
    story('Yeu Sau Mot Lan That Bong', 'Loving Again After Disappointment', 'Sau một mối tình đau, nhiều người trẻ vừa muốn yêu vừa sợ lặp lại vết cũ.', 'After a painful relationship, many young people both want love and fear repeating the old wound.', 'Họ tưởng bị đau một lần nghĩa là mình nên đóng cửa mãi.', 'They think one hurt means the heart should stay closed forever.', 'Nhưng trưởng thành trong tình yêu không phải là khóa tim lại, mà là mở mắt hơn khi mở lòng.', 'But maturity in love is not closing the heart forever. It is opening your eyes more when you open your heart.', 'Một thất bại không nhất thiết biến em thành người không thể yêu.', 'One failure does not turn you into someone unable to love.', 'Yêu lại được, nếu em mang theo bài học thay vì mang theo mù quáng cũ.', 'You can love again if you carry lessons instead of old blindness.'),
    story('Cam Xuc Manh Khong Bang Nhan Cach Tot', 'Strong Chemistry Is Not Better Than Good Character', 'Có người làm em rung động rất nhanh nhưng sống lại thiếu tử tế và thiếu ổn định.', 'Some people make your heart shake quickly, but they live without kindness or stability.', 'Tuổi trẻ hay tưởng cảm xúc mạnh là dấu hiệu chắc chắn của đúng người.', 'Youth often thinks strong emotion is proof of the right person.', 'Nhưng cảm xúc mạnh có thể đến rất nhanh còn nhân cách tốt thường lộ ra chậm hơn nhiều.', 'But strong feeling can arrive quickly while good character reveals itself much more slowly.', 'Nếu chỉ theo rung động, em rất dễ bước vào những điều đẹp ở đầu nhưng mệt ở sau.', 'If you follow chemistry alone, you may enter something sweet at first and exhausting later.', 'Đừng chỉ hỏi người đó làm tim em thế nào. Hãy hỏi họ sống ra sao.', 'Do not only ask what that person does to your heart. Ask how they live.'),
    story('Chia Tay Cho Dang Hoang', 'Ending with Dignity', 'Có những mối quan hệ không cứu được nữa nhưng người trong cuộc vẫn kéo dài vì sợ đau.', 'Some relationships can no longer be saved, yet the people inside keep dragging them because they fear pain.', 'Họ tưởng kéo dài thêm sẽ giúp bớt đau hơn lúc kết thúc.', 'They think prolonging it will make the ending softer.', 'Nhưng nhiều khi sự dây dưa chỉ làm vết thương rộng hơn và lòng tự trọng mỏng đi.', 'But often the dragging only widens the wound and thins self-respect.', 'Một cuộc chia tay đàng hoàng đau thật, nhưng nó sạch hơn rất nhiều so với việc làm tổn thương nhau thêm.', 'A dignified breakup truly hurts, but it is far cleaner than hurting each other longer.', 'Không phải mối tình nào cũng nên cứu. Có cái nên được kết thúc tử tế.', 'Not every relationship should be saved. Some should be ended well.'),
    story('Chua Lanh Truoc Khi Bat Dau Moi', 'Heal Before Starting Again', 'Có người vừa vỡ một mối quan hệ đã vội bước sang mối khác để lấp khoảng trống.', 'Some people rush into a new relationship right after heartbreak just to fill the emptiness.', 'Họ tưởng có người mới sẽ tự làm vết cũ khép lại.', 'They think a new person will automatically close the old wound.', 'Nhưng những gì chưa được nhìn kỹ thường sẽ bước theo em sang tình yêu kế tiếp.', 'But what has not been faced carefully will usually follow you into the next love.', 'Nghỉ lại một đoạn không phải cô độc. Đó là lúc dọn lòng cho sạch hơn.', 'Pausing for a while is not loneliness. It is a time to clean the heart.', 'Yêu mới không chữa được hết cái cũ nếu em còn chưa chịu chữa mình.', 'New love cannot heal the old if you still refuse to heal yourself.'),
]

extra_ch09 = [
    story('Tu Choi Lich Su', 'A Polite Refusal', 'Có lúc chỉ một câu nói lịch sự rằng mình không làm được đã cứu em khỏi rất nhiều bực dọc về sau.', 'Sometimes one polite sentence saying you cannot do it saves you from much later resentment.', 'Nhiều người tưởng từ chối là cứng và làm mất lòng.', 'Many think refusal is harsh and automatically offensive.', 'Nhưng một lời từ chối rõ ràng, nhẹ nhàng thường lành hơn một lời đồng ý miễn cưỡng.', 'But a clear and gentle refusal is often healthier than a reluctant yes.', 'Người tôn trọng em sẽ hiểu giới hạn đó.', 'People who respect you will understand that boundary.', 'Lịch sự không có nghĩa là để ai muốn lấy gì từ em cũng được.', 'Being polite does not mean letting anyone take whatever they want from you.'),
    story('Dung Giai Thich Qua Nhieu', 'Do Not Over-Explain', 'Có người từ chối xong vẫn giải thích rất dài vì sợ người khác hiểu lầm.', 'Some people refuse a request and then explain for too long because they fear misunderstanding.', 'Họ tưởng càng giải thích nhiều thì càng được thông cảm.', 'They think more explanation creates more understanding.', 'Nhưng giải thích quá mức đôi khi chỉ mở thêm cửa cho người khác mặc cả với ranh giới của em.', 'But too much explanation can open more room for others to bargain with your boundary.', 'Một câu rõ thường mạnh hơn cả đoạn dài đầy áy náy.', 'One clear sentence is often stronger than a long paragraph full of guilt.', 'Ranh giới tốt không cần quá nhiều lời. Nó cần sự nhất quán.', 'A good boundary does not need too many words. It needs consistency.'),
    story('Giup Gia Dinh Co Gioi Han', 'Helping Family with Limits', 'Có những người trẻ vì thương nhà nên lúc nào cũng sẵn sàng gánh thêm phần việc và phần lo của cả gia đình.', 'Some young people love their family so much that they keep taking more work and worry for the whole house.', 'Họ tưởng càng mệt vì nhà thì càng chứng tỏ mình có hiếu.', 'They think the more they wear themselves out for family, the more dutiful they are.', 'Nhưng yêu thương cũng cần đi cùng phân vai và sức bền, nếu không một người sẽ kiệt mà phần còn lại không đổi.', 'But love also needs structure and stamina, or one person burns out while the rest changes nothing.', 'Đỡ gia đình không có nghĩa là tan vào mọi gánh nặng của gia đình.', 'Helping family does not mean dissolving into every family burden.', 'Hiếu thảo đẹp nhất khi đi cùng sự bền lâu, không phải sự kiệt sức.', 'Filial love is most beautiful when it can last, not when it burns out.'),
    story('Tu Te Noi Lam Viec Khong Phai Ngo Nghech', 'Being Kind at Work Is Not Being Naive', 'Ở chỗ làm, có người giữ thái độ dễ chịu nhưng lại học thêm cách ghi dấu công việc và nói rõ phần của mình.', 'At work, some people stay kind while also learning to record their work and speak clearly about their part.', 'Nhiều người tưởng muốn không bị dùng thì phải trở nên lạnh hoặc sắc quá mức.', 'Many think the only way not to be used is to become cold or overly sharp.', 'Thật ra em vẫn có thể hiền mà rõ, tốt mà có nguyên tắc.', 'In truth, you can stay gentle and still be clear, good and still principled.', 'Bản lĩnh không luôn ồn ào. Có khi nó chỉ nằm ở một giọng nói mềm mà ranh giới rất chắc.', 'Strength is not always loud. Sometimes it sits in a soft voice with a firm boundary.', 'Người tử tế bền là người giữ được lòng tốt mà không để lòng tốt nuốt mất mình.', 'Sustainable kindness keeps its goodness without letting goodness swallow the self.'),
    story('Nghi Ngoi Ma Khong Co Loi', 'Resting Without Guilt', 'Có người cứ nghỉ một chút là thấy day dứt như mình đang ích kỷ hoặc lười biếng.', 'Some people feel guilty each time they rest, as if they are selfish or lazy.', 'Họ tưởng giúp người khác nghĩa là lúc nào cũng phải sẵn và hết mình.', 'They think helping others means always being available and fully open.', 'Nhưng một người cạn sạch thì lòng tốt của họ cũng méo dần và chua dần.', 'But a person who is empty inside will slowly distort even their kindness.', 'Nghỉ để hồi lại không phải phản bội ai. Đó là cách giữ cho mình còn sức mà thương đúng.', 'Resting to recover is not betrayal. It is how you keep enough strength to care well.', 'Muốn tử tế lâu, em phải cho mình quyền nghỉ.', 'If you want to stay kind for long, you must allow yourself to rest.'),
]

extra_ch10 = [
    story('Ho So Co Dau Vet', 'A Portfolio Leaves Traces', 'Có người không nói mình giỏi nhiều, nhưng mở máy ra là có bài viết, sản phẩm, và dự án để cho xem.', 'Some people do not talk much about being capable, but when they open their laptop there are articles, products, and projects to show.', 'Nhiều bạn trẻ tưởng nói hay về năng lực là đủ.', 'Many young people think speaking well about ability is enough.', 'Nhưng bằng chứng nhỏ mà thật thường thuyết phục hơn lời giới thiệu lớn.', 'But small real evidence persuades more than grand introductions.', 'Một dấu vết cụ thể có thể mở cửa nhanh hơn rất nhiều câu tự khen.', 'One concrete trace can open doors faster than many self-promoting lines.', 'Muốn kiếm việc, đừng chỉ tích kiến thức. Hãy tích cả bằng chứng.', 'If you want work, do not collect only knowledge. Collect evidence too.'),
    story('Bay Thuc Tap Khong Loi Ra', 'The Trap of Endless Unpaid Internships', 'Có người đi hết chỗ thực tập này sang chỗ khác mà vị trí vẫn mờ, lương vẫn không có.', 'Some move from one internship to another while the role stays unclear and pay never appears.', 'Họ tưởng cứ chịu khó ôm việc miễn phí thật lâu thì sớm muộn cũng được cất nhắc.', 'They think if they carry unpaid work long enough, they will eventually be lifted up.', 'Nhưng có nơi chỉ quen dùng sức trẻ giá rẻ mà không hề có đường đi rõ cho em.', 'But some places simply get used to cheap young labor and offer no clear path.', 'Người trẻ cần học nhìn xem nơi đó đang dạy mình thật hay chỉ đang dùng mình khéo.', 'Young people need to ask whether a place is truly teaching them or merely using them well.', 'Không phải cơ hội nào cũng đáng trả bằng quá nhiều thời gian miễn phí.', 'Not every opportunity is worth paying for with too much unpaid time.'),
    story('Ket Noi Khong Phai Xin Xo', 'Networking Is Not Begging', 'Nhiều người giỏi nhưng ngại kết nối vì sợ bị nghĩ là nhờ vả hoặc đánh bóng mình.', 'Many capable people avoid connection because they fear looking needy or self-promoting.', 'Họ tưởng đi một mình mới là sạch và đáng trọng.', 'They think walking alone is the purest and most respectable path.', 'Nhưng công việc thật vận hành qua con người, sự tin cậy, và những cuộc gặp đúng lúc.', 'But real work moves through people, trust, and well-timed conversations.', 'Kết nối đúng không làm em thấp đi. Nó giúp giá trị của em đi đến đúng tai đúng mắt.', 'Healthy networking does not lower you. It helps your value reach the right ears and eyes.', 'Kiếm việc không chỉ là học giỏi. Còn là học cách bước vào mạng người thật.', 'Getting work is not only about being good. It is also about entering real human networks.'),
    story('Truot Phong Van Dau', 'Failing the First Interview', 'Cuộc phỏng vấn đầu tiên làm nhiều người trẻ vấp ngay ở những chỗ mình tưởng đơn giản.', 'The first interview makes many young people stumble on things they thought were simple.', 'Họ tưởng học giỏi rồi thì nói về mình cũng sẽ tự trôi.', 'They think that if they studied well, speaking about themselves will naturally go well too.', 'Nhưng trả lời ngắn gọn, đúng trọng tâm, và cho thấy mình hiểu công việc là một kỹ năng phải luyện.', 'But answering briefly, clearly, and with real understanding is a skill that must be practiced.', 'Trượt lần đầu không đáng xấu hổ. Nó chỉ phơi ra chỗ em cần tập.', 'Failing the first time is not shameful. It only reveals what you need to practice.', 'Phỏng vấn dở không nói em vô dụng. Nó nói em còn phải học thêm một loại ngôn ngữ của công việc.', 'A poor interview does not say you are useless. It says you still need to learn one more language of work.'),
    story('Hoc Cong Cu, Khong Chi Hoc Ly Thuyet', 'Learn Tools, Not Theory Alone', 'Có người biết khái niệm rất nhiều nhưng đụng vào phần mềm, quy trình, hay công cụ thật thì lúng túng.', 'Some people know many concepts, but become awkward when touching real software, process, or tools.', 'Họ tưởng nền lý thuyết đẹp sẽ tự đổi thành khả năng làm việc.', 'They think a strong theory base will automatically turn into working ability.', 'Nhưng thị trường thường nhìn người dùng được công cụ và giải được việc cụ thể trước tiên.', 'But the market usually first notices those who can use tools and solve concrete tasks.', 'Kiến thức mạnh hơn rất nhiều khi nó đi kèm đôi tay biết làm.', 'Knowledge becomes much stronger when it comes with hands that can do.', 'Giỏi thật là khi em nối được điều mình học với điều người ta đang cần.', 'Real capability appears when you connect what you learned with what people actually need.'),
]

extra_ch11 = [
    story('Nang Nep Hon Cam Hung', 'Routine Is Stronger Than Inspiration', 'Có người chỉ làm được việc khi tâm trạng tốt nên tuần nào cũng có ngày rất sáng và ngày rất trống.', 'Some people can work only when the mood is good, so every week contains bright days and empty days.', 'Họ tưởng cảm hứng là nguồn đủ mạnh để kéo mình đi xa.', 'They think inspiration is strong enough to carry them far.', 'Nhưng đường dài thường đi bằng nề nếp trước khi đi bằng cảm xúc.', 'But long roads are usually walked by routine before feeling.', 'Một lịch nhỏ nhưng đều giúp em hơn nhiều lần bùng lên rồi tắt nhanh.', 'A small steady schedule helps more than repeated bursts followed by collapse.', 'Kỷ luật không cần đẹp. Nó cần bền.', 'Discipline does not need to look impressive. It needs to last.'),
    story('Ngu Dung Gio Cuu Rat Nhieu Thu', 'Sleeping on Time Saves Many Things', 'Nhiều người trẻ cố sửa đời bằng mục tiêu lớn nhưng bỏ qua chuyện ngủ nghỉ.', 'Many young people try to fix life with big goals while ignoring sleep.', 'Họ tưởng ngủ chỉ là chuyện phụ còn thành công mới là chuyện chính.', 'They think sleep is secondary while success is primary.', 'Nhưng một đầu óc thiếu nghỉ sẽ làm mọi kế hoạch trở nên nặng nề và dễ đổ hơn.', 'But a tired mind makes every plan heavier and easier to break.', 'Kỷ luật đôi khi bắt đầu từ giờ tắt điện chứ không phải từ câu khẩu hiệu lớn.', 'Discipline sometimes starts with bedtime, not with a grand slogan.', 'Muốn đi dài, em phải coi việc nghỉ đúng là một phần của việc cố đúng.', 'If you want to go long, proper rest must count as part of proper effort.'),
    story('Muc Tieu Nho Moi Ngay', 'One Small Daily Target', 'Có giai đoạn đời rối đến mức nếu nhìn cả quãng dài em sẽ chỉ thấy nản.', 'There are seasons when life is so messy that looking at the long road only creates discouragement.', 'Nhiều người tưởng lúc đó phải đặt mục tiêu thật lớn mới vực mình dậy được.', 'Many think they need huge goals to lift themselves back up.', 'Nhưng đôi khi thứ cứu người lại là một mục tiêu nhỏ đủ làm được trong hôm nay.', 'But sometimes what saves a person is one small target that can truly be done today.', 'Một việc xong gọn giúp nhịp sống quay lại nhanh hơn rất nhiều lời hứa lớn.', 'One completed task often restores rhythm faster than grand promises.', 'Kỷ luật bền nhiều khi được dựng bằng những bước rất nhỏ.', 'Sustainable discipline is often built from very small steps.'),
    story('Su Deu Dan Chong Buon Chan', 'Consistency Defeats Boredom', 'Làm một việc lặp lại mỗi ngày rất dễ khiến người trẻ thấy chán và muốn đổi ngay.', 'Repeating one task each day easily makes young people bored and eager to switch quickly.', 'Họ tưởng buồn chán là dấu hiệu mình đang đi sai đường.', 'They think boredom automatically means the road is wrong.', 'Nhưng nhiều kỹ năng mạnh được xây trong những ngày rất ít cảm xúc và rất lặp.', 'But many strong skills are built on days that feel repetitive and emotionally flat.', 'Nếu chạy khỏi mọi thứ vừa kịp chán, em sẽ khó có thứ gì đủ sâu.', 'If you run from everything the moment it gets dull, little will ever grow deep.', 'Buồn chán không luôn là kẻ thù. Nhiều lúc nó là cổng vào của sự thành thục.', 'Boredom is not always the enemy. Sometimes it is the gate to mastery.'),
    story('Bat Dau Lai Sau Mot Tuan Te', 'Starting Again After a Bad Week', 'Có tuần em trễ lịch, lười, làm hỏng vài việc, rồi muốn bỏ luôn cả nề nếp.', 'Some weeks you miss schedules, feel lazy, spoil a few tasks, and then want to give up the whole routine.', 'Nhiều người tưởng hỏng một tuần là hỏng luôn cả quá trình.', 'Many think a bad week ruins the whole process.', 'Nhưng người đi xa là người biết tuần xấu chỉ là tuần xấu, không phải bản án.', 'But people who go far know that a bad week is only a bad week, not a sentence.', 'Quay lại vào đầu tuần mới đôi khi là chiến thắng đủ lớn rồi.', 'Returning at the start of the next week is often a large enough victory.', 'Kỷ luật không đòi em hoàn hảo. Nó đòi em biết quay lại.', 'Discipline does not demand perfection. It asks you to return.'),
]

extra_ch12 = [
    story('Tra Lai Dieu Minh Da Muon', 'Return What You Borrowed', 'Một dấu hiệu rất thật của trưởng thành là không xem nợ nhỏ hay lời hứa nhỏ là chuyện không đáng nhớ.', 'A very real sign of maturity is not treating small debts or small promises as forgettable.', 'Nhiều người trẻ tưởng thiếu một chút rồi xin khất thêm cũng không sao.', 'Many young people think a little delay on borrowed things does not matter much.', 'Nhưng cách em xử lý những món nhỏ thường cho thấy em coi trọng trách nhiệm đến đâu.', 'But how you handle small obligations reveals how seriously you treat responsibility.', 'Người đáng tin được nhận ra từ những việc bé như vậy.', 'Trustworthy people are recognized through such small acts.', 'Trưởng thành bắt đầu từ lúc em không để người khác phải đòi phần em đã nhận.', 'Maturity begins when others do not need to chase what you owe.'),
    story('Giu Loi Voi Viec Nho', 'Keep Your Word in Small Things', 'Có người giữ lời hứa lớn rất cảm động nhưng lại quên những việc rất nhỏ mình từng nói sẽ làm.', 'Some people speak beautifully about big promises but forget very small things they said they would do.', 'Họ tưởng chỉ việc lớn mới đáng tính là trách nhiệm.', 'They think only large matters count as responsibility.', 'Nhưng cuộc sống chung được giữ bằng vô số lời hứa nhỏ được hoàn thành đều đặn.', 'But shared life is held together by many small promises completed steadily.', 'Ai xem nhẹ chuyện nhỏ thường cũng làm người khác mệt dần trong chuyện lớn.', 'Those who dismiss small duties often tire others out in bigger matters too.', 'Người lớn đáng tin là người làm xong cả phần nhỏ không ai vỗ tay.', 'A reliable adult completes even the small parts that earn no applause.'),
    story('Nhan Ra Gioi Han Cua Minh', 'Admitting Your Own Limits', 'Có lúc trưởng thành không phải là gồng lên nhận hết, mà là nói rõ mình chưa gánh nổi.', 'Sometimes maturity is not taking everything on, but saying clearly that you cannot carry it yet.', 'Nhiều người trẻ tưởng nhận hết mới là bản lĩnh.', 'Many young people think accepting everything is proof of strength.', 'Nhưng nhận quá sức rồi làm đổ mới là cách nhanh nhất để mất uy tín.', 'But taking more than you can carry and dropping it is the fastest way to lose credibility.', 'Biết giới hạn giúp em phân phối sức đúng hơn và học nhanh hơn.', 'Knowing your limits helps you use energy more wisely and learn faster.', 'Chịu trách nhiệm không có nghĩa ôm tất cả. Nó là biết ôm đúng phần mình làm được.', 'Responsibility does not mean carrying everything. It means carrying your real part well.'),
    story('Dung Cho Nguoi Lon Den Cuu Mai', 'Stop Waiting for Adults to Fix Everything', 'Có một độ tuổi em phải thôi chờ người lớn hơn giải quyết giúp các rối rắm mình tạo ra.', 'There is an age when you must stop waiting for older people to fix the problems you created.', 'Trước đó nhiều người vẫn tưởng chỉ cần thú nhận rồi sẽ có ai đó đứng ra dọn tiếp.', 'Before that, many still believe admitting the problem is enough and someone else will clean up the rest.', 'Nhưng trưởng thành bắt đầu khi em tự bước vào phần dọn hậu quả của mình.', 'But maturity begins when you step into the cleanup yourself.', 'Người lớn thật không chỉ biết báo lỗi. Họ biết sửa lỗi.', 'Real adults do not only report mistakes. They repair them.', 'Tự chịu phần bừa bộn mình gây ra là một mốc lớn của việc thành người lớn.', 'Cleaning the mess you create is a major milestone in becoming an adult.'),
    story('Song De Mai Sau Nhin Lai Khong Xau Ho', 'Live So You Will Not Be Ashamed Later', 'Cuối cùng, có những quyết định không ai chấm ngay nhưng vài năm sau chính em sẽ là người phải nhìn lại chúng.', 'In the end, some decisions are not judged right away, but years later you will look back at them yourself.', 'Nhiều người trẻ tưởng qua được hôm nay là đủ.', 'Many young people think surviving today is enough.', 'Nhưng đời dài khiến mỗi lựa chọn dần trở thành nhân cách.', 'But over a long life, each choice slowly becomes character.', 'Sống có trách nhiệm là sống sao để tương lai của mình không phải cúi mặt vì hiện tại của mình.', 'Living responsibly means living so your future self does not lower its eyes before your present self.', 'Đích của trưởng thành không chỉ là sống sót. Nó là sống cho đàng hoàng.', 'The goal of maturity is not only survival. It is decent living.'),
]

ch01_full = ch01 + extra_ch01
ch02_full = ch02 + extra_ch02
ch03_full = ch03 + extra_ch03
ch04_full = ch04 + extra_ch04
ch05_full = ch05 + extra_ch05
ch06_full = ch06 + extra_ch06
ch07_full = ch07 + extra_ch07
ch08_full = ch08 + extra_ch08
ch09_full = ch09 + extra_ch09
ch10_full = ch10 + extra_ch10
ch11_full = ch11 + extra_ch11
ch12_full = ch12 + extra_ch12

print('Dang nang cap Quyển 9 len 10 truyen moi chuong...')
make_chapter('ch01-roi-ghe-nha-truong', 'Rời Ghế Nhà Trường, Đời Không Chấm Điểm Công Khai', 'Leaving School, Entering an Ungraded Life', ch01_full)
make_chapter('ch02-cong-viec-dau-tien', 'Công Việc Đầu Tiên Và Cú Sốc Thực Tế', 'The First Job and the Shock of Reality', ch02_full)
make_chapter('ch03-tien-tu-do-sai-lam', 'Tiền Đầu Tiên, Tự Do Đầu Tiên, Sai Lầm Đầu Tiên', 'First Money, First Freedom, First Mistakes', ch03_full)
make_chapter('ch04-khong-ai-no-em-cho-dung', 'Không Ai Nợ Em Một Chỗ Đứng', 'No One Owes You a Place', ch04_full)
make_chapter('ch05-bi-tu-choi-bi-thay-the', 'Bị Từ Chối, Bị Chê, Bị Thay Thế', 'Rejected, Criticized, Replaced', ch05_full)
make_chapter('ch06-song-xa-nha', 'Lên Thành Phố, Sống Xa Nhà, Tự Lo Mọi Thứ', 'Moving Away and Taking Care of Everything', ch06_full)
make_chapter('ch07-ban-be-ra-re', 'Bạn Bè Ra Rẽ, Đường Ai Nấy Đi', 'Friends Drift, Each Person Has a Road', ch07_full)
make_chapter('ch08-tinh-yeu-tuoi-tre', 'Tình Yêu Tuổi Trẻ Và Những Ảo Tưởng Ngọt', 'Young Love and Its Sweet Illusions', ch08_full)
make_chapter('ch09-tu-te-nhung-dung-de-bi-dung', 'Tử Tế Nhưng Đừng Dễ Bị Dùng', 'Be Kind, But Do Not Be Easily Used', ch09_full)
make_chapter('ch10-gioi-khong-dong-nghia-co-viec', 'Giỏi Không Đồng Nghĩa Với Kiếm Được Việc', 'Being Good Does Not Automatically Get You a Job', ch10_full)
make_chapter('ch11-ky-luat-cuu-nguoi', 'Kỷ Luật Cứu Người Khi Hết Động Lực', 'Discipline Saves You When Motivation Is Gone', ch11_full)
make_chapter('ch12-truong-thanh-la-chiu-trach-nhiem', 'Trưởng Thành Là Bớt Đổ Lỗi, Tăng Chịu Trách Nhiệm', 'Maturity Means Less Blame and More Responsibility', ch12_full)
print('Hoan tat nang cap Quyển 9!')
