# -*- coding: utf-8 -*-
"""Quyển VI -- Vòng Quay Cuộc Đời -- Chapters 9-12"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-6/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    text = re.sub(r'(?<!\\)&', r'\\&', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 9: THIÊN NHIÊN DẠY GÌ
# ================================================================
ch9 = chapter(
    "Thiên Nhiên Dạy Gì",
    "What Nature Teaches",
    "Đi vào thiên nhiên sẽ không bao giờ là lãng phí thời gian.",
    "Going to nature is never going to waste.",
    [
    story("Quả Táo Rơi Và Vũ Trụ Của Newton", "Isaac Newton --- Anh, 1666",
          "Năm",
          [("Năm 1666, Isaac Newton đang ngồi trong vườn dưới bóng cây táo thì nhìn thấy một quả táo rơi xuống đất.",
            "In 1666, Isaac Newton was sitting in his garden under an apple tree when he saw an apple fall to the ground."),
           ("Điều mà hàng triệu người đã thấy trước đó mà không đặt câu hỏi.",
            "Something millions had seen before without questioning."),
           ("Newton hỏi: 'Tại sao quả táo luôn rơi thẳng xuống, không rơi sang ngang hay bay lên?'",
            "Newton asked: 'Why does the apple always fall straight down, not sideways or upward?'"),
           ("Câu hỏi đó dẫn ông đến lý thuyết hấp dẫn vũ trụ --- định nghĩa lại toàn bộ nền vật lý và khoa học hiện đại.",
            "That question led him to the theory of universal gravitation --- redefining all of modern physics and science."),
           ("Thiên nhiên luôn ở đó dạy bài học; điều duy nhất phân biệt nhà khoa học với người thường là nhà khoa học dừng lại và hỏi 'tại sao'.",
            "Nature is always there teaching its lessons; the only thing distinguishing the scientist from the ordinary person is that the scientist stops and asks 'why'.")],
          "Thiên nhiên không giấu bí mật của mình; nó chỉ chờ người đặt câu hỏi đủ sâu sắc.",
          "Nature does not hide its secrets; it only waits for someone to ask deep enough questions."),

    story("Mạng Nhện Và Kỹ Sư Cầu", "Kỹ thuật học từ thiên nhiên",
          "Khi",
          [("Khi kỹ sư người Anh John Roebling thiết kế cây cầu treo Brooklyn năm 1867, ông lấy cảm hứng từ cấu trúc của mạng nhện.",
            "When British engineer John Roebling designed the Brooklyn suspension bridge in 1867, he drew inspiration from the structure of a spiderweb."),
           ("Các sợi tơ nhện có cấu trúc phân tán tải trọng đồng đều, cực kỳ bền và đồng thời linh hoạt.",
            "Spider silk fibers have a structure that distributes weight evenly, extremely strong yet simultaneously flexible."),
           ("Ông áp dụng nguyên lý đó vào hệ thống dây cáp của cầu Brooklyn --- và cây cầu đứng vững hơn 150 năm.",
            "He applied that principle to the Brooklyn Bridge's cable system --- and the bridge has stood for over 150 years."),
           ("Thiên nhiên đã giải quyết bài toán kỹ thuật này từ hàng triệu năm trước khi con người bắt đầu nghĩ đến nó.",
            "Nature had solved this engineering problem millions of years before humans began thinking about it."),
           ("Khoa học biomimicry ngày nay --- học từ thiên nhiên để thiết kế --- đang cách mạng hóa công nghệ trong mọi lĩnh vực từ hàng không đến y tế.",
            "The science of biomimicry today --- learning from nature to design --- is revolutionizing technology in every field from aviation to medicine.")],
          "Những giải pháp tốt nhất cho vấn đề của con người thường đã được thiên nhiên tìm ra từ hàng triệu năm trước; hãy học hỏi thiên nhiên trước khi tái phát minh bánh xe.",
          "The best solutions to human problems have often already been discovered by nature millions of years ago; learn from nature before reinventing the wheel."),

    story("Dòng Sông Và Triết Học Heraclitus", "Heraclitus --- Hy Lạp, 500 TCN",
          "Heraclitus",
          [("Heraclitus, triết gia Hy Lạp, đứng bên dòng sông và đưa ra một trong những câu nói triết học nổi tiếng nhất lịch sử: 'Bạn không bao giờ có thể bước xuống cùng một dòng sông hai lần.'",
            "Heraclitus, the Greek philosopher, stood beside a river and delivered one of the most famous philosophical statements in history: 'You cannot step into the same river twice.'"),
           ("Lần anh bước xuống thứ hai, dòng nước đã khác. Và chính anh cũng đã khác.",
            "The second time you step in, the water is different. And you yourself are also different."),
           ("Thiên nhiên dạy rằng sự thay đổi không ngừng là bản chất của thực tại.",
            "Nature teaches that constant change is the nature of reality."),
           ("Người khổ đau không phải vì cuộc sống thay đổi --- họ khổ đau vì cưỡng lại sự thay đổi.",
            "People suffer not because life changes --- they suffer because they resist change."),
           ("Dòng sông không khóc vì mỗi ngọn nước cũ phải ra đi; nó chảy mãi về phía trước, luôn mới và luôn sống.",
            "The river does not mourn because each old wave must pass away; it flows ever forward, always new and always alive.")],
          "Thay đổi không phải là kẻ thù của bạn; đó là bản chất của cuộc sống. Người nào học cách chảy như nước sẽ không bao giờ bị vỡ.",
          "Change is not your enemy; it is the nature of life. Those who learn to flow like water will never break."),

    story("Cây Sồi Và Cây Sậy Trong Bão", "Jean de La Fontaine --- Pháp, 1668",
          "Trong",
          [("Trong bài thơ ngụ ngôn nổi tiếng của La Fontaine, cây sồi to lớn khoe khoang với cây sậy mảnh mai: 'Ngươi bị bẻ gãy bởi bất kỳ ngọn gió nhỏ nào, còn ta đứng vững trước bão lớn.'",
            "In La Fontaine's famous fable, a massive oak tree boasted to a slender reed: 'You are broken by any small wind, while I stand firm before great storms.'"),
           ("Rồi một cơn bão thực sự ập đến.",
            "Then a real storm came."),
           ("Cây sậy cúi rạp xuống, uốn mình theo từng cơn gió dữ.",
            "The reed bent low, yielding to each fierce gust."),
           ("Cây sồi cứng đầu chống chọi --- và bị bật gốc, ngã xuống.",
            "The stubborn oak resisted --- and was uprooted, crashing down."),
           ("Cây sậy vươn thẳng lại sau bão và tiếp tục sống.",
            "The reed straightened again after the storm and continued living."),
           ("Thiên nhiên dạy rằng sức mạnh thực sự không phải là cứng nhắc mà là khả năng thích nghi.",
            "Nature teaches that true strength is not rigidity but the capacity to adapt.")],
          "Người kiên cường nhất không phải là người không bao giờ cúi đầu, mà là người biết khi nào cần uốn mình và vẫn đứng dậy được sau bão.",
          "The most resilient person is not the one who never bends, but the one who knows when to bend and still rises after the storm."),

    story("Con Nhộng Và Sức Mạnh Của Đấu Tranh", "Truyện ngụ ngôn về bướm",
          "Một",
          [("Một người tìm thấy một cái kén bướm và nhìn thấy con bướm đang vất vả thoát ra khỏi lỗ nhỏ.",
            "A person found a butterfly cocoon and watched the butterfly struggling to emerge through a small opening."),
           ("Tưởng giúp bướm, người đó cắt kén rộng thêm để bướm dễ ra.",
            "Thinking to help the butterfly, the person cut the cocoon wider to make it easier to emerge."),
           ("Con bướm ra dễ dàng --- nhưng thân mình phồng lên, cánh teo tóp, không thể bay.",
            "The butterfly emerged easily --- but its body was swollen, its wings shriveled, unable to fly."),
           ("Điều người đó không biết: chính sự vật lộn qua lỗ nhỏ là cách tự nhiên bơm dịch từ thân vào cánh, tạo ra sức mạnh để bay.",
            "What the person did not know: the very struggle through the small opening is nature's way of pumping fluid from body to wing, creating the strength to fly."),
           ("Bằng cách loại bỏ đấu tranh, người đó đã loại bỏ đi sự phát triển.",
            "By removing the struggle, the person removed the growth.")],
          "Không phải mọi khó khăn đều cần được giải quyết hộ; đôi khi chính sự đấu tranh là bài học và sức mạnh mà người kia cần tự trải nghiệm.",
          "Not every difficulty needs to be solved for someone else; sometimes the struggle itself is the lesson and strength the person needs to experience themselves."),

    story("Ong Và Bài Học Về Cộng Đồng", "Quan sát khoa học về ong mật",
          "Tổ",
          [("Tổ ong hoạt động không có vua, không có chỉ huy trung tâm, nhưng với hiệu quả đáng kinh ngạc.",
            "A beehive operates without a king, without central command, but with astonishing efficiency."),
           ("Mỗi con ong đều biết vai trò của mình và thực hiện vai trò đó hoàn hảo: ong trinh sát tìm hoa, ong hộ tống bảo vệ, ong thợ chắt lọc mật, ong nữ hoàng sinh sản.",
            "Each bee knows its role and performs it perfectly: scout bees find flowers, guard bees protect, worker bees process nectar, the queen bee reproduces."),
           ("Khi tổ gặp nguy, toàn đội hy sinh cá nhân vì tập thể mà không cần lệnh.",
            "When the hive is in danger, the whole team sacrifices individually for the collective without any command."),
           ("Các nhà khoa học gọi đây là 'trí tuệ bày đàn' --- khả năng của tập thể vượt xa bất kỳ cá nhân nào.",
            "Scientists call this 'swarm intelligence' --- the capacity of the collective far exceeding any individual."),
           ("Thiên nhiên dạy: cộng đồng biết chia sẻ vai trò và hy sinh cá nhân có thể tồn tại và thịnh vượng vô hạn.",
            "Nature teaches: a community that knows how to share roles and sacrifice individually can survive and flourish indefinitely.")],
          "Sức mạnh của cộng đồng không đến từ sự chỉ huy mà đến từ mỗi thành viên hiểu rõ vai trò của mình và hành động vì lợi ích chung.",
          "The strength of a community comes not from command but from each member clearly understanding their role and acting for the common good."),

    story("Rừng Ngập Mặn Và Bài Học Về Rễ", "Sinh thái học --- Đồng bằng sông Cửu Long",
          "Rừng",
          [("Rừng ngập mặn ở vùng đồng bằng sông Cửu Long là một trong những hệ sinh thái kỳ diệu nhất thế giới.",
            "The mangrove forests of the Mekong Delta are among the most remarkable ecosystems in the world."),
           ("Cây đước, cây mắm sống trong điều kiện tưởng chừng không thể: nước mặn, bùn thiếu oxy, thủy triều lên xuống không ngừng.",
            "Mangrove trees live in seemingly impossible conditions: saltwater, oxygen-poor mud, constantly rising and falling tides."),
           ("Bí quyết của chúng: hệ thống rễ chằng chịt cắm sâu vào bùn, chắn sóng, giữ đất.",
            "Their secret: an intricate root system drilling deep into mud, blocking waves, holding soil."),
           ("Chính những rễ đó bảo vệ bờ biển khỏi xói mòn, nuôi dưỡng vô số loài sinh vật, lọc nước.",
            "Those very roots protect the coastline from erosion, nurture countless species, filter water."),
           ("Thiên nhiên dạy: khi môi trường khắc nghiệt nhất, hãy đâm rễ sâu hơn, không phải bỏ chạy.",
            "Nature teaches: when the environment is harshest, go deeper with your roots, do not flee.")],
          "Khi cuộc sống khắc nghiệt nhất, đây không phải lúc để bứng rễ chạy trốn mà là lúc để đâm rễ sâu hơn vào những gì thực sự nuôi dưỡng bạn.",
          "When life is most harsh, this is not the time to uproot and flee but to drive your roots deeper into what truly nourishes you."),

    story("Nhện Và Bài Học Tái Thiết", "Quan sát thiên nhiên",
          "Con",
          [("Con nhện mất mạng tơ của mình mỗi sáng khi sương đêm làm vỡ tơ, hoặc khi gió thổi đứt cả tấm lưới.",
            "A spider loses its web every morning when night dew tears the silk, or when wind shreds the entire net."),
           ("Nhưng nó không ngồi than thở.",
            "But it does not sit and lament."),
           ("Nó bắt đầu lại từ điểm neo đầu tiên, kiên nhẫn kéo từng sợi, từng ô trong tấm lưới mới.",
            "It begins again from the first anchor point, patiently drawing each thread, each cell of the new web."),
           ("Mỗi tấm lưới mới đẹp hơn, chính xác hơn lần trước --- vì nhện đã học được từ những lần hỏng trước đó.",
            "Each new web is more beautiful, more precise than the last --- because the spider has learned from previous failures."),
           ("Nhện không cần ai an ủi, không cần ai khuyến khích --- nó chỉ bắt đầu lại.",
            "The spider needs no consolation, no encouragement --- it simply begins again.")],
          "Sau mỗi lần mọi thứ sụp đổ, câu hỏi không phải là 'Tại sao điều này xảy ra với tôi?' mà là 'Tôi bắt đầu từ đâu?'",
          "After everything collapses, the question is not 'Why did this happen to me?' but 'Where do I begin?'"),

    story("Mặt Trời Mọc Và Triết Lý Hy Vọng", "Truyện dân gian Nhật Bản",
          "Theo",
          [("Theo truyện dân gian Nhật Bản, có một thời kỳ nữ thần mặt trời Amaterasu tức giận và ẩn vào một hang đá, khiến thế giới chìm trong bóng tối.",
            "According to Japanese legend, there was once a time when the sun goddess Amaterasu became angry and hid in a cave, plunging the world into darkness."),
           ("Mọi thần linh đều cầu xin, nhưng nữ thần không ra.",
            "All the gods pleaded, but the goddess would not emerge."),
           ("Cuối cùng, thần Ame-no-Uzume bắt đầu nhảy múa và hát ca vui vẻ trước cửa hang.",
            "Finally, the goddess Ame-no-Uzume began dancing and singing joyfully before the cave entrance."),
           ("Đám đông thần linh cười vui và vỗ tay. Tiếng vui vẻ đó khiến Amaterasu tò mò nhìn ra --- và ánh sáng trở lại thế giới.",
            "The crowd of gods laughed and applauded joyfully. That sound of joy made Amaterasu curiously peek out --- and light returned to the world."),
           ("Thiên nhiên và thần thoại cùng dạy một điều: ánh sáng không thể bị giữ mãi trong bóng tối; và lòng vui vẻ chân thành có sức mạnh triệu hồi ánh sáng quay về.",
            "Both nature and mythology teach the same thing: light cannot be kept in darkness forever; and genuine joy has the power to summon light back.")],
          "Dù đêm dài đến đâu, mặt trời vẫn mọc mỗi sáng; đó là lời hứa thiên nhiên không bao giờ thất hứa.",
          "No matter how long the night, the sun still rises each morning; this is nature's promise that is never broken."),

    story("Mùa Đông Và Bài Học Về Chờ Đợi", "Triết lý bốn mùa",
          "Những",
          [("Những cây trong rừng không chiến đấu với mùa đông; chúng chấp nhận nó.",
            "The trees in the forest do not fight winter; they accept it."),
           ("Chúng thả lá, thu sức lực vào trong, chờ đợi trong im lặng.",
            "They shed their leaves, draw strength inward, wait in silence."),
           ("Không cây nào hoảng loạn hay cố gắng giữ lại những chiếc lá cuối cùng.",
            "No tree panics or tries to hold onto the last leaves."),
           ("Và đúng như quy luật, xuân đến, chồi mới bật ra, cây đâm nhánh mới khỏe mạnh hơn.",
            "And true to the law, spring comes, new buds burst forth, the tree sends out new growth stronger than before."),
           ("Mùa đông không phải là cái chết; đó là sự tích lũy trong im lặng cho một mùa xuân sâu sắc hơn.",
            "Winter is not death; it is silent accumulation for a more profound spring."),
           ("Con người cũng có những mùa đông nội tâm --- những giai đoạn trầm, mệt mỏi, lặng thinh. Đừng hoảng sợ chúng; hãy để chúng làm việc của chúng.",
            "People also have inner winters --- periods of withdrawal, tiredness, silence. Do not fear them; let them do their work.")],
          "Giai đoạn trầm xuống trong cuộc đời không phải là sự thất bại; đó là mùa đông nội tâm đang âm thầm tích lũy sức mạnh cho mùa xuân tiếp theo.",
          "A low period in life is not failure; it is an inner winter quietly accumulating strength for the next spring."),
    ]
)

# ================================================================
# CHƯƠNG 10: KẺ THÙ DẠY GÌ
# ================================================================
ch10 = chapter(
    "Kẻ Thù Dạy Gì",
    "What Our Enemies Teach Us",
    "Bạn bè tốt dạy ta nhiều điều, nhưng kẻ thù thông minh dạy ta nhiều hơn.",
    "Good friends teach us much, but a clever enemy teaches us more.",
    [
    story("Caesar Và Brutus --- Bài Học Từ Phản Bội", "Shakespeare --- Julius Caesar",
          "Julius",
          [("Julius Caesar tin tưởng Brutus như con trai ruột; Brutus là người ông yêu quý và đặt niềm tin tuyệt đối nhất.",
            "Julius Caesar trusted Brutus like a son; Brutus was the one he loved most and trusted absolutely."),
           ("Và chính Brutus là người đâm Caesar vào ngày 15 tháng 3.",
            "And it was precisely Brutus who stabbed Caesar on the Ides of March."),
           ("Lời nói cuối cùng của Caesar theo Shakespeare: 'Et tu, Brute?' --- 'Cả anh nữa sao, Brutus?'",
            "Caesar's last words according to Shakespeare: 'Et tu, Brute?' --- 'Even you, Brutus?'"),
           ("Bài học không phải là 'đừng tin ai' mà là: ngay cả người bạn tin nhất cũng mang trong họ những mâu thuẫn và yếu đuối mà bạn không thể thấy hết.",
            "The lesson is not 'trust no one' but: even those you trust most carry contradictions and weaknesses you cannot fully see."),
           ("Caesar đã làm ra Brutus vĩ đại --- và không hiểu rằng sự vĩ đại đó cũng mang trong nó hạt giống của sự phản bội.",
            "Caesar had made Brutus great --- and did not understand that such greatness also carried within it the seed of betrayal.")],
          "Sự phản bội của người bạn tin nhất dạy bạn bài học sâu sắc nhất về bản chất con người và về giới hạn của sức hiểu biết của bạn.",
          "The betrayal of those you trust most teaches you the deepest lesson about human nature and the limits of your own understanding."),

    story("Sun Tzu Và Nghệ Thuật Học Từ Kẻ Thù", "Tôn Tử --- Trung Hoa, 500 TCN",
          "Trong",
          [("Trong 'Binh Pháp Tôn Tử', Sun Tzu dạy: 'Biết mình biết người, trăm trận trăm thắng; không biết người chỉ biết mình, thắng thua bằng nhau; không biết mình không biết người, mọi trận đều thua.'",
            "In 'The Art of War', Sun Tzu teaches: 'Know yourself and know your enemy, and you will not be imperiled in a hundred battles; know neither yourself nor your enemy, and you will be imperiled in every battle.'"),
           ("Ông nhấn mạnh rằng việc hiểu kẻ thù sâu sắc bằng cách thám thính, quan sát, phân tích là nền tảng của mọi chiến lược.",
            "He emphasized that profoundly understanding the enemy through scouting, observation and analysis is the foundation of all strategy."),
           ("Điều thú vị: để hiểu đủ sâu về kẻ thù, bạn không thể căm thù họ mù quáng --- bạn phải nhìn nhận họ một cách khách quan, thậm chí trân trọng điểm mạnh của họ.",
            "Interestingly: to understand the enemy deeply enough, you cannot blindly hate them --- you must view them objectively, even appreciating their strengths."),
           ("Người biết học hỏi từ điểm mạnh của kẻ thù là người chiến lược gia giỏi nhất.",
            "The one who knows how to learn from the enemy's strengths is the best strategist."),
           ("Kẻ thù tốt nhất là người buộc bạn phải trở nên tốt hơn.",
            "The best enemy is the one who forces you to become better.")],
          "Đừng lãng phí kẻ thù của bạn bằng cách chỉ căm ghét họ; hãy nghiên cứu họ và trở nên mạnh hơn từ sự hiểu biết đó.",
          "Do not waste your enemies by only hating them; study them and become stronger from that understanding."),

    story("Ludwig Van Beethoven Và Những Nhà Phê Bình", "Beethoven --- Đức, thế kỷ 19",
          "Trong",
          [("Trong suốt sự nghiệp của mình, Beethoven không thiếu những nhà phê bình và kẻ thù âm nhạc.",
            "Throughout his career, Beethoven was not short of critics and musical adversaries."),
           ("Khi ông mất thính lực, nhiều người tuyên bố sự nghiệp âm nhạc của ông đã chấm dứt.",
            "When he lost his hearing, many declared his musical career was over."),
           ("Nhưng Beethoven lấy những lời phê bình đó làm nhiên liệu; ông phân tích từng lời chỉ trích, tự hỏi xem có phần nào đúng không, và cải thiện.",
            "But Beethoven used those criticisms as fuel; he analyzed every critique, asked if any part was valid, and improved."),
           ("Bản Giao hưởng số 9 --- tác phẩm vĩ đại nhất ông viết --- được sáng tác khi ông đã điếc hoàn toàn, để lại cho những kẻ từng chế giễu ông câu trả lời im lặng nhưng bất tử.",
            "Symphony No. 9 --- the greatest work he ever wrote --- was composed when he was completely deaf, leaving those who once mocked him a silent but immortal answer."),
           ("Lời phê bình không giết chết ông; nó chỉ buộc ông phải tìm sâu hơn vào bên trong mình.",
            "Criticism did not kill him; it only forced him to reach deeper within himself.")],
          "Những lời chỉ trích tàn nhẫn nhất đôi khi là những người thầy trung thực nhất --- nếu bạn đủ dũng cảm để lắng nghe chúng mà không chết đuối trong chúng.",
          "The harshest criticisms are sometimes the most honest teachers --- if you are brave enough to listen to them without drowning in them."),

    story("Mandela Và Bài Học Afrikaans Từ Người Cai Tù", "Nelson Mandela --- Robben Island",
          "Trong",
          [("Trong nhà tù Robben Island, Mandela bắt đầu học tiếng Afrikaans --- ngôn ngữ của chính những người cai tù ông.",
            "In Robben Island prison, Mandela began studying Afrikaans --- the language of his very own jailers."),
           ("Bạn đồng tù hỏi ông: 'Tại sao anh học ngôn ngữ của kẻ áp bức?'",
            "Fellow prisoners asked him: 'Why study the language of the oppressors?'"),
           ("Mandela trả lời: 'Để hiểu họ. Và để nói chuyện với họ trực tiếp, không qua phiên dịch.'",
            "Mandela replied: 'To understand them. And to speak with them directly, without an interpreter.'"),
           ("Ông nghiên cứu văn hóa, lịch sử và tư duy của người Afrikaner --- không phải vì ông yêu họ, mà vì ông hiểu rằng muốn thay đổi ai đó phải hiểu họ trước.",
            "He studied the culture, history and thinking of the Afrikaners --- not because he loved them, but because he understood that to change someone you must first understand them."),
           ("Chính sự hiểu biết đó cho phép ông đàm phán hòa giải dân tộc thực sự sau khi lên nắm quyền.",
            "That very understanding allowed him to negotiate genuine national reconciliation after coming to power.")],
          "Để thay đổi kẻ thù, trước tiên phải hiểu kẻ thù; để hiểu kẻ thù, phải sẵn sàng tạm thời gác lại sự căm ghét.",
          "To change an enemy, first understand the enemy; to understand the enemy, be willing to temporarily set aside hatred."),

    story("Lão Tử Và Bài Học Về Nước", "Đạo Đức Kinh --- Lão Tử, Trung Hoa cổ đại",
          "Lão",
          [("Lão Tử dạy: 'Thứ mềm và yếu trên đời thắng được thứ cứng và mạnh.'",
            "Lao Tzu taught: 'The soft and weak in the world overcome the hard and strong.'"),
           ("Ông lấy ví dụ nước: nước là thứ mềm nhất, nhưng nước chảy mãi sẽ khoét thủng đá.",
            "He used water as an example: water is the softest thing, but water flowing persistently will hollow out rock."),
           ("Nước không tranh với đá, không đánh lại đá --- nước chỉ kiên nhẫn chảy quanh nơi đá chặn.",
            "Water does not fight the rock, does not strike back at the rock --- water only patiently flows around where the rock blocks."),
           ("Đây là bài học cho người đang đối mặt với kẻ thù mạnh hơn mình: đừng đối đầu trực tiếp, hãy kiên nhẫn và linh hoạt như nước.",
            "This is the lesson for those facing enemies stronger than themselves: do not confront directly, be patient and flexible like water."),
           ("Theo thời gian, sự kiên nhẫn mềm mại thường thắng được sức mạnh cứng nhắc.",
            "Over time, soft patience usually overcomes rigid strength.")],
          "Đôi khi cách đánh bại kẻ mạnh không phải là đối đầu mà là kiên nhẫn chảy quanh, bào mòn dần như nước với đá.",
          "Sometimes the way to defeat the strong is not confrontation but patiently flowing around, gradually wearing away like water on rock."),

    story("Abraham Lincoln Và Tủ Không Khóa Thư", "Abraham Lincoln --- Hoa Kỳ",
          "Lincoln",
          [("Lincoln có một thói quen kỳ lạ: khi bị ai đó làm ông tức giận, ông viết một bức thư gay gắt gửi cho người đó --- rồi để nó vào ngăn kéo và không bao giờ gửi.",
            "Lincoln had a strange habit: when someone made him angry, he would write a sharp letter to that person --- then put it in a drawer and never send it."),
           ("Ông gọi đây là 'thư không bao giờ gửi' --- cách xả cơn giận mà không gây hậu quả.",
            "He called these 'letters never sent' --- a way to release anger without causing consequences."),
           ("Nhưng quan trọng hơn: trong khi viết thư đó, ông buộc phải đặt mình vào vị trí người kia, hiểu tại sao họ làm vậy.",
            "But more importantly: while writing that letter, he was forced to put himself in the other person's position, understand why they did what they did."),
           ("Quá trình đó thường giúp ông thay cơn giận bằng sự thông cảm --- và đôi khi biến kẻ thù chính trị thành đồng minh.",
            "That process often helped him replace anger with empathy --- and sometimes turned political enemies into allies."),
           ("Trong Nội các của ông có không ít những người từng là kẻ thù chính trị mạnh nhất của ông.",
            "In his Cabinet were no few people who had once been his fiercest political enemies.")],
          "Hiểu kẻ thù không có nghĩa là tha thứ cho những gì họ làm; nó có nghĩa là nhìn thấy họ đủ rõ để đưa ra phản ứng khôn ngoan nhất.",
          "Understanding your enemy does not mean forgiving what they do; it means seeing them clearly enough to give the wisest response."),

    story("Người Mệt Mỏi Vì Chiến Thắng --- Phyrrus", "Phyrrus of Epirus --- Hy Lạp, 280 TCN",
          "Vua",
          [("Vua Pyrrhus của Epirus đã đánh bại quân La Mã trong trận Heraclea năm 280 TCN --- nhưng với tổn thất quá khủng khiếp.",
            "King Pyrrhus of Epirus defeated the Romans at the Battle of Heraclea in 280 BC --- but at a terrible cost."),
           ("Sau trận thắng đó, ông nói câu nói bất hủ: 'Thêm một chiến thắng như thế này, ta sẽ thua hẳn.'",
            "After that victory, he said the immortal words: 'One more victory like this and I shall be utterly lost.'"),
           ("Đây là nguồn gốc của khái niệm 'Chiến thắng Pyrrhus' --- thắng nhưng mất quá nhiều đến mức coi như thua.",
            "This is the origin of the concept 'Pyrrhic victory' --- winning but losing so much it is effectively a defeat."),
           ("Kẻ thù của Pyrrhus --- quân La Mã --- dạy ông bài học này: chiến thắng bằng cách kiệt sức mình không bao giờ là chiến thắng thực sự.",
            "Pyrrhus's enemy --- the Romans --- taught him this lesson: winning by exhausting yourself is never a real victory."),
           ("Đôi khi bài học từ kẻ thù không đến từ khi bạn thua, mà đến từ khi bạn thắng theo cách sai.",
            "Sometimes the lesson from the enemy comes not when you lose, but when you win in the wrong way.")],
          "Không phải mọi chiến thắng đều đáng theo đuổi; đôi khi bài học lớn nhất kẻ thù dạy là bài học về cái giá của cách bạn chọn để thắng.",
          "Not every victory is worth pursuing; sometimes the greatest lesson enemies teach is about the cost of how you choose to win."),

    story("Người Thầy Và Học Trò Xuất Sắc Nhất", "Truyện thiền Trung Hoa",
          "Có",
          [("Có một người thầy dạy kiếm nổi tiếng, học trò khắp nơi đến học.",
            "There was a famous sword teacher, with students coming from everywhere to learn."),
           ("Người học trò xuất sắc nhất hỏi: 'Bao giờ thì con vượt qua được thầy?'",
            "The most outstanding student asked: 'When will I surpass the teacher?'"),
           ("Người thầy mỉm cười: 'Ngay ngày con ngừng cố vượt qua ta là ngày con thực sự vượt qua được.'",
            "The teacher smiled: 'The very day you stop trying to surpass me is the day you truly surpass me.'"),
           ("Học trò ngẫm nghĩ mãi, rồi hiểu: khi còn muốn vượt qua thầy, con mắt con vẫn dán vào thầy, không nhìn được con đường riêng của mình.",
            "The student pondered for a long time, then understood: when still wanting to surpass the teacher, his eyes are still fixed on the teacher, unable to see his own unique path."),
           ("Kẻ thù và đối thủ cũng vậy: khi bạn ngừng nhìn họ như đối thủ và bắt đầu nhìn họ như người dạy học --- lúc đó bạn thực sự đã vượt qua họ.",
            "Rivals and enemies are the same: when you stop viewing them as opponents and begin viewing them as teachers --- that is when you have truly surpassed them.")],
          "Bạn chưa thực sự vượt qua kẻ thù khi bạn đánh bại họ; bạn vượt qua họ thực sự khi bạn không còn cần định nghĩa mình bằng cách so sánh với họ.",
          "You have not truly surpassed your enemy when you defeat them; you truly surpass them when you no longer need to define yourself by comparing with them."),

    story("Thái Cực Quyền Và Nghệ Thuật Dùng Sức Kẻ Thù", "Thái Cực Quyền --- Trung Hoa",
          "Thái",
          [("Thái Cực Quyền là một nghệ thuật võ thuật Trung Hoa với nguyên lý độc đáo: không chống lại sức kẻ thù bằng sức của mình.",
            "Tai Chi is a Chinese martial art with a unique principle: do not oppose the enemy's force with your own force."),
           ("Thay vào đó, người luyện Thái Cực Quyền nhận lấy sức mạnh của đòn tấn công, dẫn hướng nó, và dùng chính sức đó để phản đòn.",
            "Instead, the Tai Chi practitioner receives the force of the attack, redirects it, and uses that very force to counter."),
           ("Kẻ tấn công càng mạnh, đòn phản của người luyện Thái Cực Quyền càng mạnh.",
            "The stronger the attacker, the stronger the counterattack of the Tai Chi practitioner."),
           ("Nguyên lý này mang một triết lý sâu xa: người thực sự mạnh không cần dùng sức riêng của mình --- họ biết cách dùng sức của đối phương.",
            "This principle carries a profound philosophy: the truly strong do not need to use their own force --- they know how to use the opponent's force."),
           ("Trong cuộc sống, kẻ thù và chướng ngại vật tạo ra sức ép --- người khôn ngoan học cách dùng chính sức ép đó để tiến lên.",
            "In life, enemies and obstacles create pressure --- the wise learn to use that very pressure to advance.")],
          "Thay vì chống lại mọi thứ kẻ thù và hoàn cảnh tạo ra, hãy học cách chuyển hóa những lực đó thành năng lượng để tiến về phía trước.",
          "Instead of resisting everything enemies and circumstances create, learn to transform those forces into energy to move forward."),

    story("Bức Thư Cảm Ơn Kẻ Thù", "Triết lý Marcus Aurelius",
          "Hoàng",
          [("Hoàng đế Marcus Aurelius viết trong nhật ký: 'Bắt đầu mỗi ngày bằng cách tự nói với mình: Hôm nay tôi sẽ gặp những kẻ tò mò, vô ơn, kiêu ngạo, phản bội, ganh ghét và bất hòa.'",
            "Emperor Marcus Aurelius wrote in his diary: 'Begin each day by saying to yourself: Today I will meet people who are meddlesome, ungrateful, arrogant, deceitful, envious and unsociable.'"),
           ("Ông viết tiếp: 'Nhưng tôi đã học được rằng thiện và ác chỉ tồn tại trong hành động, không trong con người; và rằng người làm sai với tôi là người đồng loại đang hành động từ vô minh.'",
            "He continued: 'But I have learned that good and evil reside only in actions, not in persons; and that those who wrong me are fellow humans acting from ignorance.'"),
           ("Thay vì tức giận với những người khó chịu trong cuộc sống, Aurelius nhìn họ như những bài luyện tập cho sự kiên nhẫn và lòng từ bi.",
            "Instead of being angry at difficult people in life, Aurelius viewed them as exercises in patience and compassion."),
           ("Mỗi 'kẻ thù' hàng ngày là cơ hội để thực hành triết lý của mình trong thực tế, không phải trong sách vở.",
            "Every daily 'enemy' is an opportunity to practice his philosophy in reality, not in books."),
           ("Ông không yêu kẻ khó chịu --- ông dùng họ như phòng gym cho tâm hồn.",
            "He did not love difficult people --- he used them as a gym for the soul.")],
          "Những người khó chịu và đối nghịch trong cuộc sống không phải là tai nạn phiền phức; họ là những người thầy về sự kiên nhẫn, lòng từ bi và phẩm giá của bạn.",
          "Difficult and adversarial people in life are not annoying accidents; they are teachers of your patience, compassion and dignity."),
    ]
)

# ================================================================
# CHƯƠNG 11: TRẺ EM DẠY GÌ
# ================================================================
ch11 = chapter(
    "Trẻ Em Dạy Gì",
    "What Children Teach Us",
    "Để vào được vương quốc thiên đàng, các anh phải trở nên như trẻ thơ.",
    "Unless you become like children, you will not enter the kingdom.",
    [
    story("Đứa Trẻ Hỏi 'Tại Sao' Và Nhà Vật Lý", "Richard Feynman --- Hoa Kỳ",
          "Richard",
          [("Richard Feynman, nhà vật lý đoạt Nobel, nổi tiếng với khả năng giải thích những khái niệm phức tạp nhất bằng ngôn ngữ đơn giản nhất.",
            "Richard Feynman, Nobel Prize-winning physicist, was famous for his ability to explain the most complex concepts in the simplest language."),
           ("Ông nói bí quyết của ông đến từ thói quen đặt câu hỏi như một đứa trẻ: không bao giờ chấp nhận 'ai cũng biết như vậy' mà không hiểu tại sao.",
            "He said his secret came from the habit of asking questions like a child: never accepting 'everyone knows that' without understanding why."),
           ("Khi con trai ông nhỏ hỏi: 'Tại sao xe ô tô di chuyển khi ta quay chìa khóa?' --- Feynman không trả lời bằng kỹ thuật, ông cùng con ngồi xuống suy nghĩ từ đầu.",
            "When his young son asked: 'Why does the car move when you turn the key?' --- Feynman did not answer technically; he sat down with his son to think from the beginning."),
           ("Ông nói: 'Câu hỏi của trẻ em không ngây thơ; chúng chạm đúng vào những bí ẩn sâu sắc nhất mà người lớn đã ngừng hỏi vì nghĩ mình đã biết.'",
            "He said: 'Children's questions are not naive; they touch directly on the deepest mysteries that adults have stopped asking because they think they already know.'"),
           ("Feynman luôn giữ trong mình đứa trẻ không ngừng hỏi 'tại sao' --- và đó chính là nguồn gốc của sự thiên tài.",
            "Feynman always kept within himself the child who never stopped asking 'why' --- and that was the very source of his genius.")],
          "Câu hỏi đơn giản nhất của trẻ em thường chạm vào bí ẩn sâu sắc nhất; hãy giữ lại đứa trẻ tò mò đó bên trong bạn.",
          "A child's simplest question often touches the deepest mystery; keep that curious child alive within you."),

    story("Con Gái Và Bức Tranh Con Ngựa Tím", "Câu chuyện của Pablo Picasso",
          "Pablo",
          [("Pablo Picasso kể rằng khi ông còn nhỏ, ông vẽ con ngựa màu tím và mặt trăng màu xanh lá.",
            "Pablo Picasso recounted that when he was small, he painted horses purple and the moon green."),
           ("Giáo viên bảo ông rằng ngựa không tím, mặt trăng không xanh.",
            "His teacher told him horses are not purple and the moon is not green."),
           ("Ông nói: 'Nhưng tôi nhìn thấy như vậy.'",
            "He said: 'But I see them that way.'"),
           ("Nhiều năm sau, khi trở thành nghệ sĩ vĩ đại nhất thế kỷ 20, Picasso nói: 'Mọi đứa trẻ đều là nghệ sĩ. Vấn đề là làm thế nào để vẫn là nghệ sĩ khi lớn lên.'",
            "Years later, when he became the greatest artist of the 20th century, Picasso said: 'Every child is an artist. The problem is how to remain an artist once grown up.'"),
           ("Chúng ta sinh ra với khả năng nhìn thế giới không bị giới hạn bởi 'đúng' hay 'sai'; giáo dục dần dần cắt bỏ điều đó --- và nghệ thuật là nỗ lực lấy lại.",
            "We are born with the ability to see the world unconstrained by 'right' or 'wrong'; education gradually removes that --- and art is the effort to reclaim it.")],
          "Sự sáng tạo không phải là thứ bạn phải học thêm sau khi lớn lên; đó là thứ bạn phải ngừng để bị lấy đi.",
          "Creativity is not something you must learn more as you grow up; it is something you must stop allowing to be taken from you."),

    story("Đứa Bé Tha Thứ Không Cần Suy Nghĩ", "Câu chuyện tâm lý học phát triển",
          "Các",
          [("Các nhà tâm lý học quan sát thấy rằng hai đứa trẻ nhỏ có thể cãi nhau kịch liệt --- khóc, la hét --- rồi chỉ năm phút sau chơi vui vẻ bên nhau như không có chuyện gì.",
            "Psychologists observed that two small children can argue fiercely --- crying, shouting --- then just five minutes later play happily together as if nothing happened."),
           ("Người lớn có thể giữ mối thù nhiều năm từ một hiểu lầm nhỏ.",
            "Adults can hold grudges for years from a small misunderstanding."),
           ("Trẻ em không tha thứ vì chúng 'học được đức tính tha thứ' --- chúng tha thứ vì chúng chưa học cách giữ sự tức giận.",
            "Children do not forgive because they 'learned the virtue of forgiveness' --- they forgive because they have not yet learned how to hold anger."),
           ("Điều chúng ta gọi là 'học tha thứ' thực ra là học lại điều chúng ta đã biết khi còn nhỏ nhưng đã bị lập trình ra khỏi chúng ta.",
            "What we call 'learning to forgive' is actually relearning what we already knew as children but had been programmed out of us."),
           ("Trẻ em không nhớ thù; đó là khả năng thiên bẩm đáng học lại.",
            "Children do not hold grudges; that is an innate capacity worth relearning.")],
          "Tha thứ không phải là đức hạnh cao cả khó đạt được; đó là trạng thái tự nhiên mà chúng ta đã có sẵn trước khi học cách giữ hận thù.",
          "Forgiveness is not a lofty virtue hard to achieve; it is the natural state we already had before we learned to hold grudges."),

    story("Đứa Trẻ Và Người Lạ Trên Ghế Đá", "Quan sát xã hội học",
          "Trong",
          [("Trong một thí nghiệm xã hội học, người ta quan sát cách trẻ nhỏ và người lớn phản ứng với người lạ ngồi trên ghế đá công viên.",
            "In a sociology experiment, researchers observed how small children and adults react to strangers sitting on a park bench."),
           ("Trẻ nhỏ chạy đến, hỏi: 'Tên bạn là gì? Bạn có muốn chơi không?' Không hỏi tuổi tác, địa vị, chủng tộc.",
            "Small children ran over, asking: 'What is your name? Do you want to play?' No asking about age, status or race."),
           ("Người lớn nhìn người lạ, đánh giá vẻ bề ngoài, suy tính xem người đó có 'đáng' không --- và thường bỏ đi.",
            "Adults looked at the stranger, assessed their appearance, calculated whether the person was 'worthwhile' --- and usually walked away."),
           ("Trẻ em chưa học được sự phân biệt xã hội; chúng nhìn người khác với con mắt thuần khiết nhất.",
            "Children have not yet learned social discrimination; they see others with the purest eyes."),
           ("Bài học: chúng ta là những tạo vật yêu thương và kết nối khi sinh ra; sự xa cách, nghi kỵ là thứ chúng ta học về sau.",
            "The lesson: we are creatures of love and connection when born; distance and suspicion are things we learn later.")],
          "Mỗi người lạ từng là bạn bè của một đứa trẻ chưa gặp mặt; hãy nhớ lại cách nhìn người đó.",
          "Every stranger has been a friend to a child not yet met; remember how to look at people that way."),

    story("Cách Trẻ Em Học Đi Và Nghệ Thuật Thử Lại", "Nghiên cứu phát triển trẻ em",
          "Theo",
          [("Theo các nhà nghiên cứu, một đứa trẻ học đi ngã trung bình 17 lần mỗi giờ trong những ngày đầu tập đi.",
            "According to researchers, a child learning to walk falls an average of 17 times per hour in the first days of learning."),
           ("Tổng số lần ngã trước khi đi vững: khoảng 2.000 lần.",
            "Total falls before walking steadily: approximately 2,000 times."),
           ("Không có đứa trẻ nào ngã lần thứ nhất rồi quyết định: 'Đi thẳng không phải dành cho ta. Ta sẽ bò suốt đời.'",
            "No child falls for the first time and decides: 'Walking upright is not for me. I will crawl forever.'"),
           ("Chúng ngã, khóc đôi khi, rồi đứng dậy tiếp tục ngay --- không mang theo nỗi sợ thất bại.",
            "They fall, sometimes cry, then immediately get up and continue --- carrying no fear of failure."),
           ("Đây là trạng thái học tập tinh khiết nhất: không biết xấu hổ, không sợ thất bại, không lo người khác nghĩ gì.",
            "This is the purest learning state: no shame, no fear of failure, no worry about what others think.")],
          "Đứa trẻ học đi không hỏi 'Nếu ta ngã thì sao?' --- chúng chỉ đứng dậy và thử lại. Hãy học lại cách học của trẻ con.",
          "A child learning to walk does not ask 'What if I fall?' --- they simply stand up and try again. Relearn how children learn."),

    story("Câu Hỏi Của Đứa Trẻ Về Cái Chết", "Leo Tolstoy --- Nga",
          "Leo",
          [("Leo Tolstoy kể rằng khi con trai nhỏ của ông hỏi: 'Tại sao người ta phải chết?' --- ông không có câu trả lời thỏa đáng.",
            "Leo Tolstoy recounted that when his young son asked: 'Why do people have to die?' --- he had no satisfying answer."),
           ("Nhưng câu hỏi đó ám ảnh Tolstoy suốt nhiều năm, dẫn ông đến cuộc tìm kiếm triết học và tâm linh sâu sắc nhất của mình.",
            "But that question haunted Tolstoy for years, leading him to his deepest philosophical and spiritual search."),
           ("Kết quả là ông viết 'Cái Chết Của Ivan Ilyich' --- một trong những tác phẩm suy ngẫm sâu sắc nhất về ý nghĩa cuộc sống.",
            "The result was he wrote 'The Death of Ivan Ilyich' --- one of the most profound meditations on the meaning of life."),
           ("Đứa trẻ không hỏi để nịnh người lớn hay để được điểm cao --- chúng hỏi vì họ thực sự muốn biết.",
            "Children do not ask to flatter adults or earn high marks --- they ask because they genuinely want to know."),
           ("Đó là sự chân thành trí tuệ thuần khiết nhất mà người lớn có thể học lại.",
            "That is the purest intellectual honesty that adults can relearn.")],
          "Câu hỏi chân thành của đứa trẻ thường chạm đúng vào những câu hỏi triết lý sâu sắc nhất mà người lớn đã học cách tránh.",
          "A child's sincere question often hits exactly the deepest philosophical questions that adults have learned to avoid."),

    story("Đứa Trẻ Và Người Ốm Trong Bệnh Viện", "Câu chuyện về lòng từ bi bẩm sinh",
          "Tại",
          [("Tại một bệnh viện nhi, các nhà nghiên cứu quan sát thấy rằng trẻ em từ 14 đến 18 tháng tuổi đã biểu hiện sự đồng cảm.",
            "At a children's hospital, researchers observed that infants from 14 to 18 months of age already showed signs of empathy."),
           ("Khi thấy người khác khóc hoặc biểu hiện đau đớn, chúng bò đến, chạm vào, thậm chí tặng đồ chơi yêu thích của mình.",
            "When seeing others cry or show pain, they crawled over, touched, even offered their favorite toys."),
           ("Những đứa trẻ chưa được dạy về từ bi hay sẻ chia --- chúng làm điều đó tự nhiên.",
            "These children had not been taught about compassion or sharing --- they did it naturally."),
           ("Kết luận: lòng từ bi không phải là thứ cần được dạy; đó là bản năng nguyên thủy của con người bị che lấp dần bởi sự cứng rắn có điều kiện.",
            "Conclusion: compassion is not something that needs to be taught; it is the primal instinct of humans gradually covered over by conditioned hardness."),
           ("Trẻ em nhắc nhở chúng ta rằng tử tế là trạng thái tự nhiên của nhân loại, không phải sự ngoại lệ hiếm có.",
            "Children remind us that kindness is humanity's natural state, not a rare exception.")],
          "Lòng nhân từ không cần được trao giải hay được khen ngợi để tồn tại --- ở đứa bé 14 tháng tuổi, nó chỉ đơn giản là.",
          "Kindness does not need to be rewarded or praised to exist --- in a 14-month-old, it simply is."),

    story("Đứa Trẻ Và Chiếc Hộp Bao Bì", "Quan sát về sự sáng tạo thuần khiết",
          "Nhiều",
          [("Nhiều bậc cha mẹ đã trải nghiệm cảnh này: mua đồ chơi đắt tiền cho con, đứa trẻ chơi với chiếc hộp bao bì nhiều hơn với món đồ chơi.",
            "Many parents have experienced this scene: buying expensive toys for their child, the child plays with the packaging box more than the toy itself."),
           ("Chiếc hộp có thể là tàu vũ trụ, lâu đài, hang động, tàu hải tặc --- tất cả phụ thuộc vào trí tưởng tượng của đứa trẻ.",
            "The box can be a spaceship, a castle, a cave, a pirate ship --- everything depending on the child's imagination."),
           ("Đứa trẻ không bị giới hạn bởi 'chức năng chính thức' của đồ vật.",
            "The child is not limited by the 'official function' of the object."),
           ("Người lớn nhìn chiếc hộp và chỉ thấy chiếc hộp vì họ đã học cách phân loại thế giới vào những danh mục cố định.",
            "Adults look at the box and only see a box because they have learned to categorize the world into fixed categories."),
           ("Sự sáng tạo thực sự là khả năng nhìn mọi thứ ngoài chức năng được chỉ định của chúng --- và mỗi đứa trẻ đều có khả năng đó.",
            "True creativity is the ability to see things beyond their assigned function --- and every child has that ability.")],
          "Sáng tạo không cần nguyên liệu đắt tiền hay công cụ đặc biệt --- nó chỉ cần cái nhìn không bị lập trình của một đứa trẻ.",
          "Creativity does not need expensive materials or special tools --- it only needs the unprogrammed gaze of a child."),

    story("Trẻ Em Và Bài Học Về Khoảnh Khắc Hiện Tại", "Nghiên cứu tâm lý học sự chú ý",
          "Khi",
          [("Khi một đứa trẻ nhỏ ngắm một con kiến, chúng có thể ngồi đó hàng mười lăm phút, hoàn toàn bị cuốn hút.",
            "When a small child watches an ant, they can sit there for fifteen minutes, completely absorbed."),
           ("Chúng không nghĩ về những gì xảy ra hôm qua hay lo lắng về ngày mai --- chúng hoàn toàn ở trong khoảnh khắc đó.",
            "They do not think about what happened yesterday or worry about tomorrow --- they are fully in that moment."),
           ("Nhà thiền học Jon Kabat-Zinn gọi đây là 'chánh niệm' và dạy người lớn học lại khả năng này trong nhiều tuần.",
            "Meditation teacher Jon Kabat-Zinn calls this 'mindfulness' and teaches adults to relearn this capacity over weeks."),
           ("Đứa trẻ không cần một khóa học thiền nào --- chúng sống trong trạng thái đó một cách tự nhiên.",
            "Children need no meditation course --- they live in that state naturally."),
           ("Hạnh phúc của trẻ em không đến từ việc có nhiều thứ; nó đến từ sự hiện diện hoàn toàn trong khoảnh khắc chúng đang sống.",
            "Children's happiness does not come from having many things; it comes from being fully present in the moment they are living.")],
          "Hạnh phúc không phải là điểm đến tương lai --- nó là cái nhìn hoàn toàn tập trung vào khoảnh khắc này, điều mà mỗi đứa trẻ bình thường đều thực hành một cách tự nhiên.",
          "Happiness is not a future destination --- it is the gaze fully focused on this moment, something every ordinary child practices naturally."),

    story("Đứa Trẻ Không Biết Không Thể", "Câu chuyện về niềm tin không giới hạn",
          "Người",
          [("Người ta kể rằng khi Thomas Edison còn nhỏ, giáo viên cho rằng ông quá ngốc để học.",
            "It is told that when Thomas Edison was young, his teacher thought him too slow to learn."),
           ("Nhưng người mẹ của Edison không nói với ông là ông không thể học; bà nói với ông rằng ông đặc biệt và trường học không đủ tốt cho ông.",
            "But Edison's mother did not tell him he could not learn; she told him he was special and the school was not good enough for him."),
           ("Edison lớn lên với niềm tin không gì là không thể học được --- và ông thực sự học mọi thứ ông muốn.",
            "Edison grew up with the belief that nothing was too difficult to learn --- and he truly learned everything he wanted."),
           ("Trẻ em tin vào bản thân theo cách tự nhiên cho đến khi ai đó dạy chúng giới hạn của mình.",
            "Children believe in themselves naturally until someone teaches them their limitations."),
           ("Câu hỏi quan trọng nhất với người lớn không phải là 'Tôi có thể làm được không?' mà là 'Ai đã dạy tôi rằng tôi không thể?'",
            "The most important question for adults is not 'Can I do it?' but 'Who taught me that I cannot?'")],
          "Giới hạn của bạn thường không thuộc về bạn --- chúng là những lời nói ai đó đã trồng vào tâm trí bạn từ khi còn nhỏ. Bạn có quyền nhổ chúng ra.",
          "Your limitations are often not originally yours --- they are words someone planted in your mind when you were small. You have the right to uproot them."),
    ]
)

# ================================================================
# CHƯƠNG 12: THẤT BẠI DẠY GÌ
# ================================================================
ch12 = chapter(
    "Thất Bại Dạy Gì",
    "What Failure Teaches",
    "Thất bại chỉ là cơ hội để bắt đầu lại thông minh hơn.",
    "Failure is only the opportunity to begin again more intelligently.",
    [
    story("Thomas Edison Và 10.000 Thí Nghiệm", "Thomas Edison --- Hoa Kỳ, thế kỷ 19",
          "Thomas",
          [("Thomas Edison thử nghiệm hơn 10.000 loại vật liệu khác nhau trước khi tìm ra dây tóc bóng đèn phù hợp.",
            "Thomas Edison tested over 10,000 different materials before finding the right filament for the lightbulb."),
           ("Người trợ lý của ông một lần hỏi: 'Thưa ông, chúng ta đã thất bại 10.000 lần rồi, có nên bỏ cuộc không?'",
            "His assistant once asked: 'Sir, we have failed 10,000 times, should we give up?'"),
           ("Edison trả lời: 'Bỏ cuộc? Chúng ta chưa bao giờ thất bại cả. Chúng ta đã thành công tìm ra 10.000 cách không hiệu quả.'",
            "Edison replied: 'Give up? We have never failed at all. We have successfully found 10,000 ways that do not work.'"),
           ("Định nghĩa lại thất bại không phải là tự lừa dối --- đó là cách nhìn trung thực và khoa học nhất về quá trình học hỏi.",
            "Redefining failure is not self-deception --- it is the most honest and scientific way of viewing the learning process."),
           ("Mỗi thí nghiệm thất bại cho Edison biết chính xác một điều không cần thử nữa, và hướng ông sang điều khác.",
            "Each failed experiment told Edison exactly one thing not to try again, and directed him toward something else.")],
          "Thất bại không phải là phản đề của thành công; nó là một phần cấu thành của thành công --- phần mà hầu hết mọi người không muốn thừa nhận.",
          "Failure is not the opposite of success; it is a constituent part of success --- the part most people do not want to acknowledge."),

    story("Michael Jordan Bị Loại Khỏi Đội Bóng Trường", "Michael Jordan --- Hoa Kỳ",
          "Khi",
          [("Khi còn học trung học, Michael Jordan bị loại khỏi đội bóng rổ của trường vì 'không đủ tài năng'.",
            "When in high school, Michael Jordan was cut from his school's basketball team for being 'not talented enough.'"),
           ("Ông về nhà và khóc trong phòng một mình.",
            "He went home and cried alone in his room."),
           ("Nhưng ngay ngày hôm sau, ông ra sân và bắt đầu tập luyện cường độ cao hơn bao giờ hết.",
            "But the very next day, he went to the court and began training with greater intensity than ever before."),
           ("Ông nói sau này: 'Tôi đã thất bại lặp đi lặp lại trong sự nghiệp của mình. Đó là lý do tôi thành công.'",
            "He said later: 'I have missed more than 9,000 shots, lost almost 300 games, and been trusted to take the game-winning shot 26 times and missed. That is why I succeed.'"),
           ("Cú loại ở trường trung học không định nghĩa Jordan --- nó định hướng ông đến mức nỗ lực mà sau đó đã tạo nên huyền thoại.",
            "The high school cut did not define Jordan --- it directed him to the level of effort that later created the legend.")],
          "Thất bại nhỏ sớm không phải là dấu hiệu của tương lai; nó là nhiên liệu cho những ai biết cách đốt cháy nó.",
          "Early small failure is not a sign of the future; it is fuel for those who know how to burn it."),

    story("J.K. Rowling Và 12 Lần Từ Chối", "J.K. Rowling --- Anh, 1990s",
          "Trước",
          [("Trước khi Harry Potter được xuất bản, J.K. Rowling gửi bản thảo đến 12 nhà xuất bản lớn khác nhau.",
            "Before Harry Potter was published, J.K. Rowling sent her manuscript to 12 different major publishers."),
           ("12 lần từ chối. 12 lần được nói là không đủ tốt.",
            "12 rejections. 12 times told it was not good enough."),
           ("Ở thời điểm đó, Rowling là bà mẹ đơn thân sống bằng trợ cấp xã hội, viết trong tiệm cà phê trong khi con gái ngủ.",
            "At that point, Rowling was a single mother living on welfare, writing in a cafe while her daughter slept."),
           ("Nhà xuất bản thứ 13 --- Bloomsbury --- chấp nhận vì con gái 8 tuổi của biên tập viên đọc và không chịu đặt sách xuống.",
            "The 13th publisher --- Bloomsbury --- accepted because the editor's 8-year-old daughter read it and refused to put it down."),
           ("Harry Potter trở thành bộ sách bán chạy nhất mọi thời đại với hơn 500 triệu bản in.",
            "Harry Potter became the best-selling book series of all time with over 500 million copies printed.")],
          "12 cánh cửa bị đóng không có nghĩa là không có cửa nào mở; đôi khi bạn chỉ chưa gõ đúng cánh cửa.",
          "12 closed doors does not mean no door will open; sometimes you simply have not yet knocked on the right door."),

    story("Abraham Lincoln Và Chuỗi Thất Bại Kéo Dài 30 Năm", "Abraham Lincoln --- Hoa Kỳ",
          "Năm",
          [("Năm 1831: Lincoln thất bại trong kinh doanh. Năm 1832: thất bại khi tranh cử nghị viện bang.",
            "1831: Lincoln failed in business. 1832: failed in the state legislature election."),
           ("Năm 1833: thất bại kinh doanh lần nữa. 1835: người yêu mất. 1836: suy sụp thần kinh. 1843, 1848, 1855, 1856, 1858: thất bại trong các cuộc bầu cử khác nhau.",
            "1833: failed in business again. 1835: lost his sweetheart. 1836: nervous breakdown. 1843, 1848, 1855, 1856, 1858: failed in various elections."),
           ("Năm 1860, Abraham Lincoln trở thành Tổng thống thứ 16 của Hoa Kỳ và được lịch sử ghi nhận là một trong những Tổng thống vĩ đại nhất mọi thời đại.",
            "In 1860, Abraham Lincoln became the 16th President of the United States and is remembered in history as one of the greatest Presidents of all time."),
           ("Nhìn lại danh sách thất bại đó, không ai có thể nói rằng ông không xứng đáng với thành công cuối cùng.",
            "Looking back at that list of failures, no one can say he did not deserve his ultimate success."),
           ("Thất bại không bao giờ là kết luận cuối cùng; nó chỉ là chương tiếp theo đang được viết.",
            "Failure is never the final conclusion; it is only the next chapter being written.")],
          "Danh sách thất bại của bạn không nói lên điều gì về tương lai của bạn; nó chỉ nói lên rằng bạn vẫn đang cố gắng.",
          "Your list of failures says nothing about your future; it only says you are still trying."),

    story("Cô Gái Học Đàn Và Buổi Biểu Diễn Thảm Họa", "Câu chuyện nghệ thuật biểu diễn",
          "Một",
          [("Một cô gái học piano hồi hộp biểu diễn lần đầu trước khán giả và mắc nhiều lỗi nghiêm trọng --- quên bài giữa chừng, đánh sai nhiều nốt, và ngồi cứng đờ.",
            "A girl learning piano nervously performed for the first time before an audience and made serious mistakes --- forgetting the piece mid-way, playing many wrong notes, and sitting frozen."),
           ("Sau buổi diễn, cô chạy ra ngoài khóc vì xấu hổ.",
            "After the performance, she ran outside and cried in shame."),
           ("Người thầy đến gặp và nói: 'Em đã học được hôm nay thứ mà không có lớp học nào dạy được: cảm giác như thế nào khi biểu diễn trước khán giả thật.'",
            "The teacher came to her and said: 'You learned today something no classroom can teach: what it feels like to perform before a real audience.'"),
           ("'Bây giờ em đã biết cảm giác đó, em có thể bắt đầu luyện tập để vượt qua nó.'",
            "'Now that you know that feeling, you can begin practicing to overcome it.'"),
           ("Năm năm sau, cô đoạt giải nhất trong cuộc thi piano quốc tế --- và luôn nhớ đến buổi biểu diễn thảm họa đầu tiên với lòng biết ơn.",
            "Five years later, she won first place in an international piano competition --- and always remembered her first disastrous performance with gratitude.")],
          "Buổi biểu diễn tệ nhất của bạn có thể là người thầy tốt nhất của bạn --- nếu bạn không để nỗi xấu hổ che khuất bài học.",
          "Your worst performance may be your best teacher --- if you do not let shame obscure the lesson."),

    story("Kỹ Sư Dyson Và 5.127 Nguyên Mẫu", "James Dyson --- Anh, 1979-1984",
          "James",
          [("James Dyson dành 5 năm và 5.127 lần thử nghiệm thất bại để phát triển máy hút bụi không túi đầu tiên trên thế giới.",
            "James Dyson spent 5 years and 5,127 failed prototypes developing the world's first bagless vacuum cleaner."),
           ("Trong suốt thời gian đó, vợ ông làm giáo viên để nuôi gia đình trong khi ông dốc toàn bộ tiền tiết kiệm vào các thử nghiệm.",
            "Throughout that time, his wife worked as a teacher to support the family while he poured all their savings into experiments."),
           ("Ông nói sau này: 'Mỗi lần thất bại là một bước tiến, vì ít nhất tôi biết thứ đó không hoạt động.'",
            "He said later: 'Each failure was a step forward, because at least I knew that thing did not work.'"),
           ("Khi ra mắt, máy hút bụi Dyson trở thành sản phẩm bán chạy nhất nước Anh trong vòng 18 tháng.",
            "Upon launch, the Dyson vacuum cleaner became the best-selling product in Britain within 18 months."),
           ("Công ty Dyson ngày nay có giá trị hàng chục tỷ đô la --- được xây dựng trên 5.127 lần thất bại.",
            "The Dyson company today is worth tens of billions of dollars --- built on 5,127 failures.")],
          "Số lần thất bại không phải là dấu hiệu của người không thành công; đó là bằng chứng về người đủ kiên trì để tìm được câu trả lời đúng.",
          "The number of failures is not a sign of someone who will not succeed; it is evidence of someone persistent enough to find the right answer."),

    story("Người Thợ Làm Đồ Gốm Và Thất Bại Theo Kế Hoạch", "Nghiên cứu sáng tạo --- Đại học Berkeley",
          "Trong",
          [("Trong một nghiên cứu nổi tiếng tại Đại học Berkeley, giáo sư chia lớp học làm gốm thành hai nhóm.",
            "In a famous study at Berkeley, a professor divided a pottery class into two groups."),
           ("Nhóm đầu được chấm điểm dựa trên số lượng: làm càng nhiều sản phẩm càng tốt điểm cao.",
            "The first group was graded on quantity: the more products made, the higher the grade."),
           ("Nhóm hai được chấm dựa trên chất lượng: chỉ cần nộp một sản phẩm tốt nhất.",
            "The second group was graded on quality: just submit one best product."),
           ("Cuối kỳ, những sản phẩm chất lượng tốt nhất đến từ... nhóm số lượng.",
            "At the end of the semester, the best quality products came from... the quantity group."),
           ("Lý do: nhóm số lượng đã học được qua hàng trăm lần thất bại; nhóm chất lượng ngồi lý thuyết hóa về sự hoàn hảo mà không dám thực hành.",
            "The reason: the quantity group had learned through hundreds of failures; the quality group sat theorizing about perfection without daring to practice.")],
          "Muốn giỏi, hãy sản xuất nhiều --- và học hỏi từ mỗi thất bại trong quá trình đó. Hoàn hảo là kẻ thù của hoàn thành.",
          "To become good, produce a lot --- and learn from each failure in the process. Perfection is the enemy of completion."),

    story("Bạch Tuộc Và Nghệ Thuật Thoát Ra", "Khoa học về khả năng thích nghi",
          "Bạch",
          [("Bạch tuộc là một trong những sinh vật thông minh nhất đại dương dù não bộ của chúng rất khác với não bộ của động vật có xương sống.",
            "Octopuses are among the most intelligent creatures in the ocean despite their brains being very different from vertebrate brains."),
           ("Trong thí nghiệm khoa học, bạch tuộc được đặt trong bình kín có nắp vặn bên trong chứa cua --- thức ăn của chúng.",
            "In scientific experiments, octopuses were placed in sealed jars with screw-on lids, with crabs inside --- their food."),
           ("Không có ai dạy chúng cách mở nắp; mỗi con tự mày mò và thường thất bại nhiều lần trước khi tìm ra cách.",
            "No one taught them how to open the lid; each one figured it out and usually failed many times before finding the way."),
           ("Nhưng sau khi học được, chúng nhớ mãi và áp dụng vào những tình huống tương tự.",
            "But once they learned, they remembered forever and applied it to similar situations."),
           ("Và điều kỳ diệu hơn: bạch tuộc quan sát được lẫn nhau và học hỏi từ sự thất bại của nhau.",
            "And even more remarkably: octopuses can observe each other and learn from each other's failures.")],
          "Học từ thất bại của chính mình là khôn ngoan; học từ thất bại của người khác là sự khôn ngoan hiệu quả gấp đôi.",
          "Learning from your own failures is wisdom; learning from others' failures is twice as efficient a wisdom."),

    story("Samuel Beckett Và Nghệ Thuật Thất Bại Tốt Hơn", "Samuel Beckett --- Ireland",
          "Samuel",
          [("Samuel Beckett, nhà viết kịch người Ireland đoạt Nobel Văn học, có một câu nói bất hủ mà ngày nay được treo trên tường văn phòng của hàng triệu người: 'Bao giờ thử. Bao giờ thất bại. Không sao. Thử lại. Thất bại lại. Thất bại tốt hơn.'",
            "Samuel Beckett, the Irish Nobel Prize-winning playwright, has an immortal saying now hung on the walls of millions of office and studios worldwide: 'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.'"),
           ("Ông không nói 'đừng thất bại' hay 'cố đừng thất bại' --- ông nói 'thất bại tốt hơn.'",
            "He did not say 'do not fail' or 'try not to fail' --- he said 'fail better.'"),
           ("Đây là chấp nhận triệt để nhất về thất bại: không phải vì thất bại là tốt, mà vì thất bại là không thể tránh, vậy hãy làm nó có giá trị.",
            "This is the most radical acceptance of failure: not because failure is good, but because failure is inevitable, so make it worthwhile."),
           ("Mỗi lần thất bại nên sâu sắc hơn, phong phú hơn, mang nhiều thông tin hơn lần trước.",
            "Each failure should be deeper, richer, more information-laden than the last."),
           ("Người thực sự học từ thất bại không chỉ tránh được thất bại cũ mà còn thất bại ở những tầng cao hơn --- gần hơn với cái đích.",
            "Those who truly learn from failure not only avoid old failures but fail at higher levels --- closer to the target.")],
          "Mục tiêu không phải là tránh thất bại; mục tiêu là thất bại ngày càng tốt hơn, ngày càng gần đích hơn.",
          "The goal is not to avoid failure; the goal is to fail better and better, ever closer to the target."),

    story("Nghệ Sĩ Tung Hứng Và Quy Tắc Ba Lần Thả", "Nghiên cứu về học hỏi qua lỗi lầm",
          "Có",
          [("Có một nghiên cứu về cách tốt nhất để học tung hứng ba quả bóng.",
            "There is a study on the best way to learn to juggle three balls."),
           ("Nhóm đầu được dạy đừng để bóng rơi --- họ phải giữ bóng không rơi bằng mọi giá.",
            "The first group was taught never to drop the balls --- they must keep the balls in the air at all costs."),
           ("Nhóm hai được dạy hãy để bóng rơi --- quan trọng là nhặt lên và tiếp tục.",
            "The second group was taught to let the balls drop --- what matters is picking them up and continuing."),
           ("Sau ba tháng, nhóm hai học tung hứng thành thạo nhanh hơn đáng kể.",
            "After three months, the second group learned juggling significantly faster."),
           ("Lý do: nhóm hai không sợ mất bóng nên dám thử những động tác khó hơn, tích lũy nhiều dữ liệu hơn về cách điều chỉnh.",
            "The reason: the second group was not afraid of dropping so dared to attempt harder moves, accumulating more data about how to adjust.")],
          "Nỗi sợ làm rơi bóng sẽ không bao giờ cho phép bạn học cách tung hứng giỏi; chỉ có sự sẵn sàng để bóng rơi mới dạy được bạn điều đó.",
          "Fear of dropping the ball will never allow you to learn to juggle well; only the willingness to let the ball drop can teach you that."),

    story("Mảnh Vỡ Và Kintsugi --- Nghệ Thuật Nhật Bản Vàng Hóa Vết Nứt", "Kintsugi --- Nhật Bản, thế kỷ 15",
          "Kintsugi",
          [("Kintsugi là nghệ thuật Nhật Bản vá những vật gốm vỡ bằng vàng hoặc bạc, tạo ra những đường nứt óng ánh thay vì che giấu chúng.",
            "Kintsugi is the Japanese art of repairing broken pottery with gold or silver, creating gleaming lines of fracture instead of hiding them."),
           ("Triết lý đằng sau: vật bị vỡ rồi được vá không phải là vật kém hơn bản gốc --- nó là vật có lịch sử phong phú hơn và có thể đẹp hơn.",
            "The philosophy behind it: an object broken and repaired is not lesser than the original --- it is an object with a richer history and may be more beautiful."),
           ("Những đường vàng không che giấu vết nứt mà tôn vinh nó: đây là nơi vật này đã từng vỡ và đã được chữa lành.",
            "The golden lines do not hide the cracks but honor them: this is where this object once broke and was healed."),
           ("Triết lý Kintsugi được áp dụng vào cuộc sống con người: những vết thương và thất bại không phải là vết nhục cần che giấu --- chúng là bằng chứng của sức chịu đựng và sự phuc hồi.",
            "Kintsugi philosophy applied to human life: wounds and failures are not shameful marks to hide --- they are evidence of endurance and recovery."),
           ("Người đã từng trải qua và phục hồi từ thất bại không kém hơn người chưa từng thất bại --- họ có thể sâu sắc và quý giá hơn.",
            "A person who has experienced and recovered from failure is not lesser than one who has never failed --- they may be deeper and more precious.")],
          "Vết nứt trong cuộc đời bạn không phải là điểm yếu cần che giấu; hãy trám chúng bằng vàng và để chúng trở thành phần đẹp nhất của câu chuyện bạn.",
          "The cracks in your life are not weaknesses to hide; fill them with gold and let them become the most beautiful part of your story."),
    ]
)

# ================================================================
# GHI FILE
# ================================================================
files = [
    ("ch09-thien-nhien-day-gi", ch9),
    ("ch10-ke-thu-day-gi", ch10),
    ("ch11-tre-em-day-gi", ch11),
    ("ch12-that-bai-day-gi", ch12),
]
for fname, content in files:
    path = os.path.join(BASE, f"{fname}.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{fname} done")
print("All chapters 9-12 generated successfully!")
