# -*- coding: utf-8 -*-
"""Quyển VI -- Vòng Quay Cuộc Đời -- Chapters 5-8"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-6/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    text = re.sub(r'(?<!\\)&', r'\\&', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 5: VAI DIỄN VÀ CON NGƯỜI THẬT
# ================================================================
ch5 = chapter(
    "Vai Diễn Và Con Người Thật",
    "The Role and the Real Self",
    "Thế giới là một sân khấu, và tất cả chúng ta chỉ là diễn viên.",
    "All the world's a stage, and all the men and women merely players.",
    [
    story("Vua Lear Và Kẻ Mất Tất Cả Để Tìm Lại Mình", "William Shakespeare --- Anh, 1606",
          "Vua",
          [("Vua Lear khi còn quyền lực tối cao đã nhầm lẫn rằng mình chính là ngai vàng, là quyền uy, là lãnh thổ rộng lớn.",
            "King Lear, when at the peak of his power, mistakenly believed that he was his throne, his authority, his vast territories."),
           ("Ông trao vương quốc cho hai đứa con gái nịnh hót, và khi không còn gì nữa, ông hiểu ra rằng mình thực sự không biết mình là ai.",
            "He gave his kingdom to two flattering daughters, and once he had nothing left, he understood that he truly did not know who he was."),
           ("Trong cơn mưa bão trên hoang mạc, stripped of everything, Lear lần đầu tiên đặt câu hỏi thực sự: 'Kẻ không có gì thực sự là ai?'",
            "In a rainstorm on the wasteland, stripped of everything, Lear asked the real question for the first time: 'Who truly is one who has nothing?'"),
           ("Bi kịch của ông là bài học cho mọi người: chúng ta thường nhầm lẫn vai trò xã hội với bản thể thực sự của mình.",
            "His tragedy is a lesson for everyone: we often confuse our social roles with our true essence."),
           ("Chỉ khi mất đi tất cả vai trò bên ngoài, con người thực sự mới có cơ hội xuất hiện.",
            "Only when all external roles are stripped away does the true person have a chance to emerge.")],
          "Đừng nhầm lẫn những gì bạn có và những gì bạn làm với chính bạn; những thứ đó có thể mất đi, nhưng con người thật bên trong thì không.",
          "Do not confuse what you have and what you do with who you are; those things can be lost, but the true person inside cannot."),

    story("Diễn Viên Marlon Brando Và Sự Khủng Hoảng Danh Tính", "Marlon Brando --- Hollywood",
          "Marlon",
          [("Marlon Brando, một trong những diễn viên vĩ đại nhất thế kỷ 20, đã nói một câu rất đáng suy nghĩ: 'Tôi đã đóng quá nhiều vai đến mức đôi khi tôi không còn biết vai diễn nào là tôi nữa.'",
            "Marlon Brando, one of the greatest actors of the 20th century, said something very thought-provoking: 'I have played so many roles that sometimes I no longer know which character is me.'"),
           ("Ông đã dùng nghệ thuật phương pháp diễn xuất (Method Acting) để hóa thân hoàn toàn vào nhân vật, đến mức ranh giới giữa Brando và vai diễn tan biến.",
            "He used Method Acting to completely embody characters, to the point where the boundary between Brando and the role dissolved."),
           ("Điều này giúp ông tạo ra những vai diễn bất tử, nhưng cũng để lại một cuộc sống cá nhân đầy hỗn loạn.",
            "This allowed him to create immortal performances, but also left him with a deeply chaotic personal life."),
           ("Câu chuyện của Brando là lời cảnh báo: khi bạn chơi quá nhiều vai, bạn có thể đánh mất diễn viên thực sự đứng sau tất cả những vai diễn đó.",
            "Brando's story is a warning: when you play too many roles, you may lose the real actor standing behind all those roles."),
           ("Bài học không chỉ dành cho diễn viên: trong cuộc sống thường ngày, chúng ta cũng thường xuyên đóng những vai trò xã hội đến mức quên mất con người thật của mình.",
            "The lesson is not only for actors: in daily life, we also often play social roles so thoroughly that we forget our true selves.")],
          "Bạn có thể đóng nhiều vai trong cuộc sống, nhưng hãy luôn nhớ rằng bạn là diễn viên, không phải nhân vật.",
          "You may play many roles in life, but always remember that you are the actor, not the character."),

    story("Hoàng Tử Siddhartha Từ Bỏ Vai Diễn Hoàng Gia", "Phật Giáo --- Ấn Độ, 500 TCN",
          "Siddhartha",
          [("Siddhartha Gautama sinh ra trong vai diễn sẵn có của một hoàng tử: áo lụa, cung điện, vợ đẹp, thần dân.",
            "Siddhartha Gautama was born into a ready-made role as a prince: silk robes, palaces, a beautiful wife, loyal subjects."),
           ("Cha ông đã lập kế hoạch toàn bộ cuộc đời cho ông từ trước khi ông được sinh ra.",
            "His father had planned his entire life before he was even born."),
           ("Nhưng khi lần đầu nhìn thấy người già, người bệnh, người chết và một tu sĩ ăn mày, Siddhartha bắt đầu nghi ngờ: 'Vai diễn này có phải là tôi không?'",
            "But when he first saw an old man, a sick man, a dead man, and a wandering monk, Siddhartha began to question: 'Is this role really me?'"),
           ("Ông từ bỏ tất cả để đi tìm câu trả lời cho câu hỏi: 'Tôi thực sự là ai ngoài những vai trò mà người khác đặt vào tôi?'",
            "He abandoned everything to seek the answer to the question: 'Who am I truly, beyond the roles others have placed upon me?'"),
           ("Hành trình đó dẫn ông đến giác ngộ và tạo ra một trong những triết học vĩ đại nhất trong lịch sử nhân loại.",
            "That journey led him to enlightenment and created one of the greatest philosophies in human history.")],
          "Đôi khi từ bỏ vai diễn được chuẩn bị sẵn cho bạn là hành động dũng cảm nhất và khởi đầu của hành trình trở thành con người thực sự của bạn.",
          "Sometimes abandoning the role prepared for you is the bravest act and the beginning of the journey to become your true self."),

    story("Người Thợ Giày Và Hề Của Vua", "Truyện ngụ ngôn Đông Âu",
          "Có",
          [("Có một người thợ giày nghèo nhưng luôn vui vẻ, hát ca suốt ngày trong xưởng làm việc nhỏ của mình.",
            "There was a poor cobbler who was always cheerful, singing all day long in his small workshop."),
           ("Nhà vua nghe tiếng và muốn mang lại hạnh phúc cho ông, nên ban cho ông một túi vàng lớn.",
            "The king heard this and wanted to bring him happiness, so he bestowed upon him a large bag of gold."),
           ("Ngay từ khi nhận vàng, người thợ giày bắt đầu lo lắng: phải giấu vàng ở đâu? Nếu bị trộm thì sao? Nếu cháy nhà thì sao?",
            "From the moment he received the gold, the cobbler began worrying: where to hide the gold? What if it were stolen? What if the house caught fire?"),
           ("Ông không còn hát được nữa, không ngủ được nữa, không làm việc được nữa.",
            "He could no longer sing, no longer sleep, no longer work."),
           ("Cuối cùng ông trả lại túi vàng cho nhà vua và nói: 'Thưa Bệ Hạ, ngài đã lấy đi tiếng hát của con. Con muốn lấy lại con người thật của con.'",
            "Finally he returned the bag of gold to the king and said: 'Your Majesty, you have taken my song away. I want to take back my true self.'")],
          "Của cải và địa vị có thể cho bạn một vai diễn mới, nhưng cũng có thể khiến bạn đánh mất bản thân đã từng vui sống.",
          "Wealth and status may give you a new role, but they can also cause you to lose the self that once lived joyfully."),

    story("Nhà Thơ Fernando Pessoa Và Những Cái Tôi Nhiều Mặt", "Fernando Pessoa --- Bồ Đào Nha, 1888-1935",
          "Nhà",
          [("Nhà thơ người Bồ Đào Nha Fernando Pessoa không viết dưới một cái tên duy nhất --- ông tạo ra hơn 70 'dị danh' (heteronyms), mỗi người là một nhân vật hoàn chỉnh với tiểu sử, phong cách thơ và triết lý riêng.",
            "Portuguese poet Fernando Pessoa did not write under a single name --- he created over 70 'heteronyms', each a complete character with their own biography, poetic style and philosophy."),
           ("Alberto Caeiro viết về thiên nhiên đơn giản; Ricardo Reis viết thơ cổ điển Latin; Álvaro de Campos viết thơ công nghiệp hiện đại.",
            "Alberto Caeiro wrote about simple nature; Ricardo Reis wrote classical Latin poetry; Álvaro de Campos wrote modern industrial verse."),
           ("Pessoa mô tả bản thân như 'một sân khấu trong đó nhiều diễn viên đang đóng những vai khác nhau.'",
            "Pessoa described himself as 'a stage on which different actors perform different roles.'"),
           ("Nhưng điều kỳ lạ là, bằng cách khám phá tất cả những con người khác nhau trong ông, Pessoa đã để lại một trong những di sản thơ ca phong phú và độc đáo nhất thế giới.",
            "But strangely, by exploring all the different people within him, Pessoa left behind one of the richest and most unique poetry heritages in the world."),
           ("Ông không sợ những 'cái tôi' đa dạng trong mình --- ông để chúng tự do sáng tạo.",
            "He did not fear the diverse 'selves' within him --- he let them freely create.")],
          "Bên trong mỗi người có nhiều hơn một con người; sự phong phú của bạn nằm ở chỗ bạn biết cách điều hành tất cả những phần đó một cách hài hòa.",
          "Inside each person there is more than one self; your richness lies in knowing how to orchestrate all those parts harmoniously."),

    story("Người Lính Trở Về Và Câu Hỏi 'Tôi Là Ai?'", "Câu chuyện thực tế --- Hoa Kỳ sau Chiến tranh Việt Nam",
          "Nhiều",
          [("Nhiều cựu chiến binh Mỹ trở về từ Chiến tranh Việt Nam đã đối mặt với một cuộc khủng hoảng danh tính sâu sắc.",
            "Many American veterans returning from the Vietnam War faced a profound identity crisis."),
           ("Suốt nhiều năm, họ được định nghĩa bởi một vai trò duy nhất: người lính. Mọi thứ --- cách suy nghĩ, hành động, cảm nhận --- đều được định hình bởi huấn luyện quân đội.",
            "For years, they were defined by a single role: the soldier. Everything --- how they thought, acted, felt --- was shaped by military training."),
           ("Khi về nhà, họ không còn biết mình là ai ngoài bộ quân phục.",
            "When they came home, they no longer knew who they were outside the uniform."),
           ("Một cựu chiến binh tên James đã nói: 'Tôi đã tốn 10 năm chiến đấu, và chỉ nhận ra rằng tôi không bao giờ được học cách làm một người bình thường.'",
            "A veteran named James said: 'I spent 10 years fighting, and only realized that I had never been taught how to be an ordinary person.'"),
           ("Hành trình phục hồi của ông là hành trình bóc từng lớp vai diễn ra để tìm lại con người thật bên dưới --- và nhận ra rằng không bao giờ là quá muộn.",
            "His recovery journey was one of peeling away each layer of role to rediscover the real person underneath --- and discovering it is never too late.")],
          "Khi một vai trò lớn kết thúc, đừng hỏi 'Tôi sẽ làm gì bây giờ?' --- hãy hỏi 'Bây giờ tôi có cơ hội trở thành ai?'",
          "When a big role ends, do not ask 'What will I do now?' --- ask 'Who do I have the opportunity to become now?'"),

    story("CEO Và Đứa Trẻ 8 Tuổi Bên Trong", "Câu chuyện tâm lý học tích hợp",
          "Một",
          [("Một CEO thành đạt của công ty công nghệ đến gặp nhà tâm lý học với triệu chứng trầm cảm nặng dù sự nghiệp đang đỉnh cao.",
            "A successful CEO of a technology company went to see a psychologist with severe depression symptoms despite being at the peak of his career."),
           ("Nhà tâm lý học hỏi: 'Nếu đứa trẻ 8 tuổi là bạn ngày xưa nhìn vào cuộc sống hiện tại của bạn, nó sẽ nói gì?'",
            "The psychologist asked: 'If the 8-year-old child you once were looked at your current life, what would it say?'"),
           ("Vị CEO im lặng rất lâu, rồi nói: 'Nó sẽ hỏi: tại sao anh không còn vẽ tranh nữa? Tại sao anh không còn chơi với bạn bè nữa? Tại sao anh không còn cười nhiều nữa?'",
            "The CEO was silent for a long time, then said: 'It would ask: why did you stop painting? Why did you stop playing with friends? Why did you stop laughing so much?'"),
           ("Ông nhận ra rằng bằng cách hoàn hảo hóa vai diễn CEO, ông đã chôn vùi con người thật của mình.",
            "He realized that by perfecting the role of CEO, he had buried his true self."),
           ("Ông bắt đầu vẽ tranh lại vào cuối tuần. Ba tháng sau, chứng trầm cảm của ông cải thiện đáng kể mà không cần thuốc.",
            "He started painting again on weekends. Three months later, his depression improved significantly without medication.")],
          "Con người thật của bạn chưa bao giờ biến mất; nó chỉ đang chờ bạn nhớ đến nó và cho nó không gian để thở.",
          "Your true self has never disappeared; it is only waiting for you to remember it and give it space to breathe."),

    story("Võ Sĩ Và Thiền Sư --- Buông Gươm Để Tìm Mình", "Truyện Thiền Nhật Bản",
          "Một",
          [("Một võ sĩ samurai nổi tiếng đến gặp thiền sư Hakuin với câu hỏi: 'Liệu tôi có thể là một samurai và đồng thời là một người tốt không?'",
            "A famous samurai warrior went to see Zen master Hakuin with the question: 'Can I be a samurai and simultaneously a good person?'"),
           ("Hakuin hỏi lại: 'Và khi ông không cầm gươm, ông là ai?'",
            "Hakuin asked in return: 'And when you are not holding a sword, who are you?'"),
           ("Samurai lúng túng. Ông chưa bao giờ nghĩ đến điều đó.",
            "The samurai was flustered. He had never thought about that."),
           ("Hakuin nói: 'Gươm là công cụ của ông, không phải là ông. Ông cần biết ai đang cầm gươm trước khi lo lắng về cách dùng nó.'",
            "Hakuin said: 'The sword is your tool, not you. You need to know who is holding the sword before worrying about how to use it.'"),
           ("Samurai về nhà, bỏ gươm xuống, ngồi thiền 100 ngày, và trở lại với câu trả lời: 'Tôi là một người có lòng trắc ẩn, và tôi dùng gươm để bảo vệ điều đó.'",
            "The samurai went home, set down his sword, meditated for 100 days, and returned with the answer: 'I am a person with compassion, and I use the sword to protect that.'")],
          "Biết mình là ai ngoài công cụ và vai trò của mình là nền tảng để dùng những công cụ và vai trò đó một cách minh triết.",
          "Knowing who you are beyond your tools and roles is the foundation for using those tools and roles wisely."),

    story("Diêm Vương Và Người Không Có Bóng", "Truyện cổ Trung Hoa",
          "Theo",
          [("Theo truyền thuyết Trung Hoa, khi một người chết và đến trước Diêm Vương, họ bị hỏi: 'Trong cuộc đời ngươi, ngươi đã thực sự sống bao nhiêu ngày?'",
            "According to Chinese legend, when a person dies and stands before the King of Hell, they are asked: 'In your life, how many days did you truly live?'"),
           ("Không phải tổng số ngày đã qua, mà là những ngày ngươi thực sự là chính mình, không đóng giả, không che giấu.",
            "Not the total days that passed, but the days you were truly yourself, not pretending, not hiding."),
           ("Nhiều người chết đi nhận ra họ đã sống hàng nghìn ngày nhưng thực sự chỉ là chính mình trong vài chục ngày.",
            "Many who died realized they had lived thousands of days but were truly themselves for only a few dozen days."),
           ("Diêm Vương nói: 'Số ngày ngươi thực sự sống mới là cuộc đời thực của ngươi; phần còn lại chỉ là diễn xuất.'",
            "The King of Hell said: 'The days you truly lived are your real life; the rest is only performance.'"),
           ("Câu hỏi dành cho người đang sống: ngày hôm nay, bạn có thực sự sống không?",
            "The question for the living: today, are you truly living?")],
          "Cuộc đời không đo bằng số năm qua đi, mà đo bằng số ngày bạn thực sự là chính mình.",
          "Life is not measured by the number of years that pass, but by the number of days you were truly yourself."),

    story("Người Hầu Trở Thành Triết Gia", "Epictetus và Zeno --- Hy Lạp cổ đại",
          "Trong",
          [("Trong triết học khắc kỷ, Zeno of Citium dạy rằng địa vị xã hội chỉ là một vai diễn tạm thời; bản chất thực sự của con người nằm ở đức hạnh bên trong.",
            "In Stoic philosophy, Zeno of Citium taught that social status is only a temporary role; the true essence of a person lies in their inner virtue."),
           ("Epictetus, người học trò vĩ đại nhất của ông, đã chứng minh điều này: sinh ra là nô lệ, bị tàn tật, nhưng vẫn trở thành triết gia được Hoàng đế kính phục.",
            "Epictetus, his greatest student, proved this: born a slave, rendered crippled, but still became a philosopher revered by emperors."),
           ("'Đừng bao giờ để bất kỳ ai 'sở hữu' bạn bằng cách khiến bạn tin rằng bạn là vai trò họ gán cho bạn,' Epictetus dạy.",
            "'Never let anyone own you by making you believe that you are the role they assign you,' Epictetus taught."),
           ("'Bạn luôn có thể chọn cách bạn phản ứng, và trong sự lựa chọn đó, bạn luôn tự do.'",
            "'You can always choose how you respond, and in that choice, you are always free.'"),
           ("Người nô lệ không bị xích bởi xiềng sắt mà bởi sự tin tưởng rằng mình là nô lệ; người tự do không được giải phóng bởi chứng từ mà bởi sự biết mình.",
            "A slave is chained not by iron chains but by the belief that they are a slave; a free person is liberated not by a document but by self-knowledge.")],
          "Vai trò xã hội được trao cho bạn bởi hoàn cảnh, nhưng con người thật là thứ bạn tự tạo ra bằng những lựa chọn hàng ngày.",
          "Social roles are given to you by circumstances, but your true person is what you create yourself through daily choices."),
    ]
)

# ================================================================
# CHƯƠNG 6: ÁP LỰC ĐÁM ĐÔNG VÀ TỰ NGÃ
# ================================================================
ch6 = chapter(
    "Áp Lực Đám Đông Và Tự Ngã",
    "Social Pressure and the True Self",
    "Hãy là chính mình; tất cả những vị trí khác đều đã có người.",
    "Be yourself; everyone else is already taken.",
    [
    story("Galileo Đứng Trước Hội Đồng Tôn Giáo", "Galileo Galilei --- Ý, 1633",
          "Năm",
          [("Năm 1633, Galileo Galilei bị Tòa án Dị Giáo La Mã xét xử vì dám tuyên bố rằng Trái Đất quay quanh Mặt Trời, thay vì ngược lại.",
            "In 1633, Galileo Galilei was tried by the Roman Inquisition for daring to declare that the Earth revolves around the Sun, rather than the reverse."),
           ("Hội đồng đại diện cho toàn bộ ý kiến chính thống của xã hội thời đó, của Giáo hội, của học thuật.",
            "The tribunal represented the entire orthodox opinion of society then, of the Church, of academia."),
           ("Dưới áp lực đó, Galileo đã chính thức tuyên bố rút lại lý thuyết của mình để thoát khỏi hình phạt.",
            "Under that pressure, Galileo officially declared he was retracting his theory to escape punishment."),
           ("Nhưng theo truyền thuyết, khi rời khỏi phòng xét xử, ông thì thầm: 'Dù vậy, nó vẫn chuyển động.'",
            "But according to legend, as he left the courtroom, he whispered: 'And yet it moves.'"),
           ("Sự thật không thay đổi chỉ vì đám đông không chấp nhận nó; và người biết sự thật không mất đi sự thật đó dù phải im lặng trước đám đông.",
            "Truth does not change simply because the crowd refuses to accept it; and those who know the truth do not lose it even if they must be silent before the crowd.")],
          "Đám đông có thể buộc bạn im lặng, nhưng không đám đông nào có thể buộc bạn thay đổi điều bạn biết là đúng bên trong.",
          "A crowd can force you into silence, but no crowd can force you to change what you know is true inside."),

    story("Hans Christian Andersen Và Câu Bé Thiếu Quần Áo Mới", "Andersen --- Đan Mạch, 1837",
          "Trong",
          [("Trong câu chuyện 'Bộ Quần Áo Mới Của Hoàng Đế', toàn bộ thần dân và triều thần đều khen ngợi bộ quần áo tuyệt vời của hoàng đế --- dù thực ra ông chẳng mặc gì cả.",
            "In the story 'The Emperor's New Clothes', all subjects and courtiers praised the emperor's magnificent clothes --- even though he was actually wearing nothing at all."),
           ("Mọi người sợ bị gọi là ngu dốt hay không đủ tư cách nên đã nói dối theo đám đông.",
            "Everyone feared being called stupid or unqualified, so they followed the crowd in lying."),
           ("Chỉ có một đứa trẻ --- người chưa học được sợ hãi xã hội --- nói to: 'Nhưng ông ấy không mặc gì cả!'",
            "Only a child --- who had not yet learned social fear --- called out loudly: 'But he has nothing on!'"),
           ("Andersen viết câu chuyện này như một gương phản chiếu cho xã hội Đan Mạch và nhân loại: áp lực đám đông có thể khiến người ta nhìn thấy thứ không có và không nhìn thấy thứ đang có.",
            "Andersen wrote this story as a mirror for Danish society and humanity: social pressure can make people see what is not there and not see what is."),
           ("Dũng cảm nhất không phải là người mạnh nhất, mà là người đủ bình thản để nói điều mình thực sự thấy.",
            "The bravest is not the strongest person, but the one calm enough to say what they truly see.")],
          "Khi cả đám đông nhất loạt tin vào một điều, đó chính xác là lúc bạn cần tự hỏi: mình thực sự đang nhìn thấy gì?",
          "When an entire crowd unanimously believes something, that is precisely when you need to ask yourself: what am I truly seeing?"),

    story("Marie Curie Và Thế Giới Bảo Cô Không Thể", "Marie Curie --- Pháp, 1867-1934",
          "Marie",
          [("Marie Curie sống trong một thời đại mà phụ nữ không được học đại học, không được nhận giải thưởng khoa học, không được bước vào các phòng họp học thuật.",
            "Marie Curie lived in an era when women could not attend university, could not receive scientific awards, could not enter academic meeting rooms."),
           ("Đám đông nói với cô: 'Đây không phải chỗ của cô.'",
            "The crowd told her: 'This is not your place.'"),
           ("Cô đáp lại bằng cách làm việc 16-18 tiếng một ngày trong phòng thí nghiệm dột nát, lạnh giá.",
            "She responded by working 16-18 hours a day in a leaky, freezing laboratory."),
           ("Khi Viện Hàn Lâm Khoa học Pháp từ chối cho cô vào hội vì cô là phụ nữ, cô không phản đối ầm ĩ --- cô tiếp tục nghiên cứu.",
            "When the French Academy of Sciences refused to admit her because she was a woman, she did not protest loudly --- she continued researching."),
           ("Bà đoạt giải Nobel lần thứ nhất năm 1903, lần thứ hai năm 1911 --- người duy nhất trong lịch sử đoạt Nobel trong hai ngành khoa học khác nhau.",
            "She won her first Nobel Prize in 1903, the second in 1911 --- the only person in history to win Nobel Prizes in two different scientific fields.")],
          "Đám đông nói 'không thể' thường chỉ phản ánh giới hạn của chính đám đông, không phải giới hạn của bạn.",
          "When a crowd says 'impossible', it usually only reflects the crowd's own limitations, not yours."),

    story("Nguyễn Du Và Tiếng Lòng Một Mình", "Nguyễn Du --- Việt Nam, 1765-1820",
          "Nguyễn",
          [("Nguyễn Du sống trong thời kỳ đất nước loạn lạc, nhiều lần phải làm quan dưới triều đại mà ông không hoàn toàn tán đồng.",
            "Nguyen Du lived in a time of national turmoil, frequently required to serve as an official under a dynasty he did not fully endorse."),
           ("Xã hội và hoàn cảnh bao vây ông với những vai trò bắt buộc: quan lại, thần tử, người đàn ông phải tuân theo lễ giáo phong kiến.",
            "Society and circumstances surrounded him with required roles: official, subject, a man who must obey feudal propriety."),
           ("Nhưng sâu trong lòng, ông gìn giữ tiếng lòng riêng của mình --- một tâm hồn đau đáu vì những phận người khốn khổ, đặc biệt là người phụ nữ.",
            "But deep in his heart, he preserved his own inner voice --- a soul deeply pained by the suffering of humanity, especially women."),
           ("Ông đổ hết tiếng lòng đó vào 'Truyện Kiều' --- tuyệt phẩm vượt qua mọi áp lực xã hội để nói điều ông thực sự tin.",
            "He poured all that inner voice into 'The Tale of Kieu' --- a masterpiece that transcended all social pressures to say what he truly believed."),
           ("250 năm sau, tiếng lòng một mình đó vẫn còn vang vọng trong trái tim hàng triệu người Việt.",
            "250 years later, that solitary inner voice still echoes in the hearts of millions of Vietnamese people.")],
          "Khi bạn không thể nói thật bằng hành động, hãy để nghệ thuật là nơi tiếng lòng thật của bạn được tự do.",
          "When you cannot speak truth through action, let art be the place where your true inner voice is free."),

    story("Thí Nghiệm Áp Lực Đám Đông Của Asch", "Solomon Asch --- Hoa Kỳ, 1951",
          "Trong",
          [("Trong một thí nghiệm tâm lý học nổi tiếng năm 1951, Solomon Asch cho thấy rằng 75 phần trăm người bình thường sẽ đồng ý với câu trả lời sai rõ ràng nếu cả nhóm xung quanh họ đều nói câu trả lời đó là đúng.",
            "In a famous psychology experiment in 1951, Solomon Asch showed that 75 percent of ordinary people would agree with an obviously wrong answer if the entire group around them said that answer was correct."),
           ("Chỉ cần nghe ba hay bốn người khác đồng ý sai, phần lớn người ta sẽ đặt câu hỏi về những gì mắt họ đang thấy.",
            "Simply hearing three or four others agree on something wrong was enough for most people to question what their own eyes were seeing."),
           ("Chỉ 25 phần trăm người giữ vững câu trả lời đúng dù đám đông phản đối.",
            "Only 25 percent of people maintained the correct answer despite the group disagreeing."),
           ("Asch gọi những người đó là 'những người có sức kháng cự nội tâm' --- khả năng tin vào những gì mình biết ngay cả khi đám đông nói ngược lại.",
            "Asch called these people 'those with internal resistance' --- the ability to trust what they know even when the crowd says the opposite."),
           ("Bài học: đừng bao giờ đánh giá thấp sức mạnh của áp lực đám đông --- và đừng bao giờ đánh giá thấp sức mạnh của ý chí độc lập.",
            "The lesson: never underestimate the power of social pressure --- and never underestimate the power of independent will.")],
          "Sức mạnh để tin vào điều mắt bạn thấy và lý trí bạn biết, ngay cả khi đám đông phản đối, là một trong những phẩm chất hiếm có và quý giá nhất.",
          "The strength to trust what your eyes see and your reason knows, even when the crowd disagrees, is one of the rarest and most precious qualities."),

    story("Nhà Thơ Rumi Và Tiếng Sáo Từ Xa", "Rumi --- Ba Tư, thế kỷ 13",
          "Rumi",
          [("Rumi, nhà thơ thần bí người Ba Tư vĩ đại, đã từ bỏ địa vị giáo sư thần học uy tín để đi theo người thầy lang thang Shams-i-Tabrizi --- điều mà toàn bộ xã hội và học trò của ông cho là điên rồ.",
            "Rumi, the great Persian mystic poet, gave up his prestigious position as a theology professor to follow the wandering teacher Shams-i-Tabrizi --- something his entire society and students considered madness."),
           ("Học trò của ông phản đối, gia đình phản đối, xã hội phán xét.",
            "His students objected, his family objected, society judged."),
           ("Nhưng Rumi biết rằng có một tiếng gọi bên trong ông mạnh hơn tất cả những tiếng phán xét bên ngoài.",
            "But Rumi knew that there was an inner calling stronger than all the outer judgments."),
           ("Ông viết: 'Hãy sống nơi bạn sợ sống nhất. Hủy hoại thanh danh của bạn. Hãy là tên xấu.'",
            "He wrote: 'Live where you are afraid to live. Destroy your reputation. Be notorious.'"),
           ("Kết quả là ông để lại Masnavi --- 25.000 dòng thơ thần bí được xem là kiệt tác của văn chương thế giới.",
            "The result was he left behind the Masnavi --- 25,000 lines of mystical poetry considered a masterpiece of world literature.")],
          "Tiếng gọi thực sự bên trong bạn thường ngược chiều với kỳ vọng của đám đông; đó chính xác là lý do tại sao bạn cần lắng nghe nó.",
          "Your true inner calling is often contrary to the crowd's expectations; that is precisely why you need to listen to it."),

    story("Cá Hồi Và Dòng Chảy Ngược", "Ẩn dụ từ thiên nhiên",
          "Mỗi",
          [("Mỗi năm, hàng triệu con cá hồi thực hiện một hành trình kỳ diệu: bơi ngược dòng từ biển cả về con suối nơi chúng được sinh ra để đẻ trứng.",
            "Every year, millions of salmon undertake a remarkable journey: swimming upstream from the ocean back to the stream where they were born to spawn."),
           ("Chúng bơi ngược lại dòng chảy mạnh, leo qua thác nước, chống lại tự nhiên theo nghĩa đen.",
            "They swim against powerful currents, leap over waterfalls, fight against nature in the most literal sense."),
           ("Hầu hết chúng kiệt sức và chết ngay sau khi đẻ trứng.",
            "Most of them exhaust themselves and die right after spawning."),
           ("Nhưng những quả trứng đó trong con suối quê hương sẽ nở ra thế hệ cá hồi tiếp theo tiếp tục hành trình tương tự.",
            "But those eggs in the home stream will hatch into the next generation of salmon who will repeat the same journey."),
           ("Cá hồi bơi ngược dòng không vì dễ dàng hay vì đám đông khuyến khích --- chúng làm vậy vì đó là bản năng sâu thẳm nhất của chúng.",
            "Salmon swim upstream not because it is easy or because the crowd encourages it --- they do it because it is their deepest instinct.")],
          "Đôi khi điều đúng đắn nhất để làm chính là điều khó khăn nhất và đi ngược lại tất cả mọi dòng chảy xung quanh.",
          "Sometimes the most right thing to do is precisely the hardest thing and the one that goes against every current around you."),

    story("Bà Hoàng Hải Lan --- Tiếng Nói Không Ai Nghe Ban Đầu", "Truyện dân gian Việt Nam",
          "Ngày",
          [("Ngày xưa ở một làng chài, có cô gái tên Hải Lan thấy rằng đánh bắt cá theo cách truyền thống đang làm cạn kiệt biển.",
            "Long ago in a fishing village, a girl named Hai Lan saw that fishing in the traditional way was depleting the sea."),
           ("Cô đề nghị làng áp dụng mùa nghỉ đánh bắt mỗi năm ba tháng để cá có thời gian sinh sản.",
            "She proposed the village adopt a fishing rest season each year for three months to allow fish to spawn."),
           ("Cả làng cười nhạo cô: 'Con gái biết gì về biển? Ông cha ta đánh thế nào ta đánh vậy.'",
            "The whole village mocked her: 'What does a girl know about the sea? We fish as our forebears did.'"),
           ("Năm đó cô không đi biển, chờ đợi một mình trong khi cả làng đánh cá ngày đêm.",
            "That year she did not go out to sea, waiting alone while the whole village fished day and night."),
           ("Năm sau, lưới của cô đầy cá còn của làng gần như trống --- biển đã cạn kiệt.",
            "The following year, her nets were full of fish while the village's were nearly empty --- the sea had been depleted.")],
          "Người đứng một mình trước đám đông không phải vì họ kiêu ngạo, mà vì đôi khi họ nhìn thấy điều đám đông chưa kịp nhìn.",
          "Those who stand alone before a crowd do so not from arrogance, but because sometimes they see what the crowd has not yet seen."),

    story("Thiếu Niên Greta Thunberg Và Tiếng Nói Một Mình", "Greta Thunberg --- Thụy Điển, 2018",
          "Tháng",
          [("Tháng 8 năm 2018, cô bé 15 tuổi Greta Thunberg một mình ngồi trước tòa nhà Quốc hội Thụy Điển với tấm biển: 'Nghỉ học vì Khí hậu'.",
            "In August 2018, 15-year-old Greta Thunberg sat alone in front of the Swedish Parliament building with a sign reading: 'School Strike for Climate.'"),
           ("Bạn bè không tham gia. Nhiều người cho rằng cô bé điên hoặc hám nổi tiếng.",
            "Friends did not join. Many thought the girl was crazy or attention-seeking."),
           ("Cô không màng phán xét. Cô ngồi đó mỗi ngày thứ Sáu.",
            "She did not care about judgments. She sat there every Friday."),
           ("Ba tháng sau, phong trào 'Fridays for Future' lan rộng ra toàn cầu, với hàng triệu học sinh bãi khóa tại 161 quốc gia.",
            "Three months later, the 'Fridays for Future' movement spread globally, with millions of students striking in 161 countries."),
           ("Từ một cô bé ngồi một mình trước quốc hội, phong trào đó đã đưa vấn đề khí hậu lên bàn của các nguyên thủ quốc gia trên toàn thế giới.",
            "From one girl sitting alone before a parliament, the movement put the climate issue on the tables of heads of state worldwide.")],
          "Phong trào lớn nhất không bắt đầu từ đám đông --- nó bắt đầu từ một người dám ngồi một mình và giữ vững điều mình tin.",
          "The greatest movements do not begin with a crowd --- they begin with one person daring to sit alone and hold firm to what they believe."),

    story("Cây Tre Và Cơn Bão", "Triết lý Á Đông",
          "Trong",
          [("Trong cơn bão lớn, những cây to lớn cứng nhắc thường bị gãy vì chúng không chịu nhượng bộ trước sức gió.",
            "In a great storm, large rigid trees often break because they refuse to yield to the force of the wind."),
           ("Nhưng cây tre uốn mình theo gió, nghiêng gần sát mặt đất, tưởng chừng sắp gãy.",
            "But the bamboo bends with the wind, bowing nearly to the ground, appearing about to break."),
           ("Khi cơn bão qua đi, cây tre vươn thẳng lại như chưa hề có gì xảy ra.",
            "When the storm passes, the bamboo straightens again as if nothing had happened."),
           ("Triết lý tre dạy chúng ta: đôi khi bạn cần biết cúi xuống trước áp lực đám đông để sống sót, miễn là bạn biết mình sẽ đứng thẳng lại khi bão tan.",
            "The philosophy of bamboo teaches us: sometimes you need to know how to bow before social pressure to survive, as long as you know you will stand straight again when the storm passes."),
           ("Sự khôn ngoan không phải là không bao giờ cúi đầu --- mà là biết khi nào cúi và khi nào đứng thẳng.",
            "Wisdom is not about never bowing --- it is about knowing when to bow and when to stand straight.")],
          "Linh hoạt trước áp lực và kiên định với cốt lõi không phải là mâu thuẫn --- đó là bí quyết của sức bền.",
          "Being flexible under pressure and steadfast at the core are not contradictory --- that is the secret of resilience."),
    ]
)

# ================================================================
# CHƯƠNG 7: MẤT CỦA CẢI, GIỮ PHẨM GIÁ
# ================================================================
ch7 = chapter(
    "Mất Của Cải, Giữ Phẩm Giá",
    "Losing Wealth, Keeping Dignity",
    "Khi mọi thứ bị cướp đi, một thứ vẫn còn nguyên --- sự tự do của bạn để chọn thái độ của mình.",
    "When everything is taken from you, one thing remains --- your freedom to choose your attitude.",
    [
    story("Job Mất Tất Cả Và Vẫn Giữ Được Chính Mình", "Kinh Thánh --- Cựu Ước",
          "Job",
          [("Job là người giàu có, hạnh phúc, được Thượng Đề ban phúc. Rồi trong một thời gian ngắn, ông mất tất cả: gia súc, tài sản, con cái, sức khỏe.",
            "Job was wealthy, happy, blessed by God. Then within a short time, he lost everything: cattle, property, children, health."),
           ("Bạn bè đến và nói đó là hình phạt của Thượng Đế vì ông đã làm điều gì đó sai.",
            "Friends came and said it was God's punishment because he had done something wrong."),
           ("Job từ chối chấp nhận điều đó. Ông không mất đức tin, không mất phẩm giá, không mất tính chính trực --- dù ông than thở và đau khổ.",
            "Job refused to accept that. He did not lose his faith, his dignity, his integrity --- though he lamented and suffered."),
           ("Câu chuyện của Job không phải là câu chuyện tại sao người tốt phải chịu đau khổ; đó là câu chuyện về cách con người có thể giữ được chính mình khi mọi thứ bên ngoài sụp đổ.",
            "Job's story is not about why good people must suffer; it is about how a person can maintain their self when everything external collapses."),
           ("Và cuối cùng, điều duy nhất thực sự bị thử thách là liệu Job có biết mình là ai ngoài tất cả những thứ ông sở hữu không.",
            "And ultimately, the only thing truly being tested was whether Job knew who he was apart from everything he possessed.")],
          "Tài sản thực sự của bạn không phải là những gì bạn có --- mà là những gì vẫn còn lại sau khi tất cả những thứ đó bị lấy đi.",
          "Your true wealth is not what you have --- it is what remains after all of that is taken away."),

    story("Nhà Hiền Triết Và Kẻ Cướp Không Lấy Được Gì", "Truyện Thiền Nhật Bản",
          "Một",
          [("Một đêm kẻ trộm đột nhập vào nhà của thiền sư Shichiri Kojun.",
            "One night a thief broke into the home of Zen master Shichiri Kojun."),
           ("Kojun thức giấc và nói với kẻ trộm bình tĩnh: 'Ngươi đến từ xa, đừng về tay không. Hãy lấy áo trong tủ.'",
            "Kojun woke up and said calmly to the thief: 'You have come from far away, do not leave empty-handed. Take the clothes in the closet.'"),
           ("Kẻ trộm lấy quần áo và chạy. Kojun nhìn theo và gọi: 'Khách ơi, hãy cảm ơn đi.'",
            "The thief took the clothes and ran. Kojun looked after him and called: 'My guest, say thank you.'"),
           ("Kẻ đó bị bắt sau đó và kể lại chuyện này. Khi được thả ra, hắn trở lại nhà Kojun, trả lại quần áo và cúi đầu xin lỗi.",
            "The thief was caught afterward and told this story. When released, he returned to Kojun's home, returned the clothes and bowed in apology."),
           ("Kojun nhận và nói: 'Ta không mất gì cả. Nhưng ta hi vọng ngươi đã tìm được điều ngươi thực sự đang tìm kiếm.'",
            "Kojun accepted and said: 'I lost nothing at all. But I hope you have found what you were truly searching for.'")],
          "Người thực sự không có gì để mất là người không định nghĩa bản thân bằng những thứ bên ngoài.",
          "The person who truly has nothing to lose is the one who does not define themselves by external things."),

    story("Aristides Người Công Bằng Bị Lưu Đày", "Aristides --- Athens, 482 TCN",
          "Aristides",
          [("Aristides, vị tướng Athens được gọi là 'người công bằng nhất', bị bỏ phiếu lưu đày khỏi Athens bởi chính đồng bào ông.",
            "Aristides, the Athenian general called 'the most just man', was voted into exile from Athens by his own people."),
           ("Theo truyền thuyết, một người dân không biết chữ đã nhờ ông viết tên 'Aristides' vào mảnh đất để bỏ phiếu lưu đày.",
            "According to legend, an illiterate citizen asked him to write the name 'Aristides' on the potsherd to vote for exile."),
           ("Aristides hỏi: 'Ông có biết người này không? Ông có lý do gì không?' Người kia đáp: 'Không, tôi chán nghe mọi người gọi ông ta là người công bằng nhất.'",
            "Aristides asked: 'Do you know this man? Do you have any reason?' The other replied: 'No, I am tired of hearing everyone call him the most just.'"),
           ("Aristides viết tên mình vào mảnh đất của người kia không nói một lời.",
            "Aristides wrote his own name on the man's potsherd without a word."),
           ("Ông rời Athens không cay đắng, không phẫn nộ; ông biết rằng danh dự của ông không phụ thuộc vào việc Athens có công nhận nó hay không.",
            "He left Athens without bitterness, without anger; he knew that his honor did not depend on whether Athens recognized it or not.")],
          "Phẩm giá thực sự không cần được xã hội công nhận để tồn tại; nó tự tồn tại trong lòng người sở hữu nó.",
          "True dignity does not need social recognition to exist; it lives within the heart of the one who possesses it."),

    story("Người Thợ Đồ Gốm Và Trận Hỏa Hoạn", "Truyện dân gian Trung Hoa",
          "Người",
          [("Người thợ đồ gốm Lý Tốn đã mất trắng xưởng gốm sau một trận hỏa hoạn.",
            "Potter Li Cun lost his entire pottery workshop in a fire."),
           ("Hàng xóm đến an ủi, nhiều người xì xầm: 'Ông ấy sẽ phải ăn mày thôi.'",
            "Neighbors came to console him, many whispering: 'He will have to beg now.'"),
           ("Nhưng ngay ngày hôm sau, Lý Tốn ra đồng, đào đất sét, và bắt đầu nặn gốm trên mặt đất bằng tay không.",
            "But the very next day, Li Cun went to the field, dug clay, and began shaping pottery on the ground with bare hands."),
           ("Ông nói: 'Lửa lấy đi xưởng của ta, nhưng không lấy đi bàn tay và khối óc của ta.'",
            "He said: 'The fire took my workshop, but it did not take my hands and my mind.'"),
           ("Mười năm sau, xưởng gốm mới của ông lớn gấp ba lần xưởng cũ, và đồ gốm của ông nổi tiếng khắp vùng.",
            "Ten years later, his new pottery workshop was three times the size of the old one, and his pottery was famous throughout the region.")],
          "Thứ duy nhất cơn lửa không thể đốt cháy là kỹ năng, trí tuệ và ý chí bên trong bạn.",
          "The only things a fire cannot burn are the skills, intelligence and will inside you."),

    story("Ông Lão Mất Ngựa --- Họa Phúc Tương Lai", "Hoài Nam Tử --- Trung Hoa cổ đại",
          "Ở",
          [("Ở vùng biên ải Trung Hoa ngày xưa, có một ông lão nuôi ngựa. Một ngày, con ngựa quý của ông tự nhiên bỏ trốn qua biên giới.",
            "In an ancient Chinese border region, an old man raised horses. One day, his prized horse suddenly fled across the border."),
           ("Hàng xóm đến chia buồn, ông lão bình thản nói: 'Ai biết đó là họa hay phúc?'",
            "Neighbors came to commiserate; the old man calmly said: 'Who knows whether this is misfortune or blessing?'"),
           ("Vài tháng sau, con ngựa trở về dẫn theo một đàn ngựa hoang từ bên kia biên giới.",
            "A few months later, the horse returned leading a herd of wild horses from across the border."),
           ("Hàng xóm đến chúc mừng, ông lão lại bình thản: 'Ai biết đó là họa hay phúc?'",
            "Neighbors came to congratulate; the old man again calmly: 'Who knows whether this is misfortune or blessing?'"),
           ("Con trai ông cưỡi ngựa bị ngã gãy chân. Hàng xóm chia buồn, ông lại bình thản. Rồi chiến tranh nổ ra, trai tráng đi lính hết, chỉ có con ông vì gãy chân mà được miễn. Mọi người mới hiểu.",
            "His son fell from a horse and broke his leg. Neighbors commiserated; he was again calm. Then war broke out, all young men were conscripted, only his son was exempted because of his broken leg. Everyone finally understood.")],
          "Không có mất mát nào hoàn toàn là mất mát, và không có thành công nào hoàn toàn là thành công; vòng xoay của cuộc đời hiếm khi dừng lại ở một điểm cố định.",
          "No loss is entirely a loss, and no success is entirely a success; the wheel of life rarely stops at one fixed point."),

    story("Florence Nightingale Và Sứ Mệnh Sau Thất Bại", "Florence Nightingale --- Anh, thế kỷ 19",
          "Florence",
          [("Florence Nightingale lớn lên trong một gia đình quý tộc Anh với cuộc sống mà xã hội đã vạch sẵn: kết hôn với một quý ông giàu có và làm bà chủ nhà.",
            "Florence Nightingale grew up in a British aristocratic family with a life society had pre-mapped for her: marry a wealthy gentleman and become a hostess."),
           ("Cô từ chối. Gia đình phản đối dữ dội. Xã hội lên án.",
            "She refused. Her family strongly objected. Society condemned her."),
           ("Cô bỏ tất cả để đi học y tá --- một nghề mà thời đó bị coi là thấp kém, không xứng với cô gái quý tộc.",
            "She abandoned everything to study nursing --- a profession then considered low and unworthy of a noble girl."),
           ("Trong chiến tranh Crimea, bà đến bệnh viện dã chiến và nhận thấy điều kiện vệ sinh kinh khủng đang giết chết nhiều binh sĩ hơn cả chiến trận.",
            "In the Crimean War, she went to the field hospital and found that terrible sanitary conditions were killing more soldiers than battle itself."),
           ("Bà thay đổi toàn bộ hệ thống chăm sóc y tế, giảm tỷ lệ tử vong từ 42 phần trăm xuống còn 2 phần trăm --- và trở thành người khai sinh ngành điều dưỡng hiện đại.",
            "She transformed the entire medical care system, reducing mortality from 42 percent to 2 percent --- and became the founder of modern nursing.")],
          "Khi bạn mất đi những gì xã hội đã chuẩn bị sẵn cho bạn, bạn có thể tìm thấy sứ mệnh thực sự của mình.",
          "When you lose what society had prepared for you, you may find your true mission."),

    story("Mandela Trong Tù Và Sự Giàu Có Tinh Thần", "Nelson Mandela --- Nam Phi",
          "Trong",
          [("Trong nhà tù Robben Island, Nelson Mandela bị buộc lao động khổ sai tại mỏ đá vôi dưới ánh mặt trời chói chang.",
            "In Robben Island prison, Nelson Mandela was forced into hard labor at a limestone quarry under blazing sunlight."),
           ("Tất cả những thứ bên ngoài bị tước đoạt: tự do, gia đình, địa vị, của cải.",
            "All external things were stripped away: freedom, family, status, wealth."),
           ("Nhưng Mandela học tiếng Afrikaans của chính những người cai quản ông --- không phải để nịnh họ, mà để hiểu họ.",
            "But Mandela learned Afrikaans from his very own jailers --- not to flatter them, but to understand them."),
           ("Ông tổ chức các lớp học trong nhà tù, giúp đỡ những tù nhân khác, giữ vững tinh thần tập thể chống lại sự tuyệt vọng.",
            "He organized classes in prison, helped other prisoners, maintained collective spirit against despair."),
           ("Sau 27 năm, ông bước ra với điều không tù nào có thể cướp được: sự hiểu biết sâu sắc về con người và tầm nhìn để hàn gắn một dân tộc.",
            "After 27 years, he stepped out with the one thing no prison could steal: deep understanding of humanity and the vision to heal a nation.")],
          "Những năm tháng bị tước đoạt có thể trở thành những năm tháng phát triển sâu sắc nhất --- nếu bạn chọn dùng chúng như vậy.",
          "Years of deprivation can become years of deepest growth --- if you choose to use them that way."),

    story("Người Đàn Bà Không Nhà Và Tấm Lòng Rộng Mở", "Truyện thực tế --- Nhật Bản sau động đất Kobe, 1995",
          "Sau",
          [("Sau trận động đất Kobe năm 1995 làm 6.434 người thiệt mạng và hàng trăm nghìn người mất nhà, một bà cụ tên Kimura Sachiko đã mất căn nhà 40 năm trong chớp mắt.",
            "After the 1995 Kobe earthquake that killed 6,434 people and left hundreds of thousands homeless, an elderly woman named Kimura Sachiko lost her 40-year home in an instant."),
           ("Bà sống trong lều tạm trú tại công viên.",
            "She lived in a temporary shelter tent in the park."),
           ("Nhưng ngay ngày đầu tiên trong lều tạm, bà đã đi hái rau dại và nấu cháo cho những người hàng xóm bị thương quanh bà.",
            "But on the very first day in the temporary shelter, she went to gather wild vegetables and cooked porridge for the injured neighbors around her."),
           ("Khi được hỏi tại sao bà không lo cho bản thân trước, bà nói: 'Nhà tôi mất rồi nhưng tôi vẫn còn hai bàn tay và trái tim.'",
            "When asked why she did not take care of herself first, she said: 'My house is gone but I still have two hands and a heart.'"),
           ("Câu nói đó lan ra khắp trại tạm trú và trở thành khẩu hiệu tinh thần cho cuộc phục hồi của toàn thành phố.",
            "That saying spread throughout the shelter camp and became the spiritual motto for the entire city's recovery.")],
          "Khi mọi thứ bên ngoài mất đi, những gì bất diệt bên trong bạn mới thực sự được nhìn thấy.",
          "When everything external is lost, what is indestructible inside you finally becomes truly visible."),

    story("Nhà Văn Dostoevsky Và Cái Chết Giả", "Fyodor Dostoevsky --- Nga, 1849",
          "Năm",
          [("Năm 1849, Fyodor Dostoevsky bị bắt vì tham gia nhóm cách mạng và bị kết án tử hình.",
            "In 1849, Fyodor Dostoevsky was arrested for joining a revolutionary group and sentenced to death."),
           ("Ông đứng trước hàng súng, chờ chết. Vào phút cuối, lệnh ân xá đến: án được đổi thành đi đày khổ sai ở Siberia.",
            "He stood before the firing squad, waiting to die. At the last moment, the pardon came: the sentence was commuted to hard labor exile in Siberia."),
           ("Bốn năm lao động cực khổ trong băng giá Siberia, ông đã trải qua tất cả mọi sự tước đoạt.",
            "Four years of brutal labor in Siberian frost, he experienced every form of deprivation."),
           ("Nhưng từ trong địa ngục đó, ông quan sát con người, đau khổ, tội lỗi, lòng từ bi --- và ông viết.",
            "But from within that hell, he observed people, suffering, sin, compassion --- and he wrote."),
           ("Những tác phẩm ông viết sau khi trở về --- 'Tội Ác và Trừng Phạt', 'Anh Em Nhà Karamazov' --- được coi là những tiểu thuyết sâu sắc nhất trong lịch sử văn học thế giới.",
            "The works he wrote after returning --- 'Crime and Punishment', 'The Brothers Karamazov' --- are considered the most profound novels in world literary history.")],
          "Khổ đau sâu nhất có thể trở thành nghệ thuật sâu nhất; thứ bị tước đoạt bên ngoài có thể trở thành tài nguyên vô tận bên trong.",
          "The deepest suffering can become the deepest art; what is taken away outside can become an infinite resource inside."),

    story("Hạt Ngọc Trai Và Vết Thương", "Ẩn dụ từ thiên nhiên",
          "Con",
          [("Con trai ngọc không phải ngọc, không có gì đặc biệt bên ngoài.",
            "The oyster is not pearl; nothing special on the outside."),
           ("Nhưng khi một hạt cát nhỏ xâm nhập vào thân thể mềm mại bên trong của nó, gây đau và khó chịu, con trai bắt đầu một quá trình kỳ diệu.",
            "But when a tiny grain of sand penetrates its soft inner body, causing pain and discomfort, the oyster begins a remarkable process."),
           ("Nó bao bọc hạt cát bằng những lớp xà cừ mịn màng, lớp này qua lớp khác, trong nhiều năm.",
            "It wraps the grain of sand in layers of smooth nacre, layer upon layer, over many years."),
           ("Sự đau đớn nhỏ bé đó, qua thời gian, trở thành viên ngọc trai quý giá nhất.",
            "That small pain, over time, becomes the most precious pearl."),
           ("Thiên nhiên dạy chúng ta: những vết thương không nhất thiết phá hủy bạn --- chúng cũng có thể là nguyên liệu tạo nên thứ quý giá nhất bên trong bạn.",
            "Nature teaches us: wounds do not necessarily destroy you --- they can also be the raw material for the most precious thing within you.")],
          "Đau khổ không tự nó tạo ra vẻ đẹp, nhưng cách bạn đối phó với đau khổ có thể tạo ra thứ đẹp nhất bạn từng góp cho đời.",
          "Suffering does not by itself create beauty, but how you respond to suffering can create the most beautiful thing you ever contribute to the world."),
    ]
)

# ================================================================
# CHƯƠNG 8: MẤT ĐI, TÌM LẠI BẢN THÂN
# ================================================================
ch8 = chapter(
    "Mất Đi, Tìm Lại Bản Thân",
    "Losing to Find Yourself",
    "Đôi khi bạn cần mất đi để tìm lại bản thân mình.",
    "Sometimes you need to lose yourself to find yourself.",
    [
    story("Người Con Hoang Đàng Tìm Về Chính Mình", "Kinh Thánh --- Tân Ước (lược)",
          "Người",
          [("Người con thứ đòi chia gia tài rồi bỏ đi phương xa, ăn chơi phung phí đến khánh kiệt.",
            "The younger son demanded his inheritance then left for a distant land, squandering it all in reckless living."),
           ("Anh ta phải đi chăn heo để kiếm ăn và thèm cả thức ăn của heo.",
            "He ended up herding pigs for food and craved even the pig fodder."),
           ("Chính trong đáy sâu cùng cực đó, anh ta mới thực sự tỉnh ngộ: 'Tôi đã trở thành ai rồi? Điều tôi thực sự cần là gì?'",
            "It was in that absolute lowest depth that he truly came to his senses: 'What have I become? What do I truly need?'"),
           ("Anh ta đứng dậy và về nhà với lòng khiêm tốn thực sự --- không phải vì bị ép buộc mà vì đã hiểu.",
            "He rose and returned home with genuine humility --- not because he was forced but because he had understood."),
           ("Câu chuyện không nói rằng sa ngã là tốt; nó nói rằng đôi khi ta cần mất đi tất cả để tìm về điều thực sự quan trọng.",
            "The story does not say that falling is good; it says that sometimes we need to lose everything to return to what truly matters.")],
          "Những cuộc hành trình đi lạc xa nhất đôi khi là những cuộc hành trình dẫn chúng ta về gần nhất với bản thân.",
          "The journeys that stray the farthest are sometimes the ones that bring us closest to ourselves."),

    story("Hermann Hesse Và Hành Trình Siddhartha", "Hermann Hesse --- Đức, 1922",
          "Trong",
          [("Trong tiểu thuyết 'Siddhartha' của Hermann Hesse, chàng trai Siddhartha trải qua ba giai đoạn tìm kiếm bản thân.",
            "In Hermann Hesse's novel 'Siddhartha', the young man Siddhartha goes through three stages of seeking himself."),
           ("Đầu tiên, anh từ bỏ cuộc sống tu hành tâm linh để trải nghiệm thế giới vật chất, trở thành thương gia giàu có và tình nhân quyến rũ.",
            "First, he abandons spiritual life to experience the material world, becoming a wealthy merchant and seductive lover."),
           ("Anh mất chính mình trong xa hoa và cảm thấy trống rỗng đau đớn.",
            "He loses himself in luxury and feels empty and pained."),
           ("Rồi anh bỏ tất cả, đến bên dòng sông, làm người lái đò học hỏi từ những gì dòng nước dạy.",
            "Then he abandons everything, comes to a river, becomes a ferryman learning from what the flowing water teaches."),
           ("Hesse muốn nói: đôi khi ta phải đi qua tất cả các vai diễn --- giàu có, danh vọng, khoái lạc --- để cuối cùng tìm ra sự bình yên trong chính khoảnh khắc hiện tại.",
            "Hesse means: sometimes we must go through all the roles --- wealth, fame, pleasure --- to finally find peace in the present moment itself.")],
          "Không có con đường tắt đến tự tri; đôi khi bạn phải đi lạc qua tất cả những gì bạn không phải trước khi tìm ra những gì bạn thực sự là.",
          "There is no shortcut to self-knowledge; sometimes you must wander through all you are not before finding all you truly are."),

    story("Người Phụ Nữ Sau Ly Hôn --- Tìm Lại Tiếng Nói", "Câu chuyện tâm lý học thực tế",
          "Sau",
          [("Sau 20 năm hôn nhân, một người phụ nữ tên Anna bỗng nhận ra rằng trong suốt thời gian đó, bà đã luôn sống theo mong muốn và kỳ vọng của người khác.",
            "After 20 years of marriage, a woman named Anna suddenly realized that throughout that time, she had always lived according to others' wishes and expectations."),
           ("Cuộc ly hôn, dù đau đớn, đã buộc bà phải đối mặt với câu hỏi: 'Tôi thực sự muốn gì?'",
            "The divorce, though painful, forced her to confront the question: 'What do I truly want?'"),
           ("Bà báo những gì không còn muốn làm, những sở thích bị bỏ quên từ khi còn trẻ, những ước mơ bị chôn vùi vì sợ phán xét.",
            "She catalogued what she no longer wanted to do, the interests forgotten since her youth, the dreams buried for fear of judgment."),
           ("Bà đăng ký học vẽ, mở nhóm đọc sách, bắt đầu đi du lịch một mình --- tất cả những thứ bà chưa bao giờ dám làm.",
            "She enrolled in painting classes, started a book club, began traveling alone --- all the things she had never dared to do."),
           ("Ba năm sau, bà nói: 'Cuộc ly hôn mà tôi tưởng là kết thúc cuộc đời hóa ra là cái cổng dẫn vào phần thực sự nhất trong cuộc đời tôi.'",
            "Three years later she said: 'The divorce I thought was the end of my life turned out to be the gate leading to the truest part of my life.'")],
          "Đôi khi chúng ta phải mất đi những phần mà chúng ta đã định nghĩa mình để tìm lại những phần thực sự thuộc về mình.",
          "Sometimes we must lose the parts by which we have defined ourselves in order to reclaim the parts that truly belong to us."),

    story("Dante Và Hành Trình Qua Địa Ngục", "Dante Alighieri --- Ý, 1320",
          "Trong",
          [("Trong Thần Khúc, Dante mô tả hành trình tâm linh của mình bắt đầu bằng việc bị lạc trong 'khu rừng tối' giữa cuộc đời.",
            "In the Divine Comedy, Dante describes his spiritual journey beginning with being lost in a 'dark forest' in the middle of his life."),
           ("Để tìm được con đường, ông phải đi qua Địa Ngục trước.",
            "To find the way, he had to pass through Hell first."),
           ("Ông không thể đi đường tắt lên Thiên Đàng mà không trải qua tầng cùng sâu nhất của Địa Ngục.",
            "He could not take a shortcut to Paradise without traversing the deepest level of Hell."),
           ("Đây là ẩn dụ vĩ đại của Dante: sự tự tri thực sự đòi hỏi bạn phải dũng cảm nhìn vào những góc tối nhất của chính mình --- không chạy trốn, không tự lừa dối.",
            "This is Dante's great metaphor: genuine self-knowledge requires you to courageously look into your own darkest corners --- without fleeing, without self-deception."),
           ("Chỉ sau khi thấy rõ bóng tối trong mình, ánh sáng mới thực sự có ý nghĩa.",
            "Only after clearly seeing the darkness within oneself does the light finally become truly meaningful.")],
          "Hành trình khám phá bản thân không phải là hành trình lên thiên đàng thẳng tiến; đó là hành trình dũng cảm đi xuống địa ngục của chính mình trước.",
          "The journey of self-discovery is not a straight ascent to paradise; it is the courageous journey into one's own personal hell first."),

    story("Cô Bé Lọ Lem Và Đêm Tối Trước Buổi Sáng", "Charles Perrault --- Pháp, thế kỷ 17",
          "Khoảnh",
          [("Khoảnh khắc tồi tệ nhất của Lọ Lem không phải là khi cô ngồi khóc bên đống tro --- đó là khoảnh khắc quan trọng nhất.",
            "Cinderella's worst moment was not when she sat crying by the fireplace --- that was her most important moment."),
           ("Chính trong đêm tối nhất đó, cô tiên hiện ra.",
            "It was in that darkest moment that the fairy godmother appeared."),
           ("Câu chuyện Lọ Lem không phải là câu chuyện về hoàng tử đến cứu --- đó là câu chuyện về việc không từ bỏ hy vọng ngay cả trong đêm tối nhất.",
            "Cinderella's story is not a story about a prince coming to rescue --- it is a story about not giving up hope even in the darkest night."),
           ("Trong mọi câu chuyện cổ tích, đêm tối nhất luôn đến ngay trước buổi bình minh.",
            "In every fairy tale, the darkest night always comes just before the dawn."),
           ("Khi bạn cảm thấy mọi thứ tệ nhất, đó thường không phải là dấu hiệu của kết thúc --- mà là dấu hiệu của sự chuyển hóa sắp xảy ra.",
            "When you feel everything is at its worst, it is often not a sign of the end --- but a sign of transformation about to occur.")],
          "Đêm tối nhất trong cuộc đời không phải là lúc để từ bỏ hy vọng; đó chính xác là lúc điều kỳ diệu nhất có thể xảy ra.",
          "The darkest night in life is not the time to give up hope; it is precisely when the most miraculous things can happen."),

    story("Rip Van Winkle Và Cú Ngủ Quên Dài Nhất", "Washington Irving --- Mỹ, 1819",
          "Trong",
          [("Trong câu chuyện của Washington Irving, Rip Van Winkle ngủ quên trong núi 20 năm và tỉnh dậy trong thế giới đã thay đổi hoàn toàn.",
            "In Washington Irving's story, Rip Van Winkle slept in the mountains for 20 years and woke changed in a world where everything had changed."),
           ("Anh trở về làng nhưng không ai nhận ra anh; vợ đã chết, bạn bè đã già, đất nước thay chủ quyền.",
            "He returned to the village but no one recognized him; his wife had died, friends had aged, and the country had changed sovereignty."),
           ("Điều kỳ lạ: anh ta không còn là Rip Van Winkle nữa --- người đàn ông 40 tuổi trong thân xác đã già đó không biết mình là ai trong thế giới mới.",
            "The strange thing: he was no longer Rip Van Winkle --- the 40-year-old man in that aged body did not know who he was in the new world."),
           ("Irving dùng câu chuyện này để cảnh báo: người không chịu thức tỉnh và thay đổi sẽ một ngày nhận ra mình là người xa lạ ngay trong cuộc sống của chính mình.",
            "Irving uses this story to warn: those who refuse to wake up and change will one day find themselves strangers in their own lives."),
           ("Đôi khi ta cần mất đi bản thân cũ để bắt đầu tìm hiểu con người mới của mình.",
            "Sometimes we need to lose the old self to begin discovering our new self.")],
          "Đừng để những ảo tưởng và thói quen của hôm qua ru ngủ bạn trong khi thế giới và con người thật của bạn đang thay đổi.",
          "Do not let yesterday's illusions and habits lull you to sleep while the world and your true self are changing."),

    story("Người Mù Lâu Năm Nhìn Thấy Lại Ánh Sáng", "Triết lý Phật giáo về tỉnh thức",
          "Có",
          [("Có một người đàn ông bị mù từ nhỏ. Sau nhiều năm, ông được phẫu thuật và nhìn thấy ánh sáng lần đầu tiên trong cuộc đời.",
            "A man was blind from childhood. After many years, he had surgery and saw light for the first time in his life."),
           ("Nhưng điều kỳ lạ là trong những ngày đầu, ông lại cảm thấy khổ sở hơn bao giờ hết.",
            "But strangely, in the first days, he felt more distressed than ever before."),
           ("Thế giới của ánh sáng quá choáng ngợp, quá phức tạp, quá khác xa với thế giới âm thanh và xúc giác mà ông đã quen.",
            "The world of light was too overwhelming, too complex, too different from the world of sound and touch he had known."),
           ("Ông phải học lại cách nhìn từ đầu --- học cách não bộ xử lý hình ảnh, học cách tin vào mắt.",
            "He had to learn how to see from the beginning --- how the brain processes images, how to trust his eyes."),
           ("Sau một thời gian đau đớn, ông nói: 'Tôi cần mất đi thế giới quen thuộc của mình để thực sự bắt đầu sống trong thế giới thực.'",
            "After a period of pain, he said: 'I needed to lose my familiar world to truly begin living in the real world.'")],
          "Đôi khi ánh sáng mới đau hơn bóng tối đã quen; điều đó không có nghĩa là ánh sáng là sai, mà chỉ là mắt bạn cần thời gian để thích nghi.",
          "Sometimes new light hurts more than familiar darkness; that does not mean the light is wrong, only that your eyes need time to adjust."),

    story("Nhà Văn Koji Suzuki Và Vòng Xoáy Mất Ngủ", "Câu chuyện sáng tạo --- Nhật Bản",
          "Koji",
          [("Koji Suzuki, tác giả của tiểu thuyết kinh dị 'Ring' (Vòng Tròn Oan), kể rằng ý tưởng về bộ truyện nổi tiếng nhất của ông đến trong giai đoạn tồi tệ nhất cuộc đời ông.",
            "Koji Suzuki, author of the horror novel 'Ring', recounts that the idea for his most famous series came during the worst period of his life."),
           ("Ông thất nghiệp, không có tiền, phải trông con nhỏ suốt ngày trong căn hộ hẹp trong khi vợ đi làm.",
            "He was unemployed, had no money, had to watch his young children all day in a small apartment while his wife worked."),
           ("Không có máy tính, ông viết tay ở bất kỳ góc nào có thể --- nhà vệ sinh, góc bếp, khi con ngủ.",
            "Without a computer, he wrote by hand in any corner available --- the bathroom, a kitchen corner, when children napped."),
           ("Chính sự ép buộc của hoàn cảnh đó khiến ông tập trung hoàn toàn vào ý tưởng lớn nhất trong đầu thay vì phân tán.",
            "It was precisely that forced circumstance that made him focus entirely on his biggest idea rather than being scattered."),
           ("'Ring' ra đời trong căn bếp lúc nửa đêm, và trở thành một trong những tác phẩm kinh dị được chuyển thể nhiều nhất lịch sử điện ảnh thế giới.",
            "'Ring' was born in a kitchen at midnight, and became one of the most adapted horror works in world cinema history.")],
          "Những giới hạn ép buộc đôi khi là điều kiện để ý tưởng lớn nhất trong bạn cuối cùng có cơ hội bùng phát.",
          "Forced limitations are sometimes the conditions for the greatest idea within you to finally have a chance to burst forth."),

    story("Người Đàn Ông Mất Ký Ức Và Tìm Lại Cuộc Đời", "Trường hợp y tế thực tế",
          "Một",
          [("Một người đàn ông tên Henry Molaison bị mất hoàn toàn khả năng tạo ký ức mới sau một ca phẫu thuật não năm 1953, và sống trong tình trạng đó 55 năm.",
            "A man named Henry Molaison completely lost the ability to form new memories after brain surgery in 1953, and lived in that condition for 55 years."),
           ("Mỗi sáng anh thức dậy không biết hôm qua là gì, không nhớ những người chăm sóc anh, không thể tích lũy kinh nghiệm mới.",
            "Every morning he woke not knowing what yesterday was, not remembering those who cared for him, unable to accumulate new experience."),
           ("Nhưng điều kỳ lạ: anh vẫn học được những kỹ năng vận động mới --- bàn tay anh nhớ dù não anh không.",
            "But strangely: he could still learn new motor skills --- his hands remembered even when his brain could not."),
           ("Và những nhà nghiên cứu làm việc với anh nói rằng dù không có ký ức liên tục, anh vẫn có một bản sắc nhất quán: ông ấy vẫn luôn lịch sự, kiên nhẫn, tốt bụng.",
            "And researchers who worked with him said that despite having no continuous memory, he still had a consistent identity: he was always polite, patient, kind."),
           ("Bản sắc thực sự của con người, câu chuyện này gợi ý, nằm sâu hơn cả ký ức.",
            "A person's true identity, this story suggests, lies deeper than even memory.")],
          "Con người thực sự của bạn không nằm trong trí nhớ về quá khứ hay kế hoạch cho tương lai; nó hiện diện ngay trong mỗi hành động của bạn ở khoảnh khắc này.",
          "Your true person does not reside in memories of the past or plans for the future; it is present in every action you take at this very moment."),

    story("Thuyền Trưởng Và Cơn Bão Cuối Cùng", "Truyện ngụ ngôn biển cả",
          "Trong",
          [("Trong cơn bão dữ dội nhất, một thuyền trưởng lão luyện bình tĩnh điều hướng con tàu trong khi cả thủy thủ đoàn hoảng loạn.",
            "In the most violent storm, a seasoned captain calmly navigated the ship while the entire crew panicked."),
           ("Một thủy thủ trẻ hỏi: 'Thuyền trưởng không sợ à?'",
            "A young sailor asked: 'Captain, are you not afraid?'"),
           ("Thuyền trưởng trả lời: 'Sợ chứ. Nhưng tôi đã trải qua đủ bão để biết rằng con tàu trụ được hay không phụ thuộc vào người lái, không phải vào bão.'",
            "The captain replied: 'Afraid, yes. But I have been through enough storms to know that whether the ship survives depends on the helmsman, not on the storm.'"),
           ("Sau cơn bão, thủy thủ trẻ hỏi: 'Kinh nghiệm nào dạy thuyền trưởng bình tĩnh như vậy?' Thuyền trưởng mỉm cười: 'Những cơn bão trước đó mà tôi nghĩ tôi không qua được.'",
            "After the storm, the young sailor asked: 'What experience taught the captain such calm?' The captain smiled: 'The previous storms I thought I would not survive.'"),
           ("Chúng ta không biết mình mạnh như thế nào cho đến khi mạnh là lựa chọn duy nhất còn lại.",
            "We do not know how strong we are until being strong is the only option remaining.")],
          "Cơn bão hiện tại không phải là để hủy hoại bạn; đó là để cho bạn thấy con người bạn đủ sức là.",
          "The current storm is not to destroy you; it is to show you the person you are capable of being."),
    ]
)

# ================================================================
# GHI FILE
# ================================================================
files = [
    ("ch05-vai-dien-va-con-nguoi-that", ch5),
    ("ch06-ap-luc-dam-dong-va-tu-nga", ch6),
    ("ch07-mat-cua-cai-giu-pham-gia", ch7),
    ("ch08-mat-di-tim-lai-ban-than", ch8),
]
for fname, content in files:
    path = os.path.join(BASE, f"{fname}.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{fname} done")
print("All chapters 5-8 generated successfully!")
