# -*- coding: utf-8 -*-
"""Quyển VI -- Vòng Quay Cuộc Đời -- Chapters 1-4"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-6/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    text = re.sub(r'(?<!\\)&', r'\\&', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 1: GIEO ĐIỀU TỐT, GẶP ĐIỀU TỐT
# ================================================================
ch1 = chapter(
    "Gieo Điều Tốt, Gặp Điều Tốt",
    "Sow Goodness, Reap Goodness",
    "Bàn tay trao tặng hoa hồng, hương thơm vẫn còn lưu lại.",
    "The hand that gives roses always retains a little of the fragrance.",
    [
    story("Người Nông Dân Cứu Chàng Trai Chết Đuối", "Giai thoại về Thủ tướng Churchill --- Anh",
          "Một",
          [("Một buổi chiều mùa hè, người nông dân nghèo Hugh Fleming đang làm việc trên cánh đồng thì nghe tiếng kêu cứu thảm thiết vọng ra từ đầm lầy gần đó.",
            "One summer afternoon, poor farmer Hugh Fleming was working in his field when he heard desperate cries for help coming from a nearby swamp."),
           ("Ông lao xuống ngay không chút do dự và cứu được một cậu bé đang chìm dần trong bùn lầy.",
            "He plunged in without hesitation and saved a young boy who was slowly sinking into the mud."),
           ("Hôm sau, một thứ gì đó quan trọng hơn đã xảy ra: một chiếc xe ngựa sang trọng đến trước nhà ông, và bên trong là một quý ông giàu có.",
            "The next day, something even more significant occurred: a handsome carriage arrived at his home, carrying a wealthy gentleman."),
           ("Quý ông đó chính là cha của cậu bé được cứu, ông ngỏ lời muốn cho con trai của người nông dân được học tại trường y khoa danh giá nhất London.",
            "That gentleman was the father of the rescued boy, and he offered to send the farmer's son to study at the most prestigious medical school in London."),
           ("Người nông dân nhận lời; con trai ông sau này trở thành nhà khoa học Alexander Fleming, người phát minh ra Penicillin cứu sống hàng triệu người.",
            "The farmer accepted; his son later became scientist Alexander Fleming, who invented Penicillin saving millions of lives."),
           ("Còn cậu bé được cứu khỏi đầm lầy ngày ấy --- chính là người con trai của quý ông kia --- sau này trở thành Thủ tướng Winston Churchill vĩ đại.",
            "And the boy saved from the swamp that day --- the gentleman's own son --- later became the great Prime Minister Winston Churchill.")],
          "Một hành động tốt bình thường nhất có thể khởi động một chuỗi nhân quả vĩ đại thay đổi cả lịch sử nhân loại.",
          "The most ordinary good deed can trigger a chain of karma that changes the entire course of human history."),

    story("Bát Cháo Của Bà Lão Và Tướng Quân", "Truyện Dân Gian Việt Nam",
          "Trong",
          [("Trong một mùa đông giá rét, một bà lão nghèo sống một mình ven rừng đã chia sẻ bát cháo cuối cùng của mình cho một người lính đói khổ lết vào cửa nhà bà.",
            "In a bitter winter, a poor old woman living alone at the forest's edge shared her last bowl of porridge with a starving soldier who dragged himself to her door."),
           ("Người lính cảm tạ và tiếp tục hành trình gian nan của mình trong cuộc chiến.",
            "The soldier expressed gratitude and continued his arduous wartime journey."),
           ("Mười năm sau, một đoàn kỵ binh oai nghiêm dừng lại trước căn nhà tranh của bà.",
            "Ten years later, a majestic cavalry unit stopped before the woman's thatched cottage."),
           ("Vị tướng dẫn đầu xuống ngựa, cúi đầu chào người phụ nữ già nua và trao cho bà một túi vàng.",
            "The general leading the group dismounted, bowed respectfully to the aged woman, and presented her with a bag of gold."),
           ("Ông nói: 'Thưa cụ, con là người lính đói rét ngày ấy. Bát cháo của cụ đã cho con sức mạnh để tiếp tục sống và chiến đấu. Hôm nay con trở về để báo ơn.'",
            "He said: 'Elder, I am that cold and hungry soldier from years ago. Your bowl of porridge gave me the strength to keep living and fighting. Today I have returned to repay the debt.'")],
          "Lòng tốt không bao giờ mất đi, nó chỉ đi một vòng dài rồi tìm về đúng người đã gieo.",
          "Kindness is never lost; it just makes a long journey before returning to the one who sowed it."),

    story("Người Thương Gia Và Kẻ Trộm Được Tha Thứ", "Charles Dickens phóng tác --- Anh",
          "Đêm",
          [("Đêm đông lạnh giá, một người thương gia tên Edward Montague bắt gặp một cậu bé gầy guộc đang trộm một ổ bánh mì trước tiệm của ông.",
            "On a cold winter night, a merchant named Edward Montague caught a scrawny boy stealing a loaf of bread from his shop."),
           ("Thay vì giao cậu cho cảnh sát, ông mời cậu vào trong, cho cậu ăn bữa tối ấm áp và hỏi về hoàn cảnh của cậu.",
            "Instead of calling the police, he invited the boy inside, gave him a warm dinner, and asked about his circumstances."),
           ("Cậu bé kể rằng gia đình đang chết đói vì cha cậu bị bệnh không làm việc được.",
            "The boy explained that his family was starving because his father was too ill to work."),
           ("Người thương gia tặng cậu thức ăn, thuốc men, và cho cậu một việc làm nhỏ trong cửa tiệm.",
            "The merchant gave the boy food, medicine, and offered him a small job at the shop."),
           ("Hai mươi năm sau, khi doanh nghiệp của ông sắp sụp đổ vì khủng hoảng, chính người thanh niên đó --- nay là một doanh nhân thành đạt --- đã đến cứu trợ ông.",
            "Twenty years later, when his business was about to collapse due to a crisis, that same young man --- now a successful entrepreneur --- came to his rescue.")],
          "Lòng nhân từ đầu tư vào một đứa trẻ tuyệt vọng là khoản đầu tư sinh lợi nhất trên đời.",
          "Investing kindness in a desperate child is the most profitable investment in the world."),

    story("Hòn Đá Cản Đường Và Túi Vàng Dưới Lòng Đất", "Truyện Ngụ Ngôn Ấn Độ",
          "Nhà",
          [("Nhà Vua Bharata muốn thử lòng dân chúng, bèn sai người chôn một tảng đá lớn giữa con đường chính, cạnh đó để một túi vàng nhỏ và tờ giấy ghi: 'Ai dời hòn đá này sẽ nhận được túi vàng.'",
            "King Bharata wanted to test his people, so he had a large stone buried in the middle of the main road, with a small bag of gold and a note beside it reading: 'Whoever moves this stone shall receive the bag of gold.'"),
           ("Hàng trăm người qua lại, tất cả đều chỉ nhìn hòn đá rồi chê nó quá nặng, rồi bước đi than thở về sự cản trở.",
            "Hundreds of people passed by, and all of them just looked at the stone, complained it was too heavy, then walked away grumbling about the obstruction."),
           ("Chỉ có một người nông dân già tên Rajan dừng lại, không nói gì, lặng lẽ dùng hết sức bình sinh để đẩy hòn đá sang bên vệ đường.",
            "Only an old farmer named Rajan stopped, said nothing, and silently used all his might to push the stone to the side of the road."),
           ("Dưới hòn đá, ông tìm thấy túi vàng cùng một tờ giấy thứ hai ghi: 'Người dời hòn đá này không làm vì vàng, mà làm vì ích lợi cho người đi đường sau --- đó là người đáng được thưởng nhất.'",
            "Under the stone, he found the bag of gold and a second note reading: 'The one who moved this stone did not do it for the gold, but for the benefit of those who travel after --- that is the one most deserving of reward.'")],
          "Hành động vì người khác mà không tính đến lợi ích cá nhân chính là hành động cao thượng nhất và thường được đền đáp xứng đáng nhất.",
          "Acting for others without calculating personal gain is the noblest act and often the one most fittingly rewarded."),

    story("Lời Chúc Phúc Của Bà Mẹ Nghèo", "Truyện dân gian Hàn Quốc",
          "Ngày",
          [("Ngày xưa ở Hàn Quốc, có một bà mẹ nghèo mù lòa nuôi hai đứa con mà không có tiền mua đồ ăn trong mùa đông.",
            "Long ago in Korea, there was a poor blind mother raising two children with no money to buy food in winter."),
           ("Một thương gia qua đường thấy cảnh tượng đó, lặng lẽ để lại một bao gạo trước cửa nhà bà rồi đi.",
            "A passing merchant saw the scene, quietly left a sack of rice at her door, and departed."),
           ("Bà mẹ không biết ai đã làm điều đó, bà chỉ biết ngước mặt lên trời cầu nguyện, ban phúc cho người đã giúp bà.",
            "The mother did not know who had done it; she only looked up to heaven and prayed, blessing whoever had helped her."),
           ("Người thương gia đó, tên là Park Soo-Il, suốt cuộc đời làm ăn luôn gặp may mắn kỳ lạ; mỗi khi gặp nguy hiểm đều thoát nạn một cách khó hiểu.",
            "That merchant, named Park Soo-Il, throughout his business life encountered strange good fortune; whenever he faced danger, he escaped in inexplicable ways."),
           ("Ông nghĩ đó là lời cầu nguyện của người mẹ mù nghèo ngày ấy vẫn đang che chở cho ông.",
            "He believed those were the prayers of that poor blind mother from long ago still shielding him.")],
          "Lời cầu chúc chân thành từ trái tim người được cứu giúp là lá bùa hộ mạng mạnh nhất trên thế gian.",
          "A sincere blessing from the heart of someone helped is the most powerful protective talisman in the world."),

    story("Người Bác Sĩ Và Bệnh Nhân Không Có Tiền", "Albert Schweitzer --- Gabon, châu Phi",
          "Ở",
          [("Ở vùng Lambaréné thuộc Gabon Trung Phi, bác sĩ Albert Schweitzer xây bệnh viện và chữa bệnh miễn phí cho người dân nghèo trong suốt hơn 50 năm.",
            "In the Lambaréné region of Central Africa's Gabon, Doctor Albert Schweitzer built a hospital and treated the poor for free for over 50 years."),
           ("Ông đã từ bỏ sự nghiệp âm nhạc và triết học lừng danh ở châu Âu để làm điều này.",
            "He gave up a celebrated career in music and philosophy in Europe to do this."),
           ("Nhiều người hỏi ông: 'Tại sao ông lại hi sinh như vậy?' Ông chỉ trả lời bằng nụ cười: 'Bởi vì tôi may mắn hơn họ.'",
            "Many asked him: 'Why do you sacrifice like this?' He only answered with a smile: 'Because I am more fortunate than they are.'"),
           ("Năm 1952, ông được trao giải Nobel Hòa bình; ông dùng toàn bộ số tiền thưởng để mở rộng bệnh viện.",
            "In 1952, he was awarded the Nobel Peace Prize; he used the entire prizemoneu to expand the hospital."),
           ("Ông viết trong nhật ký: 'Tôi không cho đi vì muốn nhận lại. Nhưng cuộc đời lạ lùng thay --- càng cho đi tôi càng nhận được nhiều hơn, không phải tiền bạc, mà là sự bình yên trong tâm hồn.'",
            "He wrote in his diary: 'I do not give in order to receive. But how strange life is --- the more I give, the more I receive, not money, but peace within the soul.'")],
          "Người sống vì người khác không phải người mất mát nhiều nhất --- họ là người giàu có nhất vì sở hữu thứ mà tiền bạc không mua nổi.",
          "Those who live for others are not those who lose the most --- they are the richest because they own what money cannot buy."),

    story("Cây Đại Thụ Và Người Du Khách Mệt Mỏi", "Truyện ngụ ngôn Hy Lạp cổ",
          "Hai",
          [("Hai người lữ hành kiệt sức đang đi trên con đường dài dưới trời nắng chói chang thì nhìn thấy một cây đại thụ cao lớn tỏa bóng mát rộng.",
            "Two exhausted travelers walking a long road under a blazing sun spotted a tall great tree casting wide shade."),
           ("Họ ngồi xuống nghỉ ngơi bên dưới, hít thở không khí mát lành và cảm thấy sức lực hồi phục.",
            "They sat down to rest beneath it, breathed the cool air, and felt their strength restore."),
           ("Một người đàn ông nói: 'Cái cây này vô dụng quá, không có trái, không có gỗ tốt, chỉ có bóng mát mà thôi.'",
            "One man said: 'This tree is so useless, no fruit, no valuable timber, only shade.'"),
           ("Người kia lại nói: 'Anh nói sai rồi. Chính cái bóng mát mà anh cho là vô dụng đó đang cứu chúng ta khỏi chết nắng lúc này.'",
            "The other replied: 'You are wrong. It is precisely this shade you call useless that is saving us from heatstroke right now.'"),
           ("Cây đại thụ lúc đó mới rung lá thì thầm: 'Điều tốt lành mà anh không nhìn thấy giá trị ngay lúc này, có thể đang cứu anh mà anh không hay.'",
            "The great tree then rustled its leaves and whispered: 'The goodness whose value you cannot see at this moment may be saving you without your knowledge.'")],
          "Không phải mọi ân huệ đều xuất hiện dưới dạng ta nhận ra ngay; đôi khi điều tốt lành đang bao quanh ta mà ta chẳng hề hay biết.",
          "Not all blessings appear in forms we instantly recognize; sometimes goodness surrounds us without our knowledge."),

    story("Người Chèo Đò Và Triết Gia", "Truyện Phật Giáo --- Ấn Độ",
          "Một",
          [("Một triết gia nổi tiếng hỏi người chèo đò già: 'Ông biết thiên văn không?' Người chèo đò lắc đầu. 'Triết học không?' Lắc đầu. 'Văn học không?' Vẫn lắc đầu.",
            "A famous philosopher asked the old ferryman: 'Do you know astronomy?' The ferryman shook his head. 'Philosophy?' Shook his head. 'Literature?' Still shook his head."),
           ("Nhà triết học chê bai: 'Ôi, ông đã mất đi phần lớn cuộc đời rồi!'",
            "The philosopher mocked: 'Oh, you have wasted most of your life!'"),
           ("Giữa đường, con thuyền bị sóng đánh và bắt đầu chìm. Người chèo đò hỏi: 'Ông có biết bơi không?'",
            "In the middle of the river, waves struck the boat and it began to sink. The ferryman asked: 'Can you swim?'"),
           ("Nhà triết học lắc đầu hoảng loạn. Người chèo đò bình thản nói: 'Thế thì ông mới thực sự mất cả cuộc đời.'",
            "The philosopher shook his head in panic. The ferryman calmly said: 'Then it is you who has truly wasted your whole life.'"),
           ("Khi người chèo đò vớt nhà triết học lên bờ an toàn, ông nói thêm: 'Mỗi người có loại kiến thức của riêng mình. Hãy tôn trọng điều đó trước khi phán xét.'",
            "When the ferryman pulled the philosopher safely to shore, he added: 'Each person has their own kind of knowledge. Respect that before judging.'")],
          "Sự khiêm tốn là tiền lệ của sự học hỏi; kẻ coi thường người khác đang đóng cánh cửa với những bài học quý giá nhất.",
          "Humility is the prerequisite of learning; those who look down on others are shutting the door to the most precious lessons."),

    story("Người Thợ Rèn Và Viên Gạch Cuối Cùng", "Truyện cổ tích Đức",
          "Một",
          [("Một người thợ rèn già tên Hans sắp nghỉ hưu sau 40 năm làm việc cần cù và trung thực.",
            "An old blacksmith named Hans was about to retire after 40 years of diligent and honest work."),
           ("Ngày cuối cùng trước khi rời xưởng, ông tìm thấy một đứa trẻ mồ côi đang co ro dưới mưa trước cổng xưởng.",
            "On his last day before leaving the workshop, he found an orphaned child huddled in the rain at the workshop gate."),
           ("Dù đã mệt mỏi, ông vẫn dẫn cậu vào trong, cho cậu ăn, và dùng những đồng tiền tiết kiệm cuối cùng để mua cho cậu một bộ quần áo ấm.",
            "Despite his exhaustion, he brought the boy inside, fed him, and used his last saved coins to buy the boy warm clothes."),
           ("Mọi người trong làng bảo ông: 'Hans, ông điên rồi, đó là tiền dưỡng già của ông.'",
            "Villagers told him: 'Hans, you're mad, that was your retirement money.'"),
           ("Hans chỉ mỉm cười: 'Tôi đã xây ngôi nhà này bằng 40 năm lao động, nhưng viên gạch quan trọng nhất là viên gạch cuối cùng tôi đặt xuống hôm nay.'",
            "Hans only smiled: 'I built this house with 40 years of labor, but the most important brick is the one I lay down today.'"),
           ("Ba năm sau, cậu bé đã trở thành học trò của một thương gia và tìm đến trả ơn người thợ rèn già bằng cách chăm sóc ông suốt những năm tuổi già.",
            "Three years later, the boy had become a merchant's apprentice and came back to repay the old blacksmith by caring for him through all his elderly years.")],
          "Hành động tốt ở phút cuối của một hành trình có thể là hành động vĩ đại nhất và đơm hoa kết quả ngọt ngào nhất.",
          "A good deed at the final moment of a journey may be the greatest act and the one bearing the sweetest fruit."),

    story("Bãi Sao Biển Và Cô Bé", "Truyện ngụ ngôn hiện đại --- Loren Eiseley",
          "Sáng",
          [("Sáng sớm trên bãi biển sau cơn bão, hàng nghìn con sao biển bị sóng ném lên bờ đang chết dần trong ánh nắng.",
            "Early morning on the beach after a storm, thousands of starfish thrown ashore by the waves were slowly dying in the sun."),
           ("Một cô bé đang cúi xuống nhặt từng con sao biển một rồi ném chúng trở lại đại dương.",
            "A little girl was bending down picking up each starfish one by one and throwing them back into the ocean."),
           ("Một ông lão đi qua hỏi: 'Cháu làm gì vậy? Có hàng nghìn con sao biển, cháu không thể cứu tất cả được đâu.'",
            "An old man passing by asked: 'What are you doing? There are thousands of starfish, you cannot save them all.'"),
           ("Cô bé nhặt thêm một con, ném xuống biển và nói: 'Nhưng con cứu được con này.'",
            "The girl picked up another one, threw it into the sea and said: 'But I saved this one.'"),
           ("Ông lão đứng lặng một lúc, rồi cúi xuống nhặt một con sao biển khác và ném ra biển.",
            "The old man stood quietly for a moment, then bent down, picked up another starfish and tossed it into the sea."),
           ("Hai người cứ thế tiếp tục, và cùng nhau họ cứu được hơn một ngàn con sao biển trong buổi sáng hôm đó.",
            "The two continued like this, and together they saved more than a thousand starfish that morning.")],
          "Đừng để cái chưa làm được ngăn cản bạn làm điều bạn đang làm được; mỗi hành động tốt dù nhỏ bé đều có ý nghĩa với ai đó.",
          "Do not let what you cannot do prevent you from doing what you can; every good act, however small, matters to someone."),
    ]
)

# ================================================================
# CHƯƠNG 2: HÀNH ĐỘNG NHỎ, HỆ QUẢ LỚN
# ================================================================
ch2 = chapter(
    "Hành Động Nhỏ, Hệ Quả Lớn",
    "Small Actions, Large Consequences",
    "Một con bướm vỗ cánh ở Brazil có thể gây ra một cơn lốc xoáy ở Texas.",
    "A butterfly flapping its wings in Brazil can cause a tornado in Texas.",
    [
    story("Chiếc Đinh Và Vương Quốc", "Tục Ngữ Anh --- Thế kỷ 14",
          "Vì",
          [("Vì thiếu một chiếc đinh đóng móng ngựa, con ngựa bị mất móng.",
            "For want of a nail, the horseshoe was lost."),
           ("Vì mất móng ngựa, con ngựa bị ngã.",
            "For want of the horseshoe, the horse was lost."),
           ("Vì con ngựa bị ngã, người kỵ sĩ mang thư không đến được kịp.",
            "For want of the horse, the messenger was lost."),
           ("Vì thư không đến được, trận chiến bị thua.",
            "For want of the messenger, the battle was lost."),
           ("Vì thua trận, vương quốc sụp đổ.",
            "For want of the battle, the kingdom was lost."),
           ("Và tất cả chỉ vì một chiếc đinh nhỏ bé bị bỏ sót.",
            "And all for the want of one tiny horseshoe nail.")],
          "Chính những thứ nhỏ bé nhất bị bỏ qua lại thường là điểm khởi đầu của những thảm họa lớn nhất.",
          "It is precisely the smallest things overlooked that are often the starting point of the greatest catastrophes."),

    story("Bức Thư Của Gavrilo Và Chiến Tranh Thế Giới Thứ Nhất", "Lịch sử --- Sarajevo, 1914",
          "Ngày",
          [("Ngày 28 tháng 6 năm 1914, Thái tử Franz Ferdinand của Áo-Hung đến thăm Sarajevo.",
            "On June 28, 1914, Archduke Franz Ferdinand of Austria-Hungary was visiting Sarajevo."),
           ("Đoàn xe của ông đã thoát khỏi một vụ ám sát đầu tiên vào buổi sáng.",
            "His motorcade had escaped a first assassination attempt that morning."),
           ("Khi xe quay đầu để đến bệnh viện thăm những người bị thương trong vụ ám sát đó, tài xế lạc đường và dừng lại đúng trước quán cà phê nơi Gavrilo Princip đang ngồi.",
            "When the car turned around to visit the hospital for those wounded in that earlier attack, the driver took a wrong turn and stopped directly in front of the café where Gavrilo Princip was sitting."),
           ("Ngay khoảnh khắc xe dừng lại trong vài giây để quay đầu, Princip bước ra và bắn chết Thái tử.",
            "In the exact moment the car stopped for a few seconds to turn around, Princip stepped out and shot the Archduke dead."),
           ("Một chiếc xe lạc đường, một khoảnh khắc dừng xe --- đã dẫn đến một cuộc chiến tranh giết hại 20 triệu người.",
            "One wrong turn, one moment of stopping --- led to a war that killed 20 million people.")],
          "Lịch sử thay đổi bởi những quyết định nhỏ trong những khoảnh khắc chỉ kéo dài vài giây.",
          "History changes because of small decisions in moments that last just a few seconds."),

    story("Bài Toán Cộng Của Einstein Và Bức Thư Gửi Tổng Thống", "Albert Einstein --- Hoa Kỳ, 1939",
          "Năm",
          [("Năm 1939, nhà vật lý Leo Szilard lo sợ rằng Đức Quốc xã đang phát triển bom nguyên tử.",
            "In 1939, physicist Leo Szilard feared that Nazi Germany was developing an atomic bomb."),
           ("Ông thuyết phục Einstein cùng ký một bức thư gửi Tổng thống Roosevelt cảnh báo về nguy cơ này.",
            "He convinced Einstein to co-sign a letter to President Roosevelt warning about this danger."),
           ("Bức thư đó, chỉ là hai trang giấy, đã thuyết phục Roosevelt khởi động Dự án Manhattan.",
            "That letter, just two pages, convinced Roosevelt to launch the Manhattan Project."),
           ("Dự án Manhattan tốn hai tỷ đô la và huy động 130.000 người, dẫn đến việc tạo ra bom nguyên tử.",
            "The Manhattan Project cost two billion dollars and mobilized 130,000 people, leading to the creation of the atomic bomb."),
           ("Hai quả bom đã thay đổi cục diện Thế chiến II và định hình lại toàn bộ trật tự địa chính trị của thế giới hiện đại.",
            "Two bombs changed the course of World War II and reshaped the entire geopolitical order of the modern world."),
           ("Tất cả bắt đầu từ hai trang giấy được ký tên.",
            "It all started from two signed pages.")],
          "Đôi khi một hành động đơn giản --- ký tên vào một tờ giấy --- có thể thay đổi hướng đi của cả thế giới.",
          "Sometimes a simple action --- signing a piece of paper --- can alter the direction of the entire world."),

    story("Cái Ghế Trống Và Phong Trào Dân Quyền", "Rosa Parks --- Montgomery, 1955",
          "Ngày",
          [("Ngày 1 tháng 12 năm 1955, Rosa Parks, một thợ may mệt mỏi sau một ngày làm việc dài, ngồi trên một chỗ ngồi dành cho người da trắng trên xe buýt ở Montgomery, Alabama.",
            "On December 1, 1955, Rosa Parks, a tired seamstress after a long day of work, sat in a seat reserved for white passengers on a bus in Montgomery, Alabama."),
           ("Tài xế yêu cầu bà đứng dậy, bà từ chối.",
            "The driver asked her to stand up; she refused."),
           ("Sự từ chối đó dẫn đến việc bà bị bắt.",
            "That refusal led to her arrest."),
           ("Tin tức về vụ bắt giữ lan ra khắp thành phố, dẫn đến cuộc Tẩy chay xe buýt Montgomery kéo dài 381 ngày.",
            "News of the arrest spread across the city, leading to the 381-day Montgomery Bus Boycott."),
           ("Cuộc tẩy chay đó đưa Martin Luther King lên vũ đài và khởi động Phong trào Dân quyền lớn nhất lịch sử nước Mỹ.",
            "That boycott propelled Martin Luther King onto the stage and launched the greatest Civil Rights Movement in American history."),
           ("Một người phụ nữ mệt mỏi chọn ngồi xuống đã làm cả một quốc gia đứng dậy.",
            "One tired woman's choice to remain seated made an entire nation stand up.")],
          "Ý chí không nhường bộ của một người bình thường trong một khoảnh khắc bình thường có thể châm ngòi cho một cuộc cách mạng.",
          "The unyielding will of one ordinary person in one ordinary moment can ignite a revolution."),

    story("Hạt Giống Của Wangari Maathai", "Wangari Maathai --- Kenya, 1977",
          "Năm",
          [("Năm 1977, Wangari Maathai, một phụ nữ Kenya bình thường, bắt đầu một hành động nhỏ: trồng bảy cây xanh trong vườn nhà bà.",
            "In 1977, Wangari Maathai, an ordinary Kenyan woman, began a small action: planting seven trees in her backyard."),
           ("Bà mời những người phụ nữ hàng xóm cùng tham gia trồng cây; họ gọi phong trào này là 'Vành đai Xanh'.",
            "She invited neighboring women to join in planting trees; they called this movement the 'Green Belt Movement.'"),
           ("Chỉ bắt đầu từ bảy cây, phong trào đó đã lan rộng toàn Kenya và nhiều nước châu Phi.",
            "Starting from just seven trees, the movement spread across Kenya and many African countries."),
           ("Sau hơn 30 năm, phong trào đã trồng được 51 triệu cây và cải tạo lại những vùng đất bị hoang hóa.",
            "After more than 30 years, the movement had planted 51 million trees and restored degraded lands."),
           ("Năm 2004, Wangari Maathai trở thành người phụ nữ châu Phi đầu tiên giành giải Nobel Hòa bình.",
            "In 2004, Wangari Maathai became the first African woman to win the Nobel Peace Prize."),
           ("Tất cả bắt đầu từ bảy cây nhỏ.",
            "It all started with seven small trees.")],
          "Không có hành động nào quá nhỏ để thay đổi thế giới; bảy cây xanh có thể trở thành 51 triệu cây.",
          "No action is too small to change the world; seven trees can become 51 million."),

    story("Tiếng Chuông Của Alexander Graham Bell", "Alexander Graham Bell --- Canada/Mỹ, 1876",
          "Ngày",
          [("Ngày 10 tháng 3 năm 1876, Alexander Graham Bell trong phòng thí nghiệm tình cờ làm đổ axit lên quần, ông gọi to vào chiếc thiết bị dây nối sang phòng bên: 'Watson, xin hãy đến đây. Tôi cần anh!'",
            "On March 10, 1876, Alexander Graham Bell in his laboratory accidentally spilled acid on his trousers, and called out into a wire-connected device into the next room: 'Watson, come here. I need you!'"),
           ("Đây là câu nói đầu tiên được truyền đi qua điện thoại trong lịch sử loài người.",
            "This was the first sentence ever transmitted by telephone in human history."),
           ("Người trợ lý Watson trong phòng bên nghe rõ và chạy sang, không biết mình vừa chứng kiến khoảnh khắc thay đổi thế giới.",
            "His assistant Watson in the next room heard clearly and ran over, not knowing he had just witnessed a world-changing moment."),
           ("Từ tiếng gọi khẩn cấp vì làm đổ axit đó, điện thoại ra đời, rồi đến internet, rồi điện thoại thông minh --- toàn bộ cuộc cách mạng truyền thông kết nối toàn thế giới hôm nay.",
            "From that urgent call made because of spilled acid, the telephone was born, then the internet, then the smartphone --- the entire communication revolution connecting the entire world today.")],
          "Đôi khi những tai nạn vụng về nhỏ nhặt nhất lại là nguồn gốc của những phát minh vĩ đại nhất.",
          "Sometimes the clumsiest little accidents are the origin of the greatest inventions."),

    story("Người Đầu Bếp Và Công Thức Coca-Cola", "John Pemberton --- Atlanta, 1886",
          "Năm",
          [("Năm 1886, dược sĩ John Pemberton đang pha chế một loại thuốc si-rô chữa đau đầu trong phòng thí nghiệm nhỏ ở Atlanta.",
            "In 1886, pharmacist John Pemberton was preparing a syrup medicine for headaches in a small laboratory in Atlanta."),
           ("Một nhân viên vô tình pha si-rô đó với nước có ga thay vì nước thường.",
            "An employee accidentally mixed that syrup with carbonated water instead of plain water."),
           ("Cả hai uống thử và thấy nó có hương vị thú vị không ngờ.",
            "Both tried it and found it had an unexpectedly pleasant flavor."),
           ("Pemberton đặt tên cho nó là Coca-Cola và bán tại quầy thuốc với giá 5 xu một ly.",
            "Pemberton named it Coca-Cola and sold it at the pharmacy counter for 5 cents a glass."),
           ("Hôm đó ông bán được chín ly.",
            "That day he sold nine glasses."),
           ("Hôm nay, Coca-Cola bán hơn 1,8 tỷ ly mỗi ngày tại hơn 200 quốc gia trên toàn thế giới.",
            "Today, Coca-Cola sells more than 1.8 billion servings every day in over 200 countries worldwide.")],
          "Sự vô tình pha nhầm nguyên liệu của một nhân viên đã tạo ra đế chế thức uống lớn nhất thế giới.",
          "An employee's accidental mixing of ingredients created the world's largest beverage empire."),

    story("Viên Đạn Bị Bắn Lạc Và Nền Y Học Hiện Đại", "Alexis St. Martin --- Canada, 1822",
          "Năm",
          [("Năm 1822, một người thợ săn thú lông tên Alexis St. Martin bị bắn nhầm vào bụng từ khoảng cách gần, tạo ra một vết thương kỳ lạ không lành hẳn.",
            "In 1822, a fur trapper named Alexis St. Martin was accidentally shot in the abdomen at close range, creating a strange wound that never fully healed."),
           ("Bác sĩ William Beaumont chữa trị cho anh và chú ý rằng qua vết thương hở đó, ông có thể quan sát trực tiếp hoạt động tiêu hóa trong dạ dày.",
            "Doctor William Beaumont treated him and noticed that through that open wound, he could directly observe digestive activity in the stomach."),
           ("Beaumont đã thực hiện hơn 230 thí nghiệm trực tiếp trên dạ dày của St. Martin trong suốt 11 năm.",
            "Beaumont conducted over 230 direct experiments on St. Martin's stomach over 11 years."),
           ("Những nghiên cứu đó đặt nền tảng cho toàn bộ khoa học tiêu hóa hiện đại.",
            "Those studies laid the foundation for all modern gastroenterology."),
           ("Một viên đạn bị bắn lạc đã tình cờ mở ra một trong những cánh cửa lớn nhất của y học.",
            "A stray bullet accidentally opened one of the greatest doors in medicine.")],
          "Những tai nạn tưởng chừng là bi kịch đôi khi lại là những cơ hội đột phá mà khoa học không thể tạo ra trong phòng thí nghiệm.",
          "Accidents that seem like tragedies are sometimes breakthroughs that science could not create in the laboratory."),

    story("Con Sâu Và Sợi Tơ Của Hoàng Hậu Leizu", "Truyền thuyết Trung Quốc --- 2700 TCN",
          "Tương",
          [("Tương truyền rằng Hoàng hậu Leizu, vợ của Hoàng đế Huangdi, đang uống trà dưới gốc cây dâu tằm khi một kén tằm rơi vào chén trà của bà.",
            "Legend has it that Empress Leizu, wife of Emperor Huangdi, was drinking tea under a mulberry tree when a silkworm cocoon fell into her cup of tea."),
           ("Khi bà cố lấy kén ra, sợi tơ dài bắt đầu tháo ra từ kén, mỏng như gió và óng ánh như cầu vồng.",
            "As she tried to remove the cocoon, a long silk thread began unraveling from it, thin as a breath and shimmering like a rainbow."),
           ("Bà theo dõi và phát hiện ra cách nuôi tằm để lấy tơ.",
            "She observed and discovered how to raise silkworms for their thread."),
           ("Từ một kén tơ rơi vào chén trà, Trung Quốc đã có ngành tơ lụa kéo dài 5.000 năm và Con đường Tơ lụa huyền thoại nối liền Đông Tây.",
            "From one cocoon falling into a cup of tea, China gained a 5,000-year silk industry and the legendary Silk Road connecting East and West."),
           ("Một tai nạn nhỏ của thiên nhiên đã mở ra con đường giao thương và văn minh vĩ đại nhất lịch sử cổ đại.",
            "One small accident of nature opened the greatest trade and civilizational route in ancient history.")],
          "Những phát minh vĩ đại nhất không đến từ sự cố gắng tính toán mà đến từ sự chú ý đủ tinh tế để nhận ra điều kỳ diệu trong những khoảnh khắc bình thường.",
          "The greatest inventions come not from calculated effort but from attention refined enough to recognize the miraculous in ordinary moments."),

    story("Nụ Cười Và Cái악Bắt Tay", "Nghiên cứu Tâm lý học xã hội --- Hoa Kỳ",
          "Trong",
          [("Trong một thí nghiệm tâm lý học xã hội nổi tiếng, các nhà khoa học nhờ người thực nghiệm mỉm cười hoặc cau mày khi gặp người lạ trên phố.",
            "In a famous social psychology experiment, scientists asked test subjects to smile or frown when meeting strangers on the street."),
           ("Những người nhận được nụ cười thường tự động mỉm cười lại và cảm thấy tâm trạng tốt hơn trong cả ngày.",
            "Those who received a smile automatically smiled back and felt better mood throughout their day."),
           ("Tâm trạng tốt đó lan truyền qua các gia đình và đồng nghiệp của họ.",
            "That good mood spread through their families and colleagues."),
           ("Các nhà khoa học tính toán rằng một nụ cười duy nhất có thể ảnh hưởng đến tâm trạng của hàng trăm người trong xã hội lan tỏa.",
            "Scientists calculated that a single smile can affect the mood of hundreds of people in a ripple effect through society."),
           ("Ngược lại, một lời nói gay gắt hoặc bộ mặt cau có cũng lan ra theo cách tương tự --- hủy hoại tâm trạng của hàng trăm người.",
            "Conversely, a harsh word or a scowling face also spreads in the same way --- ruining the mood of hundreds of people.")],
          "Năng lượng cảm xúc của bạn không bao giờ ở lại với bạn một mình; nó lan tỏa ra xung quanh như sóng nước và ảnh hưởng đến hàng trăm người bạn không bao giờ gặp.",
          "Your emotional energy never stays with you alone; it ripples outward like water waves and affects hundreds of people you will never meet."),
    ]
)

# ================================================================
# CHƯƠNG 3: THÓI QUEN TẠO NÊN SỐ PHẬN
# ================================================================
ch3 = chapter(
    "Thói Quen Tạo Nên Số Phận",
    "Habit Shapes Destiny",
    "Gieo suy nghĩ, gặt hành động. Gieo hành động, gặt thói quen. Gieo thói quen, gặt số phận.",
    "Sow a thought, reap an action. Sow an action, reap a habit. Sow a habit, reap a destiny.",
    [
    story("Aristotle Và Nền Tảng Của Đức Hạnh", "Aristotle --- Hy Lạp, 350 TCN",
          "Triết",
          [("Triết gia Aristotle đã đưa ra một câu nói nổi tiếng mà nhân loại vẫn còn dùng đến ngày nay: 'Chúng ta là những gì chúng ta liên tục làm.'",
            "Philosopher Aristotle offered a famous saying that humanity still uses today: 'We are what we repeatedly do.'"),
           ("Ông dạy rằng đức hạnh không phải là một hành động đơn lẻ mà là một thói quen.",
            "He taught that virtue is not a single act but a habit."),
           ("Người dũng cảm không phải là người can đảm một lần duy nhất, mà là người luyện tập sự can đảm mỗi ngày.",
            "A brave person is not one who is courageous only once, but one who practices courage every day."),
           ("Người tốt bụng không phải là người cho đi một lần, mà là người biến lòng tốt thành phần không thể thiếu trong mỗi ngày sống.",
            "A kind person is not one who gives once, but one who makes kindness an inseparable part of each day of living."),
           ("Và chính những thói quen nhỏ đó, lặp lại ngày qua ngày, tạo nên phẩm cách, và phẩm cách tạo nên số phận.",
            "And those small habits, repeated day after day, create character, and character creates destiny.")],
          "Sự xuất sắc không phải là một hành động, mà là một thói quen được rèn giũa kiên trì trong hàng nghìn ngày bình thường.",
          "Excellence is not an act, but a habit forged persistently through thousands of ordinary days."),

    story("Bút Chì Và Thói Quen Viết Của Benjamin Franklin", "Benjamin Franklin --- Hoa Kỳ, thế kỷ 18",
          "Từ",
          [("Từ năm 20 tuổi, Benjamin Franklin lập ra một cuốn sổ tay nhỏ liệt kê 13 đức tính ông muốn rèn luyện: tiết độ, im lặng, trật tự, quyết tâm, tiết kiệm, cần cù, chân thành, công bằng, điều độ, sạch sẽ, bình tĩnh, trinh tiết và khiêm tốn.",
            "From age 20, Benjamin Franklin kept a small notebook listing 13 virtues he wanted to cultivate: temperance, silence, order, resolution, frugality, industry, sincerity, justice, moderation, cleanliness, tranquility, chastity and humility."),
           ("Mỗi tuần ông tập trung vào một đức tính, đánh dấu mỗi khi ông vi phạm vào đức tính đó.",
            "Each week he focused on one virtue, marking every time he violated that virtue."),
           ("Ông làm điều này liên tục suốt nhiều năm, không bỏ qua một tuần nào.",
            "He did this continuously for many years, never skipping a single week."),
           ("Franklin sau này trở thành nhà ngoại giao, nhà khoa học, nhà phát minh, nhà triết học được ngưỡng mộ nhất nước Mỹ.",
            "Franklin later became the most admired diplomat, scientist, inventor and philosopher in America."),
           ("Khi được hỏi bí quyết thành công, ông chỉ vào cuốn sổ tay nhỏ màu nâu cũ kỹ.",
            "When asked the secret to his success, he pointed to the small old brown notebook.")],
          "Một cuốn sổ nhỏ cộng với sự kỷ luật lặp lại mỗi tuần trong nhiều năm có thể tạo nên một vĩ nhân.",
          "A small notebook combined with the discipline of weekly repetition over many years can create a great person."),

    story("Dấu Vết Của Thói Quen Trong Não Bộ", "Khoa học thần kinh hiện đại",
          "Các",
          [("Các nhà khoa học thần kinh đã phát hiện ra rằng mỗi khi bạn lặp lại một hành động, não bộ tạo ra những con đường thần kinh mới và củng cố chúng.",
            "Neuroscientists have discovered that every time you repeat an action, the brain creates new neural pathways and reinforces them."),
           ("Khi bạn lặp lại hành động đó đủ nhiều lần, con đường thần kinh trở nên như một xa lộ --- tín hiệu chạy qua gần như tự động không cần tư duy.",
            "When you repeat that action enough times, the neural pathway becomes like a highway --- signals travel through it almost automatically without deliberate thinking."),
           ("Đó là lý do tại sao một nghệ sĩ dương cầm lành nghề đánh đàn mà không cần nhìn bàn tay --- thói quen đã được 'khắc' vào não.",
            "That is why a skilled pianist plays without looking at their hands --- the habit has been 'engraved' into the brain."),
           ("Nhưng điều này cũng có nghĩa là những thói quen xấu được lặp đi lặp lại cũng sẽ trở thành những đường thần kinh mạnh mẽ không kém.",
            "But this also means that bad habits repeated over and over become equally powerful neural pathways."),
           ("Não bộ không phân biệt thói quen tốt hay xấu --- nó chỉ củng cố những gì được lặp lại.",
            "The brain does not distinguish good habits from bad --- it only reinforces what is repeated.")],
          "Hãy cẩn thận với những gì bạn lặp lại, vì não bộ bạn đang âm thầm khắc chạm chúng thành định mệnh của bạn.",
          "Be careful with what you repeat, because your brain is silently engraving them into your destiny."),

    story("Thói Quen Đọc Sách Của Abraham Lincoln", "Abraham Lincoln --- Hoa Kỳ, thế kỷ 19",
          "Abraham",
          [("Abraham Lincoln lớn lên trong một gia đình nghèo ở biên giới hoang vu, không có điều kiện đến trường học chính quy.",
            "Abraham Lincoln grew up in a poor family on the wild frontier, with no access to formal schooling."),
           ("Nhưng ông có một thói quen không ai có thể lấy đi: mỗi tối, dù đã làm việc cực nhọc cả ngày, ông vẫn đọc sách dưới ánh lửa đến khi mắt không còn đọc nổi.",
            "But he had a habit no one could take away: every evening, no matter how exhaustedly he had worked all day, he read by firelight until his eyes could read no more."),
           ("Ông đọc Kinh Thánh, Shakespeare, luật pháp, lịch sử, triết học --- bất cứ cuốn sách nào ông có thể mượn được.",
            "He read the Bible, Shakespeare, law, history, philosophy --- any book he could borrow."),
           ("Bằng thói quen đọc sách kiên trì đó, ông tự học luật, tự đào tạo thành luật sư, rồi nghị sĩ, rồi Tổng thống thứ 16 của Hoa Kỳ.",
            "Through that persistent reading habit, he self-taught law, trained himself as a lawyer, then congressman, then the 16th President of the United States."),
           ("Khi được hỏi bí quyết thành công, Lincoln nói: 'Tôi học từ sách vở, từ cuộc đời và từ thói quen không bao giờ từ bỏ việc học.'",
            "When asked the secret to his success, Lincoln said: 'I learned from books, from life, and from the habit of never giving up learning.'")],
          "Giáo dục không nhất thiết đến từ trường học; nó đến từ thói quen tìm kiếm kiến thức không ngừng nghỉ mỗi ngày.",
          "Education does not necessarily come from school; it comes from the habit of seeking knowledge tirelessly every day."),

    story("Miyamoto Musashi Và Vạn Lần Luyện Kiếm", "Miyamoto Musashi --- Nhật Bản, thế kỷ 17",
          "Miyamoto",
          [("Miyamoto Musashi, kiếm sĩ vĩ đại nhất lịch sử Nhật Bản, tham gia 61 trận đấu kiếm trong đời và không thua một trận nào.",
            "Miyamoto Musashi, the greatest swordsman in Japanese history, participated in 61 sword duels throughout his life and lost not one."),
           ("Ông không sinh ra với tài năng thiên phú; ông đã rèn giũa thói quen luyện kiếm từ năm 13 tuổi mỗi ngày không nghỉ.",
            "He was not born with natural talent; he forged the habit of practicing swordsmanship daily without rest from age 13."),
           ("Ông viết trong 'Ngũ Luân Thư' rằng: 'Bạn không thể hiểu thực sự bất cứ điều gì chỉ qua vài lần thực hành; bạn phải thực hành nó hàng nghìn lần.'",
            "He wrote in 'The Book of Five Rings': 'You cannot truly understand anything through only a few practices; you must practice it thousands of times.'"),
           ("Ông không chỉ luyện kiếm mà còn luyện hội họa, viết thư pháp, làm gốm, điêu khắc --- ông áp dụng nguyên lý 'vạn lần luyện tập' vào mọi lĩnh vực.",
            "He not only trained in swordsmanship but also practiced painting, calligraphy, pottery, sculpture --- applying the principle of 'ten thousand repetitions' to every field."),
           ("Và mỗi thứ ông làm đều đạt đến đỉnh cao nghệ thuật.",
            "And everything he did reached the pinnacle of artistic mastery.")],
          "Thiên tài không phải là cái gì đó bạn được sinh ra cùng --- nó là thứ bạn tạo ra qua hàng vạn giờ thực hành kiên trì.",
          "Genius is not something you are born with --- it is something you create through tens of thousands of hours of persistent practice."),

    story("Người Bán Hàng Rong Và Thói Quen Tiết Kiệm", "Ông Amos --- Nghiên cứu kinh tế học hành vi",
          "Tại",
          [("Tại một vùng ngoại ô nghèo ở Chicago, một người bán hàng rong tên Amos kiếm được chưa đến 15.000 đô mỗi năm.",
            "In a poor suburb of Chicago, a street vendor named Amos earned less than 15,000 dollars a year."),
           ("Nhưng từ ngày đầu đi làm, ông có một thói quen kỳ lạ: trước khi tiêu một đồng tiền nào, ông luôn để riêng 10 phần trăm vào một chiếc hộp kín.",
            "But from his first day of work, he had a strange habit: before spending any money, he always set aside 10 percent into a sealed box."),
           ("Không quan trọng thu nhập tuần đó bao nhiêu, không quan trọng hóa đơn bao nhiêu --- 10 phần trăm luôn được cất trước tiên.",
            "No matter how much that week's income was, no matter how many bills there were --- 10 percent was always saved first."),
           ("Sau 40 năm bán hàng rong, Amos về hưu với hơn 400.000 đô trong tài khoản tiết kiệm.",
            "After 40 years of street vending, Amos retired with over 400,000 dollars in his savings account."),
           ("Ông không bao giờ có thu nhập cao; ông chỉ có một thói quen giản dị được thực hiện không ngừng nghỉ.",
            "He never had a high income; he only had one simple habit performed without interruption.")],
          "Thói quen nhỏ được thực hiện nhất quán trong thời gian dài có sức mạnh tạo ra những kết quả mà tài năng và may mắn không thể tạo ra.",
          "A small habit consistently practiced over a long time has the power to produce results that talent and luck cannot."),

    story("Sức Mạnh Của Thói Quen Buổi Sáng", "Napoleon, Darwin, Darwin --- Nhiều tên tuổi lớn",
          "Hầu",
          [("Hầu hết các vĩ nhân trong lịch sử đều chia sẻ một điểm chung kỳ lạ: họ có thói quen buổi sáng rất cố định và nghiêm ngặt.",
            "Most great figures in history share a strange commonality: they had very fixed and strict morning routines."),
           ("Napoleon thức dậy lúc 6 giờ sáng, đọc báo cáo quân sự ngay trên giường trước khi đặt chân xuống đất.",
            "Napoleon woke at 6 AM, reading military reports in bed before placing his feet on the floor."),
           ("Charles Darwin đi bộ một tiếng rưỡi mỗi sáng trên cùng một con đường mà ông gọi là 'con đường tư duy', sau đó mới bắt đầu viết.",
            "Charles Darwin walked for an hour and a half every morning on the same path he called his 'thinking path', then started writing."),
           ("Beethoven đếm đúng 60 hạt cà phê mỗi sáng để pha cà phê của mình.",
            "Beethoven counted exactly 60 coffee beans every morning to brew his coffee."),
           ("Những thói quen buổi sáng tưởng chừng vô nghĩa đó thực ra là đang thiết lập trạng thái tinh thần tối ưu cho cả ngày làm việc sáng tạo.",
            "Those seemingly meaningless morning habits were actually setting the optimal mental state for a full day of creative work.")],
          "Cách bạn bắt đầu buổi sáng gần như định hình cách bạn sống cả ngày; những người vĩ đại biết điều này và bảo vệ thói quen buổi sáng của họ như bảo vệ kho báu.",
          "How you begin the morning nearly shapes how you live the entire day; great people know this and protect their morning routines like guarding treasure."),

    story("Con Nhện Và Vua Bruce", "Robert the Bruce --- Scotland, 1314",
          "Sau",
          [("Sau sáu lần thất bại trên chiến trường và mất hết binh lính, Vua Robert the Bruce của Scotland trốn chạy và ẩn náu trong một hang động cô đơn.",
            "After six defeats on the battlefield and losing all his soldiers, King Robert the Bruce of Scotland was fleeing and hiding in a lonely cave."),
           ("Ông đang gần như từ bỏ hy vọng giải phóng Scotland khỏi ách chiếm đóng của Anh.",
            "He was close to giving up hope of liberating Scotland from English occupation."),
           ("Trong hang đá, ông nhìn thấy một con nhện đang cố giăng tơ từ đầu này sang đầu kia của hang, nhưng cứ giăng xong lại đứt và phải làm lại.",
            "In the cave, he watched a spider trying to spin a web from one side of the cave to the other, but the thread kept breaking and it had to start over."),
           ("Con nhện thất bại sáu lần --- đúng bằng số lần Vua Bruce thất bại --- nhưng lần thứ bảy, sợi tơ giăng thành công.",
            "The spider failed six times --- exactly the same number of times King Bruce had failed --- but on the seventh attempt, the thread held successfully."),
           ("Vua Bruce đứng dậy, tập hợp lại quân đội, và năm 1314 giành chiến thắng lừng lẫy tại trận Bannockburn, giành độc lập cho Scotland.",
            "King Bruce stood up, regrouped his army, and in 1314 won a glorious victory at the Battle of Bannockburn, winning independence for Scotland.")],
          "Thiên nhiên dạy ta bài học qua những sinh vật nhỏ nhất; đừng bao giờ từ bỏ thói quen cố gắng dù đã thất bại bao nhiêu lần.",
          "Nature teaches us lessons through the smallest creatures; never give up the habit of trying no matter how many times you have failed."),

    story("Thói Quen Lắng Nghe Của Oprah Winfrey", "Oprah Winfrey --- Hoa Kỳ",
          "Oprah",
          [("Oprah Winfrey lớn lên trong nghèo đói và bạo lực, không ai tin cô có thể thành công.",
            "Oprah Winfrey grew up in poverty and violence, and no one believed she could succeed."),
           ("Nhưng từ tuổi thiếu niên, cô xây dựng một thói quen mà cô gọi là 'lắng nghe thực sự': trong mọi cuộc trò chuyện, cô tập trung hoàn toàn vào người đối diện, như thể họ là người quan trọng nhất trên đời lúc đó.",
            "But from her teenage years, she built a habit she called 'true listening': in every conversation, she entirely focused on the person in front of her, as if they were the most important person in the world at that moment."),
           ("Thói quen này khiến mọi người cảm thấy được trân trọng và hiểu thấu, điều khiến chương trình của cô thu hút hàng triệu người xem trung thành.",
            "This habit made people feel valued and deeply understood, which is what drew millions of loyal viewers to her show."),
           ("Theo thời gian, thói quen lắng nghe đó trở thành thương hiệu cá nhân mạnh nhất của cô và nền tảng của đế chế truyền thông tỷ đô.",
            "Over time, that listening habit became her strongest personal brand and the foundation of her billion-dollar media empire."),
           ("'Tôi không thành công vì tôi thông minh hay may mắn,' Oprah nói, 'tôi thành công vì tôi dành cả cuộc đời học cách lắng nghe.'",
            "'I did not succeed because I am smart or lucky,' Oprah said, 'I succeeded because I spent my whole life learning how to listen.'")],
          "Một thói quen đơn giản như 'lắng nghe thực sự' khi được thực hành đủ lâu và đủ chân thành có thể tạo nên một đế chế.",
          "A simple habit like 'true listening', when practiced long enough and sincerely enough, can build an empire."),

    story("Thói Quen Ghi Chép Của Leonardo da Vinci", "Leonardo da Vinci --- Ý, thế kỷ 15-16",
          "Leonardo",
          [("Leonardo da Vinci luôn mang theo một cuốn sổ tay nhỏ bên mình trong suốt cuộc đời, và ông có thói quen ghi chép mọi thứ ông quan sát, tưởng tượng hoặc tự hỏi.",
            "Leonardo da Vinci always carried a small notebook throughout his life, and he had the habit of recording everything he observed, imagined or wondered about."),
           ("Chim bay như thế nào, nước chảy ra sao, cơ bắp người vận động thế nào, ánh sáng rơi vào mặt người như thế nào --- tất cả đều được vẽ và ghi chú.",
            "How birds fly, how water flows, how human muscles move, how light falls on a human face --- all were sketched and annotated."),
           ("Ông để lại khoảng 13.000 trang ghi chép và phác thảo.",
            "He left behind approximately 13,000 pages of notes and sketches."),
           ("Từ những trang ghi chép đó, ông phát minh ra ý tưởng về máy bay, xe tăng, năng lượng mặt trời, máy tính, và hàng trăm thứ khác --- 400 năm trước khi chúng thực sự được tạo ra.",
            "From those pages, he invented ideas for the airplane, tank, solar energy, calculator, and hundreds of other things --- 400 years before they were actually created."),
           ("Thiên tài của Leonardo không phải là trí tuệ siêu phàm --- đó là thói quen không bao giờ ngừng quan sát và ghi chép.",
            "Leonardo's genius was not superhuman intelligence --- it was the habit of never stopping to observe and record.")],
          "Bộ óc vĩ đại nhất trong lịch sử nhân loại không dựa vào trí nhớ --- nó dựa vào thói quen ghi lại mọi điều tò mò.",
          "The greatest mind in human history did not rely on memory --- it relied on the habit of recording every curiosity."),
    ]
)

# ================================================================
# CHƯƠNG 4: TÔI LÀ CON NGƯỜI TÔI CHỌN
# ================================================================
ch4 = chapter(
    "Tôi Là Con Người Tôi Chọn",
    "I Am Who I Choose to Be",
    "Giữa kích thích và phản ứng, luôn có một khoảng trống. Trong khoảng trống đó nằm quyền tự do và sức mạnh của chúng ta.",
    "Between stimulus and response, there is a space. In that space lies our freedom and power.",
    [
    story("Viktor Frankl Và Tự Do Cuối Cùng", "Viktor Frankl --- Áo, 1942-1945",
          "Viktor",
          [("Viktor Frankl, một bác sĩ tâm thần người Do Thái, bị đưa vào trại tập trung Auschwitz của Đức Quốc xã năm 1942.",
            "Viktor Frankl, a Jewish psychiatrist, was taken to the Auschwitz concentration camp of Nazi Germany in 1942."),
           ("Bọn lính lấy đi của ông tất cả: quần áo, nhẫn cưới, tập bản thảo nghiên cứu cả đời ông, và cuối cùng là mạng sống của vợ, cha mẹ và anh em ông.",
            "The soldiers took from him everything: his clothes, his wedding ring, his lifetime research manuscript, and ultimately the lives of his wife, parents and siblings."),
           ("Nhưng trong bóng tối tuyệt vọng nhất đó, Frankl nhận ra một điều: 'Họ có thể lấy đi tất cả những gì tôi có, nhưng họ không thể lấy đi cách tôi phản ứng với những gì xảy ra với tôi.'",
            "But in that most desperate darkness, Frankl realized one thing: 'They can take away everything I have, but they cannot take away how I respond to what happens to me.'"),
           ("Ông chọn giúp đỡ những tù nhân khác, duy trì tâm hồn minh mẫn và tìm thấy ý nghĩa ngay trong địa ngục.",
            "He chose to help other prisoners, maintain his lucid mind, and find meaning even in hell."),
           ("Ông sống sót, và cuốn sách ông viết sau này --- 'Đi tìm lẽ sống' --- đã thay đổi cuộc sống của hàng triệu người trên toàn thế giới.",
            "He survived, and the book he wrote afterwards --- 'Man's Search for Meaning' --- changed the lives of millions of people worldwide.")],
          "Hoàn cảnh có thể tước đoạt tất cả những gì bên ngoài, nhưng không ai có thể lấy đi sự lựa chọn bên trong của bạn về việc bạn sẽ là ai.",
          "Circumstances can strip away everything external, but no one can take away your inner choice of who you will be."),

    story("Nelson Mandela Và Sự Lựa Chọn Không Thù Hận", "Nelson Mandela --- Nam Phi, 1990",
          "Sau",
          [("Sau 27 năm bị giam cầm, Nelson Mandela bước ra khỏi cổng tù ngày 11 tháng 2 năm 1990.",
            "After 27 years of imprisonment, Nelson Mandela walked out of the prison gates on February 11, 1990."),
           ("Phóng viên và thế giới chờ đợi ông nói những lời căm thù đối với những kẻ đã giam cầm ông.",
            "Reporters and the world waited for him to speak words of hatred toward those who had imprisoned him."),
           ("Nhưng Mandela bước ra với nụ cười và nói: 'Khi tôi bước qua cổng nhà tù, tôi biết rằng nếu tôi không bỏ lại sự cay đắng và hận thù ở phía sau, thì tôi vẫn đang ở trong tù.'",
            "But Mandela stepped out smiling and said: 'As I walked out the gate, I knew that if I did not leave behind bitterness and hatred, I would still be in prison.'"),
           ("Ông đã chọn tha thứ không phải vì kẻ thù của ông xứng đáng được tha thứ, mà vì ông muốn được tự do thực sự.",
            "He chose to forgive not because his enemies deserved forgiveness, but because he wanted to be truly free."),
           ("Sự lựa chọn đó của ông, cùng với chính sách Hòa giải Quốc gia, đã ngăn Nam Phi khỏi một cuộc nội chiến đẫm máu.",
            "His choice, along with the National Reconciliation policy, prevented South Africa from a bloody civil war.")],
          "Tha thứ không phải là món quà tặng kẻ thù; đó là món quà bạn trao cho chính mình để được thực sự tự do.",
          "Forgiveness is not a gift to your enemy; it is a gift you give yourself in order to be truly free."),

    story("Jean Valjean Và Sự Tái Sinh Nội Tâm", "Victor Hugo --- Pháp, 1862",
          "Jean",
          [("Jean Valjean trong tiểu thuyết 'Những Người Khốn Khổ' đã bị ăn cắp một ổ bánh mì để nuôi đứa cháu đói và bị kết án 19 năm tù khổ sai.",
            "Jean Valjean in the novel 'Les Misérables' was convicted for stealing a loaf of bread to feed his starving nephew and sentenced to 19 years of hard labor."),
           ("Nhưng thứ ngục tù làm hỏng ông không phải là bức tường đá --- mà là sự cay đắng và thù hận mà ông vun đắp trong tim.",
            "But what prison corrupted in him was not the stone walls --- it was the bitterness and hatred he nurtured in his heart."),
           ("Khi ra tù, ông gặp Giám mục Myriel, người không chỉ không tố giác ông khi ông ăn trộm bạc mà còn tặng thêm đồ bạc, nói: 'Ta tặng anh những thứ này để anh mua lại lương tâm của mình.'",
            "Upon release, he met Bishop Myriel, who not only did not report him when he stole silver but gave him more silver, saying: 'I give you these so you may buy back your conscience.'"),
           ("Lòng nhân từ đó buộc Valjean phải đối mặt với lựa chọn: tiếp tục là kẻ tội phạm, hay chọn trở thành con người khác.",
            "That kindness forced Valjean to face a choice: continue being a criminal, or choose to become a different person."),
           ("Ông chọn thay đổi, và cả phần còn lại của cuộc đời ông là hành trình hiện thực hóa sự lựa chọn đó.",
            "He chose to change, and the rest of his life was the journey of actualizing that choice.")],
          "Không có hoàn cảnh nào quyết định bạn sẽ là ai; chỉ có sự lựa chọn của bạn mới có quyền đó.",
          "No circumstance decides who you will be; only your choice has that power."),

    story("Malala Yousafzai Và Tiếng Nói Không Thể Bịt", "Malala Yousafzai --- Pakistan, 2012",
          "Năm",
          [("Năm 2012, khi 15 tuổi, Malala Yousafzai bị Taliban bắn vào đầu trên xe buýt đi học vì cô đã dám lên tiếng bảo vệ quyền được học của các cô gái.",
            "In 2012, at age 15, Malala Yousafzai was shot in the head by the Taliban on a school bus because she had dared to speak up defending girls' right to education."),
           ("Cô sống sót sau phép màu y tế, nhưng điều đáng kinh ngạc hơn là điều cô làm khi hồi phục.",
            "She survived through a medical miracle, but what was even more astounding was what she did when she recovered."),
           ("Cô không im lặng, không trốn chạy, không từ bỏ. Cô đặt câu hỏi cho chính mình: 'Taliban có thể bắn vào thân thể tôi, nhưng liệu họ có thể bắn vào ý chí của tôi không?'",
            "She did not stay silent, did not flee, did not give up. She asked herself: 'The Taliban can shoot my body, but can they shoot my will?'"),
           ("Cô tiếp tục lên tiếng, thành lập Quỹ Malala, viết sách và diễn thuyết khắp thế giới.",
            "She continued to speak out, established the Malala Fund, wrote books and spoke across the world."),
           ("Năm 2014, ở tuổi 17, cô trở thành người trẻ nhất trong lịch sử giành giải Nobel Hòa bình.",
            "In 2014, at age 17, she became the youngest person in history to receive the Nobel Peace Prize.")],
          "Không ai có thể lấy đi sự lựa chọn của bạn về việc bạn đứng lên hay ngồi xuống trước bạo lực.",
          "No one can take away your choice of whether to stand up or sit down in the face of violence."),

    story("Epictetus --- Người Nô Lệ Biết Điều Gì Là Của Mình", "Epictetus --- La Mã cổ đại",
          "Epictetus",
          [("Epictetus sinh ra là nô lệ ở La Mã cổ đại, bị chủ nhân đánh đến gãy chân và tàn tật suốt đời.",
            "Epictetus was born a slave in ancient Rome, beaten by his master until his leg broke, crippled for life."),
           ("Nhưng dù bị sở hữu về thể xác, ông nhận ra một sự thật sâu sắc mà ông dạy cho học trò sau này: 'Có những thứ nằm trong quyền kiểm soát của chúng ta và những thứ không.'",
            "But though physically owned, he realized a profound truth he later taught his students: 'Some things are within our control and others are not.'"),
           ("Thân xác có thể bị xích, nhưng suy nghĩ, giá trị và phẩm cách thì không.",
            "The body can be chained, but thoughts, values and character cannot."),
           ("Ông được giải phóng, trở thành triết gia nổi tiếng nhất La Mã, và học trò của ông bao gồm Hoàng đế Marcus Aurelius.",
            "He gained his freedom, became the most influential philosopher in Rome, and his students included Emperor Marcus Aurelius."),
           ("Bài học quan trọng nhất ông dạy: 'Hãy lo lắng về những gì bạn có thể kiểm soát, và thả ra mọi thứ khác. Tự do thực sự bắt đầu từ đó.'",
            "The most important lesson he taught: 'Concern yourself only with what you can control, and release everything else. True freedom begins there.'")],
          "Người nô lệ tự do nhất là người biết rằng không ai có thể nô lệ hóa tư duy và lựa chọn bên trong của mình.",
          "The freest slave is the one who knows that no one can enslave their inner thinking and choices."),

    story("Câu Chuyện Hai Người Tù Nhìn Qua Song Sắt", "Triết lý sống --- Khuyết Danh",
          "Hai",
          [("Hai người tù đang ở trong cùng một phòng giam, nhìn qua cùng một song sắt.",
            "Two prisoners were in the same cell, looking through the same iron bars."),
           ("Một người nhìn thấy bùn và sự tối tăm của nền đất ẩm ướt.",
            "One person saw the mud and darkness of the damp ground."),
           ("Người kia ngước đầu lên và nhìn thấy những vì sao lấp lánh.",
            "The other looked up and saw the twinkling stars."),
           ("Cùng một song sắt, cùng một khung nhìn --- nhưng hai sự lựa chọn hoàn toàn khác nhau về nơi đặt tầm mắt.",
            "The same iron bars, the same frame --- but two completely different choices of where to direct one's gaze."),
           ("Người nhìn thấy bùn héo mòn dần trong tuyệt vọng; người nhìn thấy sao tìm được bình yên và hy vọng.",
            "The one who saw the mud withered gradually in despair; the one who saw the stars found peace and hope."),
           ("Cả hai đều ở trong tù, nhưng chỉ một người thực sự bị giam cầm.",
            "Both were in prison, but only one was truly imprisoned.")],
          "Cuộc sống không phải là những gì xảy ra với bạn; cuộc sống là những gì bạn lựa chọn nhìn vào và chú tâm đến.",
          "Life is not what happens to you; life is what you choose to look at and pay attention to."),

    story("Thomas Edison Và 10.000 Cách Không Thành Công", "Thomas Edison --- Hoa Kỳ, thế kỷ 19",
          "Phóng",
          [("Phóng viên hỏi Thomas Edison: 'Ông có buồn vì đã thất bại 10.000 lần trước khi phát minh ra bóng đèn không?'",
            "A reporter asked Thomas Edison: 'Are you discouraged for having failed 10,000 times before inventing the lightbulb?'"),
           ("Edison trả lời không chần chừ: 'Tôi không hề thất bại 10.000 lần. Tôi đã thành công phát hiện ra 10.000 cách không hiệu quả.'",
            "Edison replied without hesitation: 'I have not failed 10,000 times. I have successfully discovered 10,000 ways that do not work.'"),
           ("Đó không phải là lời nói hào sảng — đó là cách Edison thực sự nhìn thế giới.",
            "That was not bravado --- that was how Edison genuinely saw the world."),
           ("Ông đã chọn định nghĩa lại 'thất bại' thành 'dữ liệu hữu ích', và điều đó cho phép ông tiếp tục khi người khác từ bỏ.",
            "He chose to redefine 'failure' as 'useful data', and that allowed him to continue when others gave up."),
           ("Phát minh duy nhất định nghĩa bạn là ai không phải là bóng đèn hay máy quay phim --- mà là cách bạn chọn diễn giải những gì xảy ra với bạn.",
            "The only invention that defines who you are is not the lightbulb or the motion picture camera --- it is how you choose to interpret what happens to you.")],
          "Sự kiện không có ý nghĩa tự thân; ý nghĩa là thứ bạn gán cho nó bằng sự lựa chọn của mình.",
          "Events have no meaning in themselves; meaning is something you assign to them by your choice."),

    story("Người Đàn Bà Đan Áo Trong Trại Tập Trung", "Câu chuyện từ Holocaust --- Thế chiến II",
          "Trong",
          [("Trong một trại tập trung ở Ba Lan, một người phụ nữ tên Sophie đã xin được một ít len từ đống quần áo bị tịch thu và lặng lẽ đan áo.",
            "In a concentration camp in Poland, a woman named Sophie obtained some yarn from confiscated clothing and quietly knitted."),
           ("Những tên lính canh chế giễu bà: 'Bà đan để làm gì, sắp chết đến nơi rồi?'",
            "The guards mocked her: 'Why are you knitting, you're about to die?'"),
           ("Bà trả lời: 'Tôi đan vì tôi muốn giữ lại điều gì đó là của tôi --- một hành động mang ý nghĩa trong khi mọi ý nghĩa xung quanh tôi đang bị tước đoạt.'",
            "She replied: 'I knit because I want to keep something that is mine --- an act of meaning while all meaning around me is being stripped away.'"),
           ("Bà tiếp tục đan áo cho những trẻ em trong trại, người nào bà thấy run rẩy trong lạnh giá.",
            "She continued knitting clothing for children in the camp, whoever she saw shivering in the cold."),
           ("Bà đã chọn ai mình muốn là, dù hoàn cảnh cố sức hủy hoại điều đó.",
            "She had chosen who she wanted to be, even as circumstances tried their hardest to destroy that.")],
          "Hành động có chủ đích trong tình huống vô nghĩa là cách con người khẳng định nhân phẩm của mình trước sức mạnh hủy diệt.",
          "Purposeful action in a meaningless situation is how humans affirm their dignity in the face of destructive power."),

    story("Câu Hỏi Của Phật Đà Tại Gốc Bồ Đề", "Phật Giáo --- Ấn Độ, 500 TCN",
          "Sau",
          [("Sau 6 năm khổ tu hành xác và thiền định, Siddhartha Gautama đặt câu hỏi cốt lõi: 'Tôi thực sự là ai, không phải là cái tên, địa vị xã hội hay vai trò mà xã hội giao cho tôi?'",
            "After 6 years of asceticism and meditation, Siddhartha Gautama asked the core question: 'Who am I truly, not the name, social status or role that society has assigned me?'"),
           ("Ông đã từ bỏ cuộc sống hoàng cung xa hoa, từ bỏ cả khổ tu hành xác cực đoan, để ngồi xuống dưới gốc cây bồ đề và tìm câu trả lời.",
            "He had abandoned the luxurious palace life, abandoned extreme asceticism, to sit beneath the Bodhi tree and seek the answer."),
           ("Câu trả lời ông tìm được không phải là một danh tính cố định --- mà là sự tự do lựa chọn trở thành ai bởi hành động và tư duy của mình từng khoảnh khắc.",
            "The answer he found was not a fixed identity --- but the freedom to choose who to become through one's actions and thoughts in each moment."),
           ("Ông đặt tên cho phát hiện này là 'Tỉnh thức' --- thấy rõ rằng mọi khổ đau đến từ việc bám víu vào những danh tính cứng nhắc chúng ta tự áp lên mình.",
            "He named this discovery 'Awakening' --- seeing clearly that all suffering comes from clinging to the rigid identities we impose upon ourselves."),
           ("Triết lý này đã giải phóng hàng triệu người khỏi câu hỏi 'Tôi là ai?' và thay vào đó đặt câu hỏi 'Tôi muốn trở thành ai?'",
            "This philosophy liberated millions from the question 'Who am I?' and replaced it with the question 'Who do I want to become?'")],
          "Bạn không phải là người được tạo ra bởi quá khứ; bạn là người đang tạo ra mình ở mỗi khoảnh khắc hiện tại.",
          "You are not the person created by the past; you are the person creating yourself in every present moment."),

    story("Chọn Trở Thành Người Tốt Hơn Trong Gian Khó", "Marcus Aurelius --- La Mã, thế kỷ 2",
          "Hoàng",
          [("Hoàng đế Marcus Aurelius cai trị Đế chế La Mã trong thời kỳ đối mặt với chiến tranh liên miên, bệnh dịch, và phản loạn nội bộ.",
            "Emperor Marcus Aurelius ruled the Roman Empire during a period of constant war, plagues, and internal rebellions."),
           ("Ông không có một ngày bình yên nào trong 20 năm trị vì.",
            "He did not have a single peaceful day in 20 years of reign."),
           ("Nhưng mỗi buổi sáng, ông viết vào nhật ký --- cuốn nhật ký mà ngày nay được gọi là 'Suy Tưởng' --- câu hỏi này: 'Hôm nay tôi có thể trở thành người tốt hơn như thế nào?'",
            "But every morning, he wrote in his diary --- the diary known today as 'Meditations' --- this question: 'How can I become a better person today?'"),
           ("Ông không hỏi 'Làm thế nào để chiến thắng kẻ thù?' hay 'Làm thế nào để dẹp loạn?' Ông hỏi 'Làm thế nào để tôi trở nên tốt hơn?'",
            "He did not ask 'How can I defeat my enemies?' or 'How can I suppress the rebellion?' He asked 'How can I become better?'"),
           ("Triết học khắc kỷ của ông dạy rằng bạn không thể kiểm soát thế giới bên ngoài, nhưng bạn luôn có thể lựa chọn ai bạn muốn là trong thế giới đó.",
            "His Stoic philosophy taught that you cannot control the external world, but you can always choose who you want to be within that world.")],
          "Câu hỏi quan trọng nhất mỗi buổi sáng không phải là 'Hôm nay tôi sẽ làm gì?' mà là 'Hôm nay tôi muốn trở thành người như thế nào?'",
          "The most important question every morning is not 'What will I do today?' but 'What kind of person do I want to be today?'"),
    ]
)

# ================================================================
# GHI FILE
# ================================================================
files = [
    ("ch01-giao-dieu-tot-gap-dieu-tot", ch1),
    ("ch02-hanh-dong-nho-hau-qua-lon", ch2),
    ("ch03-thoi-quen-tao-so-phan", ch3),
    ("ch04-toi-la-con-nguoi-toi-chon", ch4),
]
for fname, content in files:
    path = os.path.join(BASE, f"{fname}.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{fname} done")
print("All chapters 1-4 generated successfully!")
