#!/usr/bin/env python3
import os
import re

CHAPTERS_DIR = os.path.join(os.path.dirname(__file__), 'chapters')
os.makedirs(CHAPTERS_DIR, exist_ok=True)

TITLE_FIXES = {
    'Bang Diem Dep, Ban Than Rong': 'Bảng Điểm Đẹp, Bản Thân Rỗng',
    'Noi Rat Nhieu, Nguoi Nghe Van Khong Hieu': 'Nói Rất Nhiều, Người Nghe Vẫn Không Hiểu',
    'Biet Nhieu Nhung Viec Nao Cung Do': 'Biết Nhiều Nhưng Việc Nào Cũng Dở',
    'Coi Thuong Viec Nho': 'Coi Thường Việc Nhỏ',
    'Hoc Nhanh Nhung Sua Cham': 'Học Nhanh Nhưng Sửa Chậm',
    'Lam Mot Minh Thi Sang, Vao Nhom Thi Dut': 'Làm Một Mình Thì Sáng, Vào Nhóm Thì Đuối',
    'Khong Biet Tu Ban Minh': 'Không Biết Tự Trình Bày Mình',
    'Vinh Quang Cu O San Choi Moi': 'Vinh Quang Cũ Ở Sân Chơi Mới',
    'Doc Nhieu Nhung Khong Tao Dau Vet': 'Đọc Nhiều Nhưng Không Tạo Dấu Vết',
    'Tu Ai Khi Bi Cham': 'Tự Ái Khi Bị Chạm',
    'Luc Nao Cung Truc Ho': 'Lúc Nào Cũng Trực Hộ',
    'Cho Muon Tien Vi Ngan Tu': 'Cho Mượn Tiền Vì Ngại Từ Chối',
    'Lam Them Phan Viec Nguoi Khac': 'Làm Thêm Phần Việc Người Khác',
    'Nhin Nhin De Hoa Khi': 'Nhịn Nhịn Để Hòa Khí',
    'Dem Nao Cung Nghe Than': 'Đêm Nào Cũng Nghe Than',
    'Luc Nao Cung Cuu Hoa': 'Lúc Nào Cũng Cứu Hỏa',
    'Dong Y Vi So Mat Long': 'Đồng Ý Vì Sợ Mất Lòng',
    'Gan Viec Nha Khong Diem Dung': 'Gánh Việc Nhà Không Điểm Dừng',
    'Bi Dan Day Bang Cam Giac Toi Loi': 'Bị Dẫn Dây Bằng Cảm Giác Tội Lỗi',
    'Hoc Noi Khong': 'Học Nói Không',
    'Yeu Xa Chi Bang Tin Nhan': 'Yêu Xa Chỉ Bằng Tin Nhắn',
    'Muon Cuu Nguoi Yeu Bang Tinh Cam': 'Muốn Cứu Người Yêu Bằng Tình Cảm',
    'Nhan Het De Giu Moi Quan He': 'Nhẫn Hết Để Giữ Mối Quan Hệ',
    'Ghen La Sau Dam': 'Ghen Là Yêu Sâu',
    'Hua Rat Hay, Sua Rat It': 'Hứa Rất Hay, Sửa Rất Ít',
    'Yeu Roi Bo Het Muc Tieu Rieng': 'Yêu Rồi Bỏ Hết Mục Tiêu Riêng',
    'Quay Lai Qua Nhieu Lan': 'Quay Lại Quá Nhiều Lần',
    'Dang Cong Khai De Giu Nguoi': 'Đăng Công Khai Để Giữ Người',
    'Khac Nhip Song': 'Khác Nhịp Sống',
    'Buong Nguoi Khong Muon O Lai': 'Buông Người Không Muốn Ở Lại',
    'Lam Am Tham, Khong Ai Thay': 'Làm Âm Thầm, Không Ai Thấy',
    'Tang Ca Mai, Luong Van Dung': 'Tăng Ca Mãi, Lương Vẫn Đứng',
    'Co Gang Sai Huong': 'Cố Gắng Sai Hướng',
    'O Noi Khong Trong Nguoi': 'Ở Nơi Không Trọng Người',
    'Bi Cuop Cong': 'Bị Cướp Công',
    'Cho Ghi Nhan Tu Den': 'Chờ Ghi Nhận Tự Đến',
    'Co Gang Vi Si Dien': 'Cố Gắng Vì Sĩ Diện',
    'Cham Chi Thieu Chien Luoc': 'Chăm Chỉ Thiếu Chiến Lược',
    'Kiet Suc Roi Moi Biet Gia': 'Kiệt Sức Rồi Mới Biết Giá',
    'Doi Cach Co': 'Đổi Cách Cố',
    'Nhom Chat Im Dan': 'Nhóm Chat Im Dần',
    'Ban Thanh Cong Truoc': 'Bạn Thành Công Trước',
    'Lech Gia Tri': 'Lệch Giá Trị',
    'Moi Nguoi Mot Moi Truong': 'Mỗi Người Một Môi Trường',
    'Than Nhung Day Den Tien': 'Thân Nhưng Đụng Đến Tiền',
    'Chi Hop Mot Giai Doan': 'Chỉ Hợp Một Giai Đoạn',
    'Cuoi Xin, Cong Viec, Khoang Cach': 'Cưới Xin, Công Việc, Khoảng Cách',
    'Gap Lai Khong Con Nhu Cu': 'Gặp Lại Không Còn Như Cũ',
    'Giu Vi Ky Niem': 'Giữ Vì Kỷ Niệm',
    'Quy Nguoi Con O Lai': 'Quý Người Còn Ở Lại',
    'Luong Ve Roi Hoa Don Den': 'Lương Về Rồi Hóa Đơn Đến',
    'Gio Giac Tu Do Thanh Troi Ngay': 'Giờ Giấc Tự Do Thành Trôi Ngày',
    'Thue Nha Moi Biet Rang Buoc': 'Thuê Nhà Mới Biết Ràng Buộc',
    'Tu Quyet La Tu Chiu': 'Tự Quyết Là Tự Chịu',
    'Khong Ai Quan, Cung Khong Ai Cuu': 'Không Ai Quản, Cũng Không Ai Cứu',
    'Cuoi Tuan Van Lo Viec': 'Cuối Tuần Vẫn Lo Việc',
    'Tu Do Tieu Tien Thanh No': 'Tự Do Tiêu Tiền Thành Nợ',
    'Qua Nhieu Lua Chon, Cang De Lac': 'Quá Nhiều Lựa Chọn, Càng Dễ Lạc',
    'Phai Cham Lai Gia Dinh': 'Phải Chạm Lại Gia Đình',
    'Tu Cam Lai Cuoc Doi': 'Tự Cầm Lái Cuộc Đời',
}


def fix(text):
    text = text.replace('%', r'\%')
    text = text.replace('&', r'\&')
    text = re.sub(r'"([^"\n]*)"', r"``\1''", text)
    return text


def split_sentences(text):
    parts = re.split(r'(?<=[.!?])\s+', text.strip())
    return [part.strip() for part in parts if part.strip()]


def align_pairs(vn, en):
    vn_parts = split_sentences(vn)
    en_parts = split_sentences(en)
    if len(vn_parts) == len(en_parts) and len(vn_parts) > 1:
        return list(zip(vn_parts, en_parts))
    return [(vn, en)]


def story(title_vn, title_en, setup_vn, setup_en, illusion_vn, illusion_en, reality_vn, reality_en, shift_vn, shift_en, lesson_vn, lesson_en):
    return {
        'title_vn': TITLE_FIXES.get(title_vn, title_vn),
        'title_en': title_en,
        'pairs': [
            (setup_vn, setup_en),
            (illusion_vn, illusion_en),
            (reality_vn, reality_en),
            (shift_vn, shift_en),
        ],
        'lesson_vn': lesson_vn,
        'lesson_en': lesson_en,
    }


def make_chapter(filename, vn_title, en_title, stories):
    lines = []
    lines.append(r'\chapter{' + fix(vn_title) + r'}')
    lines.append(r'\markboth{' + fix(vn_title) + r'}{' + fix(en_title) + r'}')
    lines.append('')
    for idx, item in enumerate(stories, 1):
        lines.append(r'\section{' + fix(item['title_vn']) + r'}')
        lines.append(r'\begin{truyen}{' + fix(item['title_vn']) + r'}{' + fix(item['title_en']) + r'}')
        first = True
        for vn, en in item['pairs']:
            for sub_vn, sub_en in align_pairs(vn, en):
                if first:
                    words = fix(sub_vn).split(' ', 1)
                    fc = words[0][0] if words[0] else ''
                    rest = words[0][1:] + (' ' + words[1] if len(words) > 1 else '')
                    lines.append(r'\chuhoa{' + fc + r'}{' + rest + r'}')
                    first = False
                else:
                    lines.append(fix(sub_vn))
                lines.append(r'\textit{(' + fix(sub_en) + r')}')
                lines.append('')
        lines.append(r'\end{truyen}')
        lines.append('')
        lines.append(r'\begin{baihoc}')
        lines.append(fix(item['lesson_vn']))
        lines.append(r'\textit{(' + fix(item['lesson_en']) + r')}')
        lines.append(r'\end{baihoc}')
        lines.append('')
        lines.append(r'\begin{ghinhoanh}')
        lines.append(r'\textbf{Short English to remember:}')
        lines.append('')
        for sentence in split_sentences(item['lesson_en']):
            lines.append(fix(sentence))
            lines.append('')
        lines.append(r'\end{ghinhoanh}')
        lines.append('')
        lines.append(r'\begin{tuhocnhanh}')
        lines.append(r'\textbf{Câu hỏi tự học / Self-study questions}')
        lines.append('')
        lines.append(r'1. Ảo tưởng nào đang làm nhân vật đau nhất? \textit{Which illusion hurts the character most?}')
        lines.append('')
        lines.append(r'2. Sự thật nào cần được chấp nhận? \textit{What truth must be accepted?}')
        lines.append('')
        lines.append(r'3. Một câu tiếng Anh em muốn nhớ là câu nào? \textit{Which English sentence do you want to remember?}')
        lines.append(r'\end{tuhocnhanh}')
        if idx < len(stories):
            lines.append(r'\ngancach')
        lines.append('')
    with open(os.path.join(CHAPTERS_DIR, filename + '.tex'), 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines))
    print(f'Da tao: {filename}.tex')


ch01 = [
    story('Bang Diem Dep, Ban Than Rong', 'A Nice Transcript, But an Empty Working Self', 'Co ban tre ra truong voi bang diem dep va mot bo ho so rat sach.', 'Some students graduate with a nice transcript and a very clean file.', 'Ban ay tuong ket qua hoc tap dep se du de nguoi ta mo cua cho minh.', 'They think good academic results alone are enough to open doors.', 'Phong van xong moi thay nha tuyen dung can dau vet cong viec, cach trinh bay, va dau hieu lam duoc viec that.', 'After the interview, they see that employers want work traces, clear speaking, and proof of real ability.', 'Luc do ban ay moi hieu hoc gioi la mot nen tang tot, nhung no khong the di thay cho nang luc xuat hien trong doi that.', 'Then they understand that good grades are a good base, but they cannot replace real-world presence.', 'Hoc gioi rat quy. Nhung muon di xa, em con phai cho doi thay em lam duoc gi.', 'Studying well matters. But to go far, you must also let life see what you can do.'),
    story('Noi Rat Nhieu, Nguoi Nghe Van Khong Hieu', 'Talking a Lot While People Still Do Not Understand', 'Co nguoi hoc rat nhanh, doc rat nhieu, nhung moi lan trinh bay y minh lai dai va mo.', 'Some people learn fast and read a lot, but whenever they explain an idea, they sound long and unclear.', 'Ho tuong biet nhieu thi tu khac nguoi khac se thay minh gioi.', 'They assume that knowing a lot will automatically make others see their ability.', 'Nhung ngoai doi, gia tri cua em con nam o cho em co the noi gon, ro, va dung van de hay khong.', 'But in real life, your value also lies in whether you can speak briefly, clearly, and to the point.', 'Nguoi gioi ma khong truyen dat duoc thuong de mat diem ngay khi can hop tac.', 'A capable person who cannot communicate often loses points at the moment teamwork begins.', 'Gioi khong chi la hieu. Gioi con la lam cho nguoi khac hieu duoc minh.', 'Being good is not only understanding. It is also making other people understand you.'),
    story('Biet Nhieu Nhung Viec Nao Cung Do', 'Knowing Many Things but Finishing Nothing', 'Co ban tre hoc du thu mot luc va luc nao cung thay minh dang phat trien.', 'Some young people learn many things at once and always feel they are growing.', 'Ban ay tuong rong la manh hon sau va biet nhieu la hon nguoi.', 'They think wide knowledge is always stronger than depth and that knowing many things means being ahead.', 'Nhung den luc can mot san pham, mot bai viet, hay mot du an xong, ban ay lai khong dua ra duoc gi tron ven.', 'But when a product, a text, or a finished project is needed, they cannot show anything complete.', 'Thi truong thuong tin nguoi lam xong hon nguoi biet nhieu ma luc nao cung dang dang do.', 'The market usually trusts the one who finishes more than the one who knows a lot but keeps everything unfinished.', 'Biet nhieu la tot. Lam xong moi bien cai tot do thanh gia tri.', 'Knowing many things is good. Finishing turns that good thing into value.'),
    story('Coi Thuong Viec Nho', 'Despising Small Tasks', 'Ngay dau di lam, co ban bi giao viec nho va thay minh bi xem nhe.', 'On the first days at work, a young worker gets small tasks and feels underestimated.', 'Ban ay tuong nguoi gioi phai duoc giao viec lon ngay lap tuc.', 'They think skilled people should receive big tasks right away.', 'Nhung viec nho la noi nguoi ta nhin cach em dung han, can than, va co giu chat luong deu hay khong.', 'But small tasks are where people watch whether you are on time, careful, and steady in quality.', 'Khong it nguoi mat co hoi lon vi thai do coi thuong phan viec mo dau.', 'Many lose bigger chances because they look down on the beginning work.', 'Nguoi gioi that khong che viec nho. Ho lam no gon va sach roi moi di len.', 'Truly capable people do not mock small tasks. They do them cleanly and then move up.'),
    story('Hoc Nhanh Nhung Sua Cham', 'Learning Fast but Correcting Slowly', 'Co nguoi tiep thu rat nhanh nhung moi khi bi gop y lai co xu huong giai thich va tu ai.', 'Some people absorb information fast, but whenever they receive feedback they become defensive and explain too much.', 'Ho tuong minh thong minh nen khong can bi sua qua nhieu.', 'They think being smart means they should not need much correction.', 'Su that la nguoi lon nhanh nhat thuong la nguoi sua nhanh nhat sau khi thay minh sai.', 'The truth is that the fastest-growing people are often those who correct themselves fastest after seeing a mistake.', 'Thong minh ma giu cai toi qua lau se bien thanh toc do phat trien rat cham.', 'Intelligence mixed with a stubborn ego becomes very slow growth.', 'Giot feedback kho nghe co the la loi the lon neu em biet sua som.', 'A hard piece of feedback can become a major advantage if you correct yourself early.'),
    story('Lam Mot Minh Thi Sang, Vao Nhom Thi Dut', 'Shining Alone but Breaking Inside a Team', 'Co ban lam bai mot minh rat gioi, nhung vao nhom lai kho hop tac va hay coi y minh la trung tam.', 'Some people work brilliantly alone, but inside a team they become hard to work with and treat their own ideas as the center.', 'Ban ay tuong ai gioi hon thi tu nhien se duoc nhin nhan nhieu hon.', 'They think the more talented person should naturally dominate the room.', 'Nhung noi lam viec can nguoi biet lang nghe, biet doi nhan, va biet de viec chung chay duoc.', 'But workplaces need people who can listen, relate, and keep the whole machine moving.', 'Gioi ma gay met cho tap the thi som muon cung bi xem la mot bai toan dat.', 'If your skill keeps exhausting the whole group, sooner or later you become an expensive problem.', 'Nang luc trong doi that co ca phan lam viec cung nguoi khac.', 'Real-world competence includes the ability to work with other people.'),
    story('Khong Biet Tu Ban Minh', 'Not Knowing How to Present Yourself', 'Co nguoi co ky nang that nhung CV, email, va phong van deu mo nhat.', 'Some people have real skill, yet their CV, emails, and interviews are all blurry.', 'Ho tuong gioi thi khong can hoc cach xuat hien.', 'They think ability means they do not need to learn how to appear well.', 'Nhung co nhung canh cua chi mo khi em biet gioi thieu dung minh, dung luc, va dung cach.', 'But some doors open only when you know how to introduce yourself at the right time in the right way.', 'Gia tri khong biet di ra anh sang thi rat de bi bo qua.', 'Value that does not step into the light is easy to overlook.', 'Di xin viec cung la mot ky nang. Nguoi tre can hoc no nghiem tuc.', 'Job seeking is also a skill. Young people need to learn it seriously.'),
    story('Vinh Quang Cu O San Choi Moi', 'Old Glory Inside a New Arena', 'Co ban tung la hoc sinh gioi cua lop, nhung vao noi moi thi xung quanh ai cung da tung gioi nhu vay.', 'A student was once the top learner in class, but in a new place almost everyone around had also been strong.', 'Ban ay tuong danh hieu cu se giup minh dung vung lau.', 'They think old titles will keep them standing for a long time.', 'San choi moi thuong xoa rat nhanh nhung ten goi dep cua qua khu va hoi em hom nay con lam duoc gi.', 'A new arena quickly erases old labels and asks what you can do today.', 'Ai om vinh quang cu qua chat thuong so hon nguoi biet bat dau lai.', 'Those who cling too tightly to past glory often fear more than those willing to start again.', 'Qua khu dep la mot nen, khong phai mot cai ghe ngoi mai.', 'A good past is a base, not a permanent seat.'),
    story('Doc Nhieu Nhung Khong Tao Dau Vet', 'Reading Much but Leaving No Trace', 'Co nguoi luon cam thay minh dang hoc vi ngay nao cung doc va xem rat nhieu.', 'Some people always feel productive because they read and watch a lot every day.', 'Ho tuong tich luy kien thuc tu khac se bien thanh gia tri.', 'They think stored knowledge will somehow turn into value by itself.', 'Nhung neu khong viet ra, lam ra, day ra, hay dung vao viec that, nhieu thu van chi nam trong dau.', 'But if nothing is written, built, taught, or applied, many things stay only in the head.', 'Nguoi tre rat de nham giua cam giac dang hoc va dau vet hoc duoc.', 'Young people easily confuse the feeling of learning with evidence of learning.', 'Hoc de lam ra mot dau vet nho con hon hoc nhieu ma khong de lai gi.', 'Learning for one small real output is better than learning a lot without leaving any trace.'),
    story('Tu Ai Khi Bi Cham', 'Feeling Hurt Every Time You Are Corrected', 'Moi lan bi sua mot loi nho, co ban lai noi ve long tu trong va cam thay minh bi coi thuong.', 'Every time a small mistake is corrected, a young person talks about self-respect and feels insulted.', 'Ban ay tuong nguoi gioi phai duoc giu the dien lien tuc.', 'They think talented people should keep their face at all times.', 'Nhung o noi lam viec, nguoi duoc trong thuong la nguoi chinh loi gon, khong keo cai toi vao giua.', 'But in workplaces, respected people are often those who fix errors cleanly without pulling ego into the center.', 'Tu ai nhanh se lam toc do hoc cham di rat nhieu.', 'Quick offense makes learning much slower.', 'Muon gioi ben, em can da day hon truoc loi sua.', 'If you want stable excellence, you need thicker skin before correction.'),
]

ch02 = [
    story('Luc Nao Cung Truc Ho', 'Always Covering Other People', 'Trong nhom, co ban tre luc nao cung nhan phan truc ho vi so moi quan he xau di.', 'In a group, one young person keeps taking extra turns because they fear hurting the relationship.', 'Ban ay tuong nhan them nhu vay la song tinh cam va tu te.', 'They think taking more like that is kindness and loyalty.', 'Nhung khi viec chung thanh thoi quen mot nguoi canh va nhieu nguoi dung, long tot da bi dung sai.', 'But when group work becomes one person carrying and many people using, kindness is being misused.', 'Den mot luc, ban ay met va am uc voi chinh su hien lanh cua minh.', 'At some point, the person becomes tired and resentful of their own softness.', 'Tu te khong co nghia la nhan het phan nguoi khac bo lai.', 'Kindness does not mean taking all the work others leave behind.'),
    story('Cho Muon Tien Vi Ngan Tu', 'Lending Money Because You Feel Shy', 'Co nguoi cho ban muon tien nhieu lan du minh khong du gia de hoi lai.', 'Some people lend money many times even though they feel awkward asking for it back.', 'Ho tuong nguoi tot thi khong nen can do tien nong voi ban be.', 'They think good people should not be strict about money with friends.', 'Nhung tien bac mo nhat la noi long tot khong co ranh gioi rat de bi thu thach.', 'But money is exactly where kindness without boundaries is tested hardest.', 'Neu em khong hoc cach noi ro, em vua mat tien vua mat luon su ton trong.', 'If you do not learn to speak clearly, you may lose both money and respect.', 'Long tot can di cung quy tac ro rang, nhat la voi tien.', 'Kindness needs clear rules, especially around money.'),
    story('Lam Them Phan Viec Nguoi Khac', 'Doing the Part That Belongs to Someone Else', 'Trong van phong, co nhan vien tre thuong xuyen sua bai, boi file, va chua loi cho nguoi khac.', 'In an office, a young worker often edits files, fills gaps, and repairs mistakes for others.', 'Ban ay tuong minh dang de tap the duoc viec va khong nen tinh toan.', 'They think they are serving the team and should not calculate too much.', 'Nhung khi su cuu hoa dien ra mai, nguoi khac co the quen song vo trach nhiem tren suc cua em.', 'But when rescue becomes constant, other people may grow comfortable living irresponsibly on your effort.', 'Ho tro co gioi han moi giup duoc lau. Gan thay thi lam em can nhanh.', 'Support with limits lasts. Carrying for others drains you fast.', 'Em co the giup, nhung dung bien minh thanh bo phan chong lung mien phi.', 'You can help, but do not turn yourself into free spare support.'),
    story('Nhin Nhin De Hoa Khi', 'Staying Silent for the Sake of Peace', 'Co ban tre thay minh bi chen viec nhung van cuoi tru vi so bi goi la kho tinh.', 'A young person sees others pushing work onto them, but still smiles because they fear being called difficult.', 'Ban ay tuong im lang la cach giu hoa khi tot nhat.', 'They think silence is the best way to keep peace.', 'Thuc ra, su im lang qua lau thuong de lai mot cai gia lon hon, do la su am uc va mot thoi quen bi xem nhe.', 'In reality, silence held too long often creates a bigger cost: resentment and a habit of being undervalued.', 'Noi mot cau ro rang som thuong nhe hon de den luc no thanh mot vet thuong lon.', 'One clear sentence early is usually lighter than waiting until it becomes a deep wound.', 'Hoa khi that khong duoc xay tren viec mot nguoi nuot het phan khong cong bang.', 'Real peace is not built by one person swallowing all unfairness.'),
    story('Dem Nao Cung Nghe Than', 'Listening to Complaints Every Night', 'Co nguoi tro thanh noi do cam xuc cho mot ban than, toi nao cung nghe mot cau chuyen cu lap lai.', 'Someone becomes the emotional dumping place for a friend who repeats the same complaint every night.', 'Ho tuong minh phai luon san sang thi moi la thuong that.', 'They think always being available is proof of true care.', 'Nhung quan tam khong co nghia la de mot nguoi rut can nang luong cua em ma khong tu thay doi gi.', 'But caring does not mean letting someone drain your energy without changing themselves.', 'Co luc dieu tu te hon la khuyen ho tim cach giai quyet thay vi tiep tuc lam bai tap than lap lai.', 'Sometimes the kinder act is to push them toward a solution instead of endless repeating.', 'Thuong nguoi khac khong dong nghia tu nhien tro thanh thung chua moi met moi cua ho.', 'Caring for others does not automatically mean becoming a bucket for all their exhaustion.'),
    story('Luc Nao Cung Cuu Hoa', 'Being the Emergency Person All the Time', 'Trong nhom hoc hay cho lam, cu gap viec gap la moi em vao lam cho xong.', 'In study groups or at work, whenever something is urgent, they call you in to finish it.', 'Em tuong minh duoc can la mot vinh du va mot dau hieu duoc tin.', 'You think being needed is an honor and proof of trust.', 'Nhung neu chuyen gi cung do vao em, co khi nguoi ta dang dung su co mat cua em de bao che cho su thieu chuan bi cua ho.', 'But if everything is dumped on you, people may be using your presence to hide their own lack of preparation.', 'Nguoi biet tu trong khong nhan het moi lan co ai hoang len.', 'People with self-respect do not absorb every crisis others create.', 'Duoc can la tot. Bi mac dinh la nguoi chua chay cho tat ca thi khong con tot nua.', 'Being needed is good. Becoming the default firefighter for everyone is not.'),
    story('Dong Y Vi So Mat Long', 'Saying Yes Because You Fear Displeasing People', 'Moi loi nho giup hay doi lich deu duoc em dong y rat nhanh.', 'Every request for help or schedule change is accepted very quickly.', 'Em tuong tu choi se lam nguoi ta that vong ve minh.', 'You think refusing will make people disappointed in you.', 'Nhung mot loi dong y khong co suc cua em ben trong thuong se bien thanh mot loi hua meo mo va mot su buc boi am tham.', 'But a yes without real capacity inside often turns into a weak promise and private frustration.', 'Noi khong dung luc co the giu duoc su ton trong tot hon mot loi dong y mien cuong.', 'A timely no can preserve more respect than a forced yes.', 'Tu choi trong sach con hon nhan roi lam do hoac lam trong am uc.', 'A clean refusal is better than acceptance followed by poor work or resentment.'),
    story('Gan Viec Nha Khong Diem Dung', 'Carrying Endless Family Tasks', 'Co ban tre o nha luc nao cung la nguoi chay viec, tu mua do den cham em, vi moi nguoi quen rang em hien.', 'At home, one young person becomes the default runner for all tasks because everyone is used to their softness.', 'Ban ay tuong gia dinh thi phai im ma chiu cho dep.', 'They think family duty means silent endurance at all times.', 'Nhung ngay ca trong gia dinh, neu vai tro khong duoc noi ro, nguoi hien nhat thuong se bi chat them viec mai.', 'But even in family, if roles are never stated clearly, the kindest person often keeps receiving extra weight.', 'San se la dep. Gan het phan cua ca nha thi khong con can bang.', 'Sharing is beautiful. Carrying the whole house is not balance.', 'Hieu thao va tu trong khong phai hai dieu doi nghich.', 'Respecting family and respecting yourself are not opposite things.'),
    story('Bi Dan Day Bang Cam Giac Toi Loi', 'Being Pulled by Guilt', 'Moi lan em tu choi, co nguoi lien noi rang em da thay doi, ich ky, hay khong con tinh cam.', 'Whenever you refuse, someone says you have changed, become selfish, or lost affection.', 'Em tuong minh co loi that nen quay lai giup du khong con muon.', 'You assume the guilt is real, so you go back and help even when you no longer want to.', 'Do la cach rat nhieu nguoi bi dan day bang cam xuc thay vi duoc ton trong bang ly le ro rang.', 'This is how many people are pulled by emotion instead of being respected through clear reason.', 'Neu em khong nhin ra, cam giac co loi se thanh cai day xich rat mem ma rat chac.', 'If you do not see it, guilt becomes a soft but strong chain.', 'Long tot can tinh tao. Neu khong, em se cho di vi bi day, khong phai vi tu nguyen.', 'Kindness needs awareness. Otherwise you give because you are pushed, not because you choose.'),
    story('Hoc Noi Khong', 'Learning to Say No', 'Sau nhieu lan met va am uc, co ban tre tap noi mot cau ngan gon rang minh khong lam duoc viec do.', 'After many tired and resentful days, a young person starts saying one short sentence: I cannot do that.', 'Ban ay so cau noi do se lam minh xau di trong mat nguoi khac.', 'They fear that sentence will make them look worse in other people’s eyes.', 'Nhung dieu xay ra la nhung ai ton trong minh van o lai, con nhung ai chi quen dung minh thi bat dau kho chiu.', 'What happens is that respectful people stay, while those who only used them become uncomfortable.', 'Cau no ngan, nhung no mo ra mot doi song nhe hon va sach hon.', 'The sentence is short, but it opens a lighter and cleaner life.', 'Noi khong la mot ky nang giu long tot song lau, khong phai mot dau hieu lanh lung.', 'Saying no is a skill that helps kindness survive, not a sign of coldness.'),
]

ch03 = [
    story('Yeu Xa Chi Bang Tin Nhan', 'Trying to Hold Long Distance Love with Messages Alone', 'Co cap doi nghi rang chi can nhan tin thuong xuyen la du giu mot moi tinh xa.', 'A couple thinks frequent texting alone can hold a long-distance relationship together.', 'Ho tuong cam xuc manh se duoc thay cho no luc song that.', 'They think strong feelings can replace real effort.', 'Nhung tinh yeu xa can them su that, ke hoach, lich gap, va su on dinh trong cach song cua ca hai.', 'But long-distance love also needs honesty, plans, meeting dates, and stability in both lives.', 'Khong co cau truc, nhung tin nhan ngot dan cung met.', 'Without structure, sweet messages slowly become tiring.', 'Tinh yeu can cam xuc, nhung de giu duoc no can nhieu hon cam xuc.', 'Love needs feeling, but keeping it needs more than feeling.'),
    story('Muon Cuu Nguoi Yeu Bang Tinh Cam', 'Trying to Rescue a Lover with Love Alone', 'Co nguoi yeu mot nguoi dang roi boi va tin rang minh thuong du se cuu duoc ho.', 'Someone loves a troubled partner and believes enough affection will save them.', 'Ban ay tuong tinh yeu co the lam thay ky luat va trach nhiem ca nhan.', 'They think love can replace discipline and personal responsibility.', 'Nhung mot nguoi khong tu muon dung day thi tinh cam cua em cung chi thanh tam chan cho ho dua vao.', 'But if a person does not want to stand up, your love becomes only another cushion for them to lean on.', 'Thuong ai do khong co nghia la phai dong vai nguoi cuu ho.', 'Loving someone does not mean becoming their savior.', 'Tinh yeu co the nang do. No khong the song ho cuoc doi cua ho.', 'Love can support. It cannot live another person’s life for them.'),
    story('Nhan Het De Giu Moi Quan He', 'Enduring Everything Just to Keep the Relationship', 'Co ban tre nhin nhin het nhung dieu khong on vi so mat nguoi minh yeu.', 'A young person keeps swallowing unhealthy things because they fear losing the one they love.', 'Ban ay tuong nhan nhieu se giu duoc lau.', 'They think enduring more will make love last longer.', 'Thuc ra, nhin vo gioi han khong cuu moi quan he. No chi day em vao cho can va ben kia quen duoc phep lam qua.', 'In reality, endless endurance does not save a relationship. It only pushes you into hurt while the other side gets used to excess.', 'Cai gi giu duoc lau phai co su ton trong, khong chi co su nhin nhuc.', 'What lasts needs respect, not only patience.', 'Nhung gioi han dep giup tinh yeu khoe hon nhung im lang cam chiu.', 'Healthy boundaries make love stronger than silent endurance.'),
    story('Ghen La Sau Dam', 'Mistaking Jealousy for Depth', 'Co cap doi xem su kiem soat, hoi han, va ghen tuong lien tuc la dau hieu cua tinh yeu manh.', 'A couple sees control, constant checking, and jealousy as signs of deep love.', 'Ho tuong cang ghen cang chung minh minh quan trong voi nhau.', 'They think the more jealousy there is, the more important they are to each other.', 'Nhung ghen thuong xuyen thuong den tu bat an hon la tu truong thanh.', 'But constant jealousy usually grows from insecurity more than maturity.', 'Tinh yeu lam nguoi ta yen tam hon, khong phai luc nao cung phai giam sat nhau.', 'Love should make people steadier, not force them to monitor each other all the time.', 'Kiem soat khong phai bang chung cua yeu sau. Thuong no la bang chung cua noi so sau.', 'Control is not proof of deep love. It is often proof of deep fear.'),
    story('Hua Rat Hay, Sua Rat It', 'Promising Beautifully but Changing Very Little', 'Co nguoi sau moi lan sai deu noi xin loi va hua se khac.', 'After every mistake, one partner apologizes and promises to change.', 'Nguoi con lai tuong chi can con hua la moi quan he con hy vong lon.', 'The other person thinks that as long as promises remain, the relationship still has strong hope.', 'Nhung loi hua lap lai ma hanh vi khong doi dan lam tinh yeu mon di nhanh hon nhieu dieu ac liet.', 'Repeated promises without changed behavior wear love down faster than many harsh events.', 'Moi tinh ben khong the dua tren loi noi dep ma khong co dau vet sua doi.', 'A stable relationship cannot rest on beautiful words without signs of repair.', 'Hay nhin vao hanh vi lap lai, khong chi vao loi noi cam dong.', 'Watch repeated behavior, not only moving words.'),
    story('Yeu Roi Bo Het Muc Tieu Rieng', 'Dropping Every Personal Goal After Falling in Love', 'Co ban tre yeu xong bo hoc, bo ke hoach, bo ca cac thoi quen tot vi muon danh het thoi gian cho nguoi kia.', 'A young person falls in love and drops study, plans, and good habits to give all time to the partner.', 'Ban ay tuong nhu vay moi la yeu het long.', 'They think this is what wholehearted love looks like.', 'Nhung moi tinh khoe khong yeu cau em cat dut duong lon cua minh de chung minh tinh cam.', 'But a healthy relationship does not require you to cut off your own road to prove love.', 'Tinh yeu tot lam doi song rong hon, khong lam em hep lai va mat huong.', 'Good love makes life wider, not smaller and directionless.', 'Dung bien tinh yeu thanh ly do de bo roi chinh minh.', 'Do not turn love into an excuse to abandon yourself.'),
    story('Quay Lai Qua Nhieu Lan', 'Going Back Too Many Times', 'Co nhung cap doi chia tay roi quay lai lien tuc vi khong chiu noi don va co don.', 'Some couples break up and return again and again because they cannot bear pain or loneliness.', 'Ho tuong quay lai nhieu lan la bang chung cho mot moi tinh dac biet.', 'They think repeated returns prove a special love.', 'Nhung co khi dieu duoc lap lai khong phai la tinh yeu lon ma la mot vong lap chua ai chiu hoc bai hoc cua minh.', 'But repetition may not be great love. It may be a loop where no one learns the needed lesson.', 'Quay lai khong sai, nhung quay lai ma van song nhu cu thi chi keo dai vet thuong.', 'Returning is not always wrong, but returning without change only stretches the wound.', 'Dung do tinh sau bang so lan quay lai. Hay do bang muc do ca hai da truong thanh hon chua.', 'Do not measure depth by the number of returns. Measure it by whether both people have grown.'),
    story('Dang Cong Khai De Giu Nguoi', 'Making Love Public in Order to Keep Someone', 'Co nguoi co gan nhieu anh, nhieu bai dang, nhieu dau hieu cong khai de doi phuong kho roi di.', 'Some people post many pictures and public signs of love so the other person will find it harder to leave.', 'Ho tuong su cong khai se tao ra su rang buoc ben.', 'They think publicity creates true commitment.', 'Nhung dieu giu mot nguoi o lai lau hon van la su ton trong, tin cay, va cach song hop nhau.', 'But what keeps someone longer is still respect, trust, and a way of living that fits.', 'Anh dep co the giu hinh anh. No khong giu duoc mot tam long da muon roi.', 'Beautiful posts can preserve an image. They cannot keep a heart that wants to leave.', 'Tinh yeu that ben trong cach song voi nhau hon la tren mat mang.', 'Real love is stronger in shared life than on the screen.'),
    story('Khac Nhip Song', 'Living in Different Rhythms', 'Co cap doi van con thuong nhau nhung mot nguoi muon on dinh som, mot nguoi van muon song rat bay.', 'A couple still cares for each other, but one wants stability early while the other still wants a drifting life.', 'Ho tuong con thuong nhau thi cac lech nhip nay tu khac se bien mat.', 'They think that as long as love remains, these differences will fade by themselves.', 'Nhung tinh yeu co the that bai khong phai vi thieu cam xuc ma vi thieu su dong nhip trong cach song.', 'Love can fail not because emotion is missing, but because life rhythms do not align.', 'Thuong nhau va hop nhau la hai chuyen gan nhau nhung khong phai mot.', 'Loving each other and fitting each other are close ideas, but not the same.', 'Muon giu duoc lau, tinh yeu can ca tinh cam lan nhip song co the song chung.', 'To last, love needs both feeling and a rhythm that can actually be lived together.'),
    story('Buong Nguoi Khong Muon O Lai', 'Letting Go of Someone Who Does Not Want to Stay', 'Den mot luc, co nguoi phai nhin vao su that rang doi phuong da muon roi di du minh con thuong.', 'At some point, someone must face the truth that the other person wants to leave even though love remains.', 'Nguoi o lai tuong co the co gang them mot chut nua de doi y nguoi kia.', 'The one left behind thinks a little more effort may change the other heart.', 'Nhung co nhung cuoc tinh khong mat vi em thieu co gang. No mat vi mot ben khong con muon di tiep.', 'But some relationships do not end because your effort was too small. They end because one side no longer wants to continue.', 'Buong tay luc do dau, nhung no giu em khoi viec phai van xin mot dieu khong con tu nguyen.', 'Letting go hurts then, but it saves you from begging for something no longer freely given.', 'Yeu sau khong co nghia la giu duoc moi nguoi. Co khi no chi giup em buon ma van giu duoc pham gia.', 'Loving deeply does not mean keeping everyone. Sometimes it only means grieving while keeping your dignity.'),
]

ch04 = [
    story('Lam Am Tham, Khong Ai Thay', 'Working Quietly While No One Notices', 'Co nhan vien tre lam rat cham chi nhung it noi, it trinh bay, va cu nghi cap tren se tu thay.', 'A young worker is diligent but quiet, explains little, and assumes superiors will notice automatically.', 'Ban ay tuong cu co gang deu la ket qua se tu den dung cho.', 'They think steady effort alone will naturally bring the right result.', 'Nhung trong nhieu noi, viec tot neu khong duoc trinh bay dung va de lai dau vet ro cung de tro nen vo hinh.', 'But in many places, good work without clear visibility and trace can still become invisible.', 'Co gang can sach, nhung cung can hoc cach de cong suc khong bi chim mat.', 'Effort must stay clean, but it also needs visibility so it does not sink.', 'Lam tot la nen. Cho nguoi ta thay duoc no la ky nang.', 'Doing good work is the base. Letting people see it is a skill.'),
    story('Tang Ca Mai, Luong Van Dung', 'Working Overtime Again and Again While Pay Stays the Same', 'Co nguoi o lai den muon rat nhieu dem va tin rang su tan tuy se som duoc dap lai.', 'Someone stays late many nights and believes such devotion will soon be rewarded.', 'Ho tuong co gang nhieu hon nguoi khac la du de doi doi xu cong bang.', 'They think harder effort than others is enough to earn fair treatment.', 'Nhung neu noi do khong co he thong ghi nhan ro rang, tang ca co the chi tro thanh mot thoi quen duoc mac dinh.', 'But if that place has no clear system of recognition, overtime can become a habit others simply expect.', 'No luc khong duoc dat dung cho se de bien thanh suc lao dong gia re.', 'Effort placed in the wrong structure easily becomes cheap labor.', 'Khong phai cu rat co gang la se duoc tra cong dung. Em con phai nhin xem minh dang co gang o dau.', 'Hard work is not always rewarded fairly. You also need to examine where you are working.'),
    story('Co Gang Sai Huong', 'Working Hard in the Wrong Direction', 'Co ban tre lam rat nhieu viec moi ngay nhung phan lon la viec don gian, khong dua minh gan muc tieu hon.', 'A young person does many things every day, but most tasks are small and do not move them closer to the goal.', 'Ban ay tuong ban ron dong nghia dang tien len.', 'They think busyness means progress.', 'Nhung co gang ma sai huong thuong chi lam nguoi ta met nhanh hon va that vong sau hon.', 'But hard work in the wrong direction usually only makes people tired faster and disappointed later.', 'Nguoi truong thanh khong chi hoi minh co dang co gang khong. Ho hoi minh dang co gang vao dau.', 'Mature people do not only ask whether they are trying. They ask where the effort is landing.', 'Cham chi la tot. Cham chi dung huong moi tao ket qua.', 'Diligence is good. Diligence in the right direction creates results.'),
    story('O Noi Khong Trong Nguoi', 'Staying in a Place That Does Not Respect People', 'Co nguoi doi rat lau su ghi nhan tu mot moi truong ma tu dau da xem con nguoi nhu mon do thay duoc.', 'Someone waits a long time for recognition from a place that has long treated people like replaceable tools.', 'Ho tuong chi can ben bi la duoc dap lai.', 'They think endurance alone will eventually be rewarded.', 'Nhung co noi van hoa sai tu goc nen em co gang bao nhieu cung chi doi lay mot chut ton thuong co he thong.', 'But some places are broken at the root, so more effort only buys more structured hurt.', 'Khon ngoan khong phai luc nao cung o lai them. Nhiều khi la biet dung luc de roi di.', 'Wisdom is not always staying longer. Sometimes it is leaving at the right time.', 'Co gang la dep. Dung co gang de nuoi mot noi khong biet quy suc nguoi.', 'Effort is noble. Do not spend it feeding a place that does not value human effort.'),
    story('Bi Cuop Cong', 'Watching Someone Else Take the Credit', 'Co du an em lam phan kho nhat, nhung den luc bao cao thi ten nguoi khac duoc nhac den nhieu hon.', 'In one project, you did the hardest part, yet another person was named more often in the report.', 'Em tuong cu lam tot thi ai cung se thay cong minh ro rang.', 'You think that if the work is good enough, fairness will reveal itself.', 'Nhung cong bang trong doi that doi khi can duoc bao ve bang cach luu dau vet, noi ro phan minh, va biet cach bao cao.', 'But fairness in real life sometimes must be protected by records, clear reporting, and naming your contribution.', 'Im lang qua lau co the bien mot nguoi co nang luc thanh mot cai bong.', 'Silence held too long can turn a capable person into a shadow.', 'Co gang can kem theo ky nang giu dau vet cong suc cua minh.', 'Effort also needs the skill of protecting the trace of your work.'),
    story('Cho Ghi Nhan Tu Den', 'Waiting for Recognition to Arrive by Itself', 'Co ban tre luon noi rang minh se chi cu chup dau lam viec, con moi thu khac roi nguoi ta se tu biet.', 'A young person says they will just lower their head and work, and people will know the rest by themselves.', 'Ban ay tuong viec noi ve thanh qua cua minh luc nao cung la khoe khoang.', 'They think mentioning their own results is always bragging.', 'Nhung co su khac nhau giua khoe khoang va bao cao ro rang de nguoi dung co the danh gia dung.', 'But there is a difference between bragging and giving a clear report so others can judge fairly.', 'Khong tu noi thay phan minh co khi la cach em de nguoi khac viet cau chuyen ve cong suc cua em.', 'If you never speak for your part, others may end up writing the story of your effort for you.', 'Khiem ton la tot. Mo ho ve gia tri cua minh thi khong tot.', 'Humility is good. Being vague about your own value is not.'),
    story('Co Gang Vi Si Dien', 'Working Hard Mainly Out of Pride', 'Co nguoi cu gan rang giu mot viec chi vi so nguoi khac thay minh bo cuoc.', 'Some people keep forcing themselves in a role mainly because they fear being seen as quitters.', 'Ho tuong cu nghi them mot chut nua se thanh kien cuong.', 'They think staying longer automatically means strength.', 'Nhung neu su co gang duoc nuoi boi si dien hon la y nghia, no se sot ruot va dot em tu ben trong.', 'But when effort is fed more by pride than by meaning, it burns you from inside.', 'Ben bi khac voi chap niem vo ich chi de giu mat mui.', 'Endurance is different from stubbornly staying just to save face.', 'Hay hoi minh dang co gang vi gia tri hay chi vi ngai xau ho.', 'Ask whether your effort serves value or only fear of shame.'),
    story('Cham Chi Thieu Chien Luoc', 'Being Hardworking but Without Strategy', 'Co nguoi rat sieu nang, ngay nao cung nhieu gio, nhung nam nao cung dung yen vi khong biet uu tien cai gi.', 'Some people work many hours every day, yet stay in the same place for years because they do not know what to prioritize.', 'Ho tuong chi can tang luong no luc la du bu lai moi thieu sot khac.', 'They think more effort can compensate for every other weakness.', 'Nhung co gang khong co chien luoc thuong tan ra thanh rat nhieu viec nho ma khong ket tinh thanh buoc nhay lon.', 'But effort without strategy often spreads into many small tasks without forming any major leap.', 'Nguoi tre can hoc chac mot vai huong quan trong hon la lam het moi thu mot chut.', 'Young people need to hold a few important directions instead of doing a little of everything.', 'No luc can duoc dan duong boi uu tien dung.', 'Effort needs to be guided by clear priorities.'),
    story('Kiet Suc Roi Moi Biet Gia', 'Learning the Cost Only After Burning Out', 'Co nguoi co gang lien tuc den muc than the va dau oc deu can ma van tu nhac minh phai gang them.', 'Some people keep pushing until body and mind are empty, yet still tell themselves to push harder.', 'Ho tuong nghi lai la yeu va cham lai la tut hau.', 'They think rest means weakness and slowing down means falling behind.', 'Den khi kiet suc, ho moi thay mot cai gia rat dat: viec van con do, chi co nguoi lam la da hong nhieu hon.', 'Only after burnout do they see the cost: the work is still there, but the person doing it is now damaged.', 'Co gang lau dai can nhan vao suc ben, khong chi vao y chi trong vai tuan nong.', 'Long-term effort must rely on stamina, not only on a few hot weeks of willpower.', 'Muon duoc tra cong dai han, em phai biet giu nguon luc cua minh.', 'If you want long-term reward, you must know how to protect your own energy.'),
    story('Doi Cach Co', 'Changing the Way You Try', 'Sau nhieu lan co gang ma khong duoc dap lai, co nguoi dung lai de xem minh can doi cach lam gi.', 'After many unrewarded attempts, someone finally stops to examine what must change.', 'Ban ay truoc do tuong chi can tang them suc la du.', 'Before that, they thought more force was enough.', 'Nhung doi khi thu em thieu khong phai no luc, ma la cach chon noi, chon viec, chon nguoi, va chon thoi diem.', 'But sometimes what is missing is not effort, but choice of place, work, people, and timing.', 'Ngay khi cach co gang doi, ket qua bat dau ro hon du no luc khong he giam.', 'Once the method changes, results become clearer even without less effort.', 'Dung chi co gang hon. Hay co gang khon hon.', 'Do not only try harder. Try wiser.'),
]

ch05 = [
    story('Nhom Chat Im Dan', 'The Group Chat Slowly Goes Quiet', 'Nhom ban than ngay xua tung noi chuyen suot ngay, nhung roi moi nguoi bat dau tra loi cham hon.', 'A close friend group once talked all day, but slowly everyone starts replying more slowly.', 'Co nguoi tuong su im lang do co nghia tinh ban dang chet.', 'Someone assumes that silence means friendship is dying.', 'Nhung lon len la luc lich song tan ra, trach nhiem day vao, va su than thiet khong con do bang tan suat tin nhan nua.', 'But growing up spreads schedules apart, pushes in responsibilities, and stops measuring closeness by message count alone.', 'Dieu can hoc la nhin tinh ban bang do that, khong chi bang do on ao.', 'The lesson is to measure friendship by truth, not only by noise.', 'Tinh ban truong thanh co luc im hon, nhung khong he nhe hon.', 'Mature friendship may become quieter, but not lighter.'),
    story('Ban Thanh Cong Truoc', 'A Friend Succeeds Earlier', 'Khi mot nguoi trong nhom co viec tot va song on hon, nguoi con lai de co mot vet cham trong long.', 'When one friend gets a good job and a more stable life first, the other feels a sting inside.', 'Ho tuong neu tinh ban that thi minh se vui tron ven va khong co chut so sanh nao.', 'They think true friendship should mean pure joy without any comparison.', 'Nhung chanh long la phan rat nguoi. Van de khong nam o cam xuc dau, ma o cach em xu ly no sach hay doc.', 'But the sting is deeply human. The real issue is whether you process it cleanly or turn it bitter.', 'Neu giu duoc su trong sang truoc thanh cong cua ban, em lon len rat nhieu.', 'If you stay clean-hearted before a friend’s success, you grow a lot.', 'Tinh ban ben can long mung cho nhau, nhung cung can su thanh that voi vet cham cua chinh minh.', 'Stable friendship needs joy for each other, but also honesty about your own sting.'),
    story('Lech Gia Tri', 'Values Begin to Split', 'Co nhung nguoi truoc kia rat hop, nhung sau vai nam thi mot ben song rat that, mot ben song rat loi.', 'Some friends once matched well, but after some years one lives with integrity while the other grows increasingly opportunistic.', 'Nguoi o lai tuong da than lau thi phai co gang giu bang moi gia.', 'The one who notices the split thinks long history means the friendship must be preserved at any cost.', 'Nhung tinh ban khong chi duoc nuoi bang ky niem. No con song bang gia tri chung o hien tai.', 'But friendship is not fed by memory alone. It also lives on shared present values.', 'Co nhung moi quan he can buoc lui de khong bi loi di trong cai khong hop nua.', 'Some bonds need distance so you are not dragged into what no longer fits.', 'Khong phai ai than lau cung nen di cung lau.', 'Not every longtime friend should remain a long-term companion.'),
    story('Moi Nguoi Mot Moi Truong', 'Each Person Lives in a Different World Now', 'Co nguoi o thanh pho lon, co nguoi ve que, co nguoi lap gia dinh, co nguoi van di hoc.', 'One friend lives in a big city, one returns home, one starts a family, and one keeps studying.', 'Ca nhom tuong chi can thuong nhau la van song duoc cung mot nhip cu.', 'The group thinks affection alone can keep the old common rhythm alive.', 'Nhung moi moi truong tao ra ap luc, lich song, va moi uu tien khac nhau.', 'But each environment creates different pressures, schedules, and priorities.', 'Tinh ban khon ngoan la tinh ban chap nhan su khac nhau ma khong doi nguoi kia phai giong minh nua.', 'Wise friendship accepts difference without forcing everyone to stay the same.', 'Ban be lon len khong phai luc nao cung di cung mot toc do.', 'As friends grow up, they do not always move at the same speed.'),
    story('Than Nhung Day Den Tien', 'Close Friends Tested by Money', 'Co doi ban rat than cho den khi co mot khoan muon, mot lan no, hoac mot viec chung lien quan den tien.', 'Some close friendships stay smooth until a loan, a debt, or a money matter appears.', 'Ho tuong da than thi tien bac nao cung co the bo qua cho nhau.', 'They think closeness means money issues can always be overlooked.', 'Nhung tien la noi rat de lo ra muc do ton trong, ro rang, va giu loi cua moi nguoi.', 'But money quickly reveals how much respect, clarity, and reliability each person really has.', 'Khong it tinh ban vo o noi khong ai muon noi ro ngay tu dau.', 'Many friendships crack where nobody wants to speak clearly from the start.', 'Than den dau thi voi tien van can ro den do.', 'No matter how close you are, money still needs clarity.'),
    story('Chi Hop Mot Giai Doan', 'Some Friends Fit Only One Season', 'Co nhung nguoi rat hop voi em thoi di hoc, vi luc do ca hai cung don gian va it loi keo cua doi.', 'Some people fit you very well during school because life is still simple and light for both of you.', 'Em tuong da hop mot doan thi se hop mai ve sau.', 'You think that if two people fit once, they will fit forever.', 'Nhung khi doi doi, cach song va tham vong doi doi, su hop nhau cung thay doi theo.', 'But when life changes, lifestyle and ambition change, and compatibility changes too.', 'Chap nhan dieu do khong phai vo on. Do la mot cach nhin that.', 'Accepting that is not betrayal. It is honesty.', 'Co nguoi den dung luc va roi di dung luc. Nhu vay da la dep.', 'Some people arrive at the right time and leave at the right time. That can still be beautiful.'),
    story('Cuoi Xin, Cong Viec, Khoang Cach', 'Marriage, Work, and Distance', 'Sau vai nam, lich hen gap ban phai tranh voi ngay cuoi, lich lam, viec con cai, va nhieu lo toan khac.', 'After some years, meeting a friend must compete with weddings, work, children, and many other concerns.', 'Em tuong neu quy nhau that thi nguoi ta se luon xep duoc thoi gian nhu xua.', 'You think true friends should always find time like before.', 'Nhung doi nguoi lon day rat nhieu viec nang. Thoi gian giam di khong nhat thiet co nghia la tinh cam giam di.', 'But adult life fills with heavy tasks. Less time does not automatically mean less care.', 'Neu hieu duoc dieu nay, em se bot tu chuyen lac nhau thanh vet tu ton.', 'If you understand this, you stop turning distance into a personal wound.', 'Ban be lon len thuong giu nhau bang chat luong gap go hon la so lan gap.', 'As friends grow older, they often hold on through quality, not frequency.'),
    story('Gap Lai Khong Con Nhu Cu', 'Meeting Again and Feeling It Is Not the Same', 'Co nhung buoi hop lop hay gap lai ban cu khien em nhan ra moi thu da khong con tu nhien nhu xua.', 'Some reunions make you realize things are no longer easy and natural like before.', 'Em tuong cam giac do co nghia moi thu dep da mat het.', 'You think that feeling means all beauty is gone.', 'Nhung co khi hai con nguoi da doi khac, va buoi gap mat trung thuc chi dang noi len dieu do.', 'But sometimes both people have changed, and an honest meeting is simply revealing that truth.', 'Khong phai ky niem sai. Chi la hien tai da khac.', 'The memory was not false. The present is simply different.', 'Truong thanh la biet ton trong ca ky niem dep lan su that hien tai.', 'Maturity means respecting both the beautiful memory and the present truth.'),
    story('Giu Vi Ky Niem', 'Holding On Only Because of Memory', 'Co nguoi tiep tuc mot tinh ban da met moi chi vi so bo di se phu long qua khu.', 'Someone keeps a tiring friendship alive only because leaving feels like betraying the past.', 'Ho tuong ky niem dep la ly do du de keo mot moi quan he di tiep.', 'They think good memories alone are enough reason to drag a relationship forward.', 'Nhung ky niem nen duoc cam on, khong nen bi ep thanh day xich cho hien tai.', 'But memories should be thanked, not forced into chains that bind the present.', 'Buong mot moi quan he het hop khong xoa ky niem dep cua no.', 'Ending an unfitting bond does not erase its beautiful memories.', 'Ky niem la dieu de nho, khong phai ly do de tu lam kho minh mai.', 'Memory is something to honor, not a reason to hurt yourself forever.'),
    story('Quy Nguoi Con O Lai', 'Valuing the Friends Who Still Remain', 'Sau nhieu lan tan ra, co nguoi bat dau thay ro ai van nho, van hoi, van xuat hien khi can.', 'After many drifting seasons, someone finally sees clearly who still remembers, asks, and shows up when needed.', 'Truoc do ho tuong phai giu tat ca moi la song co tinh.', 'Before that, they thought keeping everyone was the most heartfelt way to live.', 'Nhung doi khi su giau co cua tinh ban khong nam o so luong nguoi quen, ma o vai nguoi con that su o lai.', 'But sometimes the wealth of friendship is not in the number of contacts, but in the few who truly remain.', 'Biet quy mot vai nguoi ben lanh manh hon viec co gang om het nhung quan he da rai het.', 'Valuing a few healthy bonds is wiser than holding all frayed ones.', 'Ban than khong can dong. Chi can that.', 'True friends do not need to be many. They need to be real.'),
]

ch06 = [
    story('Luong Ve Roi Hoa Don Den', 'Salary Arrives and Bills Arrive Too', 'Ngay linh luong dau hay cuoi thang thuong lam nguoi tre thay minh co ve tu do hon.', 'Payday often makes young people feel more free.', 'Ho tuong co tien rieng la tu dong co quyen song nhe va rong hon.', 'They think having personal income automatically creates easy and wide freedom.', 'Nhung tien vua ve thi tien nha, tien an, di lai, va nhieu khoan khac cung xep hang di vao.', 'But as soon as money comes in, rent, food, transport, and many other costs line up to claim it.', 'Luc do em moi thay tu do cua nguoi lon luon di kem bang tinh.', 'Then you see that adult freedom always walks with arithmetic.', 'Tu do khong den tu viec co tien. No den tu viec biet quan no.', 'Freedom does not come from money alone. It comes from knowing how to manage it.'),
    story('Gio Giac Tu Do Thanh Troi Ngay', 'Flexible Time Turns into Lost Days', 'Khong con chuong vao lop hay nguoi nhac, co ban tre bat dau song theo hung va mat nhieu ngay vo ich.', 'With no school bell or constant reminders, a young person starts living by mood and loses many days.', 'Ban ay tuong khong bi quan la mot kieu tu do dep.', 'They think not being controlled is a beautiful kind of freedom.', 'Nhung neu khong biet tu giu nhiep, tu do rat nhanh thanh troi dat va mat huong.', 'But without self-rhythm, freedom quickly turns into drift and confusion.', 'Khong ai quan em nua co nghia la em phai hoc cach tu quan minh.', 'If no one manages you anymore, you must learn to manage yourself.', 'Tu do khong co ky luat thuong thanh mot can phong rong ma nguoi trong do dang dan mục.', 'Freedom without discipline often becomes a wide room where the person inside slowly gets lost.'),
    story('Thue Nha Moi Biet Rang Buoc', 'Rent Teaches You What Obligation Means', 'Khi co cho o rieng, em thay minh duoc tu quyet nhieu hon.', 'When you have your own room or apartment, you feel more self-directed.', 'Em tuong song rieng la cu mo cua ra la gap tu do.', 'You think living alone means opening the door and meeting freedom.', 'Nhung hop dong nha, tien coc, dien nuoc, bao tri, va lich dong tien moi thang nhac em rang moi quyen tu do deu co mot phan rang buoc di kem.', 'But rental contracts, deposits, utilities, repairs, and monthly payment dates remind you that every freedom comes with obligations.', 'Nguoi lon khong chi so huu lua chon. Ho cung so huu hoa don cua lua chon do.', 'Adults do not only own choices. They also own the bills of those choices.', 'Ra rieng khong chi cho em khong gian. No day em ve trach nhiem.', 'Living on your own gives you space, but it also teaches responsibility.'),
    story('Tu Quyet La Tu Chiu', 'Choosing for Yourself Means Carrying the Result Yourself', 'Co nguoi rat thich cam giac duoc tu minh quyet van de lon nho.', 'Some people love the feeling of deciding everything for themselves.', 'Ho tuong duoc tu quyet la phan ngon nhat cua truong thanh.', 'They think self-decision is the sweetest part of adulthood.', 'Nhung tu quyet cung co nghia la neu quyet sai, em khong con nhieu cho de do cho ai khac.', 'But deciding for yourself also means that when the choice is wrong, there is less room to blame others.', 'Phan khoc cua quyen lua chon la phan tu chiu ket qua.', 'The bitter side of choice is carrying the result yourself.', 'Tu do that di kem nang luc gan ket qua do vao chinh ten minh.', 'Real freedom comes with the ability to sign your own name under the outcome.'),
    story('Khong Ai Quan, Cung Khong Ai Cuu', 'No One Controls You, and No One Automatically Saves You', 'Luc nho, gap viec kho con co nha truong, gia dinh, hay nguoi lon day vao giup mot doan.', 'When young, hard moments often bring support from school, family, or adults.', 'Co nguoi tuong lon len se duoc tu do hon ma van co mot mang luoi cuu minh nhu cu.', 'Some think adulthood will offer more freedom while keeping the same rescue net.', 'Nhung ngoai doi, khong ai co nghia vu phai luon den dung luc de do em day.', 'But outside school life, no one is required to show up and carry you at the right moment.', 'Biet tu chuan bi, tu de phong, va tu cau cuu som la mot phan rat that cua truong thanh.', 'Knowing how to prepare, prevent, and ask early for help is a real part of adulthood.', 'Tu do khien em nhe hon khoi su quan ly. No cung bat em nang hon trong viec tu cuu.', 'Freedom lifts some control off you. It also adds the weight of self-rescue.'),
    story('Cuoi Tuan Van Lo Viec', 'Even the Weekend Carries Worry', 'Co ban tung nghi ra doi roi se muon di dau, choi luc nao cung duoc.', 'A young person once thought adult life meant going anywhere and resting whenever they wanted.', 'Ban ay tuong lich cua nguoi lon se rong hon lich hoc sinh.', 'They assume adult schedules are looser than student schedules.', 'Nhung cuoi tuan cua nguoi lon van co viec nha, loi hua, tien nong, suc khoe, va nhieu no lo ngoi ben trong.', 'But adult weekends still carry chores, promises, money concerns, health issues, and quiet worries.', 'Ngay nghi co the van la ngay nghi. Chi la no it nguyen ven hon trong tuong tuong cu.', 'A day off can still be a day off. It is simply less pure than imagined.', 'Ra doi khong it lo hon. No doi lo theo kieu khac.', 'Adult life is not worry-free. It worries in a different way.'),
    story('Tu Do Tieu Tien Thanh No', 'Spending Freedom Turns into Debt', 'Co nguoi lan dau co the mua thu minh thich va thay nhu vay moi dung la song cho ban than.', 'Someone can finally buy what they like and thinks that this is true living for oneself.', 'Ho tuong tu do tai chinh la khong can han che mong muon hien tai.', 'They think financial freedom means not limiting present desire.', 'Nhung khi the, vay app, hay nhung lan quet nhe tay bat dau quay lai doi tien, tu do do nhanh chong bien thanh no.', 'But when cards, apps, or casual swipes return asking for payment, that freedom quickly becomes debt.', 'Khong kiem che duoc mua sam thi tien kiem duoc cung chi la mot vong xich dep hon.', 'If spending cannot be controlled, earned money becomes only a prettier chain.', 'Tu do tai chinh bat dau tu han che, khong bat dau tu bua mua sam lon dau tien.', 'Financial freedom begins with restraint, not with the first big purchase.'),
    story('Qua Nhieu Lua Chon, Cang De Lac', 'Too Many Choices Can Make You More Lost', 'Ra khoi khuon hoc, nguoi tre dung truoc rat nhieu lua chon nghe, noi song, cach song, va huong di.', 'After leaving school structure, young people stand before many choices of work, place, lifestyle, and direction.', 'Ho tuong nhieu lua chon hon dong nghia nhieu tu do hon.', 'They think more options automatically mean more freedom.', 'Nhung neu ben trong khong ro minh la ai va muon gi, nhieu lua chon chi lam dau them on ao.', 'But if you are unclear inside, many options only make the mind louder.', 'Khong phai luc nao cat bot lua chon cung la mat tu do. Doi khi do la cach tim duoc huong.', 'Reducing options is not always losing freedom. Sometimes it is how direction appears.', 'Tu do that can mot cai truc ben trong de khong bi lua chon keo tan.', 'Real freedom needs an inner axis so choices do not tear you apart.'),
    story('Phai Cham Lai Gia Dinh', 'The Time Comes to Care Back for Family', 'Lon len mot chut, em thay bo me met hon va co nhieu viec nha khong con the xep cho nguoi khac.', 'As you grow, you start seeing your parents more tired and many household burdens less easy to hide.', 'Em tuong ra doi la thoat khoi viec bi giao viec va giam sat.', 'You thought adulthood meant escaping chores and supervision.', 'Nhung co mot giai doan no doi huong: em khong chi lo cho minh nua ma con bat dau de y den nguoi da lo cho minh.', 'But life later turns direction: you no longer care only for yourself, but start noticing those who once cared for you.', 'Tu do cua nguoi lon vi the khong nhe hon. No sau hon va nang hon.', 'That is why adult freedom is not lighter. It is deeper and heavier.', 'Ra doi khong phai roi khoi trach nhiem. La buoc vao tang trach nhiem moi.', 'Entering adult life is not leaving duty. It is entering a new layer of duty.'),
    story('Tu Cam Lai Cuoc Doi', 'Holding the Wheel of Your Own Life', 'Sau nhieu va cham, mot nguoi tre nhan ra thu minh can nhat khong phai la them quyen, ma la them tay lai.', 'After many collisions, a young person realizes what is most needed is not more permission, but a steadier hand on the wheel.', 'Truoc do ho tuong tu do la khong ai ngan minh.', 'Before that, they thought freedom meant nobody stopping them.', 'Gio ho thay tu do that la biet minh dang di dau, dang tra gia gi, va co du suc de chiu duong di do.', 'Now they see real freedom as knowing where they are going, what they are paying for, and whether they can carry that road.', 'Khong ai cam lai ho nua cung duoc, mien la chinh ho da hoc cach cam lai lay minh.', 'It is fine that no one drives for them anymore, as long as they have learned to drive themselves.', 'Tu do that khong phai song theo hung. La song co tay lai.', 'Real freedom is not living by impulse. It is living with your hands on the wheel.'),
]

print('Dang tao Quyển 10...')
make_chapter('ch01-tuong-gioi-la-du', 'Tưởng Giỏi Là Đủ', 'Thinking Talent Alone Is Enough', ch01)
make_chapter('ch02-tuong-tu-te-khong-bi-loi-dung', 'Tưởng Tử Tế Là Không Bị Lợi Dụng', 'Thinking Kindness Means No One Will Use You', ch02)
make_chapter('ch03-tuong-yeu-la-giu-duoc', 'Tưởng Yêu Là Giữ Được', 'Thinking Love Guarantees You Can Keep Someone', ch03)
make_chapter('ch04-tuong-co-la-duoc-tra-cong', 'Tưởng Cố Là Sẽ Được Trả Công', 'Thinking Hard Work Is Always Rewarded', ch04)
make_chapter('ch05-tuong-ban-than-di-cung-mai', 'Tưởng Bạn Thân Sẽ Đi Cùng Mãi', 'Thinking Best Friends Stay Forever', ch05)
make_chapter('ch06-tuong-ra-doi-la-tu-do', 'Tưởng Ra Đời Là Tự Do Hơn, Thực Ra Là Trách Nhiệm Hơn', 'Thinking Adult Life Means More Freedom While It Often Means More Responsibility', ch06)
print('Hoan tat Quyển 10!')
