# -*- coding: utf-8 -*-
"""Quyển V -- Hai Mặt Của Một Đồng Xu -- Chapters 5-8"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-5/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    text = re.sub(r'(?<!\\)&', r'\\&', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 5: KHẲNG ĐỊNH TRONG PHỦ ĐỊNH
# ================================================================
ch5 = chapter(
    "Khẳng Định Trong Phủ Định, Phủ Định Trong Khẳng Định", 
    "Affirmation in Negation, Negation in Affirmation",
    "Từ chối cái sai là bước đầu tiên để khẳng định cái đúng.",
    "Rejecting what is wrong is the first step in affirming what is right.",
    [
    story("Lời Khẳng Định Bằng Sự Im Lặng", "Thomas More --- Anh, 1535",
          "Khi",
          [("Khi Vua Henry VIII tự phong làm người đứng đầu Giáo hội Anh, ngài yêu cầu toàn bộ quần thần phải tuyên thệ ủng hộ.",
            "When King Henry VIII declared himself Supreme Head of the Church of England, he required all his subjects to swear an oath of support."),
           ("Thomas More, cựu Tể tướng, đã từ chối tuyên thệ, nhưng ông cũng không mở miệng chỉ trích nhà vua.",
            "Thomas More, the former Lord Chancellor, refused to take the oath, but he also kept his mouth shut from criticizing the king."),
           ("Ông chọn sự im lặng tuyệt đối; nhà vua cho rằng sự im lặng đó là một sự phủ định đầy khiêu khích.",
            "He chose absolute silence; the king considered that silence to be a provocative negation."),
           ("Thomas More bị kết án tử hình vì sự im lặng của mình.",
            "Thomas More was sentenced to death for his silence."),
           ("Nhưng bằng cách phủ định không nói ra lời thề dối trá, ông đã khẳng định mạnh mẽ nhất lương tâm và đức tin của mình trước toàn nước Anh.",
            "But by negating to speak a false oath, he made the strongest affirmation of his conscience and faith before all of England.")],
          "Đôi khi, từ chối tham gia vào sự dối trá chính là lời khẳng định đanh thép nhất cho sự thật.",
          "Sometimes, refusing to participate in a lie is the most resounding affirmation of the truth."),

    story("Chữ ``Không'' Của Rosa Parks", "Rosa Parks --- Hoa Kỳ, 1955",
          "Năm",
          [("Năm 1955 tại Montgomery, luật pháp quy định người da đen phải nhường ghế cho người da trắng trên xe buýt.",
            "In 1955 in Montgomery, the law required Black people to give up their bus seats to white passengers."),
           ("Một buổi chiều muộn, một tài xế yêu cầu Rosa Parks đứng lên nhường ghế, cô chỉ nói một từ: ``Không.''",
            "One late afternoon, a driver ordered Rosa Parks to stand up and give her seat, she said only one word: `No.'"),
           ("Sự phủ định ngắn gọn của cô đã dẫn đến việc cô bị bắt giam ngay lập tức.",
            "Her brief negation led to her immediate arrest and imprisonment."),
           ("Nhưng chính chữ ``Không'' đó đã châm ngòi cho cuộc Tẩy chay xe buýt Montgomery kéo dài 381 ngày.",
            "But that very 'No' ignited the 381-day Montgomery Bus Boycott."),
           ("Bằng cách phủ định một đạo luật bất công, cô đã khẳng định quyền bình đẳng và nhân phẩm của hàng triệu người.",
            "By negating an unjust law, she affirmed the equal rights and human dignity of millions.")],
          "Một chữ ``Không'' đúng lúc có thể kiến tạo lại cả một xã hội.",
          "A well-timed 'No' can rebuild an entire society."),

    story("Steve Jobs Từ Chối Hàng Ngàn Yù Tưởng", "Steve Jobs --- Hoa Kỳ, 1997",
          "Khi",
          [("Khi Steve Jobs trở lại Apple năm 1997, công ty đang sản xuất hàng chục dòng máy tính và máy in chồng chéo nhau.",
            "When Steve Jobs returned to Apple in 1997, the company was producing dozens of overlapping computer and printer lines."),
           ("Ông tổ chức một cuộc họp, vẽ một lưới hai nhân hai lên bảng trắng và nói: ``Chúng ta chỉ làm bốn sản phẩm.''",
            "He held a meeting, drew a two-by-two grid on the whiteboard and said: `We are only making four products.'"),
           ("Ông đã phủ định hơn 300 sản phẩm đang phát triển, cắt giảm 70 phần trăm danh mục của Apple.",
            "He negated over 300 products in development, cutting 70 percent of Apple's portfolio."),
           ("Mọi người kinh ngạc, nhưng Jobs giải thích: ``Tập trung có nghĩa là nói `KHÔNG' với một ngàn ý tưởng tốt khác.''",
            "People were shocked, but Jobs explained: `Focus means saying NO to a thousand other good ideas.'"),
           ("Sự phủ định tàn nhẫn ấy đã giúp Apple dồn toàn lực vào những sản phẩm thực sự vĩ đại, cứu công ty khỏi bờ vực phá sản.",
            "That ruthless negation allowed Apple to put all its strength into truly great products, saving the company from the brink of bankruptcy.")],
          "Để khẳng định một điều xuất sắc, bạn phải dũng cảm phủ định hàng trăm điều tốt.",
          "To affirm one excellent thing, you must bravely negate a hundred good things."),

    story("Lời Phủ Định Của Socrates", "Socrates --- Hy Lạp, 399 TCN",
          "Khắp",
          [("Khắp thành Athens, những nhà triết học tự xưng là người thông thái và biết mọi thứ trên đời.",
            "Throughout Athens, philosophers claimed to be wise and to know everything in the world."),
           ("Nhưng Socrates lại đi khắp nơi với một lời phủ định nổi tiếng: ``Tôi chỉ biết một điều, đó là tôi không biết gì cả.''",
            "But Socrates walked everywhere with a famous negation: `I know only one thing, that I know nothing.'"),
           ("Vì ông cho rằng mình không biết gì, ông liên tục đặt câu hỏi, thách thức những định kiến đã được mặc định là đúng.",
            "Because he assumed he knew nothing, he constantly asked questions, challenging assumptions taken for granted as true."),
           ("Lời sấm truyền ở đền Delphi đã gọi ông là người thông thái nhất Athens --- chính vì ông nhận bết được sự ngu dốt của mình.",
            "The Oracle of Delphi named him the wisest man in Athens --- precisely because he recognized his own ignorance."),
           ("Sống trong tư thế từ chối ảo tưởng tri thức, ông đã khẳng định được bản chất đích thực của trí tuệ.",
            "Living in a posture that rejected the illusion of knowledge, he affirmed the true nature of wisdom.")],
          "Biết giới hạn của bản thân là bước đầu tiên của trí tuệ thực sự.",
          "Knowing one's own limits is the first step of true wisdom."),

    story("Tuyên Ngôn Độc Lập --- Phủ Định Ách Thống Trị", "Thomas Jefferson --- Hoa Kỳ, 1776",
          "Trong",
          [("Trong Tuyên ngôn Độc lập Mỹ, Thomas Jefferson đã bắt đầu bằng việc liệt kê hàng loạt các hành động bạo ngược của Vua Anh.",
            "In the American Declaration of Independence, Thomas Jefferson began by listing the serial tyrannies of the British King."),
           ("Văn kiện này thực chất là một bản cáo trạng lịch sử, một sự phủ định hoàn toàn quyền lực của Đế quốc Anh đối với vùng thuộc địa.",
            "The document was essentially a historical indictment, a complete negation of the British Empire's authority over the colonies."),
           ("Nhưng cũng chính vì phủ định chế độ quân chủ chuyên chế đó, văn kiện đã đưa ra một khẳng định vĩ đại chưa từng có.",
            "But precisely because it negated that tyrannical monarchy, the document made an unprecedented and great affirmation."),
           ("Đó là: ``Mọi người sinh ra đều bình đẳng... được tạo hóa ban cho những quyền không thể xâm phạm, trong đó có quyền Sống, quyền Tự do và mưu cầu Hạnh phúc.''",
            "That is: `All men are created equal... endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.'"),
           ("Sự bác bỏ cái sai đã làm nền tảng vững chắc để xây lên nền dân chủ tự do.",
            "The rejection of the wrong served as the solid foundation to build a free democracy.")],
          "Không đập bỏ những xiềng xích mục nát, ta không thể xây dựng được đài tự do mới.",
          "Without breaking the rotting chains, we cannot build a new monument of freedom."),

    story("Galileo Và Chuyển Động Của Trái Đất", "Galileo Galilei --- Ý, 1633",
          "Trong",
          [("Trong nhiều thế kỷ, Giáo hội tin rằng Trái đất là trung tâm của vũ trụ và mọi vì sao phải xoay quanh nó.",
            "For centuries, the Church believed the Earth was the center of the universe and all stars must revolve around it."),
           ("Galileo quan sát thiên văn và nhận ra sự thật; ông bị đưa ra tòa án dị giáo và bị đe dọa thiêu sống nếu không từ bỏ quan điểm của mình.",
            "Galileo observed the heavens and discovered the truth; he was brought before the Inquisition and threatened with burning at the stake if he did not renounce his view."),
           ("Vì già yếu không muốn chịu nhục hình, ông đành phải đọc lời phủ định chính khám phá khoa học của mình trước công chúng.",
            "Being old and unwilling to suffer torture, he had to publicly read a negation of his own scientific discovery."),
           ("Nhưng ngay lúc bước xuống bục, ông khẽ thì thầm một lời khẳng định bất hủ: ``Dù sao thì trái đất vẫn quay.''",
            "But exactly as he stepped down the podium, he muttered an immortal affirmation: `And yet it moves.'"),
           ("Sự phủ định bằng môi miệng không thể xóa sổ chân lý khách quan mà ông đã khẳng định bằng lý trí.",
            "A verbal negation could not erase the objective truth he had affirmed with reason.")],
          "Sự thật không thay đổi chỉ vì con người bị ép buộc phải chối bỏ nó.",
          "Truth does not change just because people are forced to deny it."),

    story("Bức Tường Berlin Sụp Đổ", "Đức, 1989",
          "Bức",
          [("Bức tường Berlin là biểu tượng vật lý lớn nhất của sự ngăn cách, một sự phủ định tàn nhẫn đối với quyền tự do đi lại và đoàn tụ của người dân Đức.",
            "The Berlin Wall was the greatest physical symbol of separation, a cruel negation of the German people's right to move freely and reunite."),
           ("Trong 28 năm, nó đứng đó từ chối khát vọng tự do, những người cố trèo qua đều bị bắn chết.",
            "For 28 years, it stood there denying the desire for freedom, those who tried to climb over were shot dead."),
           ("Nhưng chính sự tồn tại ngang ngược của bức tường lại càng thổi bùng ngọn lửa khát vọng vượt ngục của người dân.",
            "But the very brutal existence of the wall only fanned the flames of the people's desire to escape."),
           ("Đến tháng 11 năm 1989, sức ép của sự dồn nén đã khiến bức tường này phải sụp đổ trong một đêm không đổ máu.",
            "By November 1989, the pressure of repression caused this wall to fall in a bloodless night."),
           ("Sự phủ định của bức tường cuối cùng lại trở thành nốt nhạc mở đầu cho bài ca thống nhất và dân chủ của cả châu Âu.",
            "The negation of the wall ultimately became the opening note for the song of unification and democracy of all Europe.")],
          "Càng bị áp bức và cấm đoán, khát vọng tự do của con người càng vươn lên mãnh liệt hơn.",
          "The more oppressed and forbidden, the more intensely the human thirst for freedom rises."),

    story("Muhammad Ali Từ Chối Đi Quân Dịch", "Muhammad Ali --- Hoa Kỳ, 1967",
          "Năm",
          [("Năm 1967, Muhammad Ali --- Đương kim Vô địch quyền anh Hạng nặng Thế giới --- nhận lệnh nhập ngũ để sang chiến đấu tại Việt Nam.",
            "In 1967, Muhammad Ali --- the reigning World Heavyweight Boxing Champion --- received orders to be drafted to fight in Vietnam."),
           ("Ông kiên quyết từ chối cầm súng chống lại một dân tộc không hề làm hại mình ở cách xa nửa vòng trái đất.",
            "He adamantly negated taking up arms against a people halfway across the globe who had done him no harm."),
           ("Vì tiếng ``Không'' này, Ali bị tước đai vô địch, cấm thi đấu, bị phạt tù 5 năm và mất đi những năm tháng thanh xuân chói lọi nhất của sự nghiệp.",
            "Because of this 'No', Ali was stripped of his championship title, banned from boxing, sentenced to 5 years in prison, and lost the most prime years of his career."),
           ("Nhưng bằng việc phủ định một cuộc chiến tranh vô nghĩa, ông đã khẳng định bản lĩnh của một biểu tượng hòa bình và chống phân biệt phân biệt chủng tộc.",
            "But by negating a meaningless war, he affirmed the courage of a symbol for peace and anti-racism."),
           ("Ali vĩ đại không chỉ vì những chiến thắng trên sàn võ, mà vì sức mạnh ông thể hiện khi làm trái lệnh các nhà cầm quyền.",
            "Ali was great not only for his victories in the ring, but for the strength he showed in defying the commands of power.")],
          "Kiên định với nguyên tắc đạo đức nội tâm đôi khi đòi hỏi bạn phải từ chối ngay cả vinh quang của thế gian.",
          "Holding fast to internal moral principles sometimes requires you to reject even the glory of the world."),

    story("Sự Từ Chối Của Khổng Minh Về Lương Thưởng", "Gia Cát Lượng --- Trung Quốc, thế kỷ 3",
          "Gia",
          [("Gia Cát Lượng làm Thừa tướng nước Thục, quyền khuynh triều dã, nắm cả vận mệnh quốc gia trong tay.",
            "Zhuge Liang served as Prime Minister of Shu, his power overwhelming the court, holding the nation's destiny in his hands."),
           ("Nhưng ông nhiều lần khước từ mọi bổng lộc, đất đai, châu báu mà Lưu Thiện ban thưởng cho ông.",
            "But he repeatedly negated all salaries, lands, and treasures that Liu Shan bestowed upon him."),
           ("Ông tâu với vua: ``Thần ở Thành Đô có 800 gốc dâu, 15 khoảnh ruộng gầy, con cháu đời đời ăn mặc cũng đủ, không cần ban thêm gì.''",
            "He reported to the king: `Your subject has 800 mulberry trees and 15 acres of poor land in Chengdu, enough for my descendants to eat and clothe for generations, I need no more.'"),
           ("Sự phủ định danh lợi và tiền tài tận cùng đó đã biến Khổng Minh thành biểu tượng bất diệt của lòng trung thành và thanh liêm.",
            "That extreme negation of fame and wealth made Zhuge Liang an immortal symbol of loyalty and integrity."),
           ("Ông chứng minh rằng chính trị gia vĩ đại nhất là người không đòi hỏi bất cứ thứ gì cho bản thân.",
            "He proved that the greatest politician is the one who demands nothing for himself.")],
          "Người không thể bị mua chuộc bởi tư lợi cá nhân là người có sức mạnh bảo vệ lợi ích của thiên hạ.",
          "The one who cannot be bought by personal gain is the one with the strength to protect the public good."),

    story("Cuộc Biểu Tình Ngồi Của Gandhi", "Mahatma Gandhi --- Ấn Độ, 1930s",
          "Khác",
          [("Khác với mọi phong trào giải phóng khác trên thế giới, Gandhi không kêu gọi người dân Ấn Độ cầm súng đánh lại người Anh.",
            "Unlike other liberation movements in the world, Gandhi did not call on the Indian people to take up arms against the British."),
           ("Phương pháp của ông là 'Ahimsa' (Bất bạo động) --- tuyệt đối từ chối sử dụng bạo lực, từ chối hợp tác với chính quyền.",
            "His method was 'Ahimsa' (Non-violence) --- absolutely negating the use of violence, negating cooperation with the authorities."),
           ("Người Ấn Độ bỏ việc, ngồi im trên đường phố, để mặc cho lính canh đánh đập mà không hề phản kháng.",
            "Indians quit their jobs, sat silently on the streets, letting the guards beat them without any retaliation."),
           ("Sự phủ định bạo lực này lại là đòn tấn công mạnh nhất, làm tê liệt hoàn toàn đế quốc Anh và phơi bày sự tàn bạo của kẻ thống trị.",
            "This negation of violence was the most powerful attack, completely paralyzing the British empire and exposing the brutality of the rulers."),
           ("Cuối cùng, không tốn một viên đạn, người Ấn Độ đã khẳng định được nền độc lập của họ trước đế quốc hùng mạnh nhất thế giới.",
            "Ultimately, without firing a single bullet, the Indians affirmed their independence against the world's most powerful empire.")],
          "Sức mạnh tinh thần có sức công phá mãnh liệt hơn bất kỳ vũ khí vật chất nào trên đời.",
          "Spiritual strength has more destructive power than any physical weapon on earth."),
    ]
)

# ================================================================
# CHƯƠNG 6: THẬT TRONG GIẢ, GIẢ TRONG THẬT
# ================================================================
ch6 = chapter(
    "Thật Trong Giả, Giả Trong Thật", 
    "Truth Behind Illusion, Lies Masked as Truth",
    "Những câu chuyện hư cấu hay nhất là những câu chuyện kể sự thật rõ nhất.",
    "The best fictional stories are the ones that tell the truth most clearly.",
    [
    story("Bộ Quần Áo Mới Của Hoàng Đế", "Hans Christian Andersen --- Đan Mạch, 1837",
          "Hans",
          [("Hans Christian Andersen viết một câu chuyện cổ tích về một hoàng đế kiêu ngạo thuê hai thợ may làm cho ông một bộ quần áo tàng hình.",
            "Hans Christian Andersen wrote a fairy tale about an arrogant emperor who hired two tailors to make him invisible clothes."),
           ("Đám thợ may giả vờ đang dệt, và nói rằng chỉ những kẻ ngu ngốc mới không nhìn thấy loại vải tuyệt đẹp này.",
            "The tailors pretended they were weaving, saying that only fools could not see this magnificent fabric."),
           ("Trứơc sự giả dối trơ trẽn đó, toàn bộ triều đình và dân chúng đều sợ lộ sự ngu dốt nên phải thốt lên lơig khen ngợi chiếc áo hư không.",
            "Before that brazen lie, the entire court and populace, fearing to appear foolish, uttered praise for the non-existent clothes."),
           ("Chỉ có một cậu bé vô tư mới dám thốt lên sự thật kinh hoàng: ``Nhưng ngài có mặc quần áo nào đâu!''",
            "Only an innocent little boy dared to blurt out the shocking truth: 'But he isn't wearing anything at all!'"),
           ("Dù đây là một câu chuyện bịa đặt, người ta vẫn kể nó hàng thế kỷ nay bởi nó bóc trần một sự thật bất diệt về bản chất xu nịnh hèn mọn của người lớn.",
            "Though this is an invented story, people have told it for centuries because it strips bare an immortal truth about the cowardly fawning of adults.")],
          "Nghệ thuật là một sự giả dối, nhưng lại giúp chúng ta nhận ra chân lý.",
          "Art is a lie, but it helps us realize the truth."),

    story("Con Ngựa Thành Troy", "Homer / Thần Thoại Hy Lạp --- Cổ đại",
          "Suốt",
          [("Suốt mười năm, quân Hy Lạp bao vây thành Troy bất thành; tường thành quá vững chắc không gì có thể công phá.",
            "For ten years, the Greek army unsuccessfully besieged the city of Troy; the walls were too sturdy for anything to breach."),
           ("Odysseus mưu trí đã nghĩ ra một cái bẫy khổng lồ: dựng một con ngựa gỗ khổng lồ, giấu quân tinh nhuệ vào trong rồi giả vờ rút quân để lại con ngựa làm quà lễ.",
            "The cunning Odysseus devised a giant trap: building a massive wooden horse, hiding elite troops inside, and faking a retreat while leaving the horse as an offering."),
           ("Người dân Troy hân hoan kéo cỗ máy giả tạo ấy vào trong thành để ăn mừng chiến thắng.",
            "The jubiliant Trojans pulled that fake machine into their city to celebrate victory."),
           ("Ban đêm, sự thật đẫm máu tràn ra từ bên trong vỏ bọc hòa bình giả dối, lính Hy Lạp mở cổng thành và hủy diệt vĩnh viễn vương quốc Troy.",
            "At night, a bloody truth poured out from inside the fake peaceful shell, Greek soldiers opened the gates and permanently destroyed the Trojan kingdom.")],
          "Vẻ bề ngoài rực rỡ và vô hại thường là vỏ bọc cho những hiểm họa sâu sắc nhất.",
          "A dazzling and harmless exterior is often the cover for the deepest perils."),

    story("Chiếc Mặt Nạ Của Vua Đảo Cyprus", "Truyền thuyết --- Châu Âu, thế kỷ 16",
          "Một",
          [("Một vị vua hung bạo lên ngôi ở đảo Cyprus, cả cuộc đời ông là sự tàn ác và áp bức đối với người dân.",
            "A cruel king took the throne on the island of Cyprus; his whole life was one of wickedness and oppression toward the people."),
           ("Để che giấu sự già nua và bệnh tật cuối đời, ông ra lệnh các thợ kim hoàn rèn một chiếc mặt nạ bằng vàng tuyệt đẹp, với gương mặt mỉm cười nhân từ.",
            "To hide his old age and illness in his final years, he ordered goldsmiths to forge a beautiful golden mask, with a benevolent smiling face."),
           ("Ông đeo nó suốt những năm tháng cai trị sau cùng, cố tạo ra một sự giả tạo về lòng bao dung thánh thiện.",
            "He wore it throughout his final years of rule, trying to create a facade of holy tolerance."),
           ("Khi ông chết, người dọn dẹp đã lột chiếc mặt nạ ra và kinh hoàng thấy gương mặt thật của ông đã biến dạng nhăn nhúm tột độ bởi sự thù hận dồn nén từ bên trong.",
            "When he died, the cleaners pulled off the mask and were horrified to see his real face was supremely deformed and wrinkled by the hatred compressed inside."),
           ("Mặt nạ bằng vàng có thể đánh lừa người ngoài nhưng không thể ngăn được tâm hồn độc ác bào mòn chính thể xác ông.",
            "A golden mask can deceive outsiders but cannot stop a wicked soul from eroding one's own physical body.")],
          "Sự giả dối dù có bọc vàng cũng không che được sự suy đồi của lương tâm thực sự.",
          "A lie, even wrapped in gold, cannot cover the decay of the true conscience."),

    story("Danh Tính Của Vua Hề Sác Lô", "Charlie Chaplin --- Hoa Kỳ, 1915",
          "Charlie",
          [("Charlie Chaplin xây dựng hình tượng Kẻ Lang Thang (The Tramp) vô cùng lóng ngóng, ăn mặc lố lăng và di chuyển hài hước.",
            "Charlie Chaplin created the image of The Tramp, incredibly clumsy, dressed absurdly, and moving comically."),
           ("Đằng sau những trò hề tưởng chừng như ngớ ngẩn và không thật đó, là tiếng nói vô cùng chân thực dội vào xã hội tư bản lạnh lùng.",
            "Behind those seemingly silly and unreal antics was a profoundly truthful voice striking at the cold capitalist society."),
           ("Bộ phim Modern Times giả vờ nói về chuyện công nhân bị kẹt trong máy móc, nhưng thực tế nó mô tả nỗi đau thật sự của con người bị hệ thống nghiền nát.",
            "The movie Modern Times pretended to be about workers stuck in machines, but in reality it described the true pain of humans crushed by the system."),
           ("Sự ngốc nghếch được dựng lên đã giúp Chaplin nói lên những bất công xã hội mà các diễn giả nghiệm túc chưa chắc đã nói nổi.",
            "The feigned foolishness helped Chaplin speak of social injustices that serious speakers might not have managed so well.")],
          "Sự hài hước hư cấu lại thường là tiếng nói châm biếm sâu sắc và chính xác nhất về cuộc đời.",
          "Fictional humor is often the most profound and accurate satirical voice about life."),

    story("Lời Nói Dối Của Bác Sĩ Ý", "Vittorio Sacerdoti --- Ý, 1943",
          "Trong",
          [("Trong Chiến tranh Thế giới thứ 2, khi quân Đức truy lùng những người Do Thái ở Rome, một bác sĩ tên Vittorio Sacerdoti đã tạo ra một căn bệnh giả bọc tên là ``Syndrome K''.",
            "During World War II, as Germans hunted down Jews in Rome, a doctor named Vittorio Sacerdoti fabricated a fake disease called 'Syndrome K'."),
           ("Ông đưa người Do Thái chạy trốn vào bệnh viện Fatebenefratelli, dạy họ ho sù sụ và thông báo với quân phát xít rằng họ mắc bệnh truyền nhiễm thần kinh cực kỳ nguy hiểm.",
            "He took fleeing Jews into the Fatebenefratelli hospital, taught them to cough violently and informed the fascists they had a highly dangerous, contagious neurological disease."),
           ("Bọn lính Đức sợ lây nhiễm nên không dám bước vào tòa nhà bệnh viện.",
            "The German soldiers, fearing infection, dared not step into the hospital building."),
           ("Căn bệnh giả mạo ấy không tồn tại trong y khoa, nhưng nó đã che chở và cứu sống sinh mạng của hàng chục con người có thật.",
            "That fake disease did not exist in medicine, but it sheltered and saved the actual lives of dozens of people.")],
          "Một lời nói dối thiện ý nhằm cứu người có giá trị cao cả hơn bất kỳ sự thật nào phục vụ cho cái ác.",
          "A well-intentioned lie aimed at saving lives is of higher value than any truth serving evil."),

    story("Lời Thừa Nhận Của Tào Tháo Ở Không Thành", "Gia Cát Lượng --- Trung Quốc, thời Tam Quốc",
          "Khi",
          [("Khi Tư Mã Ý kéo đại quân đánh tới thành Tây mà lượng quân sĩ trong thành của Gia Cát Lượng chỉ còn lác đác vài người già yếu.",
            "When Sima Yi marched a grand army to the West City, Zhuge Liang's soldiers inside were merely a few elderly and weak men."),
           ("Khổng Minh sai mở cửa thành tứ phía, cắt người ung dung quét dọn, còn mình thì mặc gấm lên chòi cao gảy đàn tĩnh tại.",
            "Zhuge Liang ordered all city gates opened, assigned people to sweep leisurely, while he put on brocade and sat on the high tower peacefully playing the lute."),
           ("Vỏ bọc hòa bình bên ngoài hoàn toàn là một trò lừa dối --- quân đội Thục đang trong tình trạng phòng ngự yếu kém tột cùng.",
            "The peaceful facade on the outside was purely a deception --- the Shu army was in an extremely weak defensive state."),
           ("Tuy nhiên, chính hình ảnh giả dối về sự bình tĩnh đó lại xuất phát từ sự thật về bộ óc thiên tài, đầy tự tin của Gia Cát Lượng trong quá khứ, khiến Tư Mã Ý đa nghi không dám tiến vào.",
            "However, that exact fake image of calmness stemmed from the truth of Zhuge Liang's confident, genius mind in the past, making the paranoid Sima Yi afraid to advance."),
           ("Ông đã dùng danh tiếng thật của sự cẩn trọng để bảo chứng cho chiến thuật giả của tự tin, lừa được 15 vạn hùng binh.",
            "He used the true reputation of his caution to back up the fake tactic of confidence, deceiving 150,000 strong troops.")],
          "Kẻ thống soái tài năng biết dùng sự thật làm vỏ bọc cho giả dối, và dùng sự giả dối uy hiếp đến tận tâm can đối thủ.",
          "A talented commander knows how to use truth as a cover for deception, and uses deception to threaten the enemy's very soul."),

    story("Nhà Trọng Tài Phán Xử Của Aesop", "Aesop --- Hy Lạp, cổ đại",
          "Aesop",
          [("Aesop là một nô lệ cực kỳ thông minh, nhưng để tránh bị trừng phạt bởi giới quyền quý vì sự thẳng thắn, ông đã nghĩ ra những chuyện ngụ ngôn về động vật.",
            "Aesop was an exceptionally clever slave, but to avoid punishment by the elite for his bluntness, he invented animal fables."),
           ("Một con Cáo chê nho xanh, một con Rùa thi chạy với Thỏ --- tất cả đều là động vật giả tưởng chưa từng biết nói trong lịch sử.",
            "A Fox disdaining sour grapes, a Tortoise racing a Hare --- all imaginary animals that had never spoken in history."),
           ("Tuy nhiên, người Hy Lạp từ vua chúa đến bần nông đều hiểu rằng lũ thú vật ấy chính là nói về những tính xấu hèn nhát, lười biếng hoặc kiêu ngạo của con người.",
            "However, Greeks from kings to peasants all understood that these animals were talking about the cowardly, lazy, or arrogant flaws of human beings."),
           ("Những câu chuyện giả tạo được kể với mục đích chĩa thẳng vào sự thật chua chát của xã hội loài người.",
            "Those fake stories were told with the purpose of pointing directly at the bitter truth of human society.")],
          "Khi sự thật quá chói tai để lọt lỗ tai quyền lực, người ta thường bọc nó bằng những câu chuyện cổ tích giả tưởng.",
          "When the truth is too harsh to reach the ears of power, people often wrap it in imaginary fairy tales."),

    story("Thí Nghiệm Tâm Lý Về Nhà Tù Stanford", "Philip Zimbardo --- Hoa Kỳ, 1971",
          "Năm",
          [("Năm 1971, nhà tâm lý học Philip Zimbardo đã thiết lập một ''nhà tù'' giả định ở tầng hầm Đại học Stanford, thuê các sinh viên bình thường đóng giả làm quản ngục và tội phạm.",
            "In 1971, psychologist Philip Zimbardo set up a mock 'prison' in the basement of Stanford University, hiring normal students to pretend to be guards and inmates."),
           ("Nhà tù là giả, luật lệ là giả, mọi thứ chỉ là một vở kịch phân vai.",
            "The prison was fake, the rules were fake, everything was just a role-playing act."),
           ("Nhưng trong vòng chỉ 6 ngày, những cai ngục giả bắt đầu dùng các biện pháp tra tấn tâm lý và nhục mạ bạo lực thật sự lên tù nhân.",
            "But within just 6 days, the mock guards began using genuinely violent psychological torture and humiliation on the prisoners."),
           ("Hoàn cảnh giả mạo đã lôi tuột ra bản ngã đen tối và khuynh hướng áp bức vô cùng chân thật ẩn sâu trong mỗi người bình thường.",
            "The fabricated environment dragged out the profoundly real dark ego and oppressive tendencies hidden deep within ordinary people."),
           ("Đạo diễn đã phải kêu dừng và dập tắt cuộc thí nghiệm vì những tổn thương đang diễn ra.",
            "The director had to call a halt and shut down the experiment due to the ongoing trauma.")],
          "Trao quyền lực không giới hạn vào tay con người, bạn sẽ thấy lớp vỏ bọc văn minh tan vỡ nhanh thế nào.",
          "Hand unlimited power to a human, and you will see how quickly the shell of civilization shatters."),

    story("Hiệu Ứng Thuốc Giả (Placebo)", "Y Học Hiện Đại",
          "Hiệu",
          [("Hiệu ứng Placebo là một trong những hiện tượng điên rồ nhất của cơ thể con người: khi bác sĩ kê cho bệnh nhân một viên đường vô hại nhưng bảo rằng đó là thuốc đặc trị.",
            "The Placebo effect is one of the craziest phenomena of the human body: when a doctor gives a patient a harmless sugar pill but says it is a specific medicine."),
           ("Về thể chất, viên đường ấy hoàn toàn là đồ giả vô dụng, không có chút dược tính nào.",
            "Physically, that sugar pill is utterly a useless fake, possessing no medicinal property at all."),
           ("Thế nhưng, sau khi uống thuốc giả đó, triệu chứng đau thực sự của bệnh nhân thuyên giảm, thậm chí hệ miễn dịch thực sự hoạt động mạnh mẽ hơn.",
            "Yet, after taking that fake medicine, the patient's actual pain symptoms alleviate, even their immune system truly functions more strongly."),
           ("Tâm trí tinh tưởng vào viên thuốc giả đã tạo ra những tác động sinh học chữa lành hoàn toàn là sự thật bên trong cơ thể.",
            "The mind believing in the fake pill generated biologically healing effects that were entirely true inside the body.")],
          "Niềm tin sâu sắc của tâm trí có thứ sức mạnh kỳ diệu để biến sự giả dối bên ngoài thành phép màu thật sự từ bên trong.",
          "The profound belief of the mind possesses a miraculous strength to turn an external falsehood into a real miracle from within."),

    story("Bức Họa Của Picasso Giúp Cảnh Sát Hiểu Sự Thật", "Pablo Picasso --- Tây Ban Nha, Pháp",
          "Có",
          [("Có lần, tại nhà ở Paris, xưởng vẽ của Pablo Picasso bị trộm bẻ khóa và đánh cắp một số tiền lớn.",
            "Once, at his home in Paris, Pablo Picasso's studio was broken into and a large sum of money was stolen."),
           ("Cảnh sát đến và vì Picasso là họa sĩ, họ yêu cầu ông phải vẽ lại phác họa chân dung của kẻ đột nhập mà ông kịp nhìn thấy thoáng qua.",
            "The police arrived, and since Picasso was a painter, they asked him to sketch a portrait of the intruder he had briefly glimpsed."),
           ("Danh họa thuộc trường phái lập thể đã vẽ một bức tranh méo mó, các hình khối vỡ vụn với mũi mọc ở thái dương và con mắt thụt trên gáy.",
            "The Cubist master painter drew a distorted portrait, shattered geometric forms with a nose growing on the temple and an eye sunken in the back of the neck."),
           ("Mọi người đều cho rằng bức tranh trừu tượng này là một trò đùa hư cấu không phản ánh được chút gì về nhan sắc thực của tên trộm.",
            "Everyone assumed this abstract painting was a fictional joke reflecting nothing of the thief's true visage."),
           ("Ngày hôm sau, dựa trên bức tranh đó, cảnh sát đã đi bắt... một cái máy giặt cũ và tháp Eiffel vì quá bối rối, đó là một giai thoại châm biếm về nghệ thuật.",
            "The next day, based on that painting, the police went to arrest... an old washing machine and the Eiffel Tower out of sheer confusion; it is an anecdotal satire on art.")],
          "Cái thật và cái giả đôi khi chỉ phụ thuộc vào lăng kính của người hiểu nghệ thuật; đối với thiên tài, thế giới thật thường lố bịch đến khó tin.",
          "Truth and illusion sometimes only depend on the lens of the art comprehender; for a genius, the real world is often incredibly absurd."),
    ]
)

# ================================================================
# CHƯƠNG 7: MẠNH TRONG YẾU, YẾU TRONG MẠNH
# ================================================================
ch7 = chapter(
    "Mạnh Trong Yếu, Yếu Trong Mạnh", 
    "Strength Born from Vulnerability, Weakness within Power",
    "Sức mạnh thật sự không chỉ nằm ở khả năng hủy diệt, mà nằm ở sức bền bỉ trước bão giông.",
    "True strength lies not only in the ability to destroy, but in endurance before the storm.",
    [
    story("Nước Của Đạo Đức Kinh", "Lão Tử --- Trung Quốc, thế kỷ 6 TCN",
          "Trong",
          [("Trong Đạo Đức Kinh, Lão Tử viết rằng: ``Dưới bầu trời này, không gì mềm mỏng và yếu ớt bằng nước.''",
            "In the Tao Te Ching, Lao Tzu wrote: `Under heaven, nothing is more soft and yielding than water.'"),
           ("Nước có thể linh hoạt chảy quanh mọi hòn đá, rơi vào một chiếc bình nó mang hình chiếc bình, rơi vào hồ nó rộng lớn như hồ.",
            "Water can flexibly flow around every rock, poured into a cup it takes the shape of the cup, poured into a lake it expands like the lake."),
           ("Nhưng cũng chính nước là thứ duy nhất trên đời có thể đẽo mòn những tảng đá cứng nhất và phá sập những ngọn núi hùng vĩ theo thời gian.",
            "But it is also water that is the only thing on earth that can wear away the hardest rocks and bring down majestic mountains over time."),
           ("Bởi nước không chống lại khó khăn, nó dung chứa và len lỏi qua khó khăn với sự mềm dẻo tuyệt mức.",
            "Because water does not resist difficulties, it encompasses and weaves through them with ultimate softness.")],
          "Thứ mềm mại nhất lại là thứ có sức chiến thắng cái cứng rắn nhất trên thế gian.",
          "The softest thing is what possesses the power to overcome the hardest thing in the world."),

    story("Cô Thợ May Xinh Xắn Ngừng Chuyến Xe", "Rosa Parks --- Hoa Kỳ, 1955",
          "Một",
          [("Một người phụ nữ trung niên, thấp bé, làm nghề thợ may, một ngày nọ quá đau mỏi chân và nhã nhặn ngồi yên vờ không nghe lời tài xế.",
            "A middle-aged, short, thin woman, working as a seamstress, one day had aching legs and politely sat still pretending not to hear the driver's order."),
           ("Không hề cầm súng, không to tiếng cãi vã, hành động yếu ớt của một người phụ nữ bị coi là hạng bét trong xã hội lúc bấy giờ thật tĩnh lặng.",
            "Holding no gun, shouting no argument, the fragile act of a woman considered the lowest class in society back then was very quiet."),
           ("Nhưng chính sự kháng cự mềm yếu ấy đã truyền sức mạnh to lớn đánh thức phong trào đòi quyền lợi của dân da đen khắp nước Mỹ.",
            "But that very tender resistance transmitted immense strength awakening the civil rights movement for Black citizens across America."),
           ("Những kẻ có cảnh sát, nhà tù và gậy gộc mạnh bạo đã phải nhượng bộ trước một người yếu đuối kiên gan.",
            "Those possessing police, prisons and brutal batons had to give in to a persevering weak person.")],
          "Không có áo giáp nào ngăn được sự kiên cường toát ra từ một tâm hồn không thể bị bẻ gãy.",
          "No armor can stop the resilience radiating from an unbreakable soul."),

    story("Bài Hát Của Người Giam Cầm", "Nelson Mandela --- Nam Phi, 1964",
          "Trong",
          [("Trong nhà lao Đảo Robben, những người canh ngục thuộc chính quyền da trắng sở hữu thứ vũ khí đáng sợ nhất: chiếc roi da và cánh xà lim u tối.",
            "In Robben Island prison, the guards of the white regime possessed the most terrifying weapons: the leather whip and the dark cell door."),
           ("Nelson Mandela là một người tù nhân mang số hiệu bị tước lấy quyền công dân, trở nên bất lực yếu thế trong căn phòng chật chội chưa tới vài mét vuông.",
            "Nelson Mandela was a prisoner reduced to a number stripped of civil rights, becoming powerless and disadvantaged in a cramped room of merely a few square meters."),
           ("Biết không thể chống trả bằng bạo lực, ông mỉm cười nhẹ nhàng nói chuyện đàng hoàng với chính các kẻ cai ngục của mình để học ngôn ngữ của họ.",
            "Knowing he could not fight back with violence, he gently smiled and conversed decently with his own guards to learn their language."),
           ("Sự yếu đuối của cơ thể không những không làm suy chuyển ông mà trái lại lòng khoan dung đó đã đính chính ông trở thành vị thủ lĩnh đạo đức lớn nhất, thu phục cả những trái tim cai ngục lạnh lẽo.",
            "Not only did the weakness of his body not bend him, but instead that very tolerance solidified him as the greatest moral leader, winning over even the cold hearts of the guards.")],
          "Ở tận cùng của sự bất lực thể xác người ta sẽ khám phá ra sức mạnh bất diệt của lòng kiên dung.",
          "At the very edge of physical powerlessness, one discovers the immortal strength of persevering tolerance."),

    story("Thạch Sanh Và Tiếng Đàn", "Cổ Tích --- Việt Nam",
          "Khi",
          [("Khi giặc của mười tám nước chư hầu kéo binh đao hùng hổ, cung tên gươm giáo cờ quạt rợp trời tới đối đầu với nước Việt.",
            "When the enemies from eighteen vassal states marched aggressively with troops and weapons, bows, arrows and flags darkening the sky against Viet country."),
           ("Người anh hùng Thạch Sanh không vác búa đi ra chém giết, thay vào đó chàng ngồi xuống gảy tiếng đàn ngân nga hòa bình.",
            "The hero Thach Sanh did not march out carrying an axe to slay, instead he sat down and played a resonating tune of peace on his lute."),
           ("Âm thanh đàn nỉ non khuyên răn lính tráng nhớ mẹ, thương con, khiến vũ khí trong tay thứ quân hung tàn mạnh mẽ đều rơi lả tả.",
            "The mournful lute sound advised the soldiers to remember their mothers, miss their children, causing weapons in the hands of the brutal strong army to drop scatteringly."),
           ("Một kẻ dùng sự mềm mỏng, âm nhạc yếu ớt đã áp đảo cả một cỗ máy chiến tranh cứng nhắc.",
            "A person using softness, fragile music overwhelmed an entire stiff war machine.")],
          "Vũ khí có thể dùng để đánh đổ thành trì, nhưng chỉ sự dịu dàng của cảm xúc mới thu phục được lòng người.",
          "Weapons can be used to tear down fortresses, but only the gentleness of emotion can conquer people's hearts."),

    story("Cây Tre Trước Cơn Bão", "Triết Lý Á Đông --- Tự nhiên",
          "Những",
          [("Những cây sồi cổ thụ, cây thông vững chắc lớn lên trên thảo nguyên có thân cây to đến mấy người ôm không xuể.",
            "The ancient oak trees, sturdy pines growing on the plains have trunks so large that several people cannot hug them completely."),
           ("Khi bão táp ập đến, sự cứng cáp hoành tráng ấy lại là điểm yếu chết người; chúng không chịu nhượng bộ và vì thế bị gió bẻ gãy rễ bật tung.",
            "When the storm strikes, that magnificent sturdiness is exactly their fatal weakness; they refuse to yield and thus are broken off and uprooted by the wind."),
           ("Ngược lại, một bãi trúc tre thân gầy rỗng ruột mong manh, khi bị gió thổi, chúng dễ dàng oằn mình sát mặt đất.",
            "Conversely, a grove of thin, hollow, fragile bamboos, when blown by the wind, eagerly bend themselves close to the ground."),
           ("Tuy nhiên ngay khi cơn bão đi qua, những cây tre oằn uốn ấy lại bật đứng thẳng lên, không một chiếc gãy.",
            "However, as soon as the storm passes, those bent bamboos spring back up straight, not a single one broken.")],
          "Sự linh hoạt biết cúi mình đúng lúc là cách giữ gìn sự sống trước những đòn giáng mạnh của định mệnh.",
          "The flexibility to bow correctly at the right time is the way to preserve life against the heavy blows of fate."),

    story("Đức Đạt Lai Lạt Ma Và Tình Yêu Vượt Hờn Căm", "Đạt Lai Lạt Ma thứ 14 --- Tây Tạng",
          "Đức",
          [("Đức Đạt Lai Lạt Ma bị buộc phải lưu vong khỏi quê hương Tây Tạng khi còn trẻ, là một tu sĩ mong manh với chiếc áo vá không tấc sắt trong tay.",
            "The Dalai Lama was forced into exile from his Tibetan homeland while young, a fragile monk with patched robes and no weapons in his hand."),
           ("Ông phải đối nghịch lại với một đội quân khổng lồ, súng pháo và thiết giáp vĩ đại.",
            "He had to oppose a massive army, mighty artillery and armor."),
           ("Suốt hơn sáu thập kỷ lẩn tránh, ông chưa từng kêu gọi dân mình báo thù một mạng người, mà luôn răn dạy lòng yêu thương, dùng đạo đức yếu mềm làm khiên giáp.",
            "Throughout over six decades of evasion, he has never called upon his people to revenge a single life, but always preached compassion, using soft morality as armor."),
           ("Thế nhưng uy tín và tinh thần của vị tu sĩ không tấc sắc này lại khiến giới cầm quyền mạnh bạo luôn phải rụt rè chao đảo trên trường quốc tế.",
            "Yet the prestige and spirit of this weaponless monk always makes the powerful ruling forces timid and stagger on the international stage.")],
          "Tâm từ bi yếu mềm luôn mang một lực hấp dẫn phi thường, chiến thắng được cả vũ lực súng đạn khốc liệt nhất.",
          "A fragile compassionate mind always carries an extraordinary gravity, triumphing over even the most fierce firepower."),

    story("Gót Chân Tiêu Diệt Chiến Binh Khổng Lồ", "Arthur / Thần thoại Hy Lạp --- Achilles",
          "Achilles",
          [("Achilles là vị anh hùng mạnh nhất mọi thời đại trong trận chiến thành Troy, làn da của thần chống đỡ mọi loại giáo mác chém đâm.",
            "Achilles was the strongest hero of all time in the Trojan War, his demigod skin resisting all sorts of spears and thrusts."),
           ("Dẫu đã hạ rụng vô số tướng giỏi của kẻ thù trong sự ngạo nghễ với cơ bắp vô song và ý chí như sấm vỡ.",
            "Even having struck down countless enemy generals in arrogance with his peerless muscles and thunder-like will."),
           ("Điểm yếu duy nhất vô hình của chàng nằm ở chỗ khuất lấp mềm yếu nhất nơi gót chân, nơi người mẹ từng nắm khi nhúng vào dòng sông bất tử.",
            "His only invisible weakness lay at the most hidden and fragile spot on his heel, where his mother had grasped him when dipping him into the river of immortality."),
           ("Chỉ với một mũi tên nhỏ tầm thường găm trúng vùng gót chân, biểu tượng bất bại đã gục ngã hoàn toàn.",
            "With just a single ordinary little arrow striking the heel sector, the invincible symbol collapsed entirely.")],
          "Ngay trong lớp áo giáp mạnh nhất cũng che đậy một điểm yếu chết người; đừng bao giờ chủ quan và cho mình là vô song.",
          "Even inside the strongest armor hides a fatal flaw; never be complacent and consider yourself peerless."),

    story("Chú Chó Và Chú Sư Tử", "Fable --- Châu Phi",
          "Có",
          [("Có một con Sư Tử kiêu ngạo tuyên bố mình là kẻ thống trị rừng già vì móng vuốt mạnh mẽ sắc ngọt của bản thân.",
            "There was an arrogant Lion who declared himself ruler of the jungle because of his own sharply strong claws."),
           ("Một chú chó săn nhỏ gầy gò nhìn nó và thách thức, nói rằng lòng dũng cảm thực sự không đến từ vẻ ngoài hú họa.",
            "A small, scrawny hunting dog looked at him and challenged, saying true bravery does not come from intimidating appearances."),
           ("Trong lúc sư tử hung hãn dọa nạt ầm ĩ tốn bao năng lượng, chú chó im lặng tiếp cận theo bầy rồi cắn vào chân sau con sư tử lớn, làm Sư Tử lấm lem bùn đất.",
            "While the fierce lion roared loudly expending much energy, the dog silently approached with its pack and bit the big lion's hind leg, making the Lion muddy and dirty."),
           ("Lực sĩ vĩ đại không biết kết hợp kiên trì bầy đàn dễ dàng thất bại trước một cái yếu biết chớp thời cơ.",
            "The great strongman not knowing to combine pack persistence easily fails before a weak one that knows how to seize the moment.")],
          "Kẻ yếu ớt biết kết hợp sự tỉ mỉ sắc sảo luôn khiến gã khổng lồ chủ quan phải thất điên bát đảo.",
          "A fragile one knowing how to combine keen meticulousness always drives a subjective giant utterly crazy."),

    story("Helen Keller Mù Bầu Trời Nhưng Thấy Vũ Trụ", "Helen Keller --- Hoa Kỳ, 1920",
          "Helen",
          [("Helen Keller không có thứ đặc ân thị giác và thính giác kể từ khi chưa đầy hai tuổi, nhốt cơ thể vào bóng tối câm lặng.",
            "Helen Keller had lacked the privileges of sight and hearing since she was barely two years old, locking her body in silent darkness."),
           ("Nếu có một ai là hóa thân của sự yếu đuối về cơ chế sinh lý học, người đó chính là cô bé chẳng nhìn và nghe thấy thế giới này.",
            "If anyone was the embodiment of vulnerability regarding physiological mechanisms, that person was the little girl unable to see and hear this world."),
           ("Nhưng bằng nỗ lực kiên can không tưởng, bà làm chủ cách trao đổi qua các vệt vuốt trên lòng bàn tay.",
            "But with unimaginably firm effort, she mastered communicating through tactile strokes on her palm."),
           ("Sau này chính người đàn bà yếu kém khuyết tật nhất ấy lại là một trong những diễn giả đại tài truyền lực cảm hứng khổng lồ cho hệ mặt trời tâm lý người lành lặn khác.",
            "Later this very weakest profoundly disabled woman became one of the hugely talented speakers instilling giant inspirational strength to the psychological solar system of other able-bodied people.")],
          "Yếu khuyết thể xác không bao giờ định nghĩa được sự dũng cảm bên trong khối óc linh hồn.",
          "Physical defect can never define the courage inside the mind and soul."),

    story("David và Goliath", "Kinh Thánh --- 1000 TCN",
          "Goliath",
          [("Goliath là tráng sĩ đồ sộ cao lớn như quỷ thần tẩm trong gươm gíáo kiên cố đe lườm toàn bộ phe Do Thái bủn rủn.",
            "Goliath was a giant warrior towering like a demon god armored in sturdy weapons terrifying all the trembling Israelites."),
           ("Một chàng chăn cừu tẻ nhạt cậu bé nhỏ thó David không thèm mặc áo giáp tiến tới với vỏn vẹn một cái ná ném đá trong túi.",
            "A boring shepherd, the small boy David, refused armor and advanced with merely a sling for throwing stones in his pouch."),
           ("Chính sức nhẹ mỏng của cậu lại giúp di chuyển vòng quanh nhanh thoăn thoát, điều mà vỏ thép đồ sộ khó làm.",
            "His very lightweight frailty helped him circle and move swiftly, something the bulky steel armor found hard to do."),
           ("Chàng trai yếu đuối quăng viên đá chuẩn xác trúng khe hở giữa nón giáp khiến chúa quỷ hung hồn đổ sập xuống tắt thở.",
            "The frail boy slung the stone precisely hitting the gap between the helmet making the fierce demon king collapse dead.")],
          "Kích thước khổng lồ chưa chắc là nguồn đảm bảo thành công, kẻ nhỏ nhẹ thông minh biết dùng công cụ có thể là đấng chiến thắng.",
          "Gigantic size is not necessarily a guarantee of success, a small intelligent one knowing how to use tools can be the victor."),
    ]
)

# ================================================================
# CHƯƠNG 8: BẮT ĐẦU TRONG KẾT THÚC
# ================================================================
ch8 = chapter(
    "Bắt Đầu Trong Kết Thúc, Kết Thúc Trong Bắt Đầu", 
    "Every Ending Is a Door, Every Door Is an Ending",
    "Ngày con sâu bướm gọi là ngày tận thế, thì vũ trụ gọi nó là con bướm bay.",
    "What the caterpillar calls the end of the world, the universe calls a butterfly.",
    [
    story("Naturaleza Lửa Và Cây Sequoia Rừng Xanh", "Sinh thái học --- Bắc Mỹ",
          "Trong",
          [("Trong một thời gian dài, các kiểm lâm Mỹ cố gắng dập tắt mọi vụ cháy rừng hòng bảo vệ những cây cổ thụ Sequoia nổi tiếng khổng lồ.",
            "For a long time, American rangers tied to extinguish all forest fires hoping to protect the famously giant ancient Sequoia trees."),
           ("Lạ thay, hàng thập kỷ được vô trùng cứu hỏa trôi qua, cây con Sequoia lại hoàn toàn không phát triển nữa.",
            "Strangely, decades of fire-sterile protection passed, the Sequoia seedlings absolutely stopped growing anymore."),
           ("Các nhà khoa học phát hiện ra chính ngọn lửa chết chóc thiêu rụi tầng lá dưới lại nung giãn nón hạt cứng để nhả mầm non Sequoia xuống đất mun tro ấm.",
            "Scientists discovered that the very deadly fires burning the underbrush are what roast and expand the hard cones to drop young Sequoia seeds into the warm ash soil."),
           ("Cái kết chết chóc tăm tối bằng hỏa hoạn thực ra lại chính là cánh cửa đánh thức tái sinh một mùa xuân mới bừng bung ở khu rừng Bắc Mỹ.",
            "The dark deadly end via conflagration is in fact the very door that awakens the rebirth of a blazing new spring in the North American forests.")],
          "Không có đổ nát và tro bụi tàn rữa, những sức sống mới đôi khi không thể bắt đầu sinh sôi.",
          "Without ruin and decaying ash, new vitality sometimes cannot begin to multiply."),

    story("Cánh Cửa Tù Của Nelson Mandela", "Nelson Mandela --- Nam Phi, 1990",
          "Sau",
          [("Sau khi kết thúc hai mươi bảy năm trong nhà tù đảo tối tăm quạnh hiu tước bỏ thanh xuân của ông, Mandela bước ra tự do trong thân hình cằn cỗi tuổi già.",
            "After concluding twenty-seven years in a desolate dark island prison stripping away his youth, Mandela walked out to freedom in a barren old aged body."),
           ("Người ta thường tưởng cánh cửa nhà tù khóa lại là chấm dứt hoàn toàn một tương lai đầy cống hiến.",
            "People typically thought a locked prison door was the absolute end to a future full of dedication."),
           ("Sự thật là ngày bước chân ra đánh dấu cái chết của khoảng đời lưu vong để bắt đầu cho sự trỗi dậy của một tân Tổng Thống Nam Phi đắc cử vĩ đại nhất.",
            "The truth was the day stepping out marked the death of the exiled period to begin the rise of the greatest elected new President of South Africa."),
           ("Bởi ngày kết thúc chuỗi khổ hình cũng chính là giờ khởi tạo hòa bình xóa tan nạn phân biệt chủng tộc Aparthied trên toàn lãnh thổ.",
            "Because the day concluding the chain of torments was precisely the hour instigating peace erasing the Apartheid racial segregation across the territory.")],
          "Lối ra khỏi nỗi đau khổ của ngày hôm qua chính là cổng vào sự vĩ đại của ngày mai.",
          "The exit from yesterday's suffering is the gate to tomorrow's greatness."),

    story("Thương Hiệu Apple Dưới Bàn Tay Steve Jobs Bị Đuổi", "Steve Jobs --- Hoa Kỳ, 1985",
          "Năm",
          [("Năm 1985, Steve Jobs kết thúc chặn đường huy hoàng ở Apple khi bị đẩy khỏi chính công ty do cá nhân mình khai sinh tạo dựng.",
            "In 1985, Steve Jobs concluded his glorious journey at Apple when pushed out of the very company he personally gave birth to and built."),
           ("Chặng hành trình vất vả ấy giống như cái chết của một giấc mơ lập nghiệp với kết cục đáng xấu hổ cay đắng.",
            "That strenuous journey seemed like the death of an entrepreneurial dream with an embarrassingly bitter end."),
           ("Tuy nhiên chính sự đóng lại khắc nghiệt từ ban giám đốc lại thôi thúc ông khởi đầu NeXT và mua đồ họa hoạt hình Pixar chấn động phòng vé.",
            "However that very harsh shutting down by the board urged him to start NeXT and buy Pixar animation shockingly dominating the box office."),
           ("Cái kết thúc tại Apple chính là sự chuẩn bị bắt đầu cho ông thay đổi thế giới diệu kỳ sâu sắc hơn ở thập kỷ kế tiếp.",
            "The end at Apple was precisely the preparation to start modifying the magical world more profoundly in the next decade.")],
          "Sự kết thúc của một giai đoạn đầy tổn thương đôi khi lại là sự sinh ra của một đế chế huy hoàng.",
          "The end of a traumatic phase sometimes is the birth of a glorious empire."),

    story("Đêm Trươc Khi Nhật Thực Dịch Chuyển Ánh Sáng", "Albert Einstein --- Thụy Sĩ, 1915",
          "Nhiều",
          [("Nhiều nhà vật lý thế kỷ 19 tin rằng các định luật cơ học Isaac Newton vô cùng vĩnh cửu không thể suy chuyển là điểm kết thúc tối cao của vật lý học.",
            "Many 19th century physicists believed Isaac Newton's eternally immovable mechanical laws were the supreme end point of physics."),
           ("Khối lượng và thời gian là khái niệm rắn chắc tĩnh lặng; câu chuyện vũ trụ tưởng chừng đã đóng nắp kết luận cuối cùng tuyệt đối.",
            "Mass and time were solid static concepts; the universe's story seemingly had capped its absolutely final conclusion."),
           ("Nhưng sự sụp đổ định luật Newton khi ánh sáng ngôi sao bị bẻ cong trong kỳ nhật thực lại đánh dấu sự khai sinh học mốc Thuyết Tương Đối.",
            "But the collapse of Newton's laws when starlight bent during the eclipse marked the milestone birth of the Theory of Relativity."),
           ("Một định hình dường như viên mãn kết thúc suốt nhiều trăm năm bị xé toạc mở ra điểm xuất phát cho nhận thức vật lý hiện đại vạn vật.",
            "A realization seemingly satisfactorily concluded for several hundreds of years was torn open to reveal the starting point for modern physics perception of all things.")],
          "Mọi học thuyết tri thức đạt tới cái kết giới hạn của nó đều chỉ là điểm mở màn cho một bí mật sâu rộng cao xa hơn.",
          "Every theoretical knowledge reaching its concluding limit is only an opening point for a deeper broader further secret."),

    story("Bản Giao Hưởng Thứ 9 Vĩ Đại Cúi Xuống Khép Lại", "Ludwig van Beethoven --- Áo, 1824",
          "Khi",
          [("Khi nốt nhạc tột cùng trong khúc trường ca bất hủ số chín được buông lơi chấm dứt hoàn toàn, sảnh đường bao chùm trong im lặng.",
            "When the supreme note in the immortal ninth epic fell completely silent, the hall was wrapped in stillness."),
           ("Sự thinh lặng kết màn với ông thực tế đã bao trùm từ rất lâu do sự điếc lác cướp đi khả năng cảm nhận.",
            "The concluding silence for him in reality had encompassed long ago due to deafness robbing his perceptual ability."),
           ("Nhưng khi nốt nhạc chót từ bản hòa ca của đôi tai mù ngã lụi buông đoạn kết, trọn vẹn cả kháng phòng mới đứng bật dậy nổ vỗ tay khai màn tiếng khóc mừng.",
            "But when the last musical note from the blind ears' symphony dropped its concluding segment, completely the entire audience surged up exploding in applause opening tears of joy."),
           ("Bài ca chấm dứt dội lên đỉnh phong trào lan tỏa tình anh em nhân loại, cái điếc của đôi tai nhường chỗ âm vang khai sáng linh hồn đến hậu thế.",
            "The finalizing song surged onto the peak spreading the movement of human brotherhood, the deafness of the ears yielding to the echoing enlightenment of souls to posterity.")],
          "Khoảnh khắc giai điệu cuối lịm tắt ở kiếp này là lời mở màn trường tồn cho một hành trình xuyên thời đại tương lai.",
          "The moment the final melody fades in this life is the everlasting opening act for a journey spanning future eras."),

    story("Mảnh Giấy Hôn Thú Gấp Lại", "J.K. Rowling --- Anh, 1993",
          "Cuộc",
          [("Cuộc hôn nhân đầu tiên ngắn ngủi bi đát đứt quãng, cùng công việc bị sa thải hoàn toàn khiến nhà văn bà chới với cùng đường nơi nước ngoài.",
            "The short tragic suspended first marriage, along with the completely fired job left the female writer flailing dead-ended in a foreign country."),
           ("Giấy ly hôn đặt dấu chấm hết trọn dứt vào sự ngây thơ cuộc sống có màu hồng lụa.",
            "Divorce papers put an absolute end dot on the silk pink innocent life."),
           ("Trong căn phòng trợ cấp ẩm ướt lùi lủi của ngày tàn kiệt ngã giá, cái kết bế tắc khốc liệt đó lại là mảnh mở châm ngòi cho Harry Potter xuất gia.",
            "In the damp dreary subsidy room of the exhausted fading day, that fierce dead-end conclusion was the spark snippet originating Harry Potter to depart."),
           ("Bởi không lún sâu xuống tận đáy vực mất tất cả kết thúc rồi, con người ta chẳng màng tự đập phá vươn lên bằng đam mê duy nhất vĩ đại.",
            "For without sinking to the absolute bottom valley losing everything concluded, humans wouldn't bother self-breaking to rise via the grandest single passion.")],
          "Đáy vực mất mát của sự kết thúc luôn là bệ phóng hoành tráng vững chắc dậm khởi hoàn mĩ.",
          "The valley bottom of concluding loss is always a solid majestic launchpad for perfect bounding starts."),

    story("Thất Bại Ở Pháp Và Mỹ Quốc Mở Lòng", "Anh Em Nhà Wright --- Cổ đại",
          "Sau",
          [("Sau khi nài nỉ các cơ quan khoa học quân đội trình bày ý tưởng bay bị phủ quyết chấm hết mọi nỗ lực tài trợ.",
            "After pleading with military science agencies presenting flying ideas denied concluding all funding efforts."),
           ("Giấc mơ cất cánh kết cục trong phòng lab dường hệt một dấu thập ác chết uổng đóng mồ.",
            "The take-off dream ended in the lab looking exactly like a wasted death cross sealing the grave."),
           ("Cái kết thúc từ bệ phóng tiền bạc xã hội buộc hai chàng dân sửa xe đạp bay trở ngược ra Kitty Hawk cánh đồng tự lập tay không.",
            "The end from the social money launchpad forced the two bicycle mechanics to fly back to Kitty Hawk open field individually empty handed."),
           ("Và chiếc máy bay lịch sử đầu đời khởi sự cất lên trời cao chính vì cái sự quay lưng kết thúc thảm đạm từ thế giới quyền lực kia.",
            "And the first lifetime historical airplane commenced taking to the high sky precisely because of that bleak concluding turning back from the powerful world.")],
          "Sự từ chối đóng chốt của người ngoài là cửa ngõ gọi dậy lòng tin thắp lửa nội tại tự lực.",
          "The shutting rejection of outsiders is the gateway waking up intrinsic self-made fire-lighting faith."),

    story("Lời Trăng Trối Của Socrates Chén Thuốc Độc", "Socrates --- Hy Lạp, 399 TCN",
          "Khi",
          [("Khi hình án tuyên xử uống dứt chiếc mâm đầy thuốc độc hemlock lạnh lẽo kết liễu mạng ông lão điềm nhiên bình thản chết trong tù.",
            "When the sentence verdict ordered finishing the bowl full of cold hemlock poison terminating the old man's life calmly dying in prison."),
           ("Tất thảy đám học trò than khóc thảm thương cho một dòng tư tưởng lụi tàn kết thúc biến diệt.",
            "All the flock of students cried pathetically for an extinguished concluding stream of thought vanishing away."),
           ("Nào ngờ thay thân tàn kết lìa, các bài biện triết tự do được Platon chép giấy lưu hổi ngàn năm khai sáng toàn cõi châu Âu văn minh cận đại.",
            "Unexpectedly his ruined body departed, the free dialectical essays copied down by Plato endured for thousands of years enlightening the entire realm of modern civilized Europe."),
           ("Bản án cái chết vốn dụng ý bịt miệng vĩnh viễn hóa ra lại là tiếng loa vang khai sinh nguồn sáng chói soi nhân triết tự do không nghỉ ngơi.",
            "The death sentence basically intending to silence forever turned out to be the echoing loudspeaker birthing the radiant light illuminating restless free human philosophy.")],
          "Kẻ thống trị tưởng mình đóng hòm cái chết sự kháng cự, không hay biết đã tưới chất phân bón bắt rễ cho vĩnh cửu tư tưởng vươn cành.",
          "Rulers thought they coffined the death of resistance, unaware they watered the fertilizer rooting everlasting thought to spout branches."),

    story("Thiên Hạch Sao Băng Hủy Diệt Phân Bổ Nguồn Sống", "Lịch sử Hệ Cổ Sinh --- Trái Đất",
          "Một",
          [("Một khối thiên thạch khổng lồ từ không gian hung hăng lao ập làm nổ tung xóa sổ kết thúc bạo tàn kỷ nguyên thống trị ngự trị của tộc Khủng Long.",
            "A giant meteorite from space aggressively crashed exploding blowing validating the brutal concluding era of Dinosaur domination."),
           ("Khoảng không mịt mù bao phủ khép lại triều đại hàng triệu triệu rêu đá bồ hạch thênh thang, đem lại dấu tuyệt chủng cho quái thú khổng lồ.",
            "The murky void wrapped shutting up the reigning dynasty of millions of sprawling pebbled mosses, bringing the extinction mark for giant beasts."),
           ("Nhưng tại chính điểm diệt vong u khuất của những khối hình siêu thú bạo hùng đã bắt đầu khai sinh ra kỷ nguyên cho những loài động vật có vú vi tế hưng vượng.",
            "But at the very obscure devastating point of super massive heroic beasts began birthing the era for subtle flourishing mammalian species."),
           ("Nếu chẳng có cái đứt bóng tang thương nọ làm hồi chuông kết liễu, loài tinh khôn hữu nhũ và con người mãi mãi không có kẽ hở bắt đầu một triều đại hiện hình.",
            "Without that lamentable shadow break acting as a concluding bell, intellectual mammals and humanity forever had no crevice to start a manifested dynasty.")],
          "Sự diệt vong tận tuyệt của một trật tự luôn chứa đựng khe sáng khởi xướng nôi bắt rễ kỳ quan sinh cơ hoàn toàn mới.",
          "The absolute annihilation of an order always harbors a crack of light initiating the rooting cradle of an entirely new biological marvel."),

    story("Cánh Hoa Đào Lụi Rụng Sinh Hương Cho Quả Mới", "Tự Nhiên --- Thường Thức",
          "Để",
          [("Để một vòng đời kết tinh đâm trồi sinh ra quả mọc quả hạch no căng nịnh mắt đỏ rực ngát hương cho con người gặt ngọt.",
            "For a crystallized life cycle to sprout birth bearing plump eye-catching bright red luscious drupe fruits for humans to lovingly harvest."),
           ("Những bông cánh hoa kiêu sa hồng thắm kiều diễm đã phải bắt buộc lạt mềm chấn héo rồi thả mình tàn rụng rã gục kết thúc ngay xuống đất bùn nhem bẩn.",
            "The graceful bright pink elegant flower petals absolutely had to wither softly dropping rotting collapsing concluding right onto the dirty muddy earth."),
           ("Sự biến mất tàn khốc thảm họa dưới đáy rễ lại là quá trình dồn mật dịch sinh dưỡng châm còi lên trái căng ngon.",
            "The cruel catastrophic disappearance at the root bottom is actually the nourishing nectar compressing process triggering the juicy plump fruit."),
           ("Nếu nụ hoa quyến luyến kiêu kỳ không chịu tàn khô rơi khép vòng lại, quả mới rực ngời mầm hạt chẳng thể sinh hạ tái khai đơm đọng hương cành.",
            "If the reluctant haughty bud refused to wither dry dropping closing the cycle, the radiantly new fruit sprout seed could not be given birth restarting perfuming the branch.")],
          "Bất cứ cái đẹp rực rỡ nào của quá khứ kết thúc rụng rơi chính là dưỡng liệu màu mỡ khơi lửa bừng mầm xanh nôi ươm sáng rạng lai phục.",
          "Any radiant beauty of the past concluding dropping off is precisely the fertile nutrient igniting the green sprout cradle nursery for brilliant resurrection.")
    ]
)

# ================================================================
# GHI FILE
# ================================================================
files = [
    ("ch05-khang-dinh-trong-phu-dinh", ch5),
    ("ch06-that-trong-gia", ch6),
    ("ch07-manh-trong-yeu", ch7),
    ("ch08-bat-dau-trong-ket-thuc", ch8),
]
for fname, content in files:
    path = os.path.join(BASE, f"{fname}.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{fname} done")
print("All chapters 5-8 generated successfully!")
