# -*- coding: utf-8 -*-
"""Quyển V -- Hai Mặt Của Một Đồng Xu -- Chapters 1-4"""
import os, unicodedata, re

BASE = "/Users/admin/Giang-Day-html/truyen-tich-cam-hung-quyen-5/chapters"
os.makedirs(BASE, exist_ok=True)

def story(title, source, first_letter, pairs_body, lesson_vn, lesson_en):
    lines = []
    lines.append(f"\\section{{{title}}}")
    lines.append(f"\\begin{{truyen}}{{{title}}}{{{source}}}")
    first_vn, first_en = pairs_body[0]
    rest = first_vn[len(first_letter):]
    lines.append(f"\\chuhoa{{{first_letter[0]}}}{{{first_letter[1:]}}}{rest}\\\\[4pt]")
    lines.append(f"\\textit{{({first_en})}}")
    lines.append("")
    for vn, en in pairs_body[1:]:
        lines.append(f"{vn}\\\\[4pt]")
        lines.append(f"\\textit{{({en})}}")
        lines.append("")
    lines.append("\\end{truyen}")
    lines.append("\\begin{baihoc}")
    lines.append(f"  {lesson_vn}\\\\[4pt]")
    lines.append(f"  \\textit{{({lesson_en})}}")
    lines.append("\\end{baihoc}")
    lines.append("")
    return "\n".join(lines)

def fix(text):
    text = re.sub(r'(?<!\\)%', r'\\%', text)
    return unicodedata.normalize("NFC", text)

def chapter(chap_vn, chap_en, quote_vn, quote_en, stories):
    lines = [
        "%============================================================",
        f"\\chapter{{Bài Học: {chap_vn} ({chap_en})}}",
        "\\begin{center}",
        f"  \\textit{{\\color{{truyengold}}``{quote_en}''}}\\\\[4pt]",
        f"  \\textit{{({quote_vn})}}\\\\[4pt]",
        "  \\small\\color{truyenblue}--- Cổ Kim Đông Tây ---",
        "\\end{center}",
        "\\ngancach",
        "",
    ]
    for s in stories:
        lines.append(s)
    return fix("\n".join(lines))

# ================================================================
# CHƯƠNG 1: PHÚC TRONG HỌA, HỌA TRONG PHÚC
# ================================================================
ch1 = chapter(
    "Phúc Trong Họa, Họa Trong Phúc", "Every Misfortune Carries a Hidden Blessing",
    "Điều mà hôm nay ta gọi là tai họa, ngày mai có thể là cội nguồn của phúc lộc.",
    "What we call misfortune today may be the very root of our blessings tomorrow.",
    [
    story("Tái Ông Mất Ngựa", "Hoài Nam Tử --- Trung Quốc, thế kỷ 2 TCN",
          "Tái",
          [("Tái Ông sống ở vùng biên giới; một ngày con ngựa quý của ông bỗng nhiên bỏ chạy sang đất địch.",
            "Old Man Sai lived on the frontier; one day his prized horse suddenly ran away to enemy territory."),
           ("Hàng xóm đến an ủi, ông chỉ mỉm cười nói: ``Biết đâu đây chẳng phải là phúc?''",
            "Neighbors came to console him; he simply smiled and said: `Who knows, perhaps this is a blessing?'"),
           ("Ít tháng sau, con ngựa trở về và dẫn theo một bầy ngựa hoang quý hiếm từ đất địch.",
            "A few months later, the horse returned, leading a herd of fine wild horses from enemy lands."),
           ("Hàng xóm chúc mừng ông gặp may; ông lại lắc đầu thở dài: ``Biết đâu đây chẳng phải là họa?''",
            "Neighbors congratulated him on his good fortune; he shook his head and sighed: `Who knows, perhaps this is a misfortune?'"),
           ("Con trai ông cưỡi ngựa mới thì bị ngã gãy chân; rồi chiến tranh nổ ra, trai tráng làng bị bắt lính gần hết --- chỉ con ông ở nhà vì bị gãy chân mà thoát chết.",
            "His son rode the new horse and broke his leg; then war broke out and nearly all the young men were conscripted --- only his son stayed home due to the broken leg and survived.")],
          "Phúc và họa luân chuyển nhau không ngừng; kẻ trí giữ bình thản trước cả hai, vì không ai biết điều gì đến tiếp theo.",
          "Fortune and misfortune rotate endlessly; the wise stay calm in the face of both, for no one knows what comes next."),

    story("Edison Mất Xưởng Trong Đêm", "Thomas Edison --- Hoa Kỳ, 1914",
          "Năm",
          [("Năm 1914, khi Edison đã 67 tuổi, toàn bộ xưởng nghiên cứu của ông bùng cháy trong đêm và thiêu rụi gần như toàn bộ công trình cả đời.",
            "In 1914, when Edison was 67, his entire research facility burned to the ground overnight, destroying almost all the work of his lifetime."),
           ("Con trai ông --- Charles --- chạy đến ngây người nhìn ngọn lửa, tưởng cha sẽ suy sụp.",
            "His son Charles rushed to the scene and stood frozen watching the flames, expecting his father to collapse."),
           ("Edison nhìn lửa cháy rồi quay sang nói: ``Đi gọi mẹ con lại đây; cảnh tượng như thế này không phải ngày nào cũng thấy được đâu.''",
            "Edison watched the fire, then turned and said: `Go fetch your mother; a sight like this doesn't come around every day.'"),
           ("Sáng hôm sau, ông đứng giữa đống tro than tươi cười nói: ``Tất cả những sai lầm cũ của ta đã bị thiêu sạch rồi --- ta có thể bắt đầu lại từ đầu.''",
            "The next morning, he stood in the ashes smiling and said: `All my old mistakes have been burnt away --- I can start fresh.'"),
           ("Trong vòng ba tuần, Edison đã thiết lập lại xưởng mới và tiếp tục phát minh thêm hai mươi năm nữa.",
            "Within three weeks, Edison had set up a new facility and continued inventing for another twenty years.")],
          "Trong mỗi đám cháy đều có hạt giống của sự tái sinh --- nếu bạn đủ bình tâm để nhìn thấy chúng.",
          "Within every fire lie the seeds of rebirth --- if you are calm enough to see them."),

    story("J.K. Rowling Bị Sa Thải Và Ly Hôn", "J.K. Rowling --- Anh, 1993",
          "Năm",
          [("Năm 1993, J.K. Rowling rơi xuống tận đáy: bị sa thải, ly hôn, đang nuôi con một mình trong căn hộ ẩm thấp, sống nhờ trợ cấp xã hội.",
            "In 1993, J.K. Rowling hit rock bottom: fired, divorced, raising a child alone in a damp flat, living on welfare."),
           ("Bà tự nhận mình là ``kẻ thất bại lớn nhất mà bà từng biết'' vào giai đoạn đó.",
            "She described herself as `the biggest failure she knew' during that time."),
           ("Nhưng chính trong những tháng ngày tuyệt vọng đó, bà viết không ngừng nghỉ --- và Harry Potter ra đời.",
            "But it was during those desperate months that she wrote without stopping --- and Harry Potter was born."),
           ("Sau này bà nói: ``Thất bại đã lột bỏ đi tất cả những thứ không cần thiết; chỉ còn lại thứ duy nhất quan trọng với tôi là viết.''",
            "Later she said: `Failure stripped away everything unnecessary; what was left was the one thing that truly mattered to me --- writing.'"),
           ("Bộ sách Harry Potter trở thành thương hiệu tỷ đô, và J.K. Rowling trở thành tác giả đầu tiên trong lịch sử trở thành tỷ phú nhờ viết sách.",
            "The Harry Potter series became a billion-dollar franchise, and J.K. Rowling became the first author in history to become a billionaire through writing.")],
          "Khi cuộc đời tước đoạt mọi thứ của bạn, điều còn lại chính là điều bạn thực sự là.",
          "When life strips everything away from you, what remains is who you truly are."),

    story("Thất Bại Của Trần Hưng Đạo Tại Vạn Kiếp", "Trần Hưng Đạo --- Việt Nam, 1285",
          "Năm",
          [("Năm 1285, quân Nguyên Mông tràn vào Đại Việt với lực lượng áp đảo; Trần Hưng Đạo buộc phải rút lui, nhường thành Thăng Long cho giặc.",
            "In 1285, Mongol forces flooded into Dai Viet with overwhelming numbers; Tran Hung Dao was forced to retreat, ceding Thang Long to the enemy."),
           ("Nhiều tướng sĩ hoang mang, một số thậm chí bàn chuyện đầu hàng.",
            "Many officers were demoralized; some even discussed surrender."),
           ("Trần Hưng Đạo viết hịch tướng sĩ --- một trong những áng văn nổi tiếng nhất lịch sử --- không phải từ đỉnh cao chiến thắng mà từ đáy sâu thất bại.",
            "Tran Hung Dao wrote the Proclamation to Officers --- one of the most famous texts in history --- not from the heights of victory but from the depths of defeat."),
           ("Ông dùng chính nỗi nhục của thất bại như thanh củi đốt lên ngọn lửa tinh thần cho cả quân đội.",
            "He used the very shame of defeat as kindling to ignite the fighting spirit of the entire army."),
           ("Hai năm sau, quân Đại Việt đánh tan quân Nguyên Mông trong trận Bạch Đằng --- một trong những trận thắng vĩ đại nhất châu Á thế kỷ 13.",
            "Two years later, Dai Viet's forces annihilated the Mongols at Bach Dang River --- one of the greatest military victories in 13th-century Asia.")],
          "Thất bại không phải là điểm cuối; đó là lửa thử vàng --- kẻ thật sự mạnh sẽ bước ra sáng chói hơn.",
          "Defeat is not the end; it is the fire that tests gold --- those who are truly strong emerge shining brighter."),

    story("Steve Jobs Bị Đuổi Khỏi Apple", "Steve Jobs --- Hoa Kỳ, 1985",
          "Năm",
          [("Năm 1985, ở tuổi 30, Steve Jobs bị sa thải khỏi chính công ty mà ông đã sáng lập từ tay không trong nhà để xe.",
            "In 1985, at 30 years old, Steve Jobs was fired from the very company he had founded from nothing in a garage."),
           ("Ông kể lại: ``Tôi thực sự không biết phải làm gì trong vài tháng đầu tiên; cảm giác như mình bị cả thung lũng Silicon ruồng bỏ.''",
            "He recalled: `I really didn't know what to do for the first few months; it felt like I had been rejected by the entire Silicon Valley.'"),
           ("Nhưng chính giai đoạn đó ông sáng lập NeXT và Pixar --- hai công ty đã thay đổi ngành công nghệ và điện ảnh thế giới.",
            "But during that very period he founded NeXT and Pixar --- two companies that revolutionized the technology and film industries."),
           ("Khi Apple mua lại NeXT năm 1996 và Jobs trở lại, ông đã mang theo nền tảng kỹ thuật từ NeXT để tạo ra Mac OS X, iPod, iPhone, iPad.",
            "When Apple acquired NeXT in 1996 and Jobs returned, he brought the technical foundation from NeXT to create Mac OS X, iPod, iPhone, and iPad."),
           ("Jobs nói tại lễ tốt nghiệp Stanford: ``Bị sa thải khỏi Apple là điều tốt nhất xảy ra với tôi --- sự nhẹ nhõm của kẻ mới bắt đầu thay thế sức nặng của kẻ thành công.''",
            "Jobs said at Stanford's commencement: `Getting fired from Apple was the best thing that ever happened to me --- the lightness of being a beginner replaced the heaviness of success.'")],
          "Đôi khi cú đẩy khỏi chỗ ta đang đứng chính là bàn tay định mệnh đưa ta đến chỗ ta nên đến.",
          "Sometimes the push that knocks us from where we stand is the hand of fate guiding us to where we belong."),

    story("Louis Braille Mù Mắt Lúc Ba Tuổi", "Louis Braille --- Pháp, 1812",
          "Louis",
          [("Louis Braille bị mù hoàn toàn lúc ba tuổi do tai nạn trong xưởng da của cha.",
            "Louis Braille became completely blind at age three due to an accident in his father's leather workshop."),
           ("Ở thế kỷ 19, người mù gần như bị loại khỏi xã hội --- không thể đọc, không thể học, không thể làm việc.",
            "In the 19th century, the blind were nearly excluded from society --- they could not read, study, or work."),
           ("Chính vì bị mù, Louis Braille dành toàn bộ tuổi thơ để suy nghĩ về vấn đề người mù cần gì nhất để sống được.",
            "Precisely because he was blind, Louis Braille spent his entire childhood thinking about what the blind needed most to live fully."),
           ("Năm 15 tuổi, ông phát minh ra hệ thống chữ nổi Braille --- vẫn được 285 triệu người mù trên thế giới sử dụng đến hôm nay.",
            "At 15, he invented the Braille writing system --- still used today by 285 million visually impaired people worldwide."),
           ("Nếu Louis Braille không bị mù, chắc chắn sẽ không có chữ Braille --- tai họa của một người đã trở thành ánh sáng của triệu người.",
            "Had Louis Braille not been blind, the Braille system would certainly not exist --- one person's tragedy became millions of people's light.")],
          "Chính những giới hạn khắc nghiệt nhất đôi khi tạo ra những khả năng phi thường nhất.",
          "The harshest limitations sometimes create the most extraordinary possibilities."),

    story("Beethoven Điếc Vẫn Sáng Tác Bản Giao Hưởng Số 9", "Ludwig van Beethoven --- Áo, 1824",
          "Beethoven",
          [("Beethoven bắt đầu mất thính giác từ năm 28 tuổi và điếc hoàn toàn khi ông 44 tuổi.",
            "Beethoven began losing his hearing at age 28 and was completely deaf by 44."),
           ("Nhiều người nghĩ sự nghiệp nhạc sĩ của ông đã kết thúc --- không ai điếc mà có thể sáng tác nhạc được.",
            "Many believed his musical career was over --- no deaf man could possibly compose music."),
           ("Nhưng chính trong những năm hoàn toàn điếc, Beethoven đã sáng tác những tác phẩm vĩ đại nhất của mình: Giao Hưởng Số 9, Missa Solemnis.",
            "But it was during his years of complete deafness that Beethoven composed his greatest works: Symphony No. 9, Missa Solemnis."),
           ("Khi Giao Hưởng Số 9 được biểu diễn lần đầu năm 1824, Beethoven đứng trên sân khấu nhưng không nghe được một nốt nhạc nào.",
            "When Symphony No. 9 premiered in 1824, Beethoven stood on stage but could not hear a single note."),
           ("Khi nhạc kết thúc và khán giả vỗ tay nhiệt liệt, người ta phải quay ông lại để ông nhìn thấy --- vì tai ông không còn nghe được tiếng vỗ tay nữa.",
            "When the music ended and the audience erupted in applause, someone had to turn him around so he could see --- because his ears no longer heard the clapping.")],
          "Điếc không giết được nhạc trong tâm hồn Beethoven; đôi khi mất đi một giác quan sẽ làm cho tâm hồn nghe thấy rõ hơn.",
          "Deafness could not kill the music in Beethoven's soul; sometimes losing one sense allows the soul to hear more clearly."),

    story("Hải Thượng Lãn Ông Bị Từ Chối Thi Cử", "Lê Hữu Trác --- Việt Nam, thế kỷ 18",
          "Lê",
          [("Lê Hữu Trác --- sau này là danh y Hải Thượng Lãn Ông --- hai lần dự thi và không đỗ, bị xem là kẻ thất bại dưới mắt xã hội.",
            "Le Huu Trac --- later the great physician Hai Thuong Lan Ong --- failed the imperial exams twice and was viewed as a failure by society."),
           ("Ông bỏ con đường công danh và trở về quê, lúc đó mắc bệnh nặng và nằm liệt giường.",
            "He abandoned the path of officialdom and returned home, where he fell gravely ill and was bedridden."),
           ("Trong thời gian bệnh, ông nghiên cứu y học để tự cứu mình, rồi nhận ra đây mới là con đường ông sinh ra để đi.",
            "During his illness, he studied medicine to heal himself, and realized this was the true path he was born to walk."),
           ("Ông đi khắp núi rừng tìm thuốc, học hỏi từ dân gian và các học giả, rồi viết bộ Y Tông Tâm Lĩnh hàng chục cuốn --- bách khoa toàn thư y học đầu tiên của Việt Nam.",
            "He travelled through mountains gathering herbs, learned from villagers and scholars, then wrote the Y Tong Tam Linh, dozens of volumes --- Vietnam's first medical encyclopedia."),
           ("Nếu ông đỗ khoa cử và làm quan, y học cổ truyền Việt Nam đã mất đi một tên tuổi vĩ đại nhất lịch sử.",
            "Had he passed the exams and become an official, Vietnamese traditional medicine would have lost its greatest name in history.")],
          "Con đường bị đóng lại đôi khi không phải để phạt bạn --- mà để chỉ bạn đến con đường thật sự dành cho bạn.",
          "A door closing is sometimes not a punishment --- but a redirection toward the path truly meant for you."),

    story("Nick Vujicic Sinh Ra Không Tay Không Chân", "Nick Vujicic --- Úc, 1982",
          "Nick",
          [("Nick Vujicic sinh ra hoàn toàn không có tay và chân --- một dị tật bẩm sinh cực kỳ hiếm gặp.",
            "Nick Vujicic was born with no arms and no legs --- an extremely rare congenital condition."),
           ("Thuở nhỏ, ông bị bắt nạt dữ dội ở trường, không có bạn bè, và lúc 8 tuổi đã từng cố tự tử trong bồn tắm.",
            "As a child, he was severely bullied at school, had no friends, and at age 8 even attempted suicide in a bathtub."),
           ("Nhưng rồi ông nhận ra: nếu không có cả bốn chi mà vẫn tồn tại được, thì ông có thể trở thành bằng chứng sống cho điều gì đó lớn hơn.",
            "But he came to realize: if he could survive without all four limbs, he could become living proof of something greater."),
           ("Ông học bơi, đánh golf, lướt ván, lấy bằng đại học, rồi trở thành diễn giả truyền cảm hứng đi khắp thế giới.",
            "He learned to swim, play golf, surf, earned a university degree, then became a motivational speaker traveling the world."),
           ("Nick Vujicic đã nói với hàng triệu người: ``Tôi không có tay để vươn lên, nhưng tôi có trái tim để bay.''",
            "Nick Vujicic has told millions of people: `I have no arms to reach up, but I have a heart that can fly.'")],
          "Giới hạn thể xác không bao giờ là giới hạn của tinh thần --- nếu tinh thần đó chọn không bị giới hạn.",
          "Physical limits are never the limits of the spirit --- if that spirit chooses not to be limited."),

    story("Nguyễn Du Lưu Lạc Và Truyện Kiều Ra Đời", "Nguyễn Du --- Việt Nam, 1803",
          "Nguyễn",
          [("Nguyễn Du sống trong thời loạn lạc --- ông bị cuốn vào các biến động chính trị, mất chức, sống ẩn dật nhiều năm trong đói khổ và cô đơn.",
            "Nguyen Du lived through turbulent times --- caught in political upheaval, stripped of his position, living in hiding for years in poverty and solitude."),
           ("Nhiều năm ông lưu lạc vùng Hà Tĩnh, nhìn thấy những số phận bi thương của con người giữa cơn bão lịch sử.",
            "For years he wandered through Ha Tinh province, witnessing the tragic fates of people caught in the storm of history."),
           ("Chính những năm lưu lạc đau khổ đó đã nuôi dưỡng trong ông một tâm hồn thấu cảm sâu sắc không thể học được từ sách vở.",
            "It was precisely those years of painful wandering that nurtured in him a profound empathy that no book could teach."),
           ("Từ đó, Truyện Kiều ra đời --- không phải từ cuộc đời sung sướng của một đại quan, mà từ những giọt nước mắt của kẻ thất thế.",
            "From that experience, The Tale of Kieu was born --- not from the comfortable life of a high official, but from the tears of a fallen man."),
           ("Truyện Kiều trở thành tác phẩm văn học bất hủ nhất Việt Nam, được dịch ra hàng chục thứ tiếng và UNESCO vinh danh tác giả là danh nhân văn hóa thế giới.",
            "The Tale of Kieu became Vietnam's greatest immortal literary work, translated into dozens of languages, and its author honored by UNESCO as a World Cultural Personality.")],
          "Những tác phẩm vĩ đại nhất của nhân loại thường được sinh ra từ những năm tháng đau khổ nhất của tác giả.",
          "Humanity's greatest works are often born from the most painful years of their creators."),
    ]
)

# ================================================================
# CHƯƠNG 2: THÀNH CÔNG TRONG THẤT BẠI, THẤT BẠI TRONG THÀNH CÔNG
# ================================================================
ch2 = chapter(
    "Thành Công Trong Thất Bại, Thất Bại Trong Thành Công",
    "Victory Lives in Defeat, Defeat Hides in Victory",
    "Mỗi lần ngã là một lần học; kẻ không bao giờ ngã là kẻ chưa bao giờ đi xa.",
    "Every fall is a lesson; one who never falls has never gone far.",
    [
    story("Einstein Trượt Thi Vào Đại Học", "Albert Einstein --- Thụy Sĩ, 1895",
          "Albert",
          [("Albert Einstein năm 16 tuổi dự thi vào Học viện Bách khoa Zurich và trượt --- kết quả toán vật lý xuất sắc nhưng tiếng Pháp và thực vật học quá kém.",
            "At 16, Albert Einstein sat the entrance exam for ETH Zurich and failed --- outstanding in math and physics, but far too weak in French and botany."),
           ("Ông phải học thêm một năm ở trường làng Aarau --- điều mà ông sau này gọi là ``may mắn lớn nhất cuộc đời tôi''.",
            "He had to spend an extra year at the village school in Aarau --- something he later called `the greatest stroke of luck in my life.'"),
           ("Tại Aarau, ông có thời gian tự do nghĩ về thí nghiệm tưởng tượng: điều gì xảy ra nếu bạn chạy thật nhanh bên cạnh một tia sáng?",
            "At Aarau, he had free time to imagine thought experiments: what would happen if you ran alongside a beam of light?"),
           ("Câu hỏi đó --- nảy sinh từ năm coi là thất bại --- trở thành hạt nhân của Thuyết Tương Đối Đặc Biệt mười năm sau.",
            "That question --- born in what seemed a failed year --- became the nucleus of the Special Theory of Relativity a decade later."),
           ("Einstein nhận giải Nobel Vật lý năm 1921, nhưng hành trình bắt đầu từ một kỳ thi trượt.",
            "Einstein received the Nobel Prize in Physics in 1921, but the journey started with a failed entrance exam.")],
          "Thất bại trong hệ thống hiện có đôi khi là dấu hiệu bạn đang vượt qua hệ thống đó.",
          "Failing within a system is sometimes a sign that you are outgrowing that system."),

    story("Michael Jordan Bị Loại Khỏi Đội Tuyển Trường", "Michael Jordan --- Hoa Kỳ, 1978",
          "Năm",
          [("Năm lớp 10, Michael Jordan nộp đơn vào đội bóng rổ của trường Emsley A. Laney High School và bị loại vì bị cho là ``quá thấp''.",
            "In 10th grade, Michael Jordan tried out for the varsity basketball team at Emsley A. Laney High School and was cut because he was considered `too short.'"),
           ("Ông về nhà khóc một mình trong phòng --- không ai biết điều đó cho đến khi ông tự kể hàng chục năm sau.",
            "He went home and cried alone in his room --- no one knew this until he told the story decades later."),
           ("Từ đó, ông tập luyện điên cuồng: dậy từ 6 giờ sáng, tập trước khi đến trường, tập sau khi về nhà, tập vào cuối tuần.",
            "From that moment, he trained obsessively: up at 6 a.m., practicing before school, after school, and on weekends."),
           ("Jordan nói sau này: ``Mỗi khi tôi muốn dừng lại vì mệt mỏi, tôi lại nhớ đến cái bảng danh sách mà tên tôi không có trong đó.''",
            "Jordan later said: `Every time I wanted to stop because I was tired, I thought of that list where my name wasn't on it.'"),
           ("Michael Jordan trở thành cầu thủ bóng rổ vĩ đại nhất mọi thời đại --- từ kẻ bị loại trở thành huyền thoại.",
            "Michael Jordan became the greatest basketball player of all time --- from being cut from the team to becoming a legend.")],
          "Bị từ chối đúng lúc đúng chỗ có thể là ngọn lửa thắp sáng một sự nghiệp vĩ đại.",
          "Being rejected at the right time and place can be the fire that ignites a great career."),

    story("Lần Thứ 1000 Chế Tạo Bóng Đèn Của Edison", "Thomas Edison --- Hoa Kỳ, 1879",
          "Khi",
          [("Khi phóng viên hỏi Edison rằng ông có cảm thấy nản lòng sau hơn 1.000 lần thất bại để tìm ra vật liệu làm sợi đốt bóng đèn không, ông lắc đầu cười.",
            "When a reporter asked Edison if he felt discouraged after more than 1,000 failed attempts to find the right filament for a light bulb, he shook his head and laughed."),
           ("Edison trả lời: ``Tôi không thất bại 1.000 lần; tôi thành công phát hiện ra 1.000 cách không làm được.''",
            "Edison answered: `I did not fail 1,000 times; I successfully discovered 1,000 ways it doesn't work.'"),
           ("Quan điểm này không chỉ là câu nói đẹp --- nó là phương pháp thực sự của ông: mỗi thất bại được ghi chép lại tỉ mỉ và dùng để loại suy cho lần thử tiếp theo.",
            "This attitude was not just a pretty quote --- it was his actual method: each failure was recorded meticulously and used to narrow down the next attempt."),
           ("Lần thứ 1.001, sợi carbon hóa tre Nhật Bản sáng lên và giữ được hơn 1.200 giờ liên tục.",
            "On the 1,001st try, carbonized Japanese bamboo fiber lit up and held for over 1,200 continuous hours."),
           ("Mỗi một trong 1.000 lần ``thất bại'' trước đó đều đóng góp một mảnh thông tin không thể thiếu cho thành công cuối cùng.",
            "Each of the 1,000 previous `failures' contributed an indispensable piece of information to the final success.")],
          "Thất bại chỉ là dữ liệu --- và dữ liệu chưa bao giờ là kẻ thù của người biết dùng nó.",
          "Failure is just data --- and data has never been the enemy of those who know how to use it."),

    story("Alibaba Bị Từ Chối 30 Lần", "Jack Ma --- Trung Quốc, 1995",
          "Jack",
          [("Jack Ma đã bị Harvard từ chối 10 lần, bị cảnh sát từ chối khi xin làm việc, và bị KFC từ chối khi xin phục vụ bàn cùng 24 ứng viên khác.",
            "Jack Ma was rejected by Harvard 10 times, rejected by the police when applying for work, and rejected by KFC for a waiter position along with 24 other applicants."),
           ("Năm 1995, công ty đầu tiên của ông thất bại hoàn toàn; ông quay về dạy tiếng Anh với mức lương 12 đô mỗi tháng.",
            "In 1995, his first company failed completely; he returned to teaching English for 12 dollars a month."),
           ("Năm 1999, ông thành lập Alibaba trong căn hộ nhỏ với 18 người --- mỗi người góp hết tiền tiết kiệm của mình.",
            "In 1999, he founded Alibaba in a small apartment with 18 people --- each contributing all of their savings."),
           ("Gần chục năm sau đó là những cuộc chiến sinh tử với eBay, với nhà đầu tư tháo lui, với khủng hoảng tài chính toàn cầu.",
            "The following decade was a life-and-death battle against eBay, fleeing investors, and the global financial crisis."),
           ("Alibaba IPO năm 2014 lập kỷ lục lịch sử với 25 tỷ đô --- và Jack Ma trở thành người giàu nhất Trung Quốc, xuất phát điểm từ tổng cộng hơn 30 lần bị từ chối.",
            "Alibaba's 2014 IPO set a historic record at 25 billion dollars --- and Jack Ma became China's richest man, starting from a total of over 30 rejections.")],
          "Số lần bị từ chối không đo lường giới hạn của bạn --- nó đo lường độ kiên trì của bạn.",
          "The number of times you are rejected does not measure your limits --- it measures your persistence."),

    story("Nguyễn Bỉnh Khiêm Lui Về Ở Ẩn", "Nguyễn Bỉnh Khiêm --- Việt Nam, 1542",
          "Sau",
          [("Sau nhiều năm làm quan trong triều Mạc, Nguyễn Bỉnh Khiêm nộp sớ đàn hặc 18 tên gian thần nhưng không được vua nghe, ông xin cáo quan về quê.",
            "After years serving the Mac court, Nguyen Binh Khiem submitted a memorial accusing 18 treacherous officials but the king ignored it, and he resigned and returned home."),
           ("Nhiều người cho đó là thất bại chính trị, là bỏ cuộc, là kết thúc sự nghiệp.",
            "Many saw this as political failure, as giving up, as the end of a career."),
           ("Nhưng ông về dựng Am Bạch Vân, mở trường dạy học, viết thơ chữ Nôm và chữ Hán --- và đó mới là đỉnh cao thực sự của cuộc đời ông.",
            "But he returned home, built the White Cloud Hermitage, opened a school, and wrote poetry in both Nom and Chinese script --- and that became the true peak of his life."),
           ("Từ Am Bạch Vân, ông đào tạo ra những học trò lỗi lạc nhất thế kỷ 16 và để lại kho thơ triết học nhân sinh sâu sắc bậc nhất lịch sử văn học Việt Nam.",
            "From the White Cloud Hermitage, he trained the most distinguished students of the 16th century and left behind a body of philosophical poetry among the deepest in Vietnamese literary history."),
           ("Ba chúa đều phải đến hỏi ý kiến ông về việc trị quốc --- kẻ ``thất bại'' nơi triều đình trở thành người thầy của các vương triều.",
            "Three lords came to seek his counsel on governance --- the man who `failed' at court became the teacher of dynasties.")],
          "Đôi khi rời bỏ hệ thống không phải là thất bại --- đó là sự trưởng thành.",
          "Sometimes leaving the system is not failure --- it is growth."),

    story("Abraham Lincoln --- 23 Năm Thất Bại", "Abraham Lincoln --- Hoa Kỳ, 1832--1860",
          "Abraham",
          [("Abraham Lincoln thất bại trong kinh doanh năm 1831, thua ứng cử năm 1832, thất bại trong kinh doanh lần nữa năm 1833, và bị thần kinh suy sụp năm 1836.",
            "Abraham Lincoln failed in business in 1831, lost an election in 1832, failed in business again in 1833, and had a nervous breakdown in 1836."),
           ("Ông thua ứng cử Quốc hội năm 1843, thua thêm lần nữa năm 1848, thua ứng cử Thượng viện năm 1855 và 1858.",
            "He lost congressional bids in 1843 and 1848, lost Senate races in 1855 and 1858."),
           ("Năm 1860, sau 23 năm liên tiếp thất bại, Lincoln được bầu làm Tổng thống thứ 16 của Hoa Kỳ.",
            "In 1860, after 23 straight years of defeat, Lincoln was elected as the 16th President of the United States."),
           ("Ông lãnh đạo đất nước qua Nội chiến và ký Tuyên bố Giải phóng Nô lệ --- một trong những hành động pháp lý quan trọng nhất lịch sử nhân loại.",
            "He led the nation through the Civil War and signed the Emancipation Proclamation --- one of the most consequential legal acts in human history."),
           ("Lincoln từng viết: ``Đường đi của tôi trơn trợt và tôi vấp ngã --- nhưng đó không phải là trượt; tôi đứng dậy và tiếp tục đi.''",
            "Lincoln once wrote: `My path is slippery and I stumbled --- but that was not a slip; I got up and kept going.'")],
          "Tiểu sử của những người vĩ đại nhất thường là danh sách dài nhất những lần thất bại.",
          "The biographies of the greatest people are often the longest lists of failures."),

    story("Phạm Tuân --- Từ Phi Công Bị Thương Đến Nhà Du Hành Vũ Trụ", "Phạm Tuân --- Việt Nam, 1962--1980",
          "Phạm",
          [("Phạm Tuân bắt đầu sự nghiệp phi công năm 1962; năm 1966 máy bay ông bị bắn cháy trên bầu trời Hải Phòng và ông phải nhảy dù thoát thân.",
            "Pham Tuan began his pilot career in 1962; in 1966 his aircraft was shot down over Hai Phong and he parachuted to safety."),
           ("Thay vì bị chấn thương tâm lý khiến ông bỏ nghề, chính cú rơi đó lại thôi thúc ông học hỏi và hoàn thiện kỹ năng không chiến.",
            "Instead of being traumatized into quitting, that very crash spurred him to study and perfect his aerial combat skills."),
           ("Năm 1972, ông bắn hạ máy bay B-52 của Mỹ đầu tiên trong lịch sử chiến tranh --- một chiến công làm cả thế giới kinh ngạc.",
            "In 1972, he became the first pilot in history to shoot down a B-52 --- an achievement that astonished the entire world."),
           ("Và rồi năm 1980, Phạm Tuân trở thành người Việt Nam đầu tiên và người châu Á đầu tiên bay vào vũ trụ.",
            "Then in 1980, Pham Tuan became the first Vietnamese and the first Asian to fly into outer space."),
           ("Từ chiếc máy bay bị bắn cháy năm 1966 đến vũ trụ năm 1980 --- con đường 14 năm đó chứng minh thất bại chỉ là điểm khởi đầu của một hành trình lớn hơn.",
            "From a burning plane in 1966 to outer space in 1980 --- those 14 years proved that failure is only the starting point of a greater journey.")],
          "Cú rơi không đo lường độ cao bạn có thể đạt được --- nó đo lường khả năng bạn đứng dậy.",
          "A fall does not measure how high you can reach --- it measures your ability to rise."),

    story("Coco Chanel Xuất Thân Cô Nhi Viện", "Coco Chanel --- Pháp, 1895",
          "Coco",
          [("Coco Chanel lớn lên trong cô nhi viện sau khi mẹ mất và cha bỏ đi; bà không có tiền, không có học thức, không có danh phận.",
            "Coco Chanel grew up in an orphanage after her mother died and father left; she had no money, no education, no social standing."),
           ("Ở thế kỷ đầu 1900, phụ nữ xuất thân như bà hầu như không có cơ hội nào trong xã hội thượng lưu Pháp.",
            "In the early 1900s, a woman of her background had almost no chance in French high society."),
           ("Nhưng chính vì lớn lên không có gì, bà không bị ràng buộc bởi những quy tắc thời trang của giai cấp thượng lưu.",
            "But precisely because she grew up with nothing, she was not constrained by the fashion rules of the upper class."),
           ("Trong khi phụ nữ quý tộc mặc áo nịt ngực bó chặt và váy nhiều lớp nặng nề, Chanel cắt may áo đơn giản, thoải mái, thực dụng --- và định nghĩa lại thời trang thế giới.",
            "While aristocratic women wore tight corsets and heavy layered skirts, Chanel cut simple, comfortable, practical clothes --- and redefined world fashion."),
           ("Thương hiệu Chanel hôm nay là một trong những thương hiệu xa xỉ giá trị nhất thế giới --- bắt đầu từ một đứa trẻ mồ côi không có gì cả.",
            "The Chanel brand today is one of the world's most valuable luxury labels --- begun by an orphan girl who had nothing at all.")],
          "Không có gì để mất là sự tự do lớn nhất để đổi mới; nghèo đói đôi khi là cha đẻ của sự sáng tạo.",
          "Having nothing to lose is the greatest freedom to innovate; poverty is sometimes the parent of creativity."),

    story("Nguyễn Trãi Sau 10 Năm Tù Túng", "Nguyễn Trãi --- Việt Nam, 1407--1418",
          "Năm",
          [("Năm 1407, quân Minh xâm chiếm Đại Việt; cha Nguyễn Trãi bị bắt giải về Trung Quốc và ông bị quản thúc ở Đông Quan gần mười năm.",
            "In 1407, Ming forces invaded Dai Viet; Nguyen Trai's father was taken captive to China and Nguyen Trai was placed under house arrest in Dong Quan for nearly ten years."),
           ("Những năm tù túng đó, ông không lãng phí --- ông quan sát cách cai trị của giặc, nghiên cứu binh thư, suy ngẫm về đường lối cứu nước.",
            "During those years of confinement, he did not waste time --- he observed the enemy's methods of rule, studied military strategy, and pondered ways to save the country."),
           ("Chính những năm đó đã kết tinh thành bản Bình Ngô Đại Cáo và chiến lược ``tâm công'' --- đánh bằng trí tuệ và nhân nghĩa chứ không chỉ bằng vũ lực.",
            "Those very years crystallized into the Proclamation of Victory over the Wu and the strategy of `winning hearts' --- conquering through wisdom and righteousness, not just force."),
           ("Khi Lê Lợi dấy binh, Nguyễn Trãi mang theo mười năm trí tuệ tích lũy trong giam cầm làm vũ khí bí mật.",
            "When Le Loi raised his revolt, Nguyen Trai brought with him ten years of wisdom accumulated in captivity as a secret weapon."),
           ("Bình Ngô Đại Cáo --- được viết từ những tháng năm tăm tối nhất --- trở thành bản tuyên ngôn độc lập vĩ đại nhất lịch sử Việt Nam.",
            "The Proclamation of Victory over the Wu --- written from the darkest years --- became the greatest declaration of independence in Vietnamese history.")],
          "Những giai đoạn bị nhốt kín đôi khi giải phóng tinh thần đến độ sâu nhất của nó.",
          "Periods of confinement sometimes liberate the spirit to its greatest depth."),

    story("Walt Disney Bị Sa Thải Vì Thiếu Sáng Tạo", "Walt Disney --- Hoa Kỳ, 1919",
          "Walt",
          [("Walt Disney năm 22 tuổi bị sa thải khỏi tờ báo Kansas City Star vì biên tập viên nhận xét ông ``thiếu trí tưởng tượng và không có ý tưởng hay''.",
            "At 22, Walt Disney was fired from the Kansas City Star because an editor said he `lacked imagination and had no good ideas.'"),
           ("Công ty phim hoạt hình đầu tiên của ông --- Laugh-O-Gram Studios --- phá sản hoàn toàn năm 1922, ông rơi vào cảnh trắng tay.",
            "His first animation company, Laugh-O-Gram Studios, went completely bankrupt in 1922, leaving him penniless."),
           ("Ông chuyển đến Hollywood với 40 đô la trong túi và một chiếc vali --- và bắt đầu lại từ đầu.",
            "He moved to Hollywood with 40 dollars in his pocket and one suitcase --- and started over."),
           ("Mickey Mouse ra đời năm 1928; bộ phim Bạch Tuyết năm 1937 trở thành phim hoạt hình đầu tiên trong lịch sử điện ảnh.",
            "Mickey Mouse was born in 1928; Snow White in 1937 became the first full-length animated film in cinema history."),
           ("Walt Disney nhận 22 giải Oscar trong sự nghiệp và xây dựng đế chế Walt Disney Company trị giá hàng trăm tỷ đô --- bắt đầu từ kẻ bị cho là ``thiếu trí tưởng tượng''.",
            "Walt Disney won 22 Academy Awards in his career and built the Walt Disney Company, worth hundreds of billions --- starting from someone said to `lack imagination.'")],
          "Người nói bạn không có tài năng thường là người chưa thấy đủ tầm của tài năng bạn.",
          "Those who say you lack talent are often those who have not yet seen the full scope of your talent."),
    ]
)

# ================================================================
# CHƯƠNG 3: BẠN TRONG THÙ, THÙ TRONG BẠN
# ================================================================
ch3 = chapter(
    "Bạn Trong Thù, Thù Trong Bạn",
    "Friend Hidden in Enemy, Enemy Hidden in Friend",
    "Người chỉ trích ta gay gắt nhất đôi khi là người thầy tốt nhất của ta.",
    "The harshest critic we have is sometimes our greatest teacher.",
    [
    story("Lincoln Biến Kẻ Thù Thành Nội Các", "Abraham Lincoln --- Hoa Kỳ, 1860",
          "Khi",
          [("Khi Lincoln đắc cử Tổng thống năm 1860, ông có ba đối thủ tranh cử cực kỳ gay gắt: William Seward, Salmon Chase, và Edward Bates.",
            "When Lincoln won the presidency in 1860, he had three fiercely competitive rivals: William Seward, Salmon Chase, and Edward Bates."),
           ("Mỗi người trong số đó đều cho rằng mình xứng đáng làm tổng thống hơn Lincoln và không che dấu điều đó.",
            "Each of them believed he was more qualified than Lincoln and made no secret of it."),
           ("Thế nhưng Lincoln bổ nhiệm cả ba người vào nội các của mình: Seward làm Ngoại trưởng, Chase làm Bộ trưởng Tài chính, Bates làm Bộ trưởng Tư pháp.",
            "Yet Lincoln appointed all three into his cabinet: Seward as Secretary of State, Chase as Treasury Secretary, Bates as Attorney General."),
           ("Cộng sự hỏi tại sao ông lại chọn những người ghét ông nhất vào nội các; ông trả lời: ``Vì họ là những người tài nhất đất nước --- và đất nước cần người tài, không cần người yêu mến tôi.''",
            "An aide asked why he chose his greatest enemies for the cabinet; he answered: `Because they are the most capable men in the country --- and the country needs capable men, not men who love me.'"),
           ("Nội các ``kẻ thù'' đó lãnh đạo đất nước qua Nội chiến và giúp Lincoln để lại di sản vĩ đại nhất trong lịch sử Mỹ.",
            "That cabinet of `enemies' led the nation through the Civil War and helped Lincoln leave the greatest legacy in American history.")],
          "Người thù bạn thường biết điểm yếu của bạn rõ hơn bạn bè --- hãy tận dụng điều đó.",
          "Those who hate you often know your weaknesses better than your friends --- use that."),

    story("Trần Quốc Tuấn Và Anh Giết Cha", "Trần Hưng Đạo --- Việt Nam, thế kỷ 13",
          "Trần",
          [("Trần Quốc Tuấn lớn lên với thù nhà sâu đậm: cha ông --- Trần Liễu --- bị anh là Trần Thái Tông đoạt vợ và quyền lực, chết trong cay đắng.",
            "Tran Quoc Tuan grew up with deep family hatred: his father Tran Lieu had his wife and power seized by his brother Tran Thai Tong, and died in bitterness."),
           ("Cha ông trăng trối bảo ông phải trả thù, giành lại danh dự cho dòng họ.",
            "His dying father charged him to take revenge and restore family honor."),
           ("Nhưng khi quân Nguyên Mông tràn vào, Trần Quốc Tuấn hiểu rằng nếu cứ ôm hận thù trong gia tộc thì cả đất nước sẽ mất.",
            "But when the Mongols invaded, Tran Quoc Tuan understood that clinging to family revenge would cost the entire nation."),
           ("Ông gác thù riêng lại, dâng hết tài năng phụng sự triều đình và chỉ huy quân dân đánh đuổi ba lần xâm lược Nguyên Mông.",
            "He set aside personal hatred, dedicated all his talents to serving the court, and commanded the people to defeat three Mongol invasions."),
           ("Sau thắng lợi, vua hỏi ông về lời trăng trối của cha; ông quỳ xuống và nói: ``Thần đã dâng lời hứa với cha lên làm lễ vật tế cho đất nước.''",
            "After victory, the king asked about his father's deathbed words; he knelt and said: `I offered my vow to my father as a sacrifice for the nation.'")],
          "Kẻ thù thật sự không phải là người ở ngoài kia --- mà là lòng thù hận ở trong ta ngăn ta làm điều vĩ đại.",
          "The real enemy is not the one out there --- it is the hatred within us that prevents us from doing great things."),

    story("Oprah Winfrey Và Người Quản Lý Tàn Nhẫn", "Oprah Winfrey --- Hoa Kỳ, 1976",
          "Khi",
          [("Khi còn trẻ, Oprah Winfrey làm phóng viên truyền hình ở Baltimore; người quản lý của cô nhận xét thẳng mặt: ``Cô không phù hợp với truyền hình.''",
            "Early in her career, Oprah Winfrey worked as a TV reporter in Baltimore; her producer told her to her face: `You are not suitable for television.'"),
           ("Ông ta chuyển cô xuống làm dẫn chương trình buổi sáng --- mà ông nghĩ là thứ cỏn con không quan trọng.",
            "He moved her down to hosting a morning talk show --- which he thought was a trivial, unimportant assignment."),
           ("Nhưng trên ghế dẫn chương trình đó, Oprah khám phá ra điểm mạnh thật sự của mình: khả năng kết nối cảm xúc với khán giả.",
            "But in that hosting chair, Oprah discovered her true strength: the ability to connect emotionally with her audience."),
           ("Chương trình buổi sáng của cô nhanh chóng thống trị kênh địa phương và đưa cô thẳng đến The Oprah Winfrey Show --- chương trình truyền hình được xem nhiều nhất lịch sử Mỹ.",
            "Her morning show quickly dominated local ratings and launched her directly to The Oprah Winfrey Show --- the most-watched talk show in American television history."),
           ("Người đã ``phạt'' cô bằng cách chuyển xuống ghế dẫn nhỏ --- thực ra đã trao cho cô cánh cửa cuộc đời.",
            "The person who `punished' her by moving her to a small hosting seat --- had actually given her the door to her life.")],
          "Người cho bạn cái mà bạn không muốn đôi khi là người cho bạn thứ bạn cần nhất.",
          "The person who gives you what you don't want is sometimes the one giving you what you need most."),

    story("Gandhi Và Người Anh Bỏ Tù Ông", "Mahatma Gandhi --- Nam Phi, 1906",
          "Khi",
          [("Khi viên tướng Anh Jan Smuts bỏ tù Gandhi lần đầu năm 1908 vì ông phản đối đạo luật phân biệt chủng tộc, ông ta cho rằng mình đã dập tắt được phong trào.",
            "When British general Jan Smuts first jailed Gandhi in 1908 for opposing apartheid laws, he believed he had crushed the movement."),
           ("Nhưng mỗi lần Gandhi bị bắt giam, tin tức lan rộng hơn và phong trào đấu tranh mạnh hơn.",
            "But every time Gandhi was jailed, the news spread further and the movement grew stronger."),
           ("Smuts nhận ra ông ta đang giúp Gandhi nổi tiếng và quyết định thả tự do --- nhưng đã quá muộn.",
            "Smuts realized he was making Gandhi famous and decided to release him --- but it was already too late."),
           ("Về sau, Smuts viết về Gandhi: ``Đây là người đã thay đổi tôi; ông ta dạy tôi rằng sức mạnh không phải ở thanh kiếm.''",
            "Later, Smuts wrote of Gandhi: `This is the man who changed me; he taught me that strength does not lie in the sword.'"),
           ("Hai người cựu thù --- người đã bỏ tù nhau --- cuối đời trao đổi thư từ như những người bạn tri kỷ.",
            "The two former enemies --- who had jailed each other --- corresponded in their final years like old friends.")],
          "Kẻ thù đủ mạnh để thách thức chúng ta đôi khi là người dạy ta bài học lớn nhất.",
          "An enemy strong enough to challenge us is sometimes the one who teaches our greatest lesson."),

    story("Steve Jobs Và Bill Gates", "Steve Jobs / Bill Gates --- Hoa Kỳ, 1980--2007",
          "Steve",
          [("Steve Jobs và Bill Gates là đối thủ thương mại khốc liệt nhất của thế kỷ 20; họ công khai chỉ trích nhau trong nhiều thập kỷ.",
            "Steve Jobs and Bill Gates were the fiercest business rivals of the 20th century; they publicly criticized each other for decades."),
           ("Jobs gọi Microsoft là ``kẻ ăn cắp ý tưởng''; Gates gọi Jobs là người tạo ảo giác hơn là tạo sản phẩm thực.",
            "Jobs called Microsoft `a thief of ideas'; Gates called Jobs a man who created illusions more than real products."),
           ("Nhưng ít ai biết rằng chính Bill Gates đã cứu Apple bằng khoản đầu tư 150 triệu đô năm 1997 khi Apple gần phá sản.",
            "But few knew that Bill Gates saved Apple with a 150-million-dollar investment in 1997 when Apple was near bankruptcy."),
           ("Và Jobs thừa nhận rằng chính sự cạnh tranh với Microsoft đã buộc Apple phải không ngừng đổi mới.",
            "And Jobs admitted that competition with Microsoft was what forced Apple to innovate constantly."),
           ("Khi Jobs hấp hối năm 2011, Gates là một trong số ít người ông nói chuyện lần cuối --- hai kẻ thù vĩ đại nhất ngành công nghệ hóa ra cũng là những người hiểu nhau nhất.",
            "As Jobs lay dying in 2011, Gates was one of the few people he spoke to at the end --- the two greatest enemies in tech turned out to be the ones who understood each other best.")],
          "Đối thủ thực sự là người duy nhất đủ tầm để thách thức bạn lớn lên; không có họ, bạn có thể không biết mình có thể đi xa đến đâu.",
          "A true rival is the only one at your level who can challenge you to grow; without them, you may never know how far you can go."),

    story("Tôn Tử Và Tướng Trên Chiến Trường", "Tôn Tử --- Trung Quốc, thế kỷ 5 TCN",
          "Tôn",
          [("Tôn Tử trong binh thư viết: ``Hãy biết địch như biết bạn --- vì địch cho bạn biết điều bạn thiếu.''",
            "Sun Tzu wrote in the Art of War: `Know your enemy as your friend --- for the enemy shows you what you lack.'"),
           ("Ông kể chuyện một vị tướng luôn thắng trận nhờ thói quen học từ địch: sau mỗi trận, ông phân tích kỹ những đòn tấn công mà địch dùng hiệu quả.",
            "He told of a general who always won battles by learning from the enemy: after each battle, he carefully analyzed whatever attacks the enemy used effectively."),
           ("Vị tướng đó không coi kẻ địch như kẻ thù mà như người thầy không mời --- người tự nguyện chỉ ra điểm yếu.",
            "That general did not see the enemy as a foe but as an uninvited teacher --- one who voluntarily pointed out his weaknesses."),
           ("Quân đội của ông sau nhiều năm chiến đấu trở thành đội quân biết chiến thuật đa dạng nhất --- vì họ học từ nhiều địch thủ nhất.",
            "His army, after years of fighting, became the force with the most varied tactics --- because they had learned from the most diverse enemies."),
           ("Bài học Tôn Tử: kẻ địch giỏi nhất là người thầy giỏi nhất --- nếu bạn đủ khiêm nhường để học.",
            "Sun Tzu's lesson: the best enemy is the best teacher --- if you are humble enough to learn.")],
          "Thay vì tiêu diệt kẻ thù, hãy học được từ họ trước --- điều đó vừa khôn ngoan hơn vừa có ích hơn.",
          "Before destroying your enemy, learn from them first --- that is both wiser and more profitable."),

    story("Nguyễn Huệ Học Binh Pháp Từ Quân Xiêm Thua Trận", "Quang Trung --- Việt Nam, 1785",
          "Sau",
          [("Sau khi đánh tan quân Xiêm tại Rạch Gầm -- Xoài Mút năm 1785, Nguyễn Huệ không chỉ mừng chiến thắng.",
            "After destroying the Siamese army at Rach Gam -- Xoai Mut in 1785, Nguyen Hue did not simply celebrate the victory."),
           ("Ông triệu tập tướng sĩ nghiên cứu kỹ các chiến thuật mà quân Xiêm đã dùng và những điểm mà họ gần như đã thắng.",
            "He summoned his officers to carefully study the tactics the Siamese had used and the moments when they had nearly won."),
           ("Ông nói: ``Biết ta thắng không đủ; phải biết tại sao địch gần thắng.''",
            "He said: `Knowing we won is not enough; we must know why the enemy nearly won.'"),
           ("Những bài học từ quân Xiêm được tích hợp vào chiến lược của quân Tây Sơn --- chuẩn bị cho trận Đống Đa lẫy lừng năm 1789.",
            "The lessons from the Siamese forces were incorporated into the Tay Son army's strategy --- preparing for the brilliant Battle of Dong Da in 1789."),
           ("Tại Đống Đa, Quang Trung đại phá 29 vạn quân Thanh chỉ trong năm ngày đêm --- chiến thắng thần tốc bậc nhất lịch sử châu Á.",
            "At Dong Da, Quang Trung destroyed 290,000 Qing troops in just five days and nights --- the fastest decisive victory in Asian history.")],
          "Chiến thắng của hôm nay nên là bài học cho ngày mai --- và bài học hay nhất đến từ chính kẻ địch.",
          "Today's victory should be tomorrow's lesson --- and the best lessons come from the enemy."),

    story("Churchill Và Hitler --- Kẻ Thù Tạo Ra Lãnh Tụ", "Winston Churchill --- Anh, 1940",
          "Winston",
          [("Winston Churchill bị coi là chính khách lỗi thời và thất bại trong suốt những năm 1930; ông không được ai nghe.",
            "Winston Churchill was considered an outdated and failed politician throughout the 1930s; no one listened to him."),
           ("Nhưng khi Hitler bắt đầu xâm lược châu Âu và các chính khách khác muốn nhượng bộ, Churchill là người duy nhất đã nói đúng.",
            "But when Hitler began invading Europe and other politicians wanted to appease him, Churchill was the only one who had been right all along."),
           ("Chính mối đe dọa của Hitler đã đặt Churchill vào đúng vị trí lịch sử mà ông sinh ra để làm: Thủ tướng thời chiến của nước Anh.",
            "Hitler's very threat placed Churchill in exactly the historical role he was born to fill: Britain's wartime Prime Minister."),
           ("Churchill nói: ``Nếu không có Hitler, chắc tôi đã chết già trong sự lãng quên.''",
            "Churchill said: `Without Hitler, I would probably have died in obscurity.'"),
           ("Kẻ thù lớn nhất của Churchill đã trao cho ông sân khấu lớn nhất của cuộc đời ông --- và qua đó, Churchill trao cho thế giới can đảm để tiếp tục chiến đấu.",
            "Churchill's greatest enemy gave him the greatest stage of his life --- and through it, Churchill gave the world the courage to keep fighting.")],
          "Đôi khi kẻ thù lớn nhất là người duy nhất đủ lớn để gọi ra kẻ vĩ đại trong bạn.",
          "Sometimes the greatest enemy is the only one large enough to call forth the greatness within you."),

    story("Nguyễn Công Trứ Bị Giáng Chức Nhiều Lần", "Nguyễn Công Trứ --- Việt Nam, thế kỷ 19",
          "Nguyễn",
          [("Nguyễn Công Trứ trong cuộc đời làm quan bị giáng chức, cách chức, và phát lưu nhiều lần vì dám nói thẳng sự thật.",
            "Nguyen Cong Tru was demoted, dismissed, and exiled many times during his official career for daring to speak truth directly."),
           ("Những kẻ đẩy ông xuống --- dù là vua hay quyền thần --- thực ra không thể nào dập tắt được tiếng thơ và tinh thần của ông.",
            "Those who pushed him down --- whether king or powerful ministers --- could never actually silence his poetry and spirit."),
           ("Mỗi lần bị đẩy khỏi triều đình, ông về quê khai hoang, trồng lúa, viết thơ --- và học thêm về dân tình.",
            "Every time he was expelled from court, he returned home to clear land, grow rice, write poetry --- and learn more about the people's lives."),
           ("Chính những kẻ thù chính trị đã vô tình biến ông từ một vị quan thành người gần dân nhất, hiểu đời nhất.",
            "Those political enemies inadvertently transformed him from an official into the one closest to the people, most understanding of life."),
           ("Di sản thơ Nguyễn Công Trứ sống mãi đến hôm nay --- và chúng được sinh ra không phải từ những tháng ngày quyền cao chức trọng, mà từ những năm bị đẩy xuống đáy.",
            "Nguyen Cong Tru's poetic legacy lives to this day --- and it was born not from his years of high rank, but from his years of being pushed to the bottom.")],
          "Kẻ thù hạ bệ bạn đôi khi là người xây nên di sản bất hủ cho bạn.",
          "Enemies who topple you sometimes build your most lasting legacy."),

    story("Phật Và Ma Vương Māra", "Siddhattha Gotama --- Ấn Độ, thế kỷ 5 TCN",
          "Theo",
          [("Theo truyền thống Phật giáo, khi Siddhattha Gotama ngồi thiền dưới cội Bồ Đề, Ma Vương Māra kéo đến với toàn bộ đội quân của mình để phá rối.",
            "According to Buddhist tradition, as Siddhattha Gotama meditated under the Bodhi tree, the demon Mara arrived with his entire army to disturb him."),
           ("Māra tung ra mọi thứ: cám dỗ của dục vọng, bóng đen của sợ hãi, những mũi tên của nghi ngờ.",
            "Mara unleashed everything: the temptations of desire, the shadows of fear, the arrows of doubt."),
           ("Nhưng Siddhattha không chạy trốn --- ông ngồi yên, nhìn thẳng vào Māra và nói: ``Ta thấy ngươi.''",
            "But Siddhattha did not flee --- he sat still, looked directly at Mara and said: `I see you.'"),
           ("Khoảnh khắc được nhìn thấy, được nhận diện --- Ma Vương mất sức mạnh và tan biến.",
            "The moment of being seen, being recognized --- the demon lost its power and dissolved."),
           ("Các thiền sư giải thích: Māra không phải kẻ thù từ bên ngoài --- Māra chính là những nỗi sợ, nghi ngờ, ham muốn bên trong ta; và cách duy nhất để vượt qua là nhìn thẳng vào chúng.",
            "The masters explain: Mara is not an enemy from outside --- Mara is the fear, doubt, and desire within us; and the only way through them is to look at them directly.")],
          "Kẻ thù thực sự của bạn thường không ở bên ngoài --- hãy tìm bên trong và nhìn thẳng vào đó.",
          "Your true enemy is usually not outside --- look within and face it directly."),
    ]
)

# ================================================================
# CHƯƠNG 4: YÊU TRONG GHÉT, GHÉT TRONG YÊU
# ================================================================
ch4 = chapter(
    "Yêu Trong Ghét, Ghét Trong Yêu",
    "Love Hidden in Hate, Bitterness Born in Love",
    "Ta chỉ ghét được những gì ta từng yêu; và ta chỉ yêu sâu những gì ta hiểu thật rõ.",
    "We can only hate what we once loved; and we only love deeply what we truly understand.",
    [
    story("Leo Tolstoy Và Vợ Ông", "Leo Tolstoy --- Nga, 1862--1910",
          "Leo",
          [("Leo Tolstoy và vợ ông --- Sophia --- có cuộc hôn nhân dài 48 năm đầy những lần yêu thương nồng nhiệt và những lần thù ghét sâu sắc xen kẽ nhau.",
            "Leo Tolstoy and his wife Sophia had a 48-year marriage full of intense love and deep hatred alternating with each other."),
           ("Sophia sao chép tay toàn bộ các bản thảo của Tolstoy --- đôi khi chép đi chép lại cả chục lần --- vì bà tin vào thiên tài của ông.",
            "Sophia hand-copied all of Tolstoy's manuscripts --- sometimes recopying them a dozen times --- because she believed in his genius."),
           ("Nhưng bà cũng ghi trong nhật ký: ``Đôi khi tôi ghét ông ấy đến mức không thể cùng ở trong một căn phòng.''",
            "But she also wrote in her diary: `Sometimes I hate him so deeply I cannot be in the same room.'"),
           ("Tolstoy viết về bà trong nhật ký: ``Không ai tôi yêu và không ai làm tôi đau bằng cô ấy.''",
            "Tolstoy wrote of her in his diary: `No one I love more and no one causes me more pain.'"),
           ("Nhà nghiên cứu Tolstoy nhận xét: chính sự căng thẳng giữa yêu và ghét trong hôn nhân đó đã là nguồn cảm hứng cho các tác phẩm vĩ đại nhất của ông về tình yêu và con người.",
            "Tolstoy scholars note that the very tension between love and hatred in that marriage was the inspiration for his greatest works about love and humanity.")],
          "Những mối quan hệ sâu sắc nhất không bao giờ đơn giản --- chính sự phức tạp đó là bằng chứng của chiều sâu.",
          "The deepest relationships are never simple --- that very complexity is proof of depth."),

    story("Cha Không Được Yêu Thương Vẫn Yêu Con Không Ngừng", "Câu chuyện dân gian --- Toàn cầu",
          "Có",
          [("Có người con trai lớn lên ghét cha vì cha nghèo, cha thô lỗ, cha không học thức, cha làm anh xấu hổ trước bạn bè.",
            "There was a son who grew up hating his father because his father was poor, rough, uneducated, and made him ashamed in front of friends."),
           ("Anh ta rời nhà sớm, ít liên lạc, và tự hứa sẽ không bao giờ trở thành người như cha.",
            "He left home early, rarely made contact, and promised himself he would never become like his father."),
           ("Khi cha ốm nặng, anh trở về và lần đầu tiên phải lo chăm sóc cha từng bữa ăn, từng miếng thuốc.",
            "When his father fell gravely ill, he returned and for the first time had to care for him meal by meal, medicine by medicine."),
           ("Trong những ngày đó, anh bắt đầu thấy những điều mà trước đây lòng ghét đã che khuất: đôi tay chai của cha từng làm việc để anh có cơm ăn, áo mặc.",
            "During those days, he began to see what hatred had hidden: his father's calloused hands that had worked so he could eat and be clothed."),
           ("Anh nhận ra sự ghét bỏ của mình bao lâu nay thực ra là sự yêu thương chưa được hiểu --- yêu thương bị che lấp bởi kỳ vọng và xấu hổ.",
            "He realized his lifelong hatred was actually love that had never been understood --- love covered up by expectation and shame.")],
          "Đằng sau nỗi ghét cay đắng nhất với một người thân yêu, thường là một tình yêu chưa được nói ra.",
          "Behind the bitterest hatred toward a loved one is usually a love that was never spoken."),

    story("Catherine Đại Đế Và Người Yêu Phản Bội", "Catherine II --- Nga, thế kỷ 18",
          "Catherine",
          [("Catherine Đại Đế của Nga có nhiều tình nhân --- không phải vì yếu đuối mà vì ý thức rõ về quyền lực và sự cô đơn của người đứng đầu đế quốc.",
            "Catherine the Great of Russia had many lovers --- not out of weakness but out of a clear awareness of the power and loneliness of an imperial ruler."),
           ("Khi người tình Grigory Potemkin phản bội bà bằng cách kết hôn bí mật với người khác, bà nổi giận đến mức muốn tống ông vào tù.",
            "When her lover Grigory Potemkin betrayed her by secretly marrying another, she raged so intensely she wanted him imprisoned."),
           ("Nhưng sau cơn thịnh nộ, bà nhìn lại và nhận ra rằng chính vì bà yêu ông sâu sắc đến mức nào nên nỗi phản bội mới đau đến thế.",
            "But after the rage subsided, she reflected and realized that the betrayal hurt precisely because she had loved him so deeply."),
           ("Thay vì trừng phạt, bà dần hòa giải --- hai người cuối cùng duy trì tình bạn thân thiết cho đến khi Potemkin qua đời.",
            "Instead of punishing him, she gradually reconciled --- the two eventually maintained a deep friendship until Potemkin's death."),
           ("Catherine ghi lại: ``Tôi không thể không tha thứ cho ông ta --- vì tôi nhận ra mình vẫn còn yêu, dù đau.''",
            "Catherine wrote: `I could not help forgiving him --- because I realized I still loved, even through the pain.'")],
          "Chỉ có thể giận người mà mình yêu thật sự; kẻ không yêu sẽ không bao giờ đau đến mức cần tha thứ.",
          "We can only truly rage at those we truly love; those who do not love will never hurt deeply enough to need forgiveness."),

    story("Trịnh Công Sơn --- Tình Yêu Trong Sự Chia Ly", "Trịnh Công Sơn --- Việt Nam, 1960s",
          "Trịnh",
          [("Trịnh Công Sơn viết những bản tình ca nổi tiếng nhất âm nhạc Việt Nam không phải từ hạnh phúc --- mà từ những mất mát và chia ly đau đớn.",
            "Trinh Cong Son wrote the most famous love songs in Vietnamese music not from happiness --- but from painful losses and separations."),
           ("Mỗi lần yêu rồi mất, thay vì chôn vùi cảm xúc, ông biến chúng thành nhạc.",
            "Each time he loved and lost, instead of burying the emotion, he transformed it into music."),
           ("Ông nói: ``Tôi viết nhạc không phải để than thở --- tôi viết để hiểu tại sao tôi yêu và tại sao tôi đau.''",
            "He said: `I wrote music not to complain --- I wrote to understand why I loved and why I hurt.'"),
           ("Sự ghét bỏ sau khi mất tình yêu --- nỗi giận dỗi, cô đơn, đau khổ --- tất cả đều được chắt lọc thành những giai điệu mà hàng triệu người nhận ra chính mình trong đó.",
            "The bitterness after losing love --- the anger, loneliness, grief --- all were distilled into melodies in which millions recognized themselves."),
           ("Nhạc Trịnh Công Sơn vĩ đại vì nó không giả vờ yêu là đẹp hoàn toàn --- nó thành thật với cả phần tối của tình yêu.",
            "Trinh Cong Son's music is great because it does not pretend love is entirely beautiful --- it is honest about love's darker side.")],
          "Nghệ thuật chân thật nhất không chạy trốn khỏi nỗi đau --- nó nhìn thẳng vào và tìm thấy vẻ đẹp trong đó.",
          "The most honest art does not flee from pain --- it looks directly in and finds beauty there."),

    story("Dạy Học Vì Yêu Nhưng Có Lúc Ghét Lớp", "Nghề Giáo --- Trải Nghiệm Toàn Cầu",
          "Nhiều",
          [("Nhiều giáo viên giỏi nhất thế giới đã từng trải qua những buổi sáng vào lớp và cảm thấy không muốn dạy nữa.",
            "Many of the world's best teachers have experienced mornings when they walked into class and felt like teaching no more."),
           ("Cảm giác đó --- nặng nề, mệt mỏi, thất vọng với học sinh lười biếng hay vô lễ --- chính là biểu hiện của sự quan tâm sâu sắc.",
            "That feeling --- heavy, tired, disappointed with lazy or disrespectful students --- is precisely a sign of deep caring."),
           ("Người không yêu nghề sẽ không thấy gì cả; chính người yêu mới biết thất vọng khi kỳ vọng không được đáp lại.",
            "Those who don't love the profession feel nothing; only those who love are capable of disappointment when expectations are unmet."),
           ("Những giáo viên ở lại --- dù có những ngày muốn bỏ nghề --- chính là những người học sinh nhớ mãi về sau.",
            "The teachers who stay --- even on days they want to quit --- are exactly the ones students remember forever."),
           ("Bởi vì học sinh không chỉ học kiến thức --- chúng học được rằng yêu thứ gì đó có nghĩa là kiên trì với nó ngay cả khi khó.",
            "Because students don't just learn knowledge --- they learn that loving something means persisting with it even when it is hard.")],
          "Tình yêu không phải lúc nào cũng dễ chịu --- đôi khi nó giả dạng thành nỗi mệt mỏi và thất vọng.",
          "Love is not always pleasant --- sometimes it disguises itself as exhaustion and disappointment."),

    story("Marie Curie Và Khoa Học Đã Cướp Đi Sức Khỏe Bà", "Marie Curie --- Pháp, 1898--1934",
          "Marie",
          [("Marie Curie yêu khoa học đến mức không có ranh giới --- bà nghiên cứu trong điều kiện không an toàn, tiếp xúc phóng xạ mỗi ngày trong nhiều thập kỷ.",
            "Marie Curie loved science without limits --- she worked in unsafe conditions, exposed to radiation daily for decades."),
           ("Bà biết đó là nguy hiểm nhưng vẫn tiếp tục --- tình yêu với khoa học lớn hơn sợ hãi về cái chết.",
            "She knew it was dangerous but continued --- love of science was greater than fear of death."),
           ("Hai giải Nobel, hàng trăm công bố khoa học, phòng thí nghiệm mang tên bà khắp thế giới --- tất cả mua bằng sức khỏe của bà.",
            "Two Nobel Prizes, hundreds of scientific papers, laboratories worldwide bearing her name --- all purchased with her health."),
           ("Bà chết vì bệnh máu do phóng xạ gây ra năm 1934 --- và chính những tài liệu nghiên cứu của bà đến nay vẫn bị đánh dấu `nguy hiểm phóng xạ'.",
            "She died of radiation-induced aplastic anemia in 1934 --- and her own research notebooks are still marked `radioactively dangerous' to this day."),
           ("Marie Curie từng nói: ``Trong khoa học chúng tôi không nên lo lắng về con người mà chỉ về những điều.'' --- Câu nói đó chứa đựng cả tình yêu lẫn bi kịch.",
            "Marie Curie once said: `In science we should not be interested in persons but in things.' --- That sentence holds both love and tragedy.")],
          "Tình yêu sâu sắc nhất đôi khi là tình yêu tiêu hao ta --- nhưng cũng là tình yêu tạo ra những điều bất tử.",
          "The deepest love sometimes consumes us --- but it is also the love that creates immortal things."),

    story("Lòng Thương Xót Sinh Ra Từ Nỗi Đau Riêng", "Viktor Frankl --- Áo, 1945",
          "Viktor",
          [("Viktor Frankl mất toàn bộ gia đình trong trại tập trung Auschwitz --- vợ, cha mẹ, anh trai --- chỉ sót lại một người chị.",
            "Viktor Frankl lost his entire family in Auschwitz --- wife, parents, brother --- with only one sister surviving."),
           ("Người ta tưởng thảm kịch đó sẽ biến ông thành người cay độc và thù ghét nhân loại.",
            "People expected such tragedy to turn him into someone bitter and hateful toward humanity."),
           ("Nhưng Frankl viết trong Man's Search for Meaning: ``Chính trong đau khổ tột cùng, tôi hiểu rằng không có gì có thể lấy đi được tự do cuối cùng của con người: quyền chọn thái độ của mình.''",
            "But Frankl wrote in Man's Search for Meaning: `In the most extreme suffering, I understood that nothing can take away man's last freedom: the right to choose one's attitude.'"),
           ("Ông dùng kinh nghiệm đau đớn đó để xây dựng Liệu pháp Ý nghĩa --- một trong những trường phái tâm lý học quan trọng nhất thế kỷ 20.",
            "He used that painful experience to build Logotherapy --- one of the most important schools of psychology in the 20th century."),
           ("Frankl nói: ``Đau khổ không nhất thiết phá huỷ con người; chính thiếu ý nghĩa mới phá huỷ con người.''",
            "Frankl said: `Suffering does not necessarily destroy a person; it is the lack of meaning that destroys.'")],
          "Khi đau khổ được chuyển hóa thành ý nghĩa, nó không còn là gánh nặng nữa --- nó trở thành nền tảng.",
          "When suffering is transformed into meaning, it is no longer a burden --- it becomes a foundation."),

    story("Cha Mẹ Nghiêm Khắc Và Tình Thương Ẩn Giấu", "Câu chuyện Á Đông --- Truyền thống",
          "Trong",
          [("Trong nhiều gia đình Á Đông, cha mẹ biểu lộ tình yêu không bằng lời nói ngọt ngào mà bằng sự nghiêm khắc và kỳ vọng cao.",
            "In many East Asian families, parents express love not through sweet words but through strictness and high expectations."),
           ("Đứa con nhỏ nhìn thấy người cha luôn phê phán, không bao giờ khen --- và nghĩ rằng cha không yêu mình.",
            "The young child sees a father who always criticizes, never praises --- and believes their father does not love them."),
           ("Nhưng người cha đó thức khuya dậy sớm suốt mấy chục năm, hy sinh sức khỏe và ước mơ riêng, tất cả chỉ để kiếm tiền nuôi con ăn học.",
            "But that father stayed up late and rose early for decades, sacrificing his health and personal dreams, all just to earn enough for the child's food and education."),
           ("Khi con lớn lên và có con riêng, mới hiểu rằng sự nghiêm khắc của cha là cách yêu thương duy nhất ông biết.",
            "When the child grows up and has their own child, they understand that the father's strictness was the only way he knew how to love."),
           ("Tình yêu không cần phải có hình dạng ta mong đợi để là tình yêu thật --- đôi khi nó đến dưới dạng kỳ vọng và áp lực.",
            "Love does not need to take the shape we expect to be real love --- sometimes it comes in the form of expectation and pressure.")],
          "Hãy tìm tình yêu không chỉ ở nơi ta thích --- mà ở cả nơi ta không ngờ tới.",
          "Look for love not only where you like --- but also where you least expect it."),

    story("Hận Bạo Quân Trở Thành Nguồn Sức Mạnh Của Spartacus", "Spartacus --- La Mã, 73 TCN",
          "Spartacus",
          [("Spartacus --- người nô lệ gốc Thracia --- bị ép làm đấu sĩ trong đấu trường La Mã và chứng kiến đồng loại bị giết hại như trò giải trí.",
            "Spartacus, a Thracian slave, was forced to fight as a gladiator in the Roman arenas and witnessed fellow slaves killed as entertainment."),
           ("Lòng căm thù bạo quân La Mã --- cực kỳ sâu sắc và cực kỳ chính đáng --- trở thành nhiên liệu của cuộc nổi dậy lớn nhất lịch sử La Mã.",
            "His hatred of Roman oppressors --- deeply felt and entirely justified --- became the fuel of the largest uprising in Roman history."),
           ("Spartacus lãnh đạo hơn 70.000 nô lệ và người nghèo, chiến đấu và thắng nhiều trận đánh lớn trong hai năm.",
            "Spartacus led over 70,000 slaves and poor people, winning many major battles over two years."),
           ("Tuy cuộc nổi dậy cuối cùng bị dập tắt, nhưng nó buộc La Mã phải thay đổi một số luật đối xử với nô lệ.",
            "Although the rebellion was eventually crushed, it forced Rome to change some of its laws on the treatment of slaves."),
           ("Spartacus chứng minh một điều: khi lòng căm ghét bất công đủ mạnh và đủ thanh khiết, nó có thể trở thành lửa thiêng của tự do.",
            "Spartacus proved one thing: when hatred of injustice is strong enough and pure enough, it can become the sacred fire of freedom.")],
          "Không phải mọi nỗi hận đều xấu --- hận cái ác đúng nghĩa là yêu công lý và con người.",
          "Not all hatred is bad --- hating genuine evil is precisely loving justice and humanity."),

    story("Thầy Giáo Ghét Học Sinh Không Chịu Học --- Rồi Nhận Ra Điều Gì", "Câu chuyện giáo dục --- Việt Nam",
          "Có",
          [("Có một thầy giáo kể rằng ông từng ghét một học sinh trong lớp --- cậu bé ngồi cuối lớp, không bao giờ nghe, luôn phá rối.",
            "A teacher told of a student he once despised --- the boy sat at the back, never listened, always caused disruption."),
           ("Một ngày thầy gặp mẹ cậu bé và biết rằng cha cậu vừa mất, nhà không có tiền, cậu đến trường nhịn đói.",
            "One day the teacher met the boy's mother and learned that the father had just died, the family had no money, and the boy came to school hungry."),
           ("Thầy nhận ra ``cái ghét'' trong lòng mình thực ra là sự bực bội của người quan tâm nhưng không hiểu đủ.",
            "The teacher realized that the `hatred' in his heart was actually the frustration of someone who cared but did not understand enough."),
           ("Từ hôm đó thầy bắt đầu mang cơm thêm, ngồi lại sau giờ học, và kiên nhẫn dạy riêng cậu bé.",
            "From that day the teacher started bringing extra food, staying after school, and patiently tutoring the boy one-on-one."),
           ("Cậu học sinh đó về sau thi đỗ đại học --- và bài phát biểu tốt nghiệp của anh bắt đầu bằng: ``Có một người ghét tôi nhất lớp đã thay đổi cuộc đời tôi.''",
            "That student later passed university entrance exams --- and his graduation speech began: `The person who disliked me most in class changed my life.'")],
          "Sự bực bội với ai đó có khi là tình yêu thương chưa tìm được cách biểu lộ --- hãy hỏi tại sao trước khi từ bỏ.",
          "Frustration with someone can be love that hasn't found a way to express itself --- ask why before giving up."),
    ]
)

# ================================================================
# GHI FILE
# ================================================================
files = [
    ("ch01-phuc-trong-hoa", ch1),
    ("ch02-thanh-cong-trong-that-bai", ch2),
    ("ch03-ban-trong-thu", ch3),
    ("ch04-yeu-trong-ghet", ch4),
]
for fname, content in files:
    path = os.path.join(BASE, f"{fname}.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{fname} done")
print("All chapters 1-4 generated successfully!")
